BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Lo que un ENTRENADOR necesita...\p"
	.string "Conocimiento...\n"
	.string "Estrategia...\l"
	.string "Suerte...\l"
	.string "Agallas...\l"
	.string "Espíritu...\l"
	.string "Valentía...\l"
	.string "Y habilidad...\p"
	.string "¡Bueno, yo lo tengo todo!\n"
	.string "¡Seré imparable en todo lugar!\p"
	.string "¿Eh? ¿POKéMON?\n"
	.string "¿Qué es eso?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "¿Sabes quiénes son los CEREBROS\n"
	.string "DE LA FRONTERA?\p"
	.string "Así llama SCOTT a los siete\n"
	.string "ENTRENADORES especiales que dirigen\l"
	.string "la BATTLE FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "En la BATTLE TOWER, una chica\n"
	.string "me dijo que tengo mucho talento\l"
	.string "para luchar!\p"
	.string "¡Prefiero los POKéMON CONTESTS!\p"
	.string "¡Pero soy malo en los CONTESTS!\p"
	.string "Tener talento y que algo te guste\n"
	.string "no es lo mismo.$"

