SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Parece haber una conexión\n"
	.string "entre CALORIFLUA y el MONTE CENIZA.\p"
	.string "Mis amigos e yo investigamos eso\n"
	.string "en el lab. donde yo trabajaba.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Mi hermano mayor estudiaba el mar.$"

