FuchsiaCity_House1_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Mi abuelo está con mi hermano BILL\n"
	.string "en CABO CELESTE.$"

FuchsiaCity_House1_Text_Youngster:
	.string "Vi POKéMON raros y lentos en la\n"
	.string "RUTA CICLISTA.$"

