RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "La ESCUELA DE ENTRENADORES es genial.\p"
	.string "Si estudias ahí, podrías hasta\n"
	.string "ser un LÍDER de GIMNASIO.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "ROXANNE, la LÍDER, sabe mucho\n"
	.string "sobre los POKéMON.\p"
	.string "¡Además es muy fuerte!$"

