VermilionCity_House1_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Soy el TIPO PESCA, el mayor\n"
	.string "de los HERMANOS PESCA.\p"
	.string "¿Conoces al GURÚ DE LA PESCA en\n"
	.string "el LAGO DE la FURIA?\p"
	.string "Él sueña con ver al MAGIKARP\n"
	.string "más grande del mundo.\p"
	.string "Si no te importa, ¿le mostrarías\n"
	.string "los MAGIKARP que captures?\p"
	.string "Quién sabe, podrías pescar al\n"
	.string "MAGIKARP de sus sueños.$"

VermilionCity_House1_Text_Photo:
	.string "Es una foto de gente pescando...\p"
	.string "Se lo están pasando genial...$"
