LavenderTown_Mart_MapScripts::
	.byte 0

LavenderTown_Mart_EventScript_Pokefan::
	msgbox LavenderMart_Text_PokefanM, MSGBOX_NPC
	end

LavenderTown_Mart_EventScript_Rocker::
	msgbox LavenderMart_Text_Rocker, MSGBOX_NPC
	end

LavenderMart_Text_PokefanM:
	.string "El REPEL es necesario si vas a\n"
	.string "explorar una cueva.\p"
	.string "Aunque me gusta explorar,\n"
	.string "aún no he ido a todas\l"
	.string "las cuevas.$"

LavenderMart_Text_Rocker:
	.string "Oí de un artesano que hace\n"
	.string "BALLS personalizadas en el\l"
	.string "PUEBLO AZALEA de JOHTO.\p"
	.string "¡Desearía tener algunas!$"
