gText_ApprenticeChallenge0::
	.string "Eh, soy el aprendiz n. {STR_VAR_2}\nde {STR_VAR_1}."
	.string "Snif... ¡Qué nervios tengo!$"

gText_ApprenticeChallenge1::
	.string "¡Soy el aprendiz n. {STR_VAR_2}\nde {STR_VAR_1}!"
	.string "¡Aquí vamos!$"

gText_ApprenticeChallenge2::
	.string "¡Soy el aprendiz n. {STR_VAR_2}\nde {STR_VAR_1}!"
	.string "¡Acepta mi desafío!$"

gText_ApprenticeChallenge3::
	.string "Eh... soy el aprendiz n. {STR_VAR_2}\nde {STR_VAR_1}..."
	.string "¿Crees que alguien como yo ganará?$"

gText_ApprenticeChallenge4::
	.string "¡Soy el aprendiz n. {STR_VAR_2}\nde {STR_VAR_1}!"
	.string "¡Te dejaré desafiarme!$"

gText_ApprenticeChallenge5::
	.string "Estoy muy ocupado, pero también soy\n"
	.string "el aprendiz nro. {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Soy el aprendiz nro. {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "¡Gusto en conocerte!$"

gText_ApprenticeChallenge7::
	.string "Soy el aprendiz n. {STR_VAR_2}\nde {STR_VAR_1}."
	.string "¿Puedo empezar?$"

gText_ApprenticeChallenge8::
	.string "¡Ay! ¡Soy el aprendiz {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Daré lo mejor de mí!$"

gText_ApprenticeChallenge9::
	.string "¡Yeehaw! ¡Soy el aprendiz {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Prepárate!$"

gText_ApprenticeChallenge10::
	.string "¡Soy el aprendiz 1,000 de {STR_VAR_1}!\n"
	.string "¡En verdad soy el nro. {STR_VAR_2}!$"

gText_ApprenticeChallenge11::
	.string "¡Sí, soy el aprendiz {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Hagamos que esto ruede!$"

gText_ApprenticeChallenge12::
	.string "¡Yippee-yahoo! Soy lo que llaman\n"
	.string "el aprendiz nro. {STR_VAR_2} de {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "¡Tos! Soy el aprendiz {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "¡Gusto en conocerte! ¡Tos!$"

gText_ApprenticeChallenge14::
	.string "Esto pone nervioso...\n"
	.string "Soy el aprendiz nro. {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Soy el aprendiz nro. {STR_VAR_2} de {STR_VAR_1},\n"
	.string "y eso no es mentira.$"

gText_ApprenticePleaseTeach0::
	.string "¿Eres... {PLAYER}?\n"
	.string "¡Oh! Snif... bua...\p"
	.string "¡Oh! L-lo siento...\n"
	.string "Estoy nervioso, no puedo evitarlo...\p"
	.string "Soy {STR_VAR_1}, y te admiro\n"
	.string "mucho, {PLAYER}.\p"
	.string "Soñaba con conocerte algún día\n"
	.string "y preguntarte sobre POKéMON.\p"
	.string "¡Por favor, {PLAYER}!\n"
	.string "¡Enséñame sobre POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh... P-pero...\n"
	.string "¡Buaaaaah!\p"
	.string "¡Por favor!\n"
	.string "¡Te lo ruego, por favor!$"

gText_ApprenticeWhichLevelMode0::
	.string "¿En serio? ¿Lo harás?\n"
	.string "¡Genial! ¡Increíble! ¡Awoooh!\p"
	.string "Oh... lo siento...\n"
	.string "Estoy tan feliz que lloro...\p"
	.string "Um... ¡entonces dime!\n"
	.string "Es sobre la BATTLE TOWER.\p"
	.string "¿Qué sería mejor para mí: NORMAL\n"
	.string "o nivel HARD?$"

gText_ApprenticeLevelModeThanks0::
	.string "¿{STR_VAR_1}?\n"
	.string "¡Waaaaah!\p"
	.string "¡Oh! ¡Lo siento mucho!\n"
	.string "Me hiciste feliz al elegir el\l"
	.string "nivel por mí, y por eso lloro...\p"
	.string "Snif...\n"
	.string "¡Muchas gracias!\l"
	.string "¡Por favor, vuelve a hablarme!$"

gText_ApprenticePleaseTeach1::
	.string "¡Guau! Eres {PLAYER}, ¿verdad?\n"
	.string "¡Eres increíblemente fuerte!\p"
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Acabo de ser ENTRENADOR!\p"
	.string "¡Por favor, {PLAYER}!\n"
	.string "¿Puedes ser mi maestro y decirme\l"
	.string "mucho sobre ser ENTRENADOR?$"

gText_ApprenticeRejectTeaching1::
	.string "Ay, ¿por qué?\n"
	.string "¿Oh, por favor? ¿Sí que no?\l"
	.string "¡Por favor, sé mi maestro, por favor!$"

gText_ApprenticeWhichLevelMode1::
	.string "¡Siií! ¡Genial!\p"
	.string "Lo primero que quería preguntarte\n"
	.string "es sobre la BATTLE TOWER!\p"
	.string "Las salas NORMAL y HARD...\n"
	.string "¿Cuál sería perfecta para mí?$"

gText_ApprenticeLevelModeThanks1::
	.string "¿{STR_VAR_1}, eh? ¡Es verdad!\n"
	.string "¡Daré lo mejor de mí allí!\p"
	.string "Si nos vemos aquí, ¡enséñame\n"
	.string "algo más, maestro!$"

gText_ApprenticePleaseTeach2::
	.string "Este... ¿Eres {PLAYER}?\n"
	.string "Me llamo {STR_VAR_1}.\p"
	.string "Quiero ser ENTRENADOR POKéMON,\n"
	.string "pero no sé qué hacer...\p"
	.string "Pensé que podría pedirte consejos\n"
	.string "porque eres muy famoso.\p"
	.string "{PLAYER}, ¿me darías consejos?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, pero...\p"
	.string "¡De verdad quiero ser un\n"
	.string "ENTRENADOR POKéMON!\p"
	.string "Por favor, ¿responderás mis dudas?$"

gText_ApprenticeWhichLevelMode2::
	.string "¡Gracias!\n"
	.string "¡Aquí va mi primera pregunta!\p"
	.string "La BATTLE TOWER tiene dos niveles,\n"
	.string "NORMAL y HARD, ¿verdad?\p"
	.string "¿Cuál crees que es más\n"
	.string "adecuado para mí?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, ¿el reto de {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "Si tengo otra duda, ¡volveré\n"
	.string "por tus consejos!$"

gText_ApprenticePleaseTeach3::
	.string "¿Oh? ¿Eh? Tú eres...\n"
	.string "No, no puede ser verdad.\p"
	.string "Es imposible que alguien\n"
	.string "como yo conozca a {PLAYER}.\p"
	.string "...¿De verdad eres {PLAYER}?\n"
	.string "¡No creo que hable contigo!\p"
	.string "Cuando pasa algo tan bueno,\n"
	.string "solo vienen cosas terribles\l"
	.string "ahora, lo sé...\p"
	.string "...Lo siento...\n"
	.string "Soy... {STR_VAR_1}...\p"
	.string "No hay nada especial en mí\n"
	.string "de lo que pueda estar orgulloso...\p"
	.string "Ni debería hablar de mí\n"
	.string "porque lo olvidarás...\p"
	.string "Soñé que si te conocía,\n"
	.string "{PLAYER}, tal vez podría pedirte\l"
	.string "consejos como ENTRENADOR.\p"
	.string "Pero no creo que aceptes\n"
	.string "hacer eso.\p"
	.string "...¿O serías tan amable de\n"
	.string "darme consejos?$"

gText_ApprenticeRejectTeaching3::
	.string "Lo sabía...\p"
	.string "Tenía que pasar porque soy un\n"
	.string "donnadie muy aburrido...\p"
	.string "Pero pensé que tal vez...\n"
	.string "No cambiarás de opinión, ¿verdad?\p"
	.string "Pero no me rendiré así nomás.\n"
	.string "¡Preguntaré mientras tenga suerte!\p"
	.string "Por favor, ¿serías tan amable de\n"
	.string "darme consejos?$"

gText_ApprenticeWhichLevelMode3::
	.string "¿En serio? ¡No lo puedo creer!\n"
	.string "¡No creo que me des consejos!\l"
	.string "Yo... estoy muy feliz...\p"
	.string "Lo que quiero preguntar es\n"
	.string "trivial, pero no me decido...\p"
	.string "En la BATTLE TOWER puedes\n"
	.string "elegir nivel NORMAL o HARD.\p"
	.string "¿En cuál crees que yo tendría\n"
	.string "alguna oportunidad?$"

gText_ApprenticeLevelModeThanks3::
	.string "¿{STR_VAR_1}? ¡Está bien!\n"
	.string "¿Pero crees que alguien como yo\l"
	.string "tendría una oportunidad?\p"
	.string "Daré lo mejor de mí, aunque no\n"
	.string "creo que funcione.\p"
	.string "Muchas gracias por dedicarle\n"
	.string "tiempo a alguien como yo.$"

gText_ApprenticePleaseTeach4::
	.string "¡Oh! Eres {PLAYER}{KUN}, ¿verdad?\p"
	.string "¡He oído que eres fuerte en\n"
	.string "POKéMON!\p"
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Seremos amigos!\p"
	.string "¿Sabías esto?\p"
	.string "No ganarás en la BATTLE FRONTIER\n"
	.string "si solo sabes lo que enseñan en\l"
	.string "la ESCUELA de ENTRENADORES.\p"
	.string "Quiero escuchar tus consejos.\n"
	.string "¿Estás de acuerdo, claro?$"

gText_ApprenticeRejectTeaching4::
	.string "¿Eh? ¿Por qué me rechazas?\n"
	.string "¡Soy yo quien te lo pide!\l"
	.string "¡Tienes que reconsiderarlo!$"

gText_ApprenticeWhichLevelMode4::
	.string "Bien, hay una cosa.\n"
	.string "Quiero que decidas por mí.\p"
	.string "Sabes que la BATTLE TOWER tiene\n"
	.string "salas NORMAL y HARD, ¿verdad?\p"
	.string "¿Cuál crees que sería mejor\n"
	.string "para mí, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "¿Bien, {STR_VAR_1} es lo ideal?\n"
	.string "¡Gracias!\p"
	.string "Sabiendo que tú decidiste,\n"
	.string "{PLAYER}{KUN}, no me dolerá tanto\l"
	.string "si pierdo.\p"
	.string "Te pediré consejos otra vez.\n"
	.string "¡Adiós!$"

gText_ApprenticePleaseTeach5::
	.string "¡Hola! ¡{PLAYER}{KUN}!\n"
	.string "¡Te conozco porque eres famoso!\l"
	.string "¡Dime {STR_VAR_1}! ¡Gusto en verte!\p"
	.string "Soy TRIATLETA, así que me mantengo\n"
	.string "en forma mientras crío POKéMON.\p"
	.string "También hago otras cosas\n"
	.string "como trabajar, dormir, bailar...\p"
	.string "Estando tan ocupado, no es fácil\n"
	.string "ser un ENTRENADOR decente.\p"
	.string "¡Tengo una propuesta!\p"
	.string "Debe haber una razón para vernos.\n"
	.string "{PLAYER}{KUN}, ¿compartirías tu\l"
	.string "sabiduría conmigo a veces?$"

gText_ApprenticeRejectTeaching5::
	.string "¡Oh, pero por favor!\n"
	.string "¡Alguien como yo necesita a alguien\l"
	.string "como tú, {PLAYER}{KUN}!\p"
	.string "¡De verdad necesito tus consejos!$"

gText_ApprenticeWhichLevelMode5::
	.string "¡Gracias! ¡Así me gusta!\n"
	.string "¡Empecemos con algo fácil!\p"
	.string "Sabes de los dos cursos de la\n"
	.string "BATTLE TOWER, ¿verdad?\l"
	.string "Ya sabes, nivel NORMAL y HARD.\p"
	.string "Siendo yo tan ocupado, ¿cuál\n"
	.string "debería preparar?$"

gText_ApprenticeLevelModeThanks5::
	.string "¿{STR_VAR_1}, eh? Vale, entiendo.\n"
	.string "¡Buscaré tiempo y lo intentaré!\p"
	.string "...¡Uy, debo ir a trabajar!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticePleaseTeach6::
	.string "¡No puede ser! ¡No, no!\n"
	.string "¿Acaso eres el real {PLAYER}?\p"
	.string "¡A-ja! ¡Genial! Soy {STR_VAR_1},\n"
	.string "¡encantado de conocerte!\p"
	.string "{PLAYER}, eres muy fuerte,\n"
	.string "¿verdad?\p"
	.string "¡Todos hablan de ti!\p"
	.string "¡Oh! ¡Tuve una gran idea!\n"
	.string "¡Te pediré consejos, {PLAYER}!\l"
	.string "¡Seguro que me hará más fuerte!\p"
	.string "¿No es una gran idea?\n"
	.string "¡Por favor, quiero tus consejos!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, puedes fingir ser malo,\n"
	.string "¡pero no me engañas!\l"
	.string "En realidad dices que sí, ¿verdad?$"

gText_ApprenticeWhichLevelMode6::
	.string "¡SÍ! ¡Sabía que tendrías un gran\n"
	.string "corazón, {PLAYER}!\p"
	.string "¿Qué debería preguntarte primero?\n"
	.string "...¡Ah, ya se me ocurrió algo!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "Mi pregunta es la siguiente...\p"
	.string "Si aceptara un reto de la BATTLE\n"
	.string "TOWER, ¿qué camino debería tomar?\p"
	.string "¿NORMAL o HARD?\n"
	.string "¿Cuál me queda mejor?$"

gText_ApprenticeLevelModeThanks6::
	.string "¡Oh-oh-oh!\n"
	.string "¡Dices {STR_VAR_1}!\l"
	.string "¡Gracias por una respuesta genial!\p"
	.string "Creo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Reunámonos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticePleaseTeach7::
	.string "Perdone, pero...\n"
	.string "¿Es usted {PLAYER}?\p"
	.string "Soy {STR_VAR_1}, y es un placer\n"
	.string "conocerlo.\p"
	.string "He sido su admirador\n"
	.string "por mucho tiempo...\p"
	.string "... ... ... ... ... ...\p"
	.string "Eh... espero que no encuentre\n"
	.string "esta petición pesada, pero...\p"
	.string "¿Puedo ser su aprendiz,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "¡Oh...!\p"
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\p"
	.string "...Debí desmayarme del impacto.\n"
	.string "Lo siento, debí oír mal.\p"
	.string "¡Por favor! ¡Diga que me\n"
	.string "aceptará como su aprendiz!$"

gText_ApprenticeWhichLevelMode7::
	.string "¡Oh... estoy encantado!\p"
	.string "No quiero quitarle su tiempo,\n"
	.string "así que aconséjeme en esto.\p"
	.string "Planeo aceptar un reto de la\n"
	.string "BATTLE TOWER pronto.\p"
	.string "Sin embargo, hay dos niveles...\p"
	.string "¿Cuál sería el más apto para mí?\n"
	.string "¿NORMAL o HARD?$"

gText_ApprenticeLevelModeThanks7::
	.string "¡{STR_VAR_1} es su elección!\n"
	.string "Ya veo. ¡Daré lo mejor de mí!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero contar con usted otra vez.\l"
	.string "¡Cuídese mucho!$"

gText_ApprenticePleaseTeach8::
	.string "¡Eek! ¡Eek! {PLAYER}!\n"
	.string "¡Hablaste conmigo!\l"
	.string "¡Estoy... estoy feliz!\p"
	.string "¡Yo! ¡Me llamo {STR_VAR_1}!\n"
	.string "¡Acabo de ser ENTRENADOR!\p"
	.string "¡Qué alegría verte, {PLAYER},\n"
	.string "¡famoso en el mundo POKéMON!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¿Me haces un favor, {PLAYER}?\p"
	.string "¡Acéptame como tu aprendiz!\n"
	.string "¡Quiero aprender de ti!$"

gText_ApprenticeRejectTeaching8::
	.string "¡Waaaah!\n"
	.string "{PLAYER} me rechazó...\l"
	.string "¡Es... una experiencia valiosa!\p"
	.string "{PLAYER}, ¡por favor! ¡Quiero que\n"
	.string "me digas que sí esta vez!\p"
	.string "¡Te ruego que me guíes!$"

gText_ApprenticeWhichLevelMode8::
	.string "¡Hieeeeh! ¡{PLAYER} dijo que sí!\n"
	.string "¡{PLAYER} dijo que sí!\p"
	.string "No podré dormir esta noche...\n"
	.string "¡Muchísimas gracias!\p"
	.string "¡Entonces, tengo una pregunta!\p"
	.string "En la BATTLE TOWER, ¿qué es mejor\n"
	.string "para mí, NORMAL o HARD?$"

gText_ApprenticeLevelModeThanks8::
	.string "¡{STR_VAR_1}! ¡Entendido!\n"
	.string "¡Lo entiendo perfectamente!\l"
	.string "¡Estoy delirantemente feliz!\p"
	.string "Espero que quieras enseñarme\n"
	.string "más cosas en otro momento.$"

gText_ApprenticePleaseTeach9::
	.string "¡Vaya! ¿Podrías ser...\n"
	.string "¿Serás tú... {PLAYER}{KUN}?!\l"
	.string "¿El ENTRENADOR fuerte y famoso?\l"
	.string "¡Hola! ¡Soy el más suertudo!\p"
	.string "¡Hola, me llamo {STR_VAR_1}!\p"
	.string "Buscaba a un maestro de\n"
	.string "POKéMON.\p"
	.string "Y con un tiempo impecable,\n"
	.string "¡apareces tú, {PLAYER}{KUN}!\p"
	.string "¡Así que ya lo sabes, {PLAYER}{KUN}!\n"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeRejectTeaching9::
	.string "¡Gwaaaah!\n"
	.string "Eres muy genial y duro...\p"
	.string "No seas así, por favor.\n"
	.string "¡Te lo pido!$"

gText_ApprenticeWhichLevelMode9::
	.string "¡Oh, sí! ¡Esa es una gran respuesta!\n"
	.string "¡Excelente, diría yo!\p"
	.string "¿Qué tal un primer consejo\n"
	.string "sobre la BATTLE TOWER?\p"
	.string "Si fuera, ¿qué sería mejor?\n"
	.string "¿NORMAL o HARD?$"

gText_ApprenticeLevelModeThanks9::
	.string "¡Ajá, {STR_VAR_1} al ataque!\n"
	.string "¡OK, todo OK!\l"
	.string "¡Iré a demostrar mi valor!\p"
	.string "¡Bien, te veré como mi mentor!\n"
	.string "¡Adiós!$"

gText_ApprenticePleaseTeach10::
	.string "¡Oh, hola, {PLAYER}{KUN}, ¿verdad?\n"
	.string "¡La policía te buscaba!\p"
	.string "… … …\n"
	.string "¡Claro que miento!\p"
	.string "Yo soy {STR_VAR_1}. Aunque no lo\n"
	.string "parezca, ¡soy el CAMPEÓN POKéMON!\l"
	.string "…¡Eso también es mentira!\p"
	.string "Pero esto no es mentira.\n"
	.string "No soy muy bueno luchando.\p"
	.string "¿Qué tal si eres mi maestro en\n"
	.string "todo lo relacionado con POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Si vas a ser tan frío conmigo,\n"
	.string "¡te enseñaré lo que puedo hacer!\p"
	.string "¡Buaaa! ¡Buaaa! ¡Buaaa!\n"
	.string "¡Hic!\p"
	.string "¡Jajaja, eran LÁGRIMAS FALSAS!\p"
	.string "Vamos, ¿quieres ser mi\n"
	.string "maestro POKéMON?$"

gText_ApprenticeWhichLevelMode10::
	.string "¡Yupi!\n"
	.string "¡Te compraré un barco por eso!\p"
	.string "¡Claro que miento otra vez!\n"
	.string "Pero… ¡gracias, maestro!\p"
	.string "¿Sabes que hay nivel NORMAL y\n"
	.string "DIFÍCIL en la BATTLE TOWER?\p"
	.string "No sé qué nivel debería\n"
	.string "desafiar…\p"
	.string "¿Puedes decidirlo tú, maestro?$"

gText_ApprenticeLevelModeThanks10::
	.string "¡Vale, entonces {STR_VAR_1} es mejor!\n"
	.string "¡Iré al otro nivel entonces!\p"
	.string "¡Es broma!\n"
	.string "¡Seguiré tus enseñanzas, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticePleaseTeach11::
	.string "¡A-H-O-Y!\n"
	.string "¡Eso dice ahoy, y significa hola!\p"
	.string "¡Soy {STR_VAR_1}, el MARINERO\n"
	.string "que rapea!\p"
	.string "Ahora es tu turno, cuéntame algo\n"
	.string "de ti, ¡inténtalo!\p"
	.string "¡Ajá, ajá!\n"
	.string "{PLAYER}{KUN} es tu nombre,\l"
	.string "¡y POKéMON es tu juego!\p"
	.string "Estás en una edad delicada\n"
	.string "¡donde el mundo es tu escenario!\p"
	.string "En fin, solo quiero decirte,\n"
	.string "que eres el décimo ENTRENADOR\l"
	.string "con quien hablo hoy.\p"
	.string "¡Hagamos una celebración!\n"
	.string "¡Sé mi mentor para conmemorarlo!$"

gText_ApprenticeRejectTeaching11::
	.string "¡Pero!\n"
	.string "¡Tienes que ayudarme!\p"
	.string "¡No seas tan cruel!\n"
	.string "¡Sé mi mentor, por favor!$"

gText_ApprenticeWhichLevelMode11::
	.string "¡Eso es!\n"
	.string "{PLAYER}, ¡tienes espíritu!\p"
	.string "¡Aquí va mi primera pregunta\n"
	.string "para pedir tu sugerencia!\p"
	.string "Es sobre la BATTLE TOWER,\n"
	.string "¡y depende de mi poder!\p"
	.string "Hay nivel NORMAL y DIFÍCIL,\n"
	.string "¿cuál es el mejor para mí?$"

gText_ApprenticeLevelModeThanks11::
	.string "¡Vale, {STR_VAR_1} será, dices!\n"
	.string "¡Iré y lo intentaré a mi manera!\p"
	.string "Si alguna vez necesito un consejo,\n"
	.string "{PLAYER}, ¡siempre te escucharé!$"

gText_ApprenticePleaseTeach12::
	.string "Oye, ¿no eres {PLAYER}?\n"
	.string "¿Qué hago? ¿Hablo contigo?\l"
	.string "¡Claro! ¡Si ya estoy hablando!\p"
	.string "{PLAYER}, ¿te sorprendo?\n"
	.string "¡Mejor te digo quién soy yo!\p"
	.string "Puedes llamarme {STR_VAR_1}.\n"
	.string "¡La estrella más brillante de la\l"
	.string "guitarra, ese soy yo!\p"
	.string "¿Me escuchas?\n"
	.string "¡Sí, me escuchas!\p"
	.string "Tengo mucha suerte,\n"
	.string "¡así que te pediré un favor!\p"
	.string "{PLAYER}, ¡déjame ser tu secuaz!\n"
	.string "¡Quiero que me enseñes todo!$"

gText_ApprenticeRejectTeaching12::
	.string "¿Me estás rechazando?\n"
	.string "¡Tendré que pedírtelo otra vez!\p"
	.string "{PLAYER}, ¡ruego ser tu secuaz!\n"
	.string "¡Necesito que me enseñes todo!$"

gText_ApprenticeWhichLevelMode12::
	.string "¡Qué suerte, sí, yujuu!\n"
	.string "¿Te hago una pregunta?\p"
	.string "Estamos cerca de la BATTLE TOWER,\n"
	.string "¿qué tal una sobre su poder?\p"
	.string "De las opciones que ves,\n"
	.string "¿cuál es la correcta para mí?$"

gText_ApprenticeLevelModeThanks12::
	.string "Si sugieres {STR_VAR_1},\n"
	.string "¡debe ser la mejor opción!\p"
	.string "Bueno, {PLAYER}, debo irme,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos, amigo inteligente!$"

gText_ApprenticePleaseTeach13::
	.string "¡Hola! ¡Tú!\n"
	.string "¿Podrías darme un masaje en el hombro?\p"
	.string "…¡Sí, ahí! ¡Eso es!\n"
	.string "¡Ay, ay! ¡Uff, se siente genial!\p"
	.string "Me llamo {STR_VAR_1}.\n"
	.string "Entreno karate, pero mi cuerpo no\l"
	.string "resiste tanto maltrato…\p"
	.string "Decidí luchar con POKéMON para\n"
	.string "hacerme más fuerte.\p"
	.string "Eres {PLAYER}{KUN}, ¿verdad?\n"
	.string "¿El CAMPEÓN de la LIGA POKéMON?\p"
	.string "Oye, ¿podrías darme algún\n"
	.string "consejo?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, ¿por qué?\p"
	.string "¡No molestaré mucho, lo prometo!\n"
	.string "¿Por favor?$"

gText_ApprenticeWhichLevelMode13::
	.string "Gracias. ¡Eres muy amable!\n"
	.string "...¡Cof! ¡Cof!\p"
	.string "Uff, debo fortalecerme rápido...\p"
	.string "Iré a la BATTLE TOWER ahora,\n"
	.string "pero ¿qué sería mejor para mí?\l"
	.string "¿NORMAL o HARD?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, está bien. Es {STR_VAR_1}.\n"
	.string "Iré allí ahora mismo.\p"
	.string "Espero poder pedirte ayuda\n"
	.string "más veces, ¡eres mi mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Eh... Este...\n"
	.string "{PLAYER}{KUN}...?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me pones muy nerviosa.\p"
	.string "Yo... soy {STR_VAR_1}.\p"
	.string "Me da mucha vergüenza decirlo,\n"
	.string "pero exploro ruinas antiguas y eso.\p"
	.string "Me da más vergüenza admitir que\n"
	.string "me interesa la BATTLE FRONTIER.\p"
	.string "{PLAYER}{KUN}, tienes fama de ser\n"
	.string "un TRAINER fuerte...\p"
	.string "Me cuesta decir esto,\n"
	.string "pero quiero pedirte algo.\p"
	.string "¿Podrías ser mi maestro y\n"
	.string "darme consejos?$"

gText_ApprenticeRejectTeaching14::
	.string "¡No me ignores así, por favor!\n"
	.string "No podría soportar la humillación.\p"
	.string "¡Por favor, sé mi maestro!\n"
	.string "¡Necesito tus consejos!$"

gText_ApprenticeWhichLevelMode14::
	.string "Gr-gracias...\p"
	.string "Pero no me mires así, por favor.\n"
	.string "Me pongo muy nerviosa.\p"
	.string "Por favor, respóndeme sin mirarme\n"
	.string "a los ojos.\p"
	.string "En la BATTLE TOWER...\n"
	.string "¿Qué nivel debería intentar?$"

gText_ApprenticeLevelModeThanks14::
	.string "¡Oh... De acuerdo!\n"
	.string "Intentaré hacer eso.\p"
	.string "Espero poder dar un reto valiente\n"
	.string "sin ponerme nerviosa...\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos volvemos a ver, espero que\l"
	.string "me ayudes igual.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Pareces ser {PLAYER}{KUN}...\n"
	.string "¿Pero eres real?\p"
	.string "Puedes llamarme {STR_VAR_1}.\p"
	.string "He pensado en la idea de ser\n"
	.string "aprendiz de un TRAINER fuerte.\p"
	.string "¡Tengo suerte de que aparecieras!\n"
	.string "...Realmente eres {PLAYER}{KUN}, ¿no?\p"
	.string "No, no, si eres real, está bien.\n"
	.string "Solo quiero que me reconozcas\l"
	.string "como tu aprendiz.$"

gText_ApprenticeRejectTeaching15::
	.string "¿Oh?\n"
	.string "¿Pero qué te obligaría a negarte?\p"
	.string "Pido disculpas por dudar de\n"
	.string "tu identidad.\p"
	.string "Por favor, acepta mis disculpas y\n"
	.string "acéptame como tu aprendiz.$"

gText_ApprenticeWhichLevelMode15::
	.string "¿De verdad me aceptas?\n"
	.string "No quiero celebrar antes de tiempo.\p"
	.string "Si es verdad, pido disculpas.\n"
	.string "Pero ahora necesito tu consejo.\p"
	.string "Si entro en la BATTLE TOWER,\n"
	.string "¿qué sería digno de mí?\l"
	.string "¿NORMAL o HARD?$"

gText_ApprenticeLevelModeThanks15::
	.string "¿{STR_VAR_1}?\n"
	.string "¿Estás seguro?\p"
	.string "Ya veo. Si es así, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Sé que puedo molestar, pero me alegra\n"
	.string "que me hayas aceptado.\p"
	.string "¡Nos vemos pronto!$"

gText_ApprenticeWhatHeldItem0::
	.string "Suspiro... Buaaa...\n"
	.string "¡Oh, {PLAYER}!\p"
	.string "Tengo un dilema terrible\n"
	.string "y no puedo decidirme.\p"
	.string "No sé qué objeto debería\n"
	.string "llevar mi {STR_VAR_1}.\p"
	.string "Dime, {PLAYER}.\n"
	.string "¿Qué objeto debería llevar?$"

gText_ApprenticeHoldNothing0::
	.string "¿En serio? ¿No debería hacer\n"
	.string "que mi {STR_VAR_1} lleve nada?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "¡Ah, vale! ¡Me alegra decidirlo!\n"
	.string "¡Genial! ¡Súper! ¡Awoooh!\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, me alegro mucho...\n"
	.string "Creo que yo también tengo ese {STR_VAR_1}.\p"
	.string "¡Me alegra haberlo decidido!\n"
	.string "¡Genial! ¡Súper! ¡Awoooh!\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "¡Buaaa! ¡No seas malo!\p"
	.string "Ese objeto {STR_VAR_1} ya me lo\n"
	.string "habían recomendado antes, bu…\p"
	.string "¿O quieres decir que no debo\n"
	.string "hacer que mi {STR_VAR_2} no lleve nada?$"

gText_ApprenticeWhatHeldItem1::
	.string "¡Sii! ¡Es {PLAYER}!\n"
	.string "¡Genial! ¡Quería preguntarte algo!\p"
	.string "¿Tus POKéMON llevan objetos?\n"
	.string "Quiero que los míos lleven, pero...\p"
	.string "¿Qué objeto sería bueno para\n"
	.string "que lleve {STR_VAR_1}?\p"
	.string "¿Tú qué crees?$"

gText_ApprenticeHoldNothing1::
	.string "¿Eh? ¿Quieres decir que mi {STR_VAR_1}\n"
	.string "no tiene que llevar nada?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "¡Ah, ya entiendo! ¡Haré eso!\n"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeThanksHeldItem1::
	.string "¡Vaya! Un {STR_VAR_1}, ¿eh?\n"
	.string "¡Está bien, lo haré!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, no, no me refería a eso.\n"
	.string "Quiero saber de un objeto distinto\l"
	.string "a los que ya conozco.\p"
	.string "¿O quieres decir que mi POKéMON no\n"
	.string "tiene que llevar nada esta vez?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, ¡hola!\n"
	.string "Es sobre mi {STR_VAR_1}…\p"
	.string "Quiero que lleve un buen objeto.\n"
	.string "¿Cuál sería el ideal?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, ¿entonces mi {STR_VAR_1} no tiene\n"
	.string "que llevar nada?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "¡Vale, ya entiendo!\n"
	.string "¡Nos vemos!$"

gText_ApprenticeThanksHeldItem2::
	.string "¿Oh, el objeto {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡Haré lo posible por encontrar uno!\n"
	.string "¡Nos vemos!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Alguien ya me habló sobre\n"
	.string "el {STR_VAR_1}.\p"
	.string "Quiero que mi POKéMON lleve un objeto\n"
	.string "de otro tipo.\p"
	.string "¿O crees que {STR_VAR_2} no tiene\n"
	.string "que llevar nada?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte, pero hay algo más\l"
	.string "que quería preguntarte.\p"
	.string "No creo ser tan bueno para ganar\n"
	.string "solo, así que pienso hacer que mi\l"
	.string "{STR_VAR_1} lleve un objeto.\p"
	.string "Pero no sé cuál sería el mejor.\p"
	.string "{PLAYER}, por favor, ¿podrías\n"
	.string "decidirlo tú?$"

gText_ApprenticeHoldNothing3::
	.string "¿Un POKéMON de alguien como yo\n"
	.string "estaría mejor sin un objeto?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Entiendo...\n"
	.string "Dices que no use objetos.\l"
	.string "¡Haré lo posible por no hacerlo!\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeThanksHeldItem3::
	.string "El objeto {STR_VAR_1}, ya veo.\n"
	.string "No sé si podré conseguir uno...\l"
	.string "¡No! Me esforzaré por conseguirlo.\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, pero...\n"
	.string "Creo que ya oí algo de eso...\p"
	.string "¿Será porque no usé bien\n"
	.string "el objeto {STR_VAR_1}?\p"
	.string "¿O quieres decir que mi\n"
	.string "{STR_VAR_2} no debe llevar nada?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hay algo que quería preguntarte.\p"
	.string "Tú decidiste qué POKéMON\n"
	.string "debería tener yo, ¿verdad?\p"
	.string "Pero nunca te pregunté qué objeto\n"
	.string "debería llevar equipado.\p"
	.string "Ya que me diste un consejo,\n"
	.string "¿por qué no terminar el trabajo?\p"
	.string "¿Qué sería bueno? Quiero que mi\n"
	.string "{STR_VAR_1} lleve algo equipado.$"

gText_ApprenticeHoldNothing4::
	.string "¡Oh! ¿Entonces mi {STR_VAR_1} debe\n"
	.string "dar lo mejor de sí sin objetos?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si crees que es lo mejor, así será.\p"
	.string "Sabiendo que tú decidiste,\n"
	.string "{PLAYER}{KUN}, no me pondré triste si\l"
	.string "pierdo.\p"
	.string "Bien, volveré a pedirte consejos.\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem4::
	.string "¿El objeto {STR_VAR_1}, eh?\n"
	.string "No está mal. ¡Lo usaré!\p"
	.string "Sabiendo que tú decidiste,\n"
	.string "{PLAYER}{KUN}, no me pondré triste si\l"
	.string "pierdo.\p"
	.string "Bien, volveré a pedirte consejos.\n"
	.string "¡Adiós!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "¿Eh? ¿Qué dices?\n"
	.string "Ya me habías hablado del {STR_VAR_1}\l"
	.string "antes.\p"
	.string "¿O dices que mi {STR_VAR_2} debe\n"
	.string "dar lo mejor sin llevar nada?$"

gText_ApprenticeWhatHeldItem5::
	.string "¡Hola, {PLAYER}{KUN}!\p"
	.string "Ambos estamos ocupados, pero\n"
	.string "¡nos vemos seguido de todos modos!\p"
	.string "Hoy debo caminar, limpiar\n"
	.string "y cepillar.\p"
	.string "Ni tiempo he tenido de comprarle\n"
	.string "algo a mi querido {STR_VAR_1}.\p"
	.string "No tengo tiempo, ¿me aconsejas\n"
	.string "qué debería hacer llevar\l"
	.string "a mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing5::
	.string "Ah, ¿dices que como estoy ocupado\n"
	.string "mi {STR_VAR_1} no necesita nada?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Vale, entiendo.\n"
	.string "Para eso no necesito tiempo.\p"
	.string "¡Gracias por hoy!\n"
	.string "¡Nos vemos!$"

gText_ApprenticeThanksHeldItem5::
	.string "Vale, entiendo.\n"
	.string "Buscaré tiempo para hallar ese\l"
	.string "{STR_VAR_1} que recomendaste.\p"
	.string "Me alegra tenerte como mentor.\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "¿Eh? Ya sé sobre\n"
	.string "ese {STR_VAR_1}.\p"
	.string "Ah, ya entiendo.\n"
	.string "Como soy alguien ocupado, ¿dices\l"
	.string "que mi {STR_VAR_2} no necesita nada?$"

gText_ApprenticeWhatHeldItem6::
	.string "¡Hola, {PLAYER}! ¡Soy yo!\n"
	.string "Hoy necesito tu ayuda otra vez.\l"
	.string "¡Por favor, dame un consejo!\p"
	.string "¡Redoble de tambores!\n"
	.string "Mi pregunta es...\p"
	.string "Si quiero que mi {STR_VAR_1} lleve\n"
	.string "un objeto, ¿cuál debería ser?$"

gText_ApprenticeHoldNothing6::
	.string "¿En serio? Dices que mi {STR_VAR_1}\n"
	.string "no necesita llevar ningún objeto.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "¡Vale, haré eso!\p"
	.string "Creo que es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Reunámonos aquí otra vez, ¿sí?\n"
	.string "¡Gracias!$"

gText_ApprenticeThanksHeldItem6::
	.string "¡Ajá! Un {STR_VAR_1}.\n"
	.string "¡Qué buena elección!\l"
	.string "¡Sin duda lo intentaré!\p"
	.string "Creo que es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Reunámonos aquí otra vez, ¿sí?\n"
	.string "¡Gracias!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "¡Jajaja! ¡Qué tontería!\n"
	.string "¡Ya me habías hablado de ese\l"
	.string "{STR_VAR_1} antes!\p"
	.string "¿Te sientes bien, {PLAYER}?\p"
	.string "¡Ah, espera! Dices que mi {STR_VAR_2}\n"
	.string "no necesita llevar un objeto.$"

gText_ApprenticeWhatHeldItem7::
	.string "Hola, {PLAYER}. Espero que\n"
	.string "estés muy bien.\p"
	.string "¿Puedo pedirte un consejo?\p"
	.string "En una batalla reciente, mi rival\n"
	.string "parecía haber dado a su POKéMON\l"
	.string "un objeto para llevar.\p"
	.string "Por eso, fui derrotado...\p"
	.string "No quiero quedarme atrás.\n"
	.string "Quiero que mi {STR_VAR_1}\l"
	.string "lleve un objeto también.\p"
	.string "Me gustaría que decidieras\n"
	.string "qué sería lo ideal para mi POKéMON...$"

gText_ApprenticeHoldNothing7::
	.string "En otras palabras... ¿Mi POKéMON\n"
	.string "no necesita llevar un objeto?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "¡Ahora lo entiendo todo!\n"
	.string "Seguiré intentándolo así.\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero contar contigo otra vez.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeThanksHeldItem7::
	.string "¡Un {STR_VAR_1} será!\n"
	.string "Lo pediré ahora mismo.\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero contar contigo otra vez.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Ya me lo habías dicho,\n"
	.string "y ya lo tengo.\p"
	.string "¿O quieres decir que mi POKéMON\n"
	.string "no necesita llevar un objeto?$"

gText_ApprenticeWhatHeldItem8::
	.string "¡Ay! {PLAYER}!\n"
	.string "Yo... ¡qué alegría verte de nuevo!\p"
	.string "¡Oh, oh, oh! Hay algo que\n"
	.string "tenía que preguntarte, {PLAYER}!\p"
	.string "¡Decide qué debería llevar mi {STR_VAR_1}\n"
	.string "a partir de ahora!$"

gText_ApprenticeHoldNothing8::
	.string "¡Vaya! ¡No esperaba esa respuesta!\n"
	.string "¿Entonces no necesita un objeto?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "¡Entendido perfectamente!\n"
	.string "¡Seguiré así sin ningún objeto!\p"
	.string "Espero que quieras enseñarme\n"
	.string "más cosas en otra ocasión.$"

gText_ApprenticeThanksHeldItem8::
	.string "¡{STR_VAR_1}! ¡Usaré eso!\p"
	.string "Um... {PLAYER}, ¿tú también haces\n"
	.string "que tus POKéMON lleven eso?\p"
	.string "¡Me aseguraré de conseguirlo!\n"
	.string "Espero que quieras enseñarme\l"
	.string "más cosas en otra ocasión.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "¿Oh? Ya me habías recomendado\n"
	.string "ese {STR_VAR_1} antes.\p"
	.string "¿O es que es el mejor objeto?\n"
	.string "¿O quieres decir que mi {STR_VAR_2}\l"
	.string "no necesita llevar nada?$"

gText_ApprenticeWhatHeldItem9::
	.string "¡Hola!\n"
	.string "¡Mi maestro, {PLAYER}{KUN}!\p"
	.string "Quiero pedirte consejo sobre\n"
	.string "objetos POKéMON.\p"
	.string "¿Qué crees que sería bueno que\n"
	.string "lleve mi {STR_VAR_1}?\p"
	.string "No seas tímido.\n"
	.string "¡Dímelo ya!$"

gText_ApprenticeHoldNothing9::
	.string "¿Oh? ¿Dices que mi {STR_VAR_1}\n"
	.string "puede ganar sin llevar objetos?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "¡Sí, bueno!\n"
	.string "¡Daré lo mejor de mí, a tope!\p"
	.string "¡Muy bien, gracias como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem9::
	.string "Ajá, ¿solo un {STR_VAR_1}?\n"
	.string "¡Sí, bueno!\l"
	.string "¡Iré a buscar uno, así, pum!\p"
	.string "¡Está bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "¡No, no! Ya me habías hablado de\n"
	.string "ese {STR_VAR_1} antes.\p"
	.string "Oh, espera un minuto...\n"
	.string "¿Dices que mi {STR_VAR_2}\l"
	.string "ganará sin llevar ningún objeto?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, ¡ha pasado algo\n"
	.string "increíble!\p"
	.string "Desperté hoy y mi POKéMON\n"
	.string "¡tenía 10 PEPITAS!\p"
	.string "¡Claro que miento!\n"
	.string "¡Jajajaja!\p"
	.string "Pero esto no es mentira.\n"
	.string "No soy bueno pensando en qué\l"
	.string "objetos deben llevar los POKéMON.\p"
	.string "¿Decidirías qué debe llevar mi\n"
	.string "{STR_VAR_1}, maestro?$"

gText_ApprenticeHoldNothing10::
	.string "¿Qué significa eso?\n"
	.string "¿Que no lleve nada puesto?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Vale, que no lleve nada.\n"
	.string "¡Mejor busco algo para él!\p"
	.string "¡Es broma!\n"
	.string "¡Seguiré tus enseñanzas, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeThanksHeldItem10::
	.string "¡Vale, entonces es un {STR_VAR_1}!\n"
	.string "¡Le daré cualquier cosa menos eso!\p"
	.string "¡Es broma!\n"
	.string "¡Seguiré tus enseñanzas, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Eh, ya me habías dicho eso,\n"
	.string "¿no es así?\p"
	.string "¿No hay algo más?\p"
	.string "¿O quieres decir que mi\n"
	.string "{STR_VAR_2} no cargue nada?$"

gText_ApprenticeWhatHeldItem11::
	.string "¡A-H-O-Y!\n"
	.string "¡Y eso se lee ahoy!\p"
	.string "¡Soy el MARINERO rapero!\n"
	.string "¡Te traigo una pregunta\l"
	.string "que es muy genial!\p"
	.string "¡Es una duda de objetos\n"
	.string "que pide tu sugerencia!\p"
	.string "Mi {STR_VAR_1} necesita un objeto,\n"
	.string "¿cuál sería, si me permites?$"

gText_ApprenticeHoldNothing11::
	.string "¿Es cierto?\n"
	.string "¿Mi {STR_VAR_1} no necesita\l"
	.string "llevar ningún objeto?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "¡Vale, te escucho, claro que sí!\n"
	.string "¡Mi POKéMON irá sin nada también!\p"
	.string "Si algún día necesito un consejo,\n"
	.string "{PLAYER}, ¡siempre te escucharé!$"

gText_ApprenticeThanksHeldItem11::
	.string "Vale, un {STR_VAR_1},\n"
	.string "eso es lo que usaré.\l"
	.string "¡Hice bien en dejar que eligieras!\p"
	.string "Si algún día necesito un consejo,\n"
	.string "{PLAYER}, ¡siempre te escucharé!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "¿Vale, un {STR_VAR_1}, dices?\n"
	.string "Ya me dijiste eso el otro día.\l"
	.string "Necesito una idea, algo nuevo.\p"
	.string "O, ¿qué, es cierto?\n"
	.string "¿Mi POKéMON no necesita llevar\l"
	.string "ningún objeto?$"

gText_ApprenticeWhatHeldItem12::
	.string "¡Oye, {PLAYER}!\n"
	.string "¡Te encontré otra vez hoy!\p"
	.string "¿Qué hago? ¿Me das un consejo?\n"
	.string "¡Claro! ¡Ya estoy hablando contigo!\p"
	.string "{PLAYER}, ¿te cansaste de mí?\n"
	.string "No, no puede ser, ¡imposible!\p"
	.string "¿Me escucharás?\n"
	.string "Busco un consejo, de eso\l"
	.string "estoy hablando.\p"
	.string "Es sobre un objeto para\n"
	.string "mi {STR_VAR_1} que sea bueno.\l"
	.string "Mi indecisión me tiene mal.$"

gText_ApprenticeHoldNothing12::
	.string "¿Mi {STR_VAR_1} no necesita nada?\n"
	.string "¿No tiene que llevar ningún objeto?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Si no llevar nada es lo mejor,\n"
	.string "¡haré lo que sugieres!\p"
	.string "Bueno, {PLAYER}, debo irme,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos, mi inteligente amigo!$"

gText_ApprenticeThanksHeldItem12::
	.string "Si llevar ese {STR_VAR_1} es\n"
	.string "lo mejor, ¡haré lo que sugieres!\p"
	.string "Bueno, {PLAYER}, debo irme,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos, mi inteligente amigo!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "¿No he oído hablar de ese\n"
	.string "{STR_VAR_1} antes?\l"
	.string "¡Seguro que sí, estoy convencido!\p"
	.string "¡Necesito algo nuevo!\n"
	.string "¿O mi {STR_VAR_2} no necesita nada?\l"
	.string "¿No tiene que llevar ningún objeto?$"

gText_ApprenticeWhatHeldItem13::
	.string "¡Gwah! ¡Ay! {PLAYER}{KUN}, ¡mi brazo!\n"
	.string "¡No lo toques, por favor!\p"
	.string "Debí romperlo probando objetos\n"
	.string "con mi grupo\l"
	.string "de POKéMON.\p"
	.string "Así que, dadas las cosas,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, ¿qué crees que sería\n"
	.string "bueno que lleve mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing13::
	.string "Ay...\p"
	.string "¿Entonces sugieres que mi {STR_VAR_1}\n"
	.string "no tenga que llevar nada?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, está bien. Sería más fácil\n"
	.string "para mí en este momento.\p"
	.string "Espero poder seguir pidiéndote\n"
	.string "ayuda como esta.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, está bien. Ese {STR_VAR_1}.\n"
	.string "El brazo de mi POKéMON está bien,\l"
	.string "así que le daré el objeto ahora.\p"
	.string "Espero poder seguir pidiéndote\n"
	.string "ayuda como esta.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, ya me hablaste de ese\n"
	.string "{STR_VAR_1} antes, ¿recuerdas?\p"
	.string "¿Qué tal si me dices algo\n"
	.string "aún mejor?\p"
	.string "Oh, espera un segundo.\n"
	.string "¿Sugieres que mi {STR_VAR_2}\l"
	.string "no tenga que llevar nada?$"

gText_ApprenticeWhatHeldItem14::
	.string "Eh... Este...\n"
	.string "{PLAYER}{KUN}...\p"
	.string "Por favor, no me mires así.\n"
	.string "Mis POKéMON no tienen nada.\p"
	.string "Estoy muy avergonzado por esto,\n"
	.string "pero necesito tu consejo.\p"
	.string "No sé qué objeto haría que mi\n"
	.string "{STR_VAR_1} sea fuerte.\p"
	.string "{PLAYER}{KUN}, ¿qué crees que\n"
	.string "sería bueno?$"

gText_ApprenticeHoldNothing14::
	.string "Oh... Entonces, ¿crees que sería\n"
	.string "mejor que mi {STR_VAR_1} no lleve nada?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh... ¡Está bien!\n"
	.string "Iré sin ningún objeto.\p"
	.string "Aun así, estoy muy nervioso.\n"
	.string "¿No sería genial?\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos vemos, espero que seas\l"
	.string "tan amable.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh... ¡Está bien!\n"
	.string "Iré con ese {STR_VAR_1}.\p"
	.string "Aun así, estoy muy nervioso.\n"
	.string "¿No sería genial?\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos vemos, espero que seas\l"
	.string "tan amable.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "P-pero ya escuché sobre eso.\p"
	.string "¡No me ignores así, por favor!\n"
	.string "No soportaría la humillación.\p"
	.string "Oh... ¿estoy adelantándome?\n"
	.string "¿Crees que sería mejor que\l"
	.string "mi {STR_VAR_2} no lleve objeto?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? Pareces ser {PLAYER}{KUN}...\n"
	.string "¿Pero realmente lo eres?\l"
	.string "¿Quizás eres su gemelo?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si eres {PLAYER}, olvida\l"
	.string "mi grosería, por favor.\p"
	.string "Me gustaría recibir más de\n"
	.string "tus buenos consejos.\p"
	.string "Tengo a mi {STR_VAR_1} y quiero\n"
	.string "que lleve un objeto útil.\p"
	.string "¿Cuál sería el ideal?$"

gText_ApprenticeHoldNothing15::
	.string "¿Es mejor que no lleve nada?\n"
	.string "¿Estás seguro?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Ya veo. Si es así, está bien.\n"
	.string "Gracias por tu tiempo.\p"
	.string "¡Nos vemos luego!$"

gText_ApprenticeThanksHeldItem15::
	.string "¿Un {STR_VAR_1}?\n"
	.string "¿Estás seguro?\p"
	.string "Ya veo. Si es así, está bien.\n"
	.string "Gracias por tu tiempo.\p"
	.string "Espero que mi POKéMON pueda\n"
	.string "aprovecharlo bien.\p"
	.string "¡Nos vemos luego!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, espera un momento.\n"
	.string "Creo que ya me enseñaste eso.\p"
	.string "Me gustaría que me recomiendes\n"
	.string "algo diferente esta vez.\p"
	.string "¿Acaso sugieres que mi\n"
	.string "{STR_VAR_2} no debe llevar nada?\l"
	.string "¿Estás seguro?$"

gText_ApprenticeWhichMonFirst0::
	.string "¡Waah, {PLAYER}!\n"
	.string "Tengo un dilema, buaa...\p"
	.string "Quiero luchar contra otros,\n"
	.string "pero no sé qué hacer.\p"
	.string "¿Cómo pongo a mis POKéMON\n"
	.string "para que sean más fuertes?\p"
	.string "Dime, {PLAYER}.\n"
	.string "Si fueras yo, ¿cuál de estos POKéMON\l"
	.string "enviarías primero?$"

gText_ApprenticeMonFirstThanks0::
	.string "¿Mi {STR_VAR_1} debe ir primero?\n"
	.string "¡Waaaaah!\p"
	.string "¡Oh! ¡Lo siento mucho!\n"
	.string "Me hiciste feliz al elegir\l"
	.string "mi primer POKéMON, y lloré...\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMonFirst1::
	.string "¡Sii! ¡Es {PLAYER}!\n"
	.string "¡Genial! ¡Quería preguntarte algo!\p"
	.string "Eh, de mis POKéMON, ¿cuál crees\n"
	.string "que debería salir primero?$"

gText_ApprenticeMonFirstThanks1::
	.string "¿Mi {STR_VAR_1}? Es verdad.\n"
	.string "¡Vale, haré eso!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, ¡hola!\p"
	.string "Creo que en una batalla es muy\n"
	.string "importante quién sale primero.\p"
	.string "De los POKéMON que tengo,\n"
	.string "¿cuál sería bueno enviar primero?$"

gText_ApprenticeMonFirstThanks2::
	.string "¿Mi {STR_VAR_1} va primero?\n"
	.string "¡Vale, ya entiendo!\p"
	.string "¡Nos vemos luego!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hola, {PLAYER}...\n"
	.string "Siento molestarte otra vez con\l"
	.string "otra pregunta.\p"
	.string "Tengo tan poca confianza que no\n"
	.string "sé qué haría sin ti, {PLAYER}.\p"
	.string "Quizás sea perder el tiempo\n"
	.string "preocuparme, pero no puedo\l"
	.string "decidir algo...\p"
	.string "¿Cuál de mis POKéMON debería\n"
	.string "enviar primero en batalla?$"

gText_ApprenticeMonFirstThanks3::
	.string "¿Mi {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡No creo que te molestes en\n"
	.string "responder mis dudas tan seguido!\p"
	.string "Estoy muy agradecido de que\n"
	.string "hables conmigo... ¡Gracias!$"

gText_ApprenticeWhichMonFirst4::
	.string "¡Oh, {PLAYER}{KUN}! ¡Soy yo!\n"
	.string "Me alegra verte, porque tengo\l"
	.string "un pequeño problema.\p"
	.string "No sé cómo ordenar a mis POKéMON.\n"
	.string "¿Podrías decidirlo por mí?\p"
	.string "No hace falta que decidas todo el\n"
	.string "equipo ahora mismo.\p"
	.string "¿Qué tal si eliges solo al primer\n"
	.string "POKéMON por mí?$"

gText_ApprenticeMonFirstThanks4::
	.string "¿Mi {STR_VAR_1}? ¡Genial!\p"
	.string "Sabiendo que tú lo decidiste,\n"
	.string "{PLAYER}{KUN}, no me dolerá tanto\l"
	.string "si pierdo.\p"
	.string "Bien, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMonFirst5::
	.string "¡Hola, mi maestro {PLAYER}{KUN}!\n"
	.string "¡Hoy estoy ocupado otra vez!\p"
	.string "Tengo que pedalear, comprar\n"
	.string "y tararear.\p"
	.string "Ni he tenido tiempo de decidir\n"
	.string "el orden de mi equipo POKéMON.\p"
	.string "¿Podrías revisar mi equipo?\n"
	.string "¿Cuál debería ir primero?$"

gText_ApprenticeMonFirstThanks5::
	.string "Vale, entiendo.\n"
	.string "¡Al menos tengo tiempo de poner\l"
	.string "a {STR_VAR_1} al principio!\p"
	.string "¡Uy, mi novia me espera!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMonFirst6::
	.string "¡Yoohoo! ¡Hola, {PLAYER}!\n"
	.string "¡Siempre caminas con aire rudo!\p"
	.string "¡Oye, necesito algo de ti\n"
	.string "otra vez! ¡Lo de siempre!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "Mi duda es sobre mi equipo.\p"
	.string "¿Qué POKéMON debería salir primero\n"
	.string "en una batalla?$"

gText_ApprenticeMonFirstThanks6::
	.string "¡Hmhm!\n"
	.string "¡Mi {STR_VAR_1}, dices!\l"
	.string "¡Gracias por esa respuesta genial!\p"
	.string "Creo que eso es todo lo que\n"
	.string "quería preguntarte hoy.\p"
	.string "Reunámonos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMonFirst7::
	.string "Muchas gracias por detenerte a\n"
	.string "charlar conmigo, {PLAYER}.\p"
	.string "Sé que abuso de tu amabilidad,\n"
	.string "¿pero puedo pedirte un consejo?\p"
	.string "Me gustaría que decidieras el orden\n"
	.string "de mi equipo POKéMON.\p"
	.string "Me haría feliz que eligieras\n"
	.string "qué POKéMON debería ir primero.$"

gText_ApprenticeMonFirstThanks7::
	.string "¡Será mi {STR_VAR_1}!\n"
	.string "¡Lo pondré primero ahora mismo!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeWhichMonFirst8::
	.string "¡Ay! {PLAYER}!\n"
	.string "¡Estoy feliz de verte otra vez!\p"
	.string "¡Mis POKéMON se han vuelto mucho\n"
	.string "más fuertes!\p"
	.string "Pero no siempre gano. Parece que\n"
	.string "depende de quién vaya primero.\p"
	.string "{PLAYER}, ¡por favor, ayúdame!\p"
	.string "¡Decide cuál de mis POKéMON\n"
	.string "debe salir primero!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh... Estoy muy feliz...\p"
	.string "Es como un sueño que decidas\n"
	.string "por mí, {PLAYER}.\p"
	.string "¡Entendido perfectamente!\n"
	.string "¡Iré con mi {STR_VAR_1} primero!\p"
	.string "Espero que quieras enseñarme\n"
	.string "más cosas en otra ocasión.$"

gText_ApprenticeWhichMonFirst9::
	.string "¡Hola, hola!\n"
	.string "¡Mi mentor, {PLAYER}{KUN}!\l"
	.string "¡Dame hoy tu sabio consejo!\p"
	.string "Mira, armé un equipo de\n"
	.string "tres POKéMON. Todo va bien.\p"
	.string "Pero el orden de batalla\n"
	.string "aún no está decidido.\p"
	.string "¡Aquí entras tú, {PLAYER}{KUN}!\n"
	.string "¡Tú decides qué POKéMON lidera!\p"
	.string "No seas tímido.\n"
	.string "¡Dilo ya mismo!$"

gText_ApprenticeMonFirstThanks9::
	.string "¡Ajá, mi {STR_VAR_1} lidera!\n"
	.string "¡Vale, todo bien!\l"
	.string "¡Reordenaré el equipo, así, pum!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, ¡escucha!\n"
	.string "¡Es una crisis!\p"
	.string "¡Mis tres POKéMON entran\n"
	.string "en batalla a la vez!\p"
	.string "¡Claro que es imposible!\n"
	.string "¡Wahahaha!\p"
	.string "Pero no es mentira.\n"
	.string "No soy bueno pensando en\l"
	.string "cómo alinear a mis POKéMON.\p"
	.string "¿Podrías decidir por mí quién\n"
	.string "va primero, maestro?$"

gText_ApprenticeMonFirstThanks10::
	.string "¿Vale, elegiste a mi {STR_VAR_1}?\n"
	.string "¡Haré que cualquier otro vaya primero!\p"
	.string "¡Es broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeWhichMonFirst11::
	.string "¡A-H-O-Y!\n"
	.string "¡Eso significa ahoy!\p"
	.string "¡Soy el MARINERO rapero!\n"
	.string "¡Te presento una pregunta\l"
	.string "que es muy genial!\p"
	.string "¡Es una duda sobre el equipo\n"
	.string "que pide tu sugerencia!\p"
	.string "De este grupo, ¿cuál debe ir\n"
	.string "primero en el lugar?$"

gText_ApprenticeMonFirstThanks11::
	.string "¡Vale, te escucho, claro que sí!\n"
	.string "¡Los cambiaré, así lo haré!\p"
	.string "Si alguna vez necesito un consejo,\n"
	.string "{PLAYER}, ¡siempre te haré caso!$"

gText_ApprenticeWhichMonFirst12::
	.string "¡Yahoo, {PLAYER}!\n"
	.string "¿Cómo estás?\p"
	.string "¿Qué hago? ¿Te pregunto ya?\n"
	.string "¡Sí, tengo algo que preguntarte!\l"
	.string "¿Me escuchas?\l"
	.string "¡Me escuchas!\p"
	.string "Debes decidir cuál de mis\n"
	.string "POKéMON debe ir primero\l"
	.string "en la batalla.$"

gText_ApprenticeMonFirstThanks12::
	.string "¿Mi {STR_VAR_1}? ¡Sí!\n"
	.string "¡Eso servirá, no hay problema!\p"
	.string "Bueno, {PLAYER}, debo irme,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos, mi inteligente amigo!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uff… ay… {PLAYER}{KUN}…\n"
	.string "Me duele el estómago de repente…\p"
	.string "…Ya me siento mejor…\p"
	.string "Debí estresarme mucho pensando\n"
	.string "cómo organizar a mi grupo\l"
	.string "de POKéMON.\p"
	.string "Así que, siendo así,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, ¿qué POKéMON debe\n"
	.string "ir primero para que yo gane?$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, está bien.\n"
	.string "Mi {STR_VAR_1} irá primero.\p"
	.string "Arreglaré el orden después\n"
	.string "de cenar.\p"
	.string "Espero poder pedirte ayuda\n"
	.string "así nuevamente.$"

gText_ApprenticeWhichMonFirst14::
	.string "Eh… Este…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me pones muy nervioso.\p"
	.string "Este…\n"
	.string "Realmente necesito tu consejo.\p"
	.string "Me da pena decir esto,\n"
	.string "pero ya elegí mi equipo de 3 POKéMON.\l"
	.string "No decido el orden.\p"
	.string "¿Qué POKéMON envío primero\n"
	.string "para parecer capaz?$"

gText_ApprenticeMonFirstThanks14::
	.string "¡Oh… Vale!\n"
	.string "Lideraré con mi {STR_VAR_1}.\p"
	.string "Espero dar lo mejor sin\n"
	.string "ponerme nervioso.\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos vemos, espero que seas\l"
	.string "tan servicial.$"

gText_ApprenticeWhichMonFirst15::
	.string "¿Hm? Pareces ser {PLAYER}{KUN}…\n"
	.string "¿Pero lo eres realmente?\l"
	.string "¿O eres un imitador astuto?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si eres {PLAYER}, olvida\l"
	.string "mi grosería.\p"
	.string "Quisiera tu buen consejo.\p"
	.string "Tengo aquí mi equipo POKéMON.\n"
	.string "Dime cuál de ellos\l"
	.string "debería ir primero en batalla.$"

gText_ApprenticeMonFirstThanks15::
	.string "Mi {STR_VAR_1}…\n"
	.string "¿No me estás tomando el pelo?\p"
	.string "Ya veo. Si es así, está bien.\n"
	.string "Gracias por tu tiempo.\p"
	.string "Soy como ves, pero daré\n"
	.string "lo mejor de mí.\p"
	.string "¡Encontrémonos de nuevo!$"

gText_ApprenticeWhichMon0::
	.string "Snivel…\n"
	.string "¡Oh, {PLAYER}!\p"
	.string "¡Llegas en el momento justo!\n"
	.string "Hay algo que no puedo decidir…\p"
	.string "No sé qué POKéMON debería\n"
	.string "estar usando.\p"
	.string "No me decido entre el POKéMON\n"
	.string "{STR_VAR_1} y {STR_VAR_2}…\p"
	.string "{PLAYER}, ¿cuál crees que me daría\n"
	.string "una oportunidad de ganar?$"

gText_ApprenticeMonThanks0::
	.string "Snivel… ¡Yo… lo entiendo!\n"
	.string "¡Oh! ¡Lo siento mucho!\l"
	.string "Me hiciste tan feliz que lloro…\p"
	.string "¡Haré lo posible por capturar un\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMon1::
	.string "¡Sii! ¡Es {PLAYER}!\n"
	.string "¡Sii, llegaste justo a tiempo!\l"
	.string "¡Necesito tu consejo otra vez!\p"
	.string "Eh, estoy confundido... ¿uso mi\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\p"
	.string "¿Cuál crees que debería criar,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "¡Oh, entonces mi {STR_VAR_1} es mejor!\n"
	.string "¡Está bien, haré eso!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, ¡hola!\n"
	.string "Tengo una pregunta que hacerte.\p"
	.string "Tengo el dilema de si debería\n"
	.string "criar un {STR_VAR_1} o {STR_VAR_2}.\p"
	.string "¿Qué POKéMON crees que\n"
	.string "será más fuerte?$"

gText_ApprenticeMonThanks2::
	.string "¿Tu elección es {STR_VAR_1}?\n"
	.string "¡Vale, ya entendí!\p"
	.string "¡Iré a capturar un {STR_VAR_1}\n"
	.string "fuerte ahora mismo!\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMon3::
	.string "Hola, {PLAYER}…\p"
	.string "Eh, seguro ya te olvidaste de\n"
	.string "alguien como yo…\p"
	.string "…Pero no importa si pudieras\n"
	.string "darme un consejo…\p"
	.string "No decido qué tipo de\n"
	.string "POKéMON debería criar…\p"
	.string "Me quedan el POKéMON\n"
	.string "{STR_VAR_1} y {STR_VAR_2}, pero ahí\l"
	.string "me quedé trabado…\p"
	.string "{PLAYER}, seguro no quieres\n"
	.string "molestarte, pero elige por mí.$"

gText_ApprenticeMonThanks3::
	.string "¿Pero un {STR_VAR_1} salvaje me\n"
	.string "hará caso a mí?\p"
	.string "¡Lo intentaré!\p"
	.string "¿Pero podré capturar uno…\n"
	.string "¡No! ¡Daré lo mejor de mí!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon4::
	.string "¡Oh, {PLAYER}{KUN}! ¡Qué alegría verte!\n"
	.string "¡Iba justo a buscarte!\p"
	.string "¿Puedes decidir qué tipo de POKéMON\n"
	.string "debería usar?\p"
	.string "Por ejemplo...\n"
	.string "¿Qué tal los POKéMON {STR_VAR_1}\l"
	.string "y {STR_VAR_2}?\p"
	.string "¿Cuál crees que sería\n"
	.string "mejor?$"

gText_ApprenticeMonThanks4::
	.string "¿{STR_VAR_1}? ¡Genial!\p"
	.string "Sabiendo que tú lo decidiste,\n"
	.string "{PLAYER}{KUN}, no me pondré triste si\l"
	.string "pierdo.\p"
	.string "Bien, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMon5::
	.string "¡Si es {PLAYER}{KUN}! ¿Cómo va todo?\n"
	.string "¡Estoy ocupado como siempre!\p"
	.string "Yo también quiero ser bueno con los\n"
	.string "POKéMON, pero no he podido decidir\l"
	.string "qué POKéMON debería usar.\p"
	.string "¿Ves que {STR_VAR_1} se ve fuerte?\n"
	.string "Pero {STR_VAR_2} es difícil de ignorar.\p"
	.string "{PLAYER}{KUN}, ¡dame un buen consejo!\n"
	.string "¿Cuál sería bueno para mí?$"

gText_ApprenticeMonThanks5::
	.string "Vale, entiendo.\n"
	.string "Buscaré tiempo y atraparé a ese\l"
	.string "{STR_VAR_1} que me recomendaste.\p"
	.string "Me alegra tenerte como mentor.\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMon6::
	.string "¡Oh!\n"
	.string "¡Súper, es {PLAYER}!\p"
	.string "¡No perdí tiempo presumiendo con\n"
	.string "mis amigos que te conocí!\p"
	.string "Hoy necesito tu ayuda otra vez.\n"
	.string "¡Esto será fácil para ti!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "Mi pregunta es...\p"
	.string "Si fuera a criar un POKéMON,\n"
	.string "¿entre {STR_VAR_1}\l"
	.string "o {STR_VAR_2}, cuál debería ser?$"

gText_ApprenticeMonThanks6::
	.string "¡Ahhh!\n"
	.string "¡{STR_VAR_1}, dices!\l"
	.string "¡Gracias por esa respuesta genial!\p"
	.string "Creo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Reunámonos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon7::
	.string "Oh, ¿eres tú, {PLAYER}?\n"
	.string "¡Me encanta verte de nuevo!\p"
	.string "Desde que soy tu aprendiz,\n"
	.string "mi confianza ha florecido.\p"
	.string "¡Creo que estoy listo para criar un\n"
	.string "POKéMON propio!\p"
	.string "{PLAYER}, ¿podrías elegir qué\n"
	.string "POKéMON debería criar?\p"
	.string "Las opciones son los POKéMON\n"
	.string "{STR_VAR_1} o {STR_VAR_2}...\l"
	.string "¿Cuál es el indicado para mí?$"

gText_ApprenticeMonThanks7::
	.string "¡Será un {STR_VAR_1}!\n"
	.string "¡Buscaré uno ahora mismo!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeWhichMon8::
	.string "¡Ay! ¡{PLAYER}! ¡Te vi otra vez!\n"
	.string "¡Estoy... muy feliz!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¡No debo dejar pasar esto!\p"
	.string "¿Me haces un gran favor, {PLAYER}?\n"
	.string "¡Elige un POKéMON por mí!\p"
	.string "¡Dime cuál sería mejor,\n"
	.string "{STR_VAR_1} o {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "¡Guau! ¡Decidiste por mí!\n"
	.string "Criaré un {STR_VAR_1} con\l"
	.string "todas mis fuerzas.\p"
	.string "Espero que quieras enseñarme\n"
	.string "más cosas en otro momento.$"

gText_ApprenticeWhichMon9::
	.string "¡Oye, oye!\n"
	.string "¡Mi mentor, {PLAYER}{KUN}!\p"
	.string "¡Hola! Te buscaba para recibir\n"
	.string "más de tus sabios consejos.\p"
	.string "¿Qué POKéMON sería ideal para mí,\n"
	.string "un {STR_VAR_1} o {STR_VAR_2}?\p"
	.string "No seas tímido.\n"
	.string "¡Dímelo ya mismo!$"

gText_ApprenticeMonThanks9::
	.string "¡Ajá, entonces será un {STR_VAR_1}!\n"
	.string "¡Vale, todo bien!\l"
	.string "¡Atraparé uno en una BALL ya mismo!\p"
	.string "¡Muy bien, gracias como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, ¡escucha! ¡Gran noticia!\n"
	.string "¡Atrapé un POKéMON espejismo!\p"
	.string "¡Claro que miento!\n"
	.string "¡Wahahaha!\p"
	.string "Pero esto no es mentira.\n"
	.string "No soy muy bueno atrapando\l"
	.string "POKéMON.\p"
	.string "¿Qué tal si decides por mí qué\n"
	.string "POKéMON debería atrapar,\l"
	.string "maestro?\p"
	.string "¿Cuál sería mejor?\n"
	.string "{STR_VAR_1} o {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "¿Vale, entonces elegiste {STR_VAR_1}?\n"
	.string "¡Atraparé el otro entonces!\p"
	.string "¡Es broma!\n"
	.string "¡Seguiré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeWhichMon11::
	.string "¡A-H-O-Y!\n"
	.string "¡Eso se dice ahoy!\p"
	.string "¡Soy el MARINERO rapero!\n"
	.string "¿Seguro que recuerdas quién soy?\p"
	.string "Hoy tengo una duda POKéMON\n"
	.string "que requiere tu sugerencia.\p"
	.string "Debo elegir entre este\n"
	.string "{STR_VAR_1} y {STR_VAR_2}.\l"
	.string "¿Cuál debería atrapar yo?$"

gText_ApprenticeMonThanks11::
	.string "¡{STR_VAR_1}, dices, oye, oye!\n"
	.string "¡Iré a buscar uno ahora mismo!\p"
	.string "Si alguna vez necesito un consejo,\n"
	.string "{PLAYER}, ¡siempre te escucharé!$"

gText_ApprenticeWhichMon12::
	.string "¡Vaya, pero si es {PLAYER}!\p"
	.string "¿Qué hago? ¿Pido tu consejo?\n"
	.string "¡Claro! ¡Ya estoy hablando contigo!\p"
	.string "Ha pasado tiempo. Para romper\n"
	.string "el hielo, ¡yo también quiero ayuda!\l"
	.string "¿Me escuchas?\l"
	.string "¡Me escuchas!\p"
	.string "Mis POKéMON... ¿cuál uso?\n"
	.string "Es {STR_VAR_1} o {STR_VAR_2}.\l"
	.string "¿Cuál eliges?$"

gText_ApprenticeMonThanks12::
	.string "Si {STR_VAR_1} es el mejor,\n"
	.string "¡haré lo que sugieres!\p"
	.string "Bueno, {PLAYER}, debo irme,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos, amigo inteligente!$"

gText_ApprenticeWhichMon13::
	.string "Hola, {PLAYER}{KUN}...\n"
	.string "Tengo un dolor de cabeza horrible...\p"
	.string "Debí preocuparme demasiado por\n"
	.string "qué POKéMON debería criar.\p"
	.string "Así que, estando así las cosas,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, si tuviera que elegir\n"
	.string "entre {STR_VAR_1} y\l"
	.string "{STR_VAR_2}, ¿cuál sería?$"

gText_ApprenticeMonThanks13::
	.string "Hm, {STR_VAR_1}, está bien.\n"
	.string "Buscaré uno cuando me sienta mejor.\p"
	.string "Espero poder seguir pidiéndote\n"
	.string "ayuda así.$"

gText_ApprenticeWhichMon14::
	.string "Eh... Este...\n"
	.string "{PLAYER}{KUN}...?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me pongo muy nerviosa...\l"
	.string "Yo... necesito tu consejo.\p"
	.string "Estoy avergonzada, pero no puedo\n"
	.string "decidir qué POKéMON usar.\p"
	.string "Si fueran {STR_VAR_1} o\n"
	.string "{STR_VAR_2}, ¿cuál sería mejor?$"

gText_ApprenticeMonThanks14::
	.string "¡Oh... Vale!\n"
	.string "Daré lo mejor con {STR_VAR_1}.\p"
	.string "Espero dar lo mejor sin\n"
	.string "ponerme tan nerviosa.\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos vemos, espero que seas\l"
	.string "tan servicial.$"

gText_ApprenticeWhichMon15::
	.string "¿Hm? Pareces ser {PLAYER}{KUN}…\n"
	.string "¿Pero eres real?\p"
	.string "No, no, si eres real, está bien.\n"
	.string "Por cierto, me gustaría obtener\l"
	.string "tu consejo.\p"
	.string "Es sobre el POKéMON que usaré.\p"
	.string "Si las opciones son los POKéMON\n"
	.string "{STR_VAR_1} y {STR_VAR_2}, ¿cuál es\l"
	.string "más digno de mí?$"

gText_ApprenticeMonThanks15::
	.string "¿{STR_VAR_1}?\n"
	.string "¿Estás seguro?\p"
	.string "Ya veo. Si es así, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Espero que sea algo que incluso yo\n"
	.string "pueda manejar con aplomo.\p"
	.string "¡Encontrémonos de nuevo!$"

gText_ApprenticeWhichMove0::
	.string "¡Waaah! ¡Oh, {PLAYER}!\n"
	.string "Snif... Hic...\p"
	.string "¡Tengo un dilema!\n"
	.string "No puedo elegir un movimiento\l"
	.string "para mi {STR_VAR_1}...\p"
	.string "Por favor, {PLAYER}.\n"
	.string "¿Puedes decidir por mí?\p"
	.string "Para mi {STR_VAR_1}, ¿qué movimiento\n"
	.string "sería mejor: {STR_VAR_2}\l"
	.string "o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "¿{STR_VAR_1}?\n"
	.string "¡Waaaaah!\p"
	.string "¡Oh! ¡Lo siento, {PLAYER}!\n"
	.string "Me hiciste tan feliz al elegir\l"
	.string "el movimiento que lloro...\p"
	.string "Snif...\n"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMove1::
	.string "¡Sii! ¡Hola, {PLAYER}!\n"
	.string "¡Necesito tu consejo otra vez!\p"
	.string "Quiero enseñarle a mi {STR_VAR_1}\n"
	.string "un movimiento genial.\p"
	.string "Me gustan los movimientos\n"
	.string "{STR_VAR_2} o {STR_VAR_3}.\l"
	.string "¿Cuál me recomiendas?$"

gText_ApprenticeMoveThanks1::
	.string "¿{STR_VAR_1} es mejor? ¡Ya veo!\n"
	.string "¡Vale, elegiré ese!\p"
	.string "Si nos vemos aquí, ¡enséñame\n"
	.string "algo más, profesor!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, ¡hola!\n"
	.string "Es sobre mi {STR_VAR_1}, pero\l"
	.string "me preocupan sus movimientos.\p"
	.string "Verás, son los movimientos {STR_VAR_2}\n"
	.string "y {STR_VAR_3}.\p"
	.string "¿Cuál es más fuerte y mejor para\n"
	.string "mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "¿Tu elección es {STR_VAR_1}?\n"
	.string "¡Vale, entiendo!\p"
	.string "¡Le enseñaré {STR_VAR_1} a\n"
	.string "mi POKéMON ahora mismo!\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "¡No tengo remedio, de verdad!\p"
	.string "Decidí criar un POKéMON,\n"
	.string "pero ahora no puedo decidir qué\l"
	.string "movimiento debe aprender…\p"
	.string "Sé que esto no significa nada\n"
	.string "para ti, {PLAYER}.\p"
	.string "Pero para mí es muy importante…\p"
	.string "Por favor, {PLAYER}, ¿podrías elegir\n"
	.string "un movimiento para mi {STR_VAR_1}?\p"
	.string "Si pudieras elegir entre\n"
	.string "{STR_VAR_2} y {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "¡Entiendo!\p"
	.string "Pero ¿estará dispuesto a aprender\n"
	.string "{STR_VAR_1} por mí...?\l"
	.string "¡No! ¡Daré lo mejor de mí!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove4::
	.string "¡Oh, {PLAYER}{KUN}!\n"
	.string "¡Yo también esperaba verte!\p"
	.string "Me preguntaba qué movimiento\n"
	.string "le iría bien a mi {STR_VAR_1}.\p"
	.string "No me decido, ¿podrías elegir\n"
	.string "tú por mí?\p"
	.string "Por ejemplo... ¿Qué tal los\n"
	.string "{STR_VAR_2} y {STR_VAR_3}?\l"
	.string "¿Cuál sería mejor?$"

gText_ApprenticeMoveThanks4::
	.string "¿{STR_VAR_1}? ¡Genial!\p"
	.string "Sabiendo que tú decidiste,\n"
	.string "{PLAYER}{KUN}, no me dolerá\l"
	.string "tanto si pierdo.\p"
	.string "Bien, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMove5::
	.string "¿Cómo puede haber tanto trabajo?\n"
	.string "¡Hey, si es {PLAYER}{KUN}!\l"
	.string "¿Cómo va todo?\p"
	.string "Desde que desperté, he hecho\n"
	.string "jogging, natación y cocina!\p"
	.string "¡No creerás lo ocupado que estoy!\p"
	.string "¡Ni puedo decidir qué movimiento\n"
	.string "debe aprender mi {STR_VAR_1}!\p"
	.string "{STR_VAR_2} se ve bien, ¿no?\n"
	.string "Pero {STR_VAR_3} también es decente.\p"
	.string "{PLAYER}{KUN}, ¡dame un buen\n"
	.string "consejo! ¿Qué movimiento es mejor?$"

gText_ApprenticeMoveThanks5::
	.string "Vale, entendido.\n"
	.string "Haré un hueco en mi horario y\l"
	.string "enseñaré ese movimiento.\p"
	.string "Me alegra tenerte como mentor.\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMove6::
	.string "¡Oh! ¡Qué suerte!\n"
	.string "¡Te vi de nuevo, {PLAYER}!\l"
	.string "Hoy necesito tu ayuda otra vez.\p"
	.string "¡Redoble de tambores!\n"
	.string "Mi pregunta es...\p"
	.string "Para mi {STR_VAR_1}, ¿qué movimiento\n"
	.string "le va mejor, {STR_VAR_2} o\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "¡Ahhh!\n"
	.string "¡{STR_VAR_1}, dices!\l"
	.string "¡Gracias por esa gran respuesta!\p"
	.string "Creo que eso es todo lo que\n"
	.string "quería preguntarte hoy.\p"
	.string "Volvamos a vernos aquí, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove7::
	.string "Hola, {PLAYER}.\n"
	.string "Espero que estés bien.\p"
	.string "Debo pedirte consejo otra vez.\n"
	.string "Es sobre mi querido {STR_VAR_1}.\p"
	.string "¿Cuál sería el movimiento ideal\n"
	.string "para mi {STR_VAR_1}?\l"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "¡Será {STR_VAR_1}!\n"
	.string "¡Se lo enseñaré ahora mismo!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero contar contigo otra vez.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeWhichMove8::
	.string "¡Ay! ¡{PLAYER}! ¡Te vi otra vez!\n"
	.string "¡Estoy... muy feliz!\p"
	.string "Cuando necesito ayuda, tú siempre\n"
	.string "estás ahí, {PLAYER}!\p"
	.string "¡Hoy quiero que me recomiendes\n"
	.string "un movimiento!\p"
	.string "¡Elige un movimiento para\n"
	.string "mi {STR_VAR_1}!\p"
	.string "¿Cuál sería mejor,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "¡Oh-oh-oh! ¡Gracias!\n"
	.string "¡Será {STR_VAR_1}!\l"
	.string "¡Entendido perfectamente!\p"
	.string "Espero que quieras enseñarme\n"
	.string "más cosas en otra ocasión.$"

gText_ApprenticeWhichMove9::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Espero recibir más de tus\l"
	.string "sabios consejos hoy!\p"
	.string "¿Cuál sería el mejor movimiento\n"
	.string "para mi {STR_VAR_1}?\p"
	.string "¡Debe ser algo que me haga\n"
	.string "ganar así de fácil!\p"
	.string "¿Sería {STR_VAR_2}?\n"
	.string "¿O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "¡Ajá, será {STR_VAR_1}!\n"
	.string "¡Sí, genial!\l"
	.string "¡Se lo enseñaré, así, pum!\p"
	.string "¡Muy bien, gracias como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, ¡es increíble!\p"
	.string "¡Mi POKéMON!\n"
	.string "¡Aprendió seis movimientos!\p"
	.string "¡Claro que miento!\n"
	.string "¡Jajajaja!\p"
	.string "Pero esto no es mentira.\n"
	.string "No soy bueno eligiendo ataques\l"
	.string "para mi POKéMON.\p"
	.string "¿Podrías decidir qué ataque\n"
	.string "debería enseñarle?\p"
	.string "{STR_VAR_2} o {STR_VAR_3}, ¿cuál\n"
	.string "le va mejor a mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "¿Vale, entonces elegiste {STR_VAR_1}?\n"
	.string "¡Entonces elegiré otro!\p"
	.string "¡Es broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeWhichMove11::
	.string "¡A-H-O-Y!\n"
	.string "¡Y eso se deletrea ahoy!\p"
	.string "¡Soy el MARINERO rapero!\n"
	.string "Siempre estoy al día, no preguntes.\p"
	.string "Hoy tengo una duda de ataques\n"
	.string "que requiere tu sugerencia!\p"
	.string "{STR_VAR_2} y {STR_VAR_3} son\n"
	.string "los ataques. ¿Cuál es mejor\l"
	.string "para que mi {STR_VAR_1} fluya?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, ¡dices tú, hey, hey!\n"
	.string "¡Iré a enseñarlo ahora mismo!\p"
	.string "Si necesito un consejo,\n"
	.string "{PLAYER}, ¡siempre te escucharé!$"

gText_ApprenticeWhichMove12::
	.string "¡Oh, sí, si es {PLAYER}!\p"
	.string "¿Qué hago? ¿Me das un consejo?\n"
	.string "¡Claro! ¡Ya estoy hablando contigo!\p"
	.string "{PLAYER}, ¿te sorprendo?\n"
	.string "Quiero tu consejo, ¿no ves?\p"
	.string "¿Me escuchas?\n"
	.string "¡Me estás escuchando!\p"
	.string "Mi {STR_VAR_1}, ¿qué debe usar?\n"
	.string "Es {STR_VAR_2} o {STR_VAR_3},\l"
	.string "¿cuál eliges?$"

gText_ApprenticeMoveThanks12::
	.string "Si ese {STR_VAR_1} es el mejor,\n"
	.string "¡haré lo que sugieras!\p"
	.string "Bueno, {PLAYER}, debo irme libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos, mi inteligente amigo!$"

gText_ApprenticeWhichMove13::
	.string "¡Gahack! ¡Gaah! Oh, {PLAYER}{KUN}...\n"
	.string "Tengo este resfriado horrible...\p"
	.string "Quiero elegir un movimiento para mi\n"
	.string "POKéMON, pero no puedo...\p"
	.string "Así que, estando las cosas así,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, si tuviera que elegir\n"
	.string "entre {STR_VAR_2} y {STR_VAR_3} para\l"
	.string "mi {STR_VAR_1}, ¿cuál sería?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, está bien. ¡Cof!\n"
	.string "Se lo enseñaré cuando mejore.\p"
	.string "Espero poder seguir pidiéndote\n"
	.string "ayuda así.$"

gText_ApprenticeWhichMove14::
	.string "Er... Um...\n"
	.string "{PLAYER}{KUN}...?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me pongo muy nerviosa...\l"
	.string "Yo... necesito tu consejo.\p"
	.string "Estoy muy avergonzada, pero no puedo\n"
	.string "decidir qué ataque enseñarle\l"
	.string "a mi POKéMON.\p"
	.string "Es para mi {STR_VAR_1}.\n"
	.string "Si las opciones fueran {STR_VAR_2} o\l"
	.string "{STR_VAR_3}, ¿cuál sería mejor?$"

gText_ApprenticeMoveThanks14::
	.string "¡Oh... Vale!\n"
	.string "Probaré con {STR_VAR_1}.\p"
	.string "Espero poder enseñarle ese ataque...\n"
	.string "Esto es tan estresante...\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos vemos, espero que seas\l"
	.string "tan amable.$"

gText_ApprenticeWhichMove15::
	.string "¿Hm? Pareces ser {PLAYER}{KUN}...\n"
	.string "¿Pero eres real?\p"
	.string "¿Quizás eres uno de esos imitadores\n"
	.string "tan populares?\p"
	.string "No, no, si eres real, está bien.\n"
	.string "¡No te enfades, te lo aseguro!\p"
	.string "Por cierto, me gustaría obtener\n"
	.string "tu consejo.\p"
	.string "Es sobre mi {STR_VAR_1}.\p"
	.string "¿Qué ataque sería mejor usar,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "¿{STR_VAR_1}?\n"
	.string "¿No hay duda sobre eso?\p"
	.string "Ya veo. Si es así, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Espero que sea algo que incluso\n"
	.string "mi POKéMON pueda aprender.\p"
	.string "¡Nos vemos pronto!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… ¿{PLAYER}?\n"
	.string "¡Es {PLAYER}!\l"
	.string "¡Oh! Snif… bua… ¡Escucha!\p"
	.string "Yo… Al luchar, me pongo nervioso,\n"
	.string "lloro aunque gane la batalla…\p"
	.string "Quisiera decir algo genial\n"
	.string "cuando gane…\p"
	.string "¡Por favor, {PLAYER}!\n"
	.string "¿Podrías enseñarme algo genial\l"
	.string "para decir y así no llorar?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "¡Genial! ¡Increíble! ¡Awoooh!\n"
	.string "¡Es muy cool!\p"
	.string "Oh… lo siento…\n"
	.string "Estoy tan feliz que lloro…\p"
	.string "Snif… ¡{PLAYER}!\n"
	.string "¡Muchas gracias por todo!\p"
	.string "Lucharé lo mejor que pueda por\n"
	.string "ti, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "¡La próxima vez… lucharemos!$"

gText_ApprenticePickWinSpeech1::
	.string "¡Sii! ¡Es {PLAYER}! ¡Hola!\n"
	.string "¡Quería preguntarte algo!\p"
	.string "Quiero decir algo genial cuando\n"
	.string "gane un combate.\p"
	.string "¿Tienes alguna frase genial que\n"
	.string "me puedas recomendar?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "¡Oh, vaya! ¡Eso es genial!\n"
	.string "¡Vale, diré eso!\p"
	.string "¡Gracias por enseñarme todo esto!\n"
	.string "¡Daré lo mejor de mí\l"
	.string "dondequiera que vaya ahora!\p"
	.string "¡Cuando nos veamos, será para\n"
	.string "una batalla!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, ¡hola!\p"
	.string "Mis POKéMON y yo estamos listos\n"
	.string "para todo, salvo una cosa.\p"
	.string "Creo que sería bueno tener\n"
	.string "algo que gritar al ganar.\p"
	.string "¿Podrías pensar en algo bueno\n"
	.string "para decir?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…¡Genial!\n"
	.string "¡Usaré eso!\p"
	.string "Saldré a luchar por todas\n"
	.string "partes.\p"
	.string "Quién sabe, quizá luche contra\n"
	.string "ti algún día, {PLAYER}.\p"
	.string "¡La próxima vez, nos vemos en\n"
	.string "una batalla!$"

gText_ApprenticePickWinSpeech3::
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte, pero no puedo…\p"
	.string "Incluso cuando…\n"
	.string "Incluso si gano, no tengo nada\l"
	.string "especial que decir…\p"
	.string "Sé que no importa mucho\n"
	.string "para ti, {PLAYER}.\p"
	.string "Pero para mí es muy importante…\p"
	.string "Por favor, {PLAYER}, ¿qué digo\n"
	.string "si gano una batalla?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Eso es inspirador...\p"
	.string "Eh... ¿está bien que alguien como yo\n"
	.string "diga algo así?\p"
	.string "¡No! ¡Daré lo mejor de mí!\p"
	.string "{PLAYER}, gracias por tenerme\n"
	.string "paciencia durante tanto tiempo...\p"
	.string "Prometo esforzarme de ahora en más.\p"
	.string "Seguro que me olvidarás pronto,\n"
	.string "¡pero volvamos a vernos\l"
	.string "en algún lugar!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hay algo que quiero que escuches.\p"
	.string "Sé que no siempre sueno\n"
	.string "amable o educado…\p"
	.string "Cuando gano, creo que parezco\n"
	.string "alguien arrogante.\p"
	.string "No quiero que me odien,\n"
	.string "así que quiero decir algo lindo a\l"
	.string "quien derrote.\p"
	.string "¡Pero no se me ocurre nada!\n"
	.string "¿Podrías pensar algo por mí?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "¡Nada mal!\n"
	.string "¡Sí, usaré eso!\p"
	.string "Me pondré en camino y haré lo\n"
	.string "posible con lo que me enseñaste\l"
	.string "de corazón.\p"
	.string "¡Siento haber sido tan insistente\n"
	.string "contigo!\p"
	.string "La próxima luchamos, ¿vale?\n"
	.string "¡Nos vemos!$"

gText_ApprenticePickWinSpeech5::
	.string "¡No supero lo ocupado que estoy!\n"
	.string "Ah, hola, te buscaba, {PLAYER}{KUN}.\p"
	.string "¿Estás bien, como siempre?\n"
	.string "Para mí nada ha cambiado.\p"
	.string "Tengo que correr, luchar y mapear.\n"
	.string "¿Por qué estoy tan ocupado?\p"
	.string "Pero aunque lo esté, sería grosero\n"
	.string "darme la vuelta e irme\l"
	.string "sin decir nada tras ganar.\p"
	.string "¿Qué frase genial resaltaría mi\n"
	.string "estilo al marcharme?\l"
	.string "{PLAYER}{KUN}, ¡ayúdame!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Vale, entiendo.\n"
	.string "¡Tendré tiempo de decir eso!\p"
	.string "Honestamente, me alegra haber\n"
	.string "tenido un mentor como tú.\p"
	.string "Haré tiempo de alguna forma para\n"
	.string "dedicarme a las batallas.\p"
	.string "¡Gracias por todo, {PLAYER}{KUN}!\n"
	.string "¡Algún día lucharemos tú y yo!$"

gText_ApprenticePickWinSpeech6::
	.string "¡Tuve suerte otra vez!\n"
	.string "{PLAYER}! ¡Qué alegría verte!\l"
	.string "¡Como siempre, necesito tu consejo!\p"
	.string "¡Redoble de tambores!\n"
	.string "Mi última pregunta es…\p"
	.string "Si gano una batalla y quiero\n"
	.string "cerrar con estilo, ¿qué\l"
	.string "debería decir?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Eso… ¡Eso es fabuloso!\n"
	.string "¡Es digno y genial! ¡La usaré!\p"
	.string "…Oye, creo que me estoy volviendo\n"
	.string "bueno en esto, ¿eh?\p"
	.string "Pienso retar a otros\n"
	.string "ENTRENADORES desde ahora.\p"
	.string "{PLAYER}, tu consejo me ayudó mucho.\p"
	.string "¡Quizás algún día\n"
	.string "lucharemos!\p"
	.string "¡Gracias por todo!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "¡Me alegra mucho conocerte!\p"
	.string "Ya no tengo preocupaciones\n"
	.string "sobre mis POKéMON.\p"
	.string "Lo que me preocupa soy yo…\p"
	.string "¿Sabes qué dice un ENTRENADOR\n"
	.string "al ganar una batalla?\p"
	.string "¡Definitivamente yo también\n"
	.string "quisiera hacer eso!\p"
	.string "Por favor, ¿qué debería decir\n"
	.string "cuando gane una batalla?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "¡Ah! ¡Esa frase! ¡Me refresca\n"
	.string "y me hace sentir renacido!\p"
	.string "¡Debo usarla ahora mismo!\p"
	.string "Y ahora, debo marcharme,\n"
	.string "{PLAYER}…\p"
	.string "Lucharé contra muchos otros,\n"
	.string "pero no olvidaré tus enseñanzas.\p"
	.string "Tal vez algún día…\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech8::
	.string "¡Ay! ¡Vi a {PLAYER}!\n"
	.string "¡Estoy feliz de verte!\p"
	.string "¡Oh-oh-oh! ¡Hay algo que\n"
	.string "tengo que preguntarte!\p"
	.string "Hace poco gané una batalla.\n"
	.string "¡Fue muy emocionante!\p"
	.string "¡Pero me puse tan feliz que\n"
	.string "me trabé y no pude decir nada!\p"
	.string "¡{PLAYER}, por favor, piensa\n"
	.string "una frase para cuando yo gane!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "¡Waaaaah!\n"
	.string "¡¿Voy a decir eso?!\l"
	.string "¡Estoy... delirando de alegría!\p"
	.string "¡Gr-gr-gracias!\n"
	.string "¡Ya no me queda nada que lamentar!\p"
	.string "Ahora viajaré y lucharé\n"
	.string "contra todo tipo de gente.\p"
	.string "Te debo todo, {PLAYER}.\n"
	.string "¡De verdad, muchas gracias!\p"
	.string "Debo irme, ¡pero luchemos\n"
	.string "algún día!$"

gText_ApprenticePickWinSpeech9::
	.string "¡Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Sabes, tengo ganas de viajar\n"
	.string "y luchar donde sea.\p"
	.string "Pero antes, quiero tu consejo\n"
	.string "una vez más, ¡por favor!\p"
	.string "Si gano una batalla, ¿qué sería\n"
	.string "un buen alarde para decirle al\l"
	.string "ENTRENADOR derrotado?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "¡Uh-huh, qué dulce!\n"
	.string "¡Sí, genial!\l"
	.string "¡Intentaré decir eso, a tope!\p"
	.string "¡Y ahora, es hora de decir adiós!\n"
	.string "¡Gracias por todas las cosas!\p"
	.string "Dame una batalla algún día, ¿ok?\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, ¡hay un gran problema!\p"
	.string "Cuando gano, presumo de ello\n"
	.string "¡por al menos una hora!\p"
	.string "¡Claro que miento!\n"
	.string "¡Wahahaha!\p"
	.string "Pero esto no es mentira.\n"
	.string "No soy muy bueno charlando.\p"
	.string "Entonces, ¿decides por mí qué\n"
	.string "decir tras ganar una batalla,\l"
	.string "maestro?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "¿Eso es lo que debo decir, eh?\n"
	.string "¡Entonces evitaré decir eso!\p"
	.string "¡Es broma!\n"
	.string "¡Obedeceré tus enseñanzas, maestro!\p"
	.string "¡Gracias por enseñarme todo este\n"
	.string "tiempo, maestro!\p"
	.string "Al fin entiendo qué significa ser\n"
	.string "un ENTRENADOR.\p"
	.string "Saldré a ganar batallas\n"
	.string "contra cualquier ENTRENADOR.\p"
	.string "¡Quizás seas tú algún día, maestro!\p"
	.string "¡Eso es todo!\n"
	.string "¡Adiós, mi maestro!$"

gText_ApprenticePickWinSpeech11::
	.string "¡A-H-O-Y!\n"
	.string "¡Y eso se deletrea ahoy!\p"
	.string "¡Soy el MARINERO rapero!\n"
	.string "Será mi última pregunta,\l"
	.string "¡no llores!\p"
	.string "¡Es una pregunta de frases\n"
	.string "que pide tu sugerencia!\p"
	.string "Si gano un combate, ¿qué puedo decir\n"
	.string "de forma muy genial?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "¡Perfecto! Usaré eso.\n"
	.string "¡Hice bien en dejarte elegir!\p"
	.string "¡Y ahora creo que lo mejor\n"
	.string "será volar del nido!\p"
	.string "Gracias por todo lo que enseñaste.\n"
	.string "¡Me voy a una racha de batallas!\p"
	.string "¡B-O-N-V-O-Y-A-G-E!\n"
	.string "¡Eso es bon voyage,\l"
	.string "¡mi homenaje para ti!$"

gText_ApprenticePickWinSpeech12::
	.string "¡Ah, sí, {PLAYER}!\n"
	.string "¡Te encontré otra vez!\p"
	.string "¿Qué hago? ¿Te pregunto otra vez?\n"
	.string "¡Claro! ¡Ya te estoy preguntando!\p"
	.string "En fin, {PLAYER}...\n"
	.string "¿Me escuchas?\l"
	.string "¡Me escuchas!\l"
	.string "¡Necesito más consejos!\p"
	.string "Es sobre qué debería gritar.\n"
	.string "Algo genial para decir cuando\l"
	.string "una batalla termine bien.\p"
	.string "¡Vamos, quiero oírte decirlo!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "¡Está bien, está bien!\n"
	.string "¡Lo usaré porque es genial!\p"
	.string "Ya no tengo más que preguntarte.\n"
	.string "Solo queda decir adiós con la mano.\p"
	.string "Quizá algún día nos veamos,\n"
	.string "y uno deba ser derrotado.\p"
	.string "Pero ya es hora de despedirnos.\p"
	.string "Bueno, {PLAYER}, debo ser libre,\n"
	.string "¡pero no te olvides de mí!\p"
	.string "¡Cuídate, {PLAYER}!\n"
	.string "¡Te quiero!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, terminé...\n"
	.string "No deja de gotear mi nariz...\p"
	.string "Intentaba pensar en algo\n"
	.string "genial para decir al ganar.\p"
	.string "Me inspiró tanto que lloré,\n"
	.string "y ahora mi nariz no para...\p"
	.string "Así que, estando así las cosas,\n"
	.string "tú decide por mí, {PLAYER}{KUN}.\p"
	.string "Cuando gane una batalla,\n"
	.string "¿qué debería decir?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "... ... ...Está bien.\n"
	.string "¡No, es impresionante!\l"
	.string "¡Me hace brotar nuevas lágrimas!\p"
	.string "A pesar de mis lágrimas y mi\n"
	.string "nariz, ¡usaré esa frase!\p"
	.string "Ya no tengo más que preguntarte,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "¡De ahora en adelante, somos rivales!\n"
	.string "¡Gracias por todo!$"

gText_ApprenticePickWinSpeech14::
	.string "Eh... Este...\n"
	.string "{PLAYER}{KUN}...\p"
	.string "Por favor, no me mires así.\n"
	.string "Me pones muy nervioso.\p"
	.string "Yo... necesito tu consejo otra vez.\n"
	.string "Será el último, aunque...\p"
	.string "Es vergonzoso preguntar,\n"
	.string "¿pero y si gano una batalla?\l"
	.string "¿Qué debería decir?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "¡Oh... De acuerdo!\n"
	.string "¡Intentaré decir eso!\l"
	.string "Quizá esté muy nerviosa...\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Debo despedirme ahora.\p"
	.string "Seguiré todo lo que me enseñaste,\n"
	.string "{PLAYER}{KUN}, y daré lo mejor.$"

gText_ApprenticePickWinSpeech15::
	.string "¿Hm? Pareces ser {PLAYER}{KUN}...\n"
	.string "¿Pero lo eres realmente?\l"
	.string "¿Quizá un MUÑECO de {PLAYER}?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si eres real, por favor\l"
	.string "olvida mi grosería.\p"
	.string "No te enojes. Solo deseo\n"
	.string "más de tus buenos consejos.\p"
	.string "Es sobre una frase.\p"
	.string "Más preciso, ¿qué debería decir\n"
	.string "si gano una batalla?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "... ... ... ... ... ...\n"
	.string "Cuando gane un combate...\p"
	.string "{STR_VAR_1}\p"
	.string "...¿Hablas en serio?\p"
	.string "Ya veo. Si es en serio, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Espero que yo también pueda\n"
	.string "usar bien esa frase.\p"
	.string "Parece que ya no necesito\n"
	.string "más consejos.\p"
	.string "Creo que es hora de despedirme\n"
	.string "y seguir mi propio camino.\p"
	.string "¡Gracias, mi mentor!\n"
	.string "¡Perdón por mi escepticismo!$"
