BattleDome_Text_Potential1::
	.string "¡El mejor candidato a campeón!$"

BattleDome_Text_Potential2::
	.string "Un equipo finalista seguro.$"

BattleDome_Text_Potential3::
	.string "Probable finalista del top 3.$"

BattleDome_Text_Potential4::
	.string "Candidato a quedar en primer lugar.$"

BattleDome_Text_Potential5::
	.string "Un equipo con potencial de élite.$"

BattleDome_Text_Potential6::
	.string "La sorpresa de este torneo.$"

BattleDome_Text_Potential7::
	.string "Un equipo mejor que el promedio.$"

BattleDome_Text_Potential8::
	.string "Un equipo promedio en este torneo.$"

BattleDome_Text_Potential9::
	.string "Un equipo con potencial promedio.$"

BattleDome_Text_Potential10::
	.string "Un equipo más débil que el promedio.$"

BattleDome_Text_Potential11::
	.string "Un equipo que busca su primer triunfo.$"

BattleDome_Text_Potential12::
	.string "Una victoria hará orgulloso al equipo.$"

BattleDome_Text_Potential13::
	.string "En general, un equipo débil.$"

BattleDome_Text_Potential14::
	.string "Un equipo con potencial muy bajo.$"

BattleDome_Text_Potential15::
	.string "Es improbable que ganen el torneo.$"

BattleDome_Text_Potential16::
	.string "El equipo con menos chance de ganar.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "¡La superestrella invencible!$"

BattleDome_Text_StyleRiskDisaster::
	.string "A veces arriesga el desastre total.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Experto en batallas prolongadas.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varía tácticas según el rival.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Tiene un patrón de victoria duro.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "A veces usa un movimiento raro.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Usa ataques sorpresivos y disruptivos.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Vigila siempre los PS en batalla.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Guarda energía y luego la pierde.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Experto en debilitar rivales.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Usa tácticas basadas en la suerte.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Ataca con un aire majestuoso.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Usa ataques fuertes de pocos PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Debilita y luego ataca.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Lucha resistiendo todo ataque.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Experto en alterar al rival.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Usa ataques fuertes y directos.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Usa ataques fuertes agresivamente.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Lucha esquivando con astucia.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Experto en ataques molestos.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Usa muchos ataques populares.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Usa combos muy poderosos.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Usa ataques muy probables.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Usa ataques espectaculares.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Prioriza el ataque sobre la defensa.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Prioriza la defensa sobre el ataque.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Ataca rápido con movimientos fuertes.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Usa movimientos con efectos extra.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Usa una mezcla equilibrada de ataques.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Este es el mensaje de prueba 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Este es el mensaje de prueba 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Este es el mensaje de prueba 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Este es el mensaje de prueba 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Sube PS y ATAQUE.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Sube PS y DEFENSA.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Sube PS y VELOCIDAD.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Sube PS y AT. ESP.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Sube PS y DEF. ESP.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Sube ATAQUE y DEFENSA.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Sube ATAQUE y VELOCIDAD.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Sube ATAQUE y ATQ. ESPECIAL.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Sube ATAQUE y DEF. ESPECIAL.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Sube DEFENSA y VELOCIDAD.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Sube DEFENSA y ATQ. ESPECIAL.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Sube DEFENSA y DEF. ESPECIAL.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Sube VELOCIDAD y ATQ. ESPECIAL.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Sube VELOCIDAD y DEF. ESPECIAL.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Sube ATQ. ESP. y DEF. ESPECIAL.$"

BattleDome_Text_EmphasizesHP::
	.string "Potencia los PS.$"

BattleDome_Text_EmphasizesAtk::
	.string "Potencia el ATAQUE.$"

BattleDome_Text_EmphasizesDef::
	.string "Potencia la DEFENSA.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Potencia la VELOCIDAD.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Potencia el AT. ESP.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Potencia la DEF. ESP.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Ignora PS y ATAQUE.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Ignora PS y DEFENSA.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Ignora PS y VELOCIDAD.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Ignora PS y ATQ. ESPECIAL.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Ignora PS y DEF. ESPECIAL.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Ignora ATAQUE y DEFENSA.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Ignora ATAQUE y VELOCIDAD.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Ignora ATAQUE y ATQ. ESPECIAL.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Ignora ATAQUE y DEF. ESPECIAL.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Ignora DEFENSA y VELOCIDAD.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Baja DEFENSA y ATQ. ESPECIAL.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Baja DEFENSA y DEF. ESPECIAL.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Baja VELOCIDAD y ATQ. ESPECIAL.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Baja VELOCIDAD y DEF. ESPECIAL.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Baja ATQ. y DEF. ESPECIAL.$"

BattleDome_Text_NeglectsHP::
	.string "Baja los PS.$"

BattleDome_Text_NeglectsAtk::
	.string "Baja el ATAQUE.$"

BattleDome_Text_NeglectsDef::
	.string "Baja la DEFENSA.$"

BattleDome_Text_NeglectsSpeed::
	.string "Descuida la VELOCIDAD.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Descuida el ATQ. ESP.$"

BattleDome_Text_NeglectsSpDef::
	.string "Descuida la DEF. ESP.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Cria POKéMON de forma equilibrada.$"

BattleDome_Text_LetTheBattleBegin::
	.string "¡Que comience la batalla!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} ganó usando {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "¡{STR_VAR_1} es el campeón!$"

BattleDome_Text_TrainerWonByDefault::
	.string "¡{STR_VAR_1} ganó por defecto!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} ganó por defecto!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} ganó sin usar ataques!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} ganó sin usar movimientos!$"

BattleDome_Text_Round1Match1::
	.string "Ronda 1, Combate 1$"

BattleDome_Text_Round1Match2::
	.string "Ronda 1, Combate 2$"

BattleDome_Text_Round1Match3::
	.string "Ronda 1, Combate 3$"

BattleDome_Text_Round1Match4::
	.string "Ronda 1, Combate 4$"

BattleDome_Text_Round1Match5::
	.string "Ronda 1, Combate 5$"

BattleDome_Text_Round1Match6::
	.string "Ronda 1, Combate 6$"

BattleDome_Text_Round1Match7::
	.string "Ronda 1, Combate 7$"

BattleDome_Text_Round1Match8::
	.string "Ronda 1, Combate 8$"

BattleDome_Text_Round2Match1::
	.string "Ronda 2, Combate 1$"

BattleDome_Text_Round2Match2::
	.string "Ronda 2, Combate 2$"

BattleDome_Text_Round2Match3::
	.string "Ronda 2, Combate 3$"

BattleDome_Text_Round2Match4::
	.string "Ronda 2, Combate 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal, Combate 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal 2$"

BattleDome_Text_FinalMatch::
	.string "Gran Final$"
