FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenido a la CARPA DE BATALLA:\n"
	.string "¡ARENA!\p"
	.string "¡Soy tu guía del Torneo Set KO!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Ahora, ¿quieres aceptar el desafío\n"
	.string "de un Torneo Set KO?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "¡Esperaremos tu desafío en\n"
	.string "otra ocasión!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "En la CARPA DE BATALLA: ARENA,\n"
	.string "hacemos el Torneo Set KO.\p"
	.string "Todos entran con un equipo de\n"
	.string "tres POKéMON.\p"
	.string "Los tres POKéMON deben estar en el\n"
	.string "orden en que aparecerán.\p"
	.string "En batalla, los POKéMON saldrán\n"
	.string "uno a uno en el orden fijado.\p"
	.string "Una vez que un POKéMON entra,\n"
	.string "debe seguir hasta que termine.\p"
	.string "Si el combate sigue empatado en\n"
	.string "tres turnos, habrá un juez.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "por favor, guarda la partida.\p"
	.string "Si no guardas, no podrás\n"
	.string "continuar con tu desafío.\p"
	.string "Si logras vencer a tres\n"
	.string "ENTRENADORES seguidos,\l"
	.string "te daremos un gran premio.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Antes de ir a la CARPA DE BATALLA,\n"
	.string "debo guardar. ¿Está bien?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Hay dos niveles de desafío,\n"
	.string "Nivel 50 y Nivel Abierto.\l"
	.string "¿Cuál eliges?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Muy bien, ahora elige a tus\n"
	.string "tres POKéMON, por favor.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "¡Querido desafiante!\p"
	.string "No tienes los tres POKéMON\n"
	.string "necesarios para entrar.\p"
	.string "Tampoco deben llevar el mismo\n"
	.string "tipo de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} no valen.\p"
	.string "Cuando estés preparado,\n"
	.string "por favor, regresa.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "¡Querido retador!\p"
	.string "No tienes los tres POKéMON\n"
	.string "necesarios para entrar.\p"
	.string "Para calificar, trae tres\n"
	.string "especies de POKéMON distintas.\p"
	.string "Tampoco deben llevar el mismo\n"
	.string "tipo de objeto.\p"
	.string "HUEVOS{STR_VAR_1} no valen.\p"
	.string "Cuando estés preparado,\n"
	.string "por favor, regresa.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ahora te guiaré hacia\n"
	.string "la CARPA DE BATALLA.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "¡Querido retador!\p"
	.string "No guardaste la partida antes\n"
	.string "de apagarla, ¿verdad?\p"
	.string "Es lamentable, pero eso ha\n"
	.string "causado tu descalificación\l"
	.string "del desafío.\p"
	.string "Puedes, claro, iniciar un\n"
	.string "desafío nuevo.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "¡Espléndido! ¡Has vencido a\n"
	.string "tres ENTRENADORES seguidos!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Espera mientras guardo la partida.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Por tu racha de 3 victorias,\n"
	.string "te entregamos este premio.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} recibió el premio\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "¿Oh?\n"
	.string "Tu MOCHILA parece estar llena.\p"
	.string "Haz espacio y regresa\n"
	.string "por tu premio.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "¡Muchas gracias por participar!\p"
	.string "Espera mientras guardo la partida.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "¡Esperamos tu desafío en\n"
	.string "otra ocasión!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Esperábamos con ansias\n"
	.string "tu llegada.\p"
	.string "Antes de ir a la CARPA DE BATALLA,\n"
	.string "debo guardar. Por favor, espera.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenido a la CARPA DE BATALLA:\n"
	.string "PALACIO!\p"
	.string "Aquí se prueba la confianza del\n"
	.string "ENTRENADOR en sus POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "¿Quieres aceptar el desafío de la\n"
	.string "CARPA DE BATALLA: PALACIO?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "En la CARPA DE BATALLA: PALACIO,\n"
	.string "hay una regla crucial que debe\l"
	.string "obedecerse.\p"
	.string "Solo se permite cambiar los\n"
	.string "POKéMON al entrar y salir.\p"
	.string "De lo contrario, está prohibido\n"
	.string "dar órdenes a los POKéMON.\p"
	.string "Lucharán según su naturaleza\n"
	.string "y pelearán por su cuenta.\p"
	.string "Confía en tus POKéMON\n"
	.string "y vigila sus movimientos.\p"
	.string "Si logras vencer a tres\n"
	.string "ENTRENADORES seguidos,\l"
	.string "te daremos un premio.\p"
	.string "Si quieres interrumpir el\n"
	.string "desafío, guarda la partida.\p"
	.string "Si no guardas antes de salir,\n"
	.string "quedarás descalificado.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Cuando fortalezcas tu corazón\n"
	.string "y a tus POKéMON, debes volver.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Hay dos niveles de dificultad,\n"
	.string "Nivel 50 y Nivel Abierto.\l"
	.string "¿Cuál desafío eliges?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Suspiro...\p"
	.string "No tienes los tres POKéMON\n"
	.string "necesarios para el desafío.\p"
	.string "Para entrar, debes traer tres\n"
	.string "especies de POKéMON distintas.\p"
	.string "Tampoco deben llevar el mismo\n"
	.string "tipo de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} no valen.\p"
	.string "Vuelve cuando estés\n"
	.string "preparado.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Suspiro...\p"
	.string "No tienes los tres POKéMON\n"
	.string "necesarios para el desafío.\p"
	.string "Para entrar, debes traer tres\n"
	.string "especies de POKéMON distintas.\p"
	.string "Tampoco deben llevar el mismo\n"
	.string "tipo de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} no valen.\p"
	.string "Vuelve cuando estés\n"
	.string "preparado.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bien. Ahora, elige a tus\n"
	.string "tres POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Debo guardar antes de llevarte a la\n"
	.string "TIENDA DE BATALLA. ¿Está bien?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bien.\n"
	.string "Ahora, sígueme.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Es un honor ver las hazañas de\n"
	.string "tus POKéMON.\p"
	.string "Los resultados se registrarán.\n"
	.string "Por favor, espera un momento.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Para lograr 3 victorias seguidas...\p"
	.string "El vínculo con tus POKéMON\n"
	.string "parece firme y verdadero.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Tu hazaña será registrada.\n"
	.string "Por favor, espera un momento.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Por tu hazaña de 3 victorias,\n"
	.string "te damos este premio.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Bienvenido a la CARPA DE COMBATE:\n"
	.string "FÁBRICA!\p"
	.string "Soy tu guía en el Torneo de\n"
	.string "Intercambio.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "¿Quieres aceptar el desafío de\n"
	.string "Intercambio?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "En la CARPA DE COMBATE: FÁBRICA,\n"
	.string "hacemos eventos de Intercambio\l"
	.string "con POKéMON de alquiler.\p"
	.string "Primero, te prestaremos tres\n"
	.string "POKéMON para este evento.\p"
	.string "Con los POKéMON de alquiler,\n"
	.string "debes hacer un COMBATE INDIVIDUAL.\p"
	.string "Si ganas, podrás intercambiar\n"
	.string "uno de tus POKéMON de alquiler.\p"
	.string "Repite el ciclo de combatir y\n"
	.string "cambiar; si ganas tres veces\l"
	.string "seguidas, ganarás un gran premio.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "por favor, guarda la partida.\p"
	.string "Si no guardas antes de salir,\n"
	.string "quedarás descalificado.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Esperamos tu próxima visita.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "¿Qué nivel quieres desafiar?\n"
	.string "¿Nivel 50 o Nivel 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Antes de empezar el desafío,\n"
	.string "debo guardar los datos. ¿Está bien?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Bien, cuidaré de tus POKéMON\n"
	.string "mientras compites.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Por aquí, por favor.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "¡Gracias por participar!\p"
	.string "Te devolveré tus POKéMON a cambio\n"
	.string "de los POKéMON de alquiler.\p"
	.string "Debo guardar tus resultados.\n"
	.string "Espera, por favor.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Te devolveré tus POKéMON a cambio\n"
	.string "de los POKéMON de alquiler.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "¡Felicidades!\n"
	.string "¡Ganaste tres combates seguidos!\p"
	.string "Te devolveré tus POKéMON a cambio\n"
	.string "de los POKéMON de alquiler.\p"
	.string "Debo guardar tus resultados.\n"
	.string "Espera, por favor.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Por tu racha de 3 victorias,\n"
	.string "te damos este premio.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "¡Oh!\n"
	.string "Parece que no tienes espacio.\p"
	.string "Haz espacio en tu MOCHILA y\n"
	.string "avísame.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "¡Te estábamos esperando!\p"
	.string "Antes de seguir el desafío,\n"
	.string "debo guardar la partida.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Siento decirte que no guardaste\n"
	.string "antes de salir la última vez.\p"
	.string "Por eso, quedas descalificado\n"
	.string "de tu desafío.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Te devolveremos tus POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} recibió el premio\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Las reglas de intercambio están aquí.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "¿Qué sección quieres leer?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "En el Intercambio, solo puedes usar\n"
	.string "tres POKéMON.\p"
	.string "Ya sea alquilando o cambiando,\n"
	.string "tu equipo no puede tener dos o más\l"
	.string "del mismo POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Solo puedes cambiar POKéMON con el\n"
	.string "ENTRENADOR que acabas de vencer.\p"
	.string "Solo puedes cambiar por los POKéMON\n"
	.string "usados por el ENTRENADOR vencido.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Tras cada victoria, puedes cambiar\n"
	.string "uno de tus POKéMON por uno del\l"
	.string "oponente derrotado.\p"
	.string "No podrás cambiar POKéMON con el\n"
	.string "tercer ENTRENADOR del evento.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Hay dos puntos clave al intercambiar\n"
	.string "POKéMON.\p"
	.string "Primero, al cambiar, no puedes ver\n"
	.string "los stats del POKéMON que vas\l"
	.string "a recibir.\p"
	.string "Segundo, los POKéMON de tu equipo\n"
	.string "están en orden según cómo los\l"
	.string "alquilaste.\p"
	.string "Este orden no cambia aunque\n"
	.string "hagas intercambios.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Los POKéMON de la TIENDA DE BATALLA:\n"
	.string "FACTORY son todos alquilados.\p"
	.string "Todos los POKéMON alquilados están al\n"
	.string "Nivel 50.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Las reglas de la TIENDA DE BATALLA\n"
	.string "VERDANTURF están listadas.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "¿Qué encabezado quieres leer?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "En la TIENDA DE BATALLA VERDANTURF,\n"
	.string "los POKéMON deben pensar y\l"
	.string "luchar por sí mismos.\p"
	.string "A diferencia del campo, los POKéMON\n"
	.string "que viven con personas actúan según\l"
	.string "su naturaleza.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Según su naturaleza, un POKéMON\n"
	.string "podría preferir atacar siempre.\p"
	.string "Otro POKéMON podría preferir\n"
	.string "protegerse de cualquier daño.\p"
	.string "Otro podría disfrutar molestando o\n"
	.string "confundiendo a sus rivales.\p"
	.string "Según su naturaleza, un POKéMON\n"
	.string "tendrá movimientos favoritos que sabe\l"
	.string "usar bien.\p"
	.string "También puede haber movimientos que\n"
	.string "le cueste usar.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Hay movimientos ofensivos que causan\n"
	.string "daño directo al rival.\p"
	.string "Hay movimientos defensivos para\n"
	.string "prepararse ante ataques o\l"
	.string "para curar PS y demás.\p"
	.string "Hay otros movimientos extraños que\n"
	.string "debilitan al rival con problemas de\l"
	.string "estadísticas, veneno o\l"
	.string "parálisis.\p"
	.string "Los POKéMON usarán movimientos de\n"
	.string "estas tres categorías.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Sin órdenes de su ENTRENADOR,\n"
	.string "un POKéMON puede no usar bien\l"
	.string "ciertos movimientos.\p"
	.string "Un POKéMON no es bueno usando\n"
	.string "movimientos que no le gustan.\p"
	.string "Si solo conoce movimientos que no\n"
	.string "van con su naturaleza, no podrá\l"
	.string "alcanzar su potencial.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Según su naturaleza, un POKéMON puede\n"
	.string "usar movimientos que no van con él\l"
	.string "cuando esté en problemas.\p"
	.string "Si un POKéMON actúa raro en un\n"
	.string "apuro, obsérvalo con cuidado.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "En esta CARPA DE BATALLA, los\n"
	.string "niveles de los POKéMON serán\l"
	.string "ajustados al Nivel 50.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Las reglas de la CARPA DE\n"
	.string "BATALLA: PALACIO aparecen aquí.$"
