PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPÁ: ¡Hola, {PLAYER}!\p"
	.string "Acabo de recibir una BAYA muy rara.\n"
	.string "Quiero que te la quedes.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si ves BAYAS creciendo en suelo\n"
	.string "fértil, puedes tomarlas.\p"
	.string "Pero planta una BAYA en el mismo\n"
	.string "sitio. Es por cortesía.\p"
	.string "Toma, compartiré esto contigo.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Por tu aspecto, debes ser un\n"
	.string "ENTRENADOR, ¿no?\p"
	.string "Los ENTRENADORES suelen dar BAYAS\n"
	.string "a sus POKéMON.\p"
	.string "Tú decides si cultivas BAYAS\n"
	.string "o las usas.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Regué las plantas cada día.\n"
	.string "Crecieron muchas flores.\p"
	.string "Y también me dieron muchas BAYAS.\p"
	.string "¡Toma!\n"
	.string "¡Puedes quedártela!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Me esforzaré mucho para cultivar\n"
	.string "BAYAS de diferentes colores.\p"
	.string "¡Espero que tú también lo hagas!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "¿De qué color serán las BAYAS que\n"
	.string "buscaré hoy?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Amo usar la máquina BERRY CRUSH,\n"
	.string "así que colecciono BAYAS.\p"
	.string "Compartiré una contigo, si quieres.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Deberías probar la máquina\n"
	.string "BERRY CRUSH con tus amigos.$"

Route114_Text_FunToThinkAboutBerries:
	.string "¿Qué BAYA plantar?\n"
	.string "¿Usar las BAYAS o guardarlas?\p"
	.string "Es divertido pensarlo.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Las BAYAS crecen con la luz solar.\p"
	.string "Ayudamos a que crezcan regándolas\n"
	.string "con frecuencia.\p"
	.string "Es una muestra de amor, ¿no?$"

Route120_Text_YesYouUnderstand:
	.string "Sí, sí.\n"
	.string "Entiendes lo que quiero decir.\p"
	.string "Toma esto.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh... Pero es importante que tengas\n"
	.string "tus propias impresiones...\p"
	.string "Puedes quedarte con esto.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Creo que esa BAYA es rara.\n"
	.string "Espero que la cuides con mucho amor.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Conseguiré más BAYAS del\n"
	.string "MAESTRO BAYA.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "En el fondo...\p"
	.string "Así como la brisa fresca le va al mar,\n"
	.string "así me va a mí.\p"
	.string "Y a ti, una BAYA te queda perfecta...\p"
	.string "¿Por qué será?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "En el fondo...\p"
	.string "¡Es porque eres un ENTRENADOR!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "En resumidas cuentas...\p"
	.string "La simplicidad me sienta bien,\n"
	.string "{POKEBLOCK}S van bien con POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Llamame el MAESTRO BAYA.\p"
	.string "Sueño con llenar el mundo de\n"
	.string "flores, así que cultivo BAYAS\l"
	.string "y las reparto a todos.\p"
	.string "¡Tú mereces una!$"

Route123_BerryMastersHouse_Text_YoureDeservingOfMulch:
	.string "El ABONO CRECIMIENTO hace que\n"
	.string "cualquier BAYA crezca ya. ¡Usa\l"
	.string "uno con la BAYA de hoy!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "¿Para qué ser tacaño?\n"
	.string "¡Toma otro!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Visita la tienda PRETTY PETAL\n"
	.string "cerca de FUNDA CIUDAD.\p"
	.string "¡Que las flores llenen el mundo!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Ya terminé por hoy.\n"
	.string "Vuelve otro día.\p"
	.string "¡Que las flores llenen el mundo!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Como mi esposo cultiva BAYAS,\n"
	.string "oh, es el mejor del mundo.\p"
	.string "Me hace sentir muy orgullosa.\p"
	.string "Por cierto, niño, ¿has oído\n"
	.string "algún buen dicho últimamente?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "¡Ah! ¡Qué dicho tan notable!\n"
	.string "¡Es muy inspirador!\p"
	.string "Quiero que tengas esto.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "¡Oh! Es un buen dicho.\n"
	.string "Eres alguien notable.\p"
	.string "Quiero que tengas esto.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Mis cuatro nietos deben ser\n"
	.string "mejores que mi esposo.\p"
	.string "¡Joy nunca sale de mi vida!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "¡Hola!\p"
	.string "Esta es la floristería PRETTY PETAL.\n"
	.string "¡Llevando flores a todo el mundo!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, ¿quieres aprender sobre\n"
	.string "las BAYAS?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "¿Tu nombre es?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Es un nombre lindo.\p"
	.string "{PLAYER}{KUN}, ¿quieres aprender sobre\n"
	.string "las BAYAS?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Las BAYAS crecen en árboles que\n"
	.string "solo prosperan en suelo limoso.\p"
	.string "Si tomas BAYAS, asegúrate de\n"
	.string "plantar una en suelo limoso.\p"
	.string "Una BAYA plantada brotará pronto,\n"
	.string "será planta, florecerá lindo,\l"
	.string "y dará BAYAS otra vez.\p"
	.string "Quiero ver el mundo entero\n"
	.string "lleno de flores hermosas.\l"
	.string "Ese es mi sueño.\p"
	.string "Ayúdame, {PLAYER}{KUN}. Planta BAYAS\n"
	.string "y trae más flores al mundo.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Las flores dan mucha felicidad a\n"
	.string "la gente, ¿no crees?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "¡Hola!\p"
	.string "Cuanto más cuides las flores,\n"
	.string "más bellas florecerán.\p"
	.string "Te gustará cuidarlas, estoy segura.\n"
	.string "Toma esto.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mientras crecen las BAYAS,\n"
	.string "riégalas con el BALDE WAILMER.\p"
	.string "Ah, otra cosa.\p"
	.string "Si no recoges las BAYAS pronto,\n"
	.string "caerán al suelo.\l"
	.string "Pero volverán a brotar.\p"
	.string "¿No es genial?\n"
	.string "Es como si quisieran vivir.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Quiero ser como mis hermanas.\n"
	.string "¡Yo también cultivo flores!\p"
	.string "¡Toma esto!\n"
	.string "¡Es para ti!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Un POKéMON come una BAYA para sanar,\n"
	.string "o puede llevarla equipada.\p"
	.string "En una región lejana que visité,\n"
	.string "tenían una máquina que mezcla\l"
	.string "BAYAS y hace dulces\l"
	.string "para POKéMON.\p"
	.string "Yo también quiero dulces.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hola, ¿cómo te llamas?\p"
	.string "… … …  … … …  … … …\n"
	.string "¡Vale. ¡Qué bien!\p"
	.string "Mi nombre es KIRI.\p"
	.string "Mis padres me llamaron así para que\n"
	.string "crezca sana y bondadosa.\l"
	.string "Eso es lo que deseaban.\p"
	.string "Toma una de estas.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "¡KIRI también te dará esta BAYA!\n"
	.string "¡Me gusta muchísimo!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Me pregunto qué deseo habrá\n"
	.string "en tu nombre.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Primavera, verano, otoño e invierno.\p"
	.string "Si naces en primavera, ¿te gusta\n"
	.string "la primavera? ¿Y si naces en\l"
	.string "verano, te gusta el verano?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "KIRI nació en otoño,\n"
	.string "¡por eso amo el otoño!\p"
	.string "¿Qué estación te gusta?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh...\n"
	.string "No importa...\p"
	.string "Hay tanto que quiero saber...$"
