gText_Birch_Welcome::
	.string "¡Hola! ¡Siento la espera!\p"
	.string "¡Bienvenido al mundo POKéMON!\p"
	.string "Mi nombre es OAK.\p"
	.string "Me llaman el PROFESOR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "A esto es a lo que llamamos\p"
	.string "un “POKéMON”.\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Este mundo está lleno de\n"
	.string "criaturas llamadas POKéMON.\p"
	.string "Humanos y POKéMON viven juntos\n"
	.string "y se apoyan mutuamente.\p"
	.string "Algunos juegan con POKéMON,\n"
	.string "otros luchan con ellos.\p"
	.string "Pero aún no sabemos todo sobre\n"
	.string "los POKéMON.\p"
	.string "Quedan muchos misterios por\n"
	.string "resolver. Por eso estudio\l"
	.string "POKéMON cada día.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "¿Y tú quién eres?$"

gText_Birch_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿O eres una chica?$"

gText_Birch_Difficulty::
	.string "Aha...\p"
	.string "Y... ¿cómo crees que será\n"
	.string "esta aventura?$"

gText_Birch_LockDifficulty::
	.string "Si quieres cambiar la DIFICULTAD\n"
	.string "abre el MENÚ de OPCIONES y\l"
	.string "cámbiala desde ahí.\p"
	.string "También puedes bloquearla.\n"
	.string "¿Quieres bloquear la\l"
	.string "DIFICULTAD elegida?\p"
	.string "No podrás cambiarla luego.$"

gText_Birch_Challenge::
	.string "Oh, ¿es así?\p"
	.string "Bien, aclarado eso...\n"
	.string "¿Esperas algún DESAFÍO\l"
	.string "en tu viaje?\p"
	.string "¿Y cuál es tu nombre?$"

gText_Birch_WhatsYourName::
	.string "Ahora, ¿cómo dijiste que era\n"
	.string "tu nombre?$"

gText_Birch_SoItsPlayer::
	.string "¡Oh! ¿Así que eres {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, ¿estás listo?\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Habrá momentos divertidos y\n"
	.string "retos difíciles.\p"
	.string "¡Un mundo de sueños y POKéMON\n"
	.string "te espera! ¡Vamos!\p"
	.string "¡Nos vemos luego!\p"
	.string "$"
