BerryBlender_Text_BlendWithTheBlendMaster:
	.string "MAESTRO MEZCLA: ¡Así es!\n"
	.string "¡Yo soy el MAESTRO MEZCLA!\p"
	.string "¡Mezcla conmigo y verás la maestría\n"
	.string "que tengo al mezclar!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "MAESTRO MEZCLA: ¡Hmm! ¿Así que quieres\n"
	.string "ver mi maestría en acción?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "¡Hmm!\p"
	.string "¡Veo que estás muy ocupado ahora!\p"
	.string "¡Pero no temas!\n"
	.string "¡Estaré aquí todo el día!\l"
	.string "¡Vuelve pronto de tu recado!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "¡Hmm!\p"
	.string "¡No tienes ni una sola BAYA!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Vuelve pronto con algunas BAYAS!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "¡Claro!\n"
	.string "¡Claro!\p"
	.string "Por cierto...\n"
	.string "¿Sabes cómo hacer {POKEBLOCK}S\l"
	.string "con BAYAS?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "¡Hmm!\p"
	.string "¡Ah, pero es un proceso simple!\p"
	.string "Cuando la flecha de la MEZCLADORA\n"
	.string "llegue a tu marca, pulsa el Botón A.\p"
	.string "Eso es todo lo que tienes que hacer.\p"
	.string "Cuando veas mi precisión al pulsar\n"
	.string "el Botón A, lo entenderás.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "¡Bien!\p"
	.string "¡Empecemos entonces!\p"
	.string "¡Junto al MAESTRO MEZCLA,\n"
	.string "vamos a usar la MEZCLADORA de BAYAS!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "¡Hmmm!\p"
	.string "¡Parece que no tienes\n"
	.string "el ESTUCHE {POKEBLOCK}!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Busca el ESTUCHE {POKEBLOCK} y vuelve!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "¡Hmmm!\p"
	.string "¡Tu ESTUCHE {POKEBLOCK} está lleno!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Usa {POKEBLOCK}S y vuelve pronto!$"

BerryBlender_Text_WhoaAwesome:
	.string "¡Vaya!\n"
	.string "¡Increíble!$"

BerryBlender_Text_WickedlyFast:
	.string "¡Rápido a más no poder!$"

BerryBlender_Text_WhatAnExpert:
	.string "¡Qué experto!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "¡Al mezclar con el MAESTRO,\n"
	.string "hicimos {POKEBLOCK}S increíbles!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Ojos que siguen la flecha con\n"
	.string "intensidad de máquina...\p"
	.string "Una mano que pulsa el Botón A\n"
	.string "con precisión de reloj...\p"
	.string "Tener esto hace que el MAESTRO\n"
	.string "de MEZCLA sea realmente genial.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "El MAESTRO de MEZCLA entrena\n"
	.string "sus habilidades en las montañas.\p"
	.string "A veces viene a VIRIDIAN\n"
	.string "a mezclar BAYAS todo el día.$"
