CableClub_Text_WelcomeWhichCableClubService:
	.string "Bienvenido al CLUB CABLE\n"
	.string "POKéMON.\p"
	.string "¿Qué servicio deseas\n"
	.string "utilizar?$"

CableClub_Text_WhichService:
	.string "¿Qué servicio deseas\n"
	.string "utilizar?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Intercambia POKéMON con otro jugador\n"
	.string "usando el cable cable Game Link de GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Puedes luchar contra otro ENTRENADOR\n"
	.string "usando el cable cable Game Link de GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Usa el RINCÓN DE RÉCORDS con otros\n"
	.string "usando el cable cable Game Link de GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Cerrar este menú.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Para una BATALLA DOBLE, debes tener\n"
	.string "al menos dos POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Para intercambiar, debes llevar\n"
	.string "al menos dos POKéMON contigo.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Un POKéMON con la BAYA {STR_VAR_1}\n"
	.string "no puede ser intercambiado.$"

gText_PleaseWaitForLink::
	.string "Por favor, espera.\n"
	.string "... ... Botón B: Cancelar$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Cuando todos estén listos...\n"
	.string "Botón A: Confirmar\l"
	.string "Botón B: Cancelar$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Enlace con {STR_VAR_1} jugadores.\n"
	.string "Botón A: Confirmar\l"
	.string "Botón B: Cancelar$"

gText_AwaitingLinkup::
	.string "Esperando conexión...\n"
	.string "... ... Botón B: Cancelar$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Debes guardar tu progreso antes\n"
	.string "del enlace. ¿Quieres guardar?$"

CableClub_Text_PleaseEnter:
	.string "Por favor, entra.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Ahora te llevaré a tu habitación.$"

Text_SomeoneIsNotReadyToLink:
	.string "Alguien no está listo.\p"
	.string "Vuelve cuando todos estén\n"
	.string "preparados.$"

Text_LinkErrorPleaseReset:
	.string "Lo siento, hay un error de enlace…\n"
	.string "Reinicia e inténtalo de nuevo.$"

Text_PlayersMadeDifferentSelections:
	.string "Parece que los jugadores han\n"
	.string "elegido opciones distintas.$"

CableClub_Text_PleaseVisitAgain:
	.string "Por favor, vuelve pronto.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "El número de participantes es\n"
	.string "incorrecto.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "El modo BATALLA INDIVIDUAL no\n"
	.string "es para {STR_VAR_1} jugadores.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "El modo BATALLA DOBLE no puede\n"
	.string "ser para {STR_VAR_1} jugadores.$"

CableClub_Text_NeedFourPlayers:
	.string "Se necesitan cuatro jugadores para\n"
	.string "este modo de batalla.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Confirma el número de\n"
	.string "jugadores y empieza de nuevo.$"

Text_TerminateLinkConfirmation:
	.string "El enlace se cortará si sales\n"
	.string "de la sala. ¿Está bien?$"

Text_TerminateLinkPleaseWait:
	.string "Cortando enlace...\n"
	.string "Te sacarán de la sala\l"
	.string "ahora. Por favor, espera.$"

CableClub_Text_TooBusyToNotice:
	.string "Este ENTRENADOR está muy\n"
	.string "ocupado para notar...$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "¡Genial! Vi la de {STR_VAR_1}\n"
	.string "TARJETA ENTRENADOR!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "¡Genial! Vi la de {STR_VAR_1}\n"
	.string "TARJETA ENTRENADOR!\p"
	.string "¡Es una tarjeta {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Toma tu lugar y comienza\n"
	.string "tu batalla.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Toma tu asiento y comienza\n"
	.string "tu intercambio.$"

RecordCorner_Text_ThanksForComing:
	.string "Gracias por venir.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Los datos de la TRAINER CARD\n"
	.string "serán sobrescritos.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "¡Espero verte pronto!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Lo siento mucho.\p"
	.string "Aún no podemos hacer intercambios\n"
	.string "con ENTRENADORES de otras\l"
	.string "regiones…$"

CableClub_Text_OtherTrainerNotReady:
	.string "El otro ENTRENADOR no está listo.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Tienes al menos un POKéMON\n"
	.string "que no puede ser transferido.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Toma asiento y espera, por favor.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} envió un\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Error de transmisión.\p"
	.string "No mezcles datos con juegos\n"
	.string "Ruby o Sapphire japoneses.\p"
	.string "Tampoco mezcles Emerald japonés\n"
	.string "con Ruby o Sapphire extranjeros.\l"
	.string "Hazlo por separado.$"

CableClub_Text_AdapterNotConnected:
	.string "El Adaptador Inalámbrico no\n"
	.string "está conectado bien.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Se pide a los participantes que\n"
	.string "pasen al mostrador de recepción.$"

@ Unused
CableClub_Text_Hello:
	.string "¡Hola!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Espera, por favor.$"

CableClub_Text_YouMayTradeHere::
	.string "Puedes intercambiar POKéMON\n"
	.string "con otro ENTRENADOR aquí.$"

CableClub_Text_YouMayBattleHere::
	.string "Puedes luchar contra tus amigos\n"
	.string "aquí.$"

CableClub_Text_CanMakeBerryPowder::
	.string "De dos a cinco ENTRENADORES\n"
	.string "pueden hacer POLVO BAYA juntos.$"

CableClub_Text_CanMixRecords::
	.string "Los datos de dos a cuatro jugadores\n"
	.string "se pueden mezclar.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Una guía de los diversos servicios\n"
	.string "del CLUB INALÁMBRICO.$"

CableClub_Text_CancelSelectedItem::
	.string "Cancela el elemento del MENÚ.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "¿Qué modo de batalla prefieres?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Vuelve al paso anterior.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Para usar el servicio de BAYAS,\n"
	.string "debes tener al menos una BAYA.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Para entrar al CUARTO UNIÓN, debes\n"
	.string "tener al menos dos POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Ningún POKéMON con la {STR_VAR_1}\n"
	.string "BAYA puede entrar al UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Esta es la SALA DE UNIÓN del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Tu Adaptador Inalámbrico no\n"
	.string "está conectado correctamente.\p"
	.string "Vuelve pronto.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh...\n"
	.string "¡Disculpa!$"

CableClub_Text_PlayerIsWaiting:
	.string "Parece que {STR_VAR_1} está\n"
	.string "jugando ahora mismo.\l"
	.string "¡Ve a por ello!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Puedo explicarte las reglas si\n"
	.string "quieres.\p"
	.string "¿Qué juego quieres que describa?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“SALTO POKéMON”\p"
	.string "Haz que tu POKéMON salte la cuerda\n"
	.string "de LÁTIGO CEPA con el botón A.\p"
	.string "Solo POKéMON mini de 70 cm\n"
	.string "o menos pueden participar.\p"
	.string "POKéMON que solo nadan, cavan\n"
	.string "o vuelan no saltan bien.\p"
	.string "Por eso, esos POKéMON no pueden\n"
	.string "participar.\p"
	.string "Pasarán cosas buenas si todos\n"
	.string "saltan a tiempo.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“COSECHA DE DODRIO”\p"
	.string "Guía las tres cabezas de DODRIO\n"
	.string "para atrapar BAYAS que caen.\p"
	.string "Usa derecha, arriba o izquierda en\n"
	.string "el Control Pad {PLUS} para moverlas.\p"
	.string "Para jugar, debes tener\n"
	.string "un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si quieres jugar a algo,\n"
	.string "avísale al anciano que está aquí.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "¡Hola, bienvenido!\n"
	.string "¿Vienes a jugar usando la\l"
	.string "Comunicación Inalámbrica?\p"
	.string "¿Puedes esperar un momento?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "¡Muy bien, vuelve pronto!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "El Adaptador Inalámbrico no está\n"
	.string "conectado. ¡Vuelve cuando lo esté!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Muy bien, ¿a qué juego quieres\n"
	.string "jugar?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "¿Qué POKéMON te gustaría\n"
	.string "ingresar?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Listo, ya puedes empezar.\n"
	.string "¡No dejes que te ganen!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "¿Te vas ya?\n"
	.string "¡Vuelve pronto!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Parece que no tienes POKéMON que\n"
	.string "puedan participar...\p"
	.string "¿Quieres que te explique qué\n"
	.string "POKéMON pueden entrar?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“POKéMON JUMP” es para POKéMON de\n"
	.string "28 pulgadas o menos.\p"
	.string "No pueden entrar los POKéMON que\n"
	.string "no saben saltar.\p"
	.string "Como los que solo nadan,\n"
	.string "cavan o vuelan.\p"
	.string "Eso es todo lo que debes saber.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "RECOLECCIÓN DE BAYAS DODRIO es un\n"
	.string "juego solo para DODRIO.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "¿Podrías intentar esto desde el\n"
	.string "principio otra vez, por favor?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Bienvenido al CLUB WIRELESS\n"
	.string "DE POKéMON, SECCIÓN DIRECTA.\p"
	.string "Aquí puedes interactuar\n"
	.string "directamente con tus amigos.\p"
	.string "¿A qué habitación quieres\n"
	.string "entrar?$"

CableClub_Text_TradePokemon:
	.string "¿Quieres intercambiar POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "¿Qué Modo de Batalla quieres\n"
	.string "jugar?$"

CableClub_Text_AccessRecordCorner:
	.string "¿Quieres entrar al\n"
	.string "RINCÓN DE RÉCORDS?$"

CableClub_Text_UseBerryCrush:
	.string "¿Quieres usar el sistema de\n"
	.string "TRITURADO DE BAYAS?$"

CableClub_Text_ExplainBattleModes:
	.string "Hay tres Modos de Batalla.\p"
	.string "BATALLA INDIVIDUAL es para dos\n"
	.string "ENTRENADORES con uno o más POKéMON.\p"
	.string "Cada ENTRENADOR puede tener un\n"
	.string "POKéMON en batalla a la vez.\p"
	.string "BATALLA DOBLE es para dos\n"
	.string "ENTRENADORES con dos o más POKéMON.\p"
	.string "Cada ENTRENADOR enviará dos\n"
	.string "POKéMON en batalla a la vez.\p"
	.string "BATALLA MULTI es para cuatro\n"
	.string "ENTRENADORES con uno o más POKéMON.\p"
	.string "Cada ENTRENADOR puede tener un\n"
	.string "POKéMON en batalla a la vez.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Decidan cuál de los dos\n"
	.string "será el LÍDER.\p"
	.string "El otro jugador debe elegir\n"
	.string "“UNIRSE AL GRUPO”.$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Decidan cuál de los cuatro\n"
	.string "será el LÍDER DEL GRUPO.\p"
	.string "Los otros deben elegir\n"
	.string "“UNIRSE AL GRUPO”.$"

CableClub_Text_ChooseGroupLeader:
	.string "Decidan quién de ustedes será\n"
	.string "el LÍDER DEL GRUPO.\p"
	.string "Los otros jugadores deben elegir\n"
	.string "“UNIRSE AL GRUPO”.$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Bienvenido al CLUB UNIÓN del\n"
	.string "POKéMON WIRELESS.\p"
	.string "Aquí puedes interactuar con\n"
	.string "otros ENTRENADORES, incluso\l"
	.string "con algunos que no conozcas.\p"
	.string "¿Quieres entrar a la SALA?$"

CableClub_Text_UnionRoomInfo:
	.string "Los ENTRENADORES de la SALA UNIÓN\n"
	.string "serán jugadores cercanos que\l"
	.string "también hayan entrado a la SALA.\p"
	.string "Puedes hacer muchas cosas aquí,\n"
	.string "como intercambiar saludos.\p"
	.string "Puedes usar dos POKéMON hasta\n"
	.string "Nv. 30 para un combate individual.\p"
	.string "Puedes participar en un chat de\n"
	.string "dos a cinco personas.\p"
	.string "O puedes registrar un POKéMON\n"
	.string "para intercambiar.\p"
	.string "¿Quieres entrar a la SALA?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Espero que disfrutes tu tiempo en\n"
	.string "la SALA UNIÓN.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "¡Hola!\n"
	.string "Mi nombre es TEALA.\p"
	.string "Debe ser tu primera vez\n"
	.string "por aquí.\p"
	.string "Te enseñaré cómo funciona el\n"
	.string "Sistema de Comunicación Wireless.\p"
	.string "Primero, debo mostrarte este\n"
	.string "piso de nuestro POKéMON CENTER.\p"
	.string "Por aquí, por favor.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "En el último piso hay dos salas\n"
	.string "y el WONDERTRADE.\p"
	.string "Primero, el sistema WONDERTRADE.\p"
	.string "El hombre del mostrador puede\n"
	.string "explicarlo mejor, ¡él sabe\l"
	.string "más que yo sobre eso!\p"
	.string "Por favor, ve a hablar con él.\p"
	.string "Segundo, la sala del centro.\n"
	.string "Es la SALA UNIÓN.\p"
	.string "Puedes conectarte con ENTRENADORES\n"
	.string "cercanos que también hayan\l"
	.string "entrado a la SALA UNIÓN.\p"
	.string "Con ellos puedes chatear,\n"
	.string "luchar e intercambiar.\p"
	.string "Por último, la sala de la derecha\n"
	.string "es el RINCÓN DIRECTO.\p"
	.string "Aquí puedes luchar o cambiar\n"
	.string "POKéMON con tus amigos.\p"
	.string "Si el Adaptador Wireless no está\n"
	.string "conectado, puedes usar un\l"
	.string "cable cable Game Link de GBA.\p"
	.string "En ese caso, debes ir al\n"
	.string "RINCÓN DIRECTO.\p"
	.string "Espero que disfrutes el Sistema\n"
	.string "de Comunicación Wireless.$"

CableClub_Text_AskAboutLinking:
	.string "¡Hola, {PLAYER}!\p"
	.string "Soy TEALA, la asistente del\n"
	.string "2F del CENTRO POKéMON.\p"
	.string "¿Quieres preguntarme algo sobre\n"
	.string "la conexión?$"

CableClub_Text_ExplainWirelessClub:
	.string "Te explicaré cómo funciona el\n"
	.string "CLUB INALÁMBRICO POKéMON.\p"
	.string "En este piso superior hay\n"
	.string "dos salas.\p"
	.string "Primero, la sala de la izquierda.\n"
	.string "Es la SALA UNIÓN.\p"
	.string "Puedes conectarte con ENTRENADORES\n"
	.string "cercanos que hayan entrado\l"
	.string "en la SALA UNIÓN.\p"
	.string "Con ellos puedes chatear,\n"
	.string "luchar e intercambiar.\p"
	.string "Segundo, la sala de la derecha\n"
	.string "es el RINCÓN DIRECTO.\p"
	.string "Aquí puedes luchar o cambiar\n"
	.string "POKéMON con tus amigos.\p"
	.string "A veces no hallarás a tus amigos\n"
	.string "en la SALA UNIÓN\l"
	.string "o el RINCÓN DIRECTO.\p"
	.string "En ese caso, acércate más\n"
	.string "a tus amigos.\p"
	.string "Si el Adaptador Inalámbrico no\n"
	.string "está conectado, usa un\l"
	.string "cable Game Link de GBA.\p"
	.string "Si es así, debes ir\n"
	.string "al RINCÓN DIRECTO.\p"
	.string "¡Espero que disfrutes el Sistema\n"
	.string "de Comunicación Inalámbrica!$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "¡Espero que disfrutes el Sistema\n"
	.string "de Comunicación Inalámbrica!$"
