Text_PictureBookShelf:
	.string "Hay libros de imágenes de POKéMON.$"

Text_BookShelf:
	.string "Está lleno de todo tipo de libros.$"

Text_PokemonCenterBookShelf:
	.string "¡Revistas de POKéMON!\n"
	.string "POKéMON PAL…\p"
	.string "MANUAL POKéMON…\n"
	.string "POKéMON ADORABLES…$"

Text_Vase:
	.string "Este florero parece caro…\n"
	.string "Miré adentro…\p"
	.string "Pero estaba vacío.$"

Text_EmptyTrashCan:
	.string "Está vacío.$"

Text_ShopShelf:
	.string "Los estantes rebosan de todo tipo de\n"
	.string "productos de POKéMON.$"

Text_Blueprint:
	.string "¿Un plano de algún tipo?\n"
	.string "¡Es muy complicado!$"
