@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Un movimiento muy atractivo.$"

gText_UserMoreEasilyStartled::
	.string "Tras esto, el usuario se\n"
	.string "asusta más fácilmente.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Atrae mucho, pero no se\n"
	.string "puede repetir al final.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Se puede usar repetidamente\n"
	.string "sin aburrir al JUEZ.$"

gText_AvoidStartledByOthersOnce::
	.string "Evita asustarse por otros\n"
	.string "una sola vez.$"

gText_AvoidStartledByOthers::
	.string "Puede evitar que otros\n"
	.string "lo asusten.$"

gText_AvoidStartledByOthersLittle::
	.string "Evita asustarse un poco\n"
	.string "por otros.$"

gText_UserLessLikelyStartled::
	.string "Tras esto, es menos probable\n"
	.string "que el usuario se asuste.$"

gText_SlightlyStartleFrontMon::
	.string "Asusta un poco al\n"
	.string "POKéMON de enfrente.$"

gText_SlightlyStartleAppealed::
	.string "Asusta un poco a los que\n"
	.string "ya hicieron su exhibición.$"

gText_StartleAppealedBeforeUser::
	.string "Asusta al POKéMON que\n"
	.string "se exhibió antes que tú.$"

gText_StartleAllAppealed::
	.string "Asusta a todo POKéMON que\n"
	.string "ya haya hecho su exhibición.$"

gText_BadlyStartleFrontMon::
	.string "Asusta mucho al\n"
	.string "POKéMON de enfrente.$"

gText_BadlyStartleAppealed::
	.string "Asusta mucho a los que\n"
	.string "ya hicieron su exhibición.$"

gText_StartleAppealedBeforeUser2::
	.string "Asusta al POKéMON que\n"
	.string "se exhibió antes que tú.$"

gText_StartleAllAppealed2::
	.string "Asusta a todo POKéMON que\n"
	.string "ya haya hecho su exhibición.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Desvía la atención del JUEZ\n"
	.string "lejos de los demás.$"

gText_StartleMonHasJudgesAttention::
	.string "Asusta al POKéMON que\n"
	.string "tiene la atención del JUEZ.$"

gText_JamOthersMissesTurn::
	.string "Aturde a los demás y pierde\n"
	.string "un turno de exhibición.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Asusta a los POKéMON que\n"
	.string "hicieron el mismo tipo de gala.$"

gText_BadlyStartleCoolAppeals::
	.string "Asusta mucho a los POKéMON\n"
	.string "que hicieron galas COOL.$"

gText_BadlyStartleBeautyAppeals::
	.string "Asusta mucho a los POKéMON\n"
	.string "que hicieron galas BEAUTY.$"

gText_BadlyStartleCuteAppeals::
	.string "Asusta mucho a los POKéMON\n"
	.string "que hicieron galas CUTE.$"

gText_BadlyStartleSmartAppeals::
	.string "Asusta mucho a los POKéMON\n"
	.string "que hicieron galas SMART.$"

gText_BadlyStartleToughAppeals::
	.string "Asusta mucho a los POKéMON\n"
	.string "que hicieron apelaciones Duras.$"

gText_MakeMonAfterUserNervous::
	.string "Pone nervioso al POKéMON\n"
	.string "que sigue al usuario.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Pone nerviosos a todos los\n"
	.string "POKéMON tras el usuario.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Empeora la condición de los\n"
	.string "que hicieron apelaciones.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Asusta mucho a los POKéMON\n"
	.string "en buena condición.$"

gText_AppealGreatIfPerformedFirst::
	.string "La apelación es genial si\n"
	.string "se hace al principio.$"

gText_AppealGreatIfPerformedLast::
	.string "La apelación es genial si\n"
	.string "se hace al final.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Hace que la apelación sea\n"
	.string "tan buena como las previas.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Hace que el atractivo sea tan\n"
	.string "bueno como el anterior.$"

gText_AppealBetterLaterItsPerformed::
	.string "El atractivo funciona mejor\n"
	.string "si se hace más tarde.$"

gText_AppealVariesDependingOnTiming::
	.string "La calidad del atractivo varía\n"
	.string "según el momento en que se use.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Funciona bien si es del mismo\n"
	.string "tipo que el anterior.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Funciona bien si es de un tipo\n"
	.string "distinto al anterior.$"

gText_AffectedByAppealInFront::
	.string "Depende de qué tan bien salga\n"
	.string "el atractivo anterior.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Sube la condición del usuario.\n"
	.string "Evita que se ponga nervioso.$"

gText_AppealWorksWellIfConditionGood::
	.string "El atractivo funciona bien si\n"
	.string "la condición del usuario es buena.$"

gText_NextAppealMadeEarlier::
	.string "El próximo atractivo podrá\n"
	.string "hacerse antes el próximo turno.$"

gText_NextAppealMadeLater::
	.string "El próximo atractivo podrá\n"
	.string "hacerse después el próximo turno.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Hace que el orden del próximo\n"
	.string "turno se altere más fácilmente.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Altera el orden de los\n"
	.string "atractivos en el próximo turno.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Un atractivo que emociona al\n"
	.string "público en cualquier CONTEST.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Asusta a los POKéMON que\n"
	.string "hicieron buenos atractivos.$"

gText_AppealBestMoreCrowdExcited::
	.string "El atractivo funciona mejor\n"
	.string "si el público está emocionado.$"

gText_TemporarilyStopCrowdExcited::
	.string "Evita temporalmente que el\n"
	.string "público se emocione.$"

@ Unused move names

gText_RainDance::
	.string "DANZA LLUVIA$"

gText_Rage::
	.string "Furia$"

gText_FocusEnergy::
	.string "ENERGÍA INTERIOR$"

gText_Hypnosis::
	.string "HIPNOSIS$"

gText_Softboiled::
	.string "CURASANAS$"

gText_HornAttack::
	.string "CORNADA$"

gText_SwordsDance::
	.string "DANZA ESPADA$"

gText_Conversion::
	.string "CONVERSIÓN$"

gText_SunnyDay::
	.string "DÍA SOLEADO$"

gText_Rest2::
	.string "DESCANSO$"

gText_Vicegrip::
	.string "TORNILLO$"

gText_DefenseCurl::
	.string "ENROLLAR$"

gText_LockOn::
	.string "FIJAR$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "GENIAL$"

gContestMoveTypeBeautyText::
	.string "BELLEZA$"

gContestMoveTypeCuteText::
	.string "LINDO$"

gContestMoveTypeSmartText::
	.string "INTELIGENTE$"

gContestMoveTypeToughText::
	.string "FUERTE$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "¡Turno {STR_VAR_1}!\n"
	.string "¿Qué movimiento usará?$"

gText_AppealNumButItCantParticipate::
	.string "¡Turno {STR_VAR_1}!\n"
	.string "¡Pero no puede participar!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} hizo un atractivo con\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} observaba\n"
	.string "a los demás.$"

gText_AllOutOfAppealTime::
	.string "¡Se acabó el tiempo\n"
	.string "de atractivo!$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Pero el atractivo fue\n"
	.string "bloqueado.$"

gText_FollowedAnotherMonsLead::
	.string "Siguió el ejemplo de otro\n"
	.string "POKéMON.$"

gText_ButItMessedUp::
	.string "Pero cometió un error.$"

gText_WentBetterThanUsual::
	.string "Salió mejor de lo\n"
	.string "habitual.$"

gText_JudgeLookedAwayForSomeReason::
	.string "El JUEZ miró hacia otro lado\n"
	.string "por alguna razón.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Se esforzó para mejorar sus\n"
	.string "errores pasados.$"

gText_CantMakeAnyMoreMoves::
	.string "Ya no puede hacer\n"
	.string "más movimientos.$"

gText_WorkedFrighteninglyWell::
	.string "Funcionó asombrosamente\n"
	.string "bien.$"

gText_WorkedHardAsStandoutMon::
	.string "Se esforzó tanto como el\n"
	.string "POKéMON destacado.$"

gText_JudgedLookedOnExpectantly::
	.string "El JUEZ miraba con\n"
	.string "expectativa.$"

gText_WorkedRatherWell::
	.string "Salió bastante bien.$"

gText_WorkedLittleBetterThanUsual::
	.string "Salió un poco mejor\n"
	.string "de lo habitual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} no logró\n"
	.string "destacar nada…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} no destacó\n"
	.string "demasiado…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} llamó un\n"
	.string "poco la atención.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} llamó\n"
	.string "mucha atención.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} captó\n"
	.string "toda la atención.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} aún no ha\n"
	.string "hecho su exhibición.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "La expectativa crece por\n"
	.string "la exhibición de {STR_VAR_1}.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "La opinión del JUEZ sobre\n"
	.string "{STR_VAR_1} no cambió.$"

gText_MonsXChangedPerceptions::
	.string "La {STR_VAR_3} de {STR_VAR_1}\n"
	.string "cambió las percepciones.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff::
	.string "El efecto de la exhibición\n"
	.string "especial terminó.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Todas las exhibiciones\n"
	.string "parecen ahora iguales.$"

gText_CheapenedMonsAppeal::
	.string "Esto le quitó valor a la\n"
	.string "exhibición de {STR_VAR_2}.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Le quitó atractivo\n"
	.string "a los anteriores.$"

gText_StoleAttentionAwayFromMon::
	.string "Le robó la atención\n"
	.string "a {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Le quitó atractivo\n"
	.string "al de {STR_VAR_2}.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Le quitó mucho atractivo\n"
	.string "a otros concursos.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Creció la expectativa por\n"
	.string "el turno de {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Le quitó atractivo\n"
	.string "a los anteriores.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Le quitó atractivo al\n"
	.string "favorito del JUEZ.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "El atractivo de otros\n"
	.string "bajó a la mitad.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Destacó para compensar\n"
	.string "haberse trabado.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Ya no puede participar\n"
	.string "en los concursos.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Tocó al JUEZ con un\n"
	.string "estilo fantástico.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Subió la expectativa por\n"
	.string "los próximos turnos.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Destacó tanto como los\n"
	.string "estilos especiales.$"

gText_StoodOutAsMuchAsMon::
	.string "Destacó tanto como\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Los fallos pasaron\n"
	.string "más desapercibidos.$"

gText_EveryonesAppealsMadeSame::
	.string "Todos los estilos\n"
	.string "se volvieron iguales.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Se volvió más consciente\n"
	.string "de los otros POKéMON.$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} ya no puede\n"
	.string "hacer un atractivo.$"

gText_SettledDownJustLittleBit::
	.string "Se calmó solo un\n"
	.string "poco.$"

gText_BecameObliviousToOtherMons::
	.string "Ignoró por completo a\n"
	.string "los otros POKéMON.$"

gText_BecameLessAwareOfOtherMons::
	.string "Se volvió menos consciente\n"
	.string "de los otros POKéMON.$"

gText_StoppedCaringAboutOtherMons::
	.string "Ya no le importan mucho\n"
	.string "los otros POKéMON.$"

gText_TriedToStartleOtherMons::
	.string "Intentó asustar a los\n"
	.string "otros POKéMON.$"

gText_TriedToDazzleOthers::
	.string "Intentó deslumbrar a\n"
	.string "los demás.$"

gText_JudgeLookedAwayFromMon::
	.string "El JUEZ miró hacia otro\n"
	.string "lado que {STR_VAR_1}.$"

gText_TriedToUnnerveNextMon::
	.string "Intentó poner nervioso\n"
	.string "al siguiente POKéMON.$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} se puso\n"
	.string "nervioso.$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Intentó inquietar a los\n"
	.string "POKéMON que esperaban.$"

gText_TauntedMonsDoingWell::
	.string "Se burló de los POKéMON\n"
	.string "que iban bien.$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} recuperó\n"
	.string "su forma.$"

gText_TriedToJamMonDoingWell::
	.string "Intentó frenar a los\n"
	.string "POKéMON que iban bien.$"

gText_StandoutMonHustledEvenMore::
	.string "El brillante {STR_VAR_1}\n"
	.string "se esforzó aún más.$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Casi nadie lo notó,\n"
	.string "{STR_VAR_1} se esforzó.$"

gText_WorkedAsMuchAsMonBefore::
	.string "Se esforzó tanto como\n"
	.string "el POKéMON anterior.$"

gText_MonsAppealDidNotGoWell::
	.string "El encanto de {STR_VAR_1}\n"
	.string "no funcionó bien.$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Se esforzó tanto como el\n"
	.string "POKéMON anterior.$"

gText_MonsAppealDidNotGoWell2::
	.string "El encanto de {STR_VAR_1}\n"
	.string "no funcionó bien.$"

gText_MonsAppealDidNotGoWell3::
	.string "El encanto de {STR_VAR_1}\n"
	.string "no funcionó bien.$"

gText_MonsAppealWentSlightlyWell::
	.string "El encanto de {STR_VAR_1}\n"
	.string "funcionó un poco.$"

gText_MonsAppealWentPrettyWell::
	.string "El encanto de {STR_VAR_1}\n"
	.string "funcionó muy bien.$"

gText_MonsAppealWentExcellently::
	.string "El atractivo de {STR_VAR_1}\n"
	.string "fue excelente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "El atractivo de {STR_VAR_1}\n"
	.string "fue un fracaso.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "El atractivo de {STR_VAR_1}\n"
	.string "no funcionó muy bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "El atractivo de {STR_VAR_1}\n"
	.string "estuvo regular.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "El atractivo de {STR_VAR_1}\n"
	.string "estuvo bastante bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "El atractivo de {STR_VAR_1}\n"
	.string "estuvo muy bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "El atractivo de {STR_VAR_1}\n"
	.string "fue excelente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Es del mismo tipo que el\n"
	.string "POKéMON anterior. ¡Bien!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "No es del mismo tipo que\n"
	.string "el anterior... ¡bien!$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Destacó mucho más que\n"
	.string "el POKéMON anterior.$"

gText_DidntDoAsWellAsMonBefore::
	.string "No le fue tan bien como\n"
	.string "al POKéMON anterior.$"

gText_MonsConditionRoseAboveUsual::
	.string "La condición de {STR_VAR_1}\n"
	.string "está mejor que siempre.$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "¡El estado de {STR_VAR_1}\n"
	.string "hizo que luciera genial!$"

gText_MovedUpInLineForNextAppeal::
	.string "Subió un puesto en la fila\n"
	.string "para el próximo turno.$"

gText_MovedBackInLineForNextAppeal::
	.string "Bajó un puesto en la fila\n"
	.string "para el próximo turno.$"

gText_ScrambledUpOrderForNextTurn::
	.string "Subió varios puestos en\n"
	.string "el orden del próximo turno.$"

gText_JudgeLookedAtMonExpectantly::
	.string "El JUEZ miró a\n"
	.string "{STR_VAR_1} con expectación.$"

gText_AppealComboWentOverWell::
	.string "El combo de atractivo\n"
	.string "funcionó bien.$"

gText_AppealComboWentOverVeryWell::
	.string "El combo de atractivo\n"
	.string "funcionó muy bien.$"

gText_AppealComboWentOverExcellently::
	.string "El combo de atractivo\n"
	.string "fue excelente.$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} logró\n"
	.string "desviar la mirada.$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} logró\n"
	.string "evitar verlo.$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} no se\n"
	.string "inmuta por eso.$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} se\n"
	.string "distrajo un poco.$"

gText_TriedToStartleOtherPokemon::
	.string "Intentó asustar al\n"
	.string "otro POKéMON.$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} miró hacia\n"
	.string "abajo distraído.$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} se volvió\n"
	.string "por distracción.$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} no pudo\n"
	.string "evitar gritar.$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} no pudo\n"
	.string "evitar saltar.$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} tropezó\n"
	.string "por distracción.$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} estaba\n"
	.string "muy nervioso.$"

gText_ButItMessedUp2::
	.string "Pero falló.$"

gText_ButItFailedToMakeTargetNervous::
	.string "Pero no logró poner\n"
	.string "nervioso al rival.$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Pero no logró poner\n"
	.string "a nadie nervioso.$"

gText_ButItWasIgnored::
	.string "Pero fue ignorado...$"

gText_CouldntImproveItsCondition::
	.string "Pero no pudo mejorar\n"
	.string "su condición...$"

gText_BadConditionResultedInWeakAppeal::
	.string "Su mala condición\n"
	.string "causó un débil atractivo.$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} no\n"
	.string "se vio afectado.$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} decepcionó\n"
	.string "al repetir el atractivo.$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_3} de {STR_VAR_1}\n"
	.string "salió muy bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "no cayó bien aquí…$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "animó a la multitud.$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} no puede lucirse\n"
	.string "el próximo turno…$"

gText_AttractedCrowdsAttention::
	.string "Atrajo la atención\n"
	.string "de la multitud.$"

gText_CrowdContinuesToWatchMon::
	.string "La multitud sigue\n"
	.string "viendo a {STR_VAR_3}.$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} es ignorado.$"

gText_Contest_Shyness::
	.string "timidez$"

gText_Contest_Anxiety::
	.string "ansiedad$"

gText_Contest_Laziness::
	.string "pereza$"

gText_Contest_Hesitancy::
	.string "vacilación$"

gText_Contest_Fear::
	.string "miedo$"

gText_Contest_Coolness::
	.string "estilo$"

gText_Contest_Beauty::
	.string "belleza$"

gText_Contest_Cuteness::
	.string "ternura$"

gText_Contest_Smartness::
	.string "inteligencia$"

gText_Contest_Toughness::
	.string "fortaleza$"

@ Unused
gText_Tension::
	.string "TENSIÓN$"

gText_CoolMove::
	.string "Mov. GENIAL$"

gText_BeautyMove::
	.string "Mov. BELLA$"

gText_CuteMove::
	.string "Mov. LINDO$"

gText_SmartMove::
	.string "Mov. INTELIGENTE$"

gText_ToughMove::
	.string "Mov. FUERTE$"

gText_3QuestionMarks::
	.string "???$"
