gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} de {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "CONCURSO$"

gContestRankNormal::
	.string "RANGO NORMAL$"

gContestRankSuper::
	.string "RANGO SÚPER$"

gContestRankHyper::
	.string "RANGO HIPER$"

gContestRankMaster::
	.string "RANGO MASTER$"

gContestLink::
	.string "VÍNCULO$"

gContestCoolness::
	.string "GENIALIDAD$"

gContestBeauty::
	.string "BELLEZA$"

gContestCuteness::
	.string "TERNURA$"

gContestSmartness::
	.string "INTELIGENCIA$"

gContestToughness::
	.string "DUREZA$"

gContestPaintingCool1::
	.string "Súper genial sin parar--\n"
	.string "el inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "¡Hola!\n"
	.string "El atractivo POKéMON {STR_VAR_1}$"

gContestPaintingCool3::
	.string "El maravilloso, increíble y\n"
	.string "grandioso {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "La última Venus del siglo--\n"
	.string "la bella {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "{STR_VAR_1} y su sonrisa\n"
	.string "deslumbrante y brillante$"

gContestPaintingBeauty3::
	.string "La superidol del POKéMON CENTER\n"
	.string "la incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "La dulce y encantadora {STR_VAR_1}$"

gContestPaintingCute2::
	.string "El lindo {STR_VAR_1}\n"
	.string "retrato de victoria$"

gContestPaintingCute3::
	.string "¡Guiñanos un ojo!\n"
	.string "El lindo POKéMON {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "El maestro de la inteligencia\n"
	.string "el sabio POKéMON {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}, el elegido\n"
	.string "sobre todo POKéMON$"

gContestPaintingSmart3::
	.string "El excelente {STR_VAR_1}\n"
	.string "en su momento de elegancia$"

gContestPaintingTough1::
	.string "El veloz y musculoso\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough2::
	.string "El fuerte, más fuerte y\n"
	.string "el más fuerte {STR_VAR_1}$"

gContestPaintingTough3::
	.string "El poderoso y resistente\n"
	.string "hiper POKéMON {STR_VAR_1}$"
