@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Turno perdido$"

gText_LinkStandby4::
	.string "¡Enlace listo!$"

gText_WinnerIsPlayersMonCongrats::
	.string "¡Ganó {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Felicidades!$"

gText_WinnerIsPlayersMon::
	.string "¡Ganó {STR_VAR_2} de {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Juez primario: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Juez secundario: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Evento fijado: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "El movimiento más usado:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "El POKéMON más impresionante:\n"
	.string "El {STR_VAR_2} de {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Evento fijado: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "No habrá programa de TV\n"
	.string "porque el ENTRENADOR perdió.{PAUSE_UNTIL_PRESS}$"
