EventTicket_Text_OldSeaMapTooFar:
	.string "¿Qué pasa, jovencito?\p"
	.string "¿Tú eres quien tiene el\n"
	.string "viejo mapa roto?\p"
	.string "Déjame verlo.\n"
	.string "… … … … … …\p"
	.string "Vaya, esto queda muy lejos.\n"
	.string "Me temo que no puedo ayudarte…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: ¡Espera un segundo!\p"
	.string "¿Cómo voy a rechazar a alguien\n"
	.string "a quien le debo tanto?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, lo siento mucho.\p"
	.string "Viniste a buscar mi ayuda\n"
	.string "y casi te rechazamos.\p"
	.string "Déjame arreglar las cosas.\p"
	.string "¡Zarparemos ahora mismo!\p"
	.string "¡Busquemos la isla de este\n"
	.string "VIEJO MAPA MARINO!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "¿Tú trajiste ese ticket\n"
	.string "extraño?\p"
	.string "A donde vas es una isla\n"
	.string "que está muy, muy lejos.\p"
	.string "Nadie sabe qué hay allí…\p"
	.string "¡Solo pensarlo me emociona\n"
	.string "como marino!\p"
	.string "¡Sube a bordo, jovencito!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "¿Quieres volver a CIUDAD OLIVO?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Qué isla tan rara, ¿eh?\n"
	.string "¿Quieres volver a CIUDAD OLIVO?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "¿Tú trajiste esos tickets\n"
	.string "extraños?\p"
	.string "… … …Hm.\p"
	.string "Estos tickets te llevan a islas\n"
	.string "que están muy, muy lejos.\p"
	.string "Nadie sabe qué hay allí,\n"
	.string "ni qué podría pasar.\p"
	.string "¡Solo pensarlo me emociona\n"
	.string "como marino!\p"
	.string "¡Sube a bordo, jovencito!\n"
	.string "¿A dónde navegamos primero?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "¿Escuchaste eso?\n"
	.string "Ese gruñido bajo que viene de ahí.\p"
	.string "¿Estás seguro de que es seguro?\n"
	.string "¿Crees que deberíamos irnos?$"

FarawayIsland_Entrance_Text_Sign:
	.string "La letra se borra, como si fuera\n"
	.string "de hace mucho tiempo…\p"
	.string "“…ber, día 6\n"
	.string "Si algún humano…viene aquí…\l"
	.string "otra vez…que sea alguien bueno…\l"
	.string "…con esa esperanza, me voy…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
