EventTicket_Text_ShowOldSeaMap:
	.string "El ferry a PORTALON es…\p"
	.string "¿Perdón?\n"
	.string "¿Podemos ir a este lugar del mapa?\p"
	.string "Conozco a alguien que te ayudará.\n"
	.string "Espera, por favor.$"

EventTicket_Text_ThatPass:
	.string "El ferry a PORTALON es…\p"
	.string "¿Oh?\n"
	.string "Ese PASE…$"

EventTicket_Text_ShowEonTicket:
	.string "¡Hola! ¿Tú trajiste ese PASE\n"
	.string "tan extraño?\p"
	.string "Buscas llegar a una pequeña isla\n"
	.string "muy al sur.\p"
	.string "No sabemos qué encontraremos\n"
	.string "al llegar allá, sí.\l"
	.string "¡Me da escalofríos!\p"
	.string "¡Todos a bordo!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Hola, no hay nada que ver ni hacer\n"
	.string "en esta isla olvidada.\p"
	.string "¿Volvemos a CIUDAD OLIVO?$"

EventTicket_Text_SailHome:
	.string "¡Muy bien, entonces!\n"
	.string "¡Naveguemos a casa!$"

EventTicket_Text_AsYouLike:
	.string "¡Está bien, como quieras!$"

SouthernIsland_Interior_Text_Sign:
	.string "“Los sueños son otra realidad.\n"
	.string "Nunca lo olvides…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Quienes pierden sus recuerdos\n"
	.string "buscan grabarlos en su corazón…”$"
