@ Battle Tower
gText_AnabelWonSilver::
	.string "Es muy decepcionante…$"

gText_AnabelDefeatSilver::
	.string "Está bien, entiendo…$"

gText_AnabelWonGold::
	.string "Lo siento muchísimo…$"

gText_AnabelDefeatGold::
	.string "Gracias…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "¡Jajaja! ¿No te da vergüenza?\n"
	.string "¡Todos están mirando!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "Pero qué…$"

gText_TuckerWonGold::
	.string "¡Mi título de DOME ACE no es adorno!$"

gText_TuckerDefeatGold::
	.string "¡Jajaja!\n"
	.string "¡Eres inspirador!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "¡Buen trabajo!\n"
	.string "Fue una buena lección, ¿eh?$"

gText_NolandDefeatSilver::
	.string "¡Bien hecho!\n"
	.string "¡Sabes lo que haces!$"

gText_NolandWonGold::
	.string "¡Oye, oye, oye!\n"
	.string "¿Ya terminaste?$"

gText_NolandDefeatGold::
	.string "¿Qué pasó aquí?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Humph…$"

gText_LucyDefeatSilver::
	.string "Urk…$"

gText_LucyWonGold::
	.string "¡Ja!$"

gText_LucyDefeatGold::
	.string "¡Rayos!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "¡Oh, vamos!\n"
	.string "¡Tienes que esforzarte más!$"

gText_GretaDefeatSilver::
	.string "¡No puede ser!\n"
	.string "¡Buen trabajo!$"

gText_GretaWonGold::
	.string "¡Jeje!\n"
	.string "¿Qué esperabas?$"

gText_GretaDefeatGold::
	.string "¿Eh?\n"
	.string "¡¿Hablas en serio?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Tus POKéMON son débiles porque\n"
	.string "¡eres un ENTRENADOR débil!$"

gText_SpenserDefeatSilver::
	.string "Ah...\n"
	.string "Esto ya es otro nivel...$"

gText_SpenserWonGold::
	.string "¡Gwahahaha!\n"
	.string "¡Hermanos, no hay nada que temer!$"

gText_SpenserDefeatGold::
	.string "¡Gwah!\n"
	.string "¡Jajajaja!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "¡Oye! ¡¿Qué te pasa!\n"
	.string "¡Esfuérzate más! ¡Levántate!$"

gText_BrandonDefeatSilver::
	.string "¡Eso es! ¡Lo hiciste genial!\n"
	.string "¡Te esforzaste mucho por esto!$"

gText_BrandonWonGold::
	.string "¡Oye! ¡No te rindas ahora!\n"
	.string "¡Levántate! ¡Confía en ti mismo!$"

gText_BrandonDefeatGold::
	.string "¡Eso es! ¡Lo lograste!\n"
	.string "¡Seguiste luchando por esto!$"
