LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Es el RINCÓN DE LOTERÍA POKéMON.\p"
	.string "Si el número del BOLETO LOTO coincide\n"
	.string "con el ID de alguno de tus POKéMON,\l"
	.string "recibirás un regalo fabuloso.\p"
	.string "¿Quieres sacar un BOLETO LOTO\n"
	.string "POKéMON?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Vuelve mañana, por favor.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Vuelve a visitarnos pronto.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Elige un BOLETO LOTO.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "El número del BOLETO LOTO es {STR_VAR_1}.\p"
	.string "Revisaré si este número coincide\n"
	.string "con el ID de alguno de tus\l"
	.string "POKéMON. Por favor, espera.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "¡Felicidades!\p"
	.string "El ID de tu equipo\n"
	.string "{STR_VAR_1} coincide con el\l"
	.string "número del LOTO TICKET!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "¡Felicidades!\p"
	.string "El ID de tu PC\n"
	.string "{STR_VAR_1} coincide con el\l"
	.string "número del LOTO TICKET!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Lo siento.\n"
	.string "Ningún número coincidió.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "¡Dos dígitos coinciden! Ganas el\n"
	.string "tercer premio!\l"
	.string "¡Ganaste {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "¡Tres dígitos coinciden! Ganas el\n"
	.string "segundo premio!\l"
	.string "¡Ganaste {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "¡Cuatro dígitos coinciden! Ganas el\n"
	.string "primer premio!\l"
	.string "¡Ganaste {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "¡Cielos, los cinco dígitos\n"
	.string "coinciden!\p"
	.string "¡Ganaste el premio mayor!\n"
	.string "¡Ganaste {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "¿Oh?\n"
	.string "Parece que no tienes espacio.\p"
	.string "Haz espacio en tu MOCHILA y\n"
	.string "avísame.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "¿{PLAYER}?\n"
	.string "Sí, te estaba esperando.\p"
	.string "Este es el premio que guardamos\n"
	.string "para ti.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Por favor, vuelve a visitarnos.$"
