MatchCall_WildBattleText1::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Vi a este {STR_VAR_2} hace poco\n"
	.string "pero no pude atraparlo.\p"
	.string "¡Estuve tan cerca!\n"
	.string "Bueno, ¡nos vemos!$"

MatchCall_WildBattleText2::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Intenté atrapar un lindo {STR_VAR_2}\n"
	.string "hace un ratito.\p"
	.string "Pero se escapó.\n"
	.string "¡Me decepcioné mucho!\p"
	.string "¡Vale, adiós!$"

MatchCall_WildBattleText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Intenté atrapar a este\n"
	.string "{STR_VAR_2}, pero huyó.\p"
	.string "¡Estuve muy cerca!\p"
	.string "Me arruinó el día...\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_WildBattleText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "¿Conoces al POKéMON {STR_VAR_2}?\n"
	.string "Casi logro atrapar uno.\p"
	.string "Fue hace poco tiempo.\n"
	.string "Creí que lo tenía, pero escapó.\p"
	.string "Si lo veo otra vez, lo atraparé\n"
	.string "sin duda.\p"
	.string "Vale, ¡nos vemos luego!$"

MatchCall_WildBattleText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Atrapaste POKéMON últimamente?\p"
	.string "Hace poco casi atrapo uno,\n"
	.string "pero se soltó.\p"
	.string "¡Bueno, cuídate!$"

MatchCall_WildBattleText6::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\l"
	.string "¿Atrapaste POKéMON últimamente?\p"
	.string "Casi atrapo uno el otro día.\n"
	.string "Pero de algún modo escapó.\p"
	.string "Cuídate mucho.$"

MatchCall_WildBattleText7::
	.string "...¿Eh, {PLAYER}{KUN}?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¡Oh, espera! ¡Espera!\n"
	.string "Puedo atrapar a este {STR_VAR_2}...\p"
	.string "¡Aaarrgh! ¡Se escapó!\n"
	.string "¡Estuve tan cerca!$"

MatchCall_WildBattleText8::
	.string "Hola, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\p"
	.string "¿Has tenido éxito atrapando\n"
	.string "POKéMON últimamente?\p"
	.string "Estuve muy cerca hace poco,\n"
	.string "pero mi objetivo escapó.\p"
	.string "¡Debo esforzarme más!\n"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Y bien? ¿Estás reuniendo más\n"
	.string "POKéMON?\p"
	.string "¡A mí me va fatal!\n"
	.string "¡Todos se me escapan!\p"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Mira, estuve a punto de\n"
	.string "atrapar a este {STR_VAR_2}…\p"
	.string "Pero se me escapó…\p"
	.string "Debo esforzarme más.\n"
	.string "Nos vemos.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo te va todo?\p"
	.string "Intenté atrapar un {STR_VAR_2}\n"
	.string "salvaje, pero logró huir.\p"
	.string "Me siento derrotado…$"

MatchCall_WildBattleText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Sigues atrapando POKéMON?\p"
	.string "He intentado atraparlos\n"
	.string "yo mismo, pero no es fácil.\p"
	.string "¡El mundo POKéMON es complejo!$"

MatchCall_WildBattleText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "¿Has atrapado POKéMON?\p"
	.string "He intentado atraparlos\n"
	.string "yo mismo, pero sin éxito.\p"
	.string "¡El mundo POKéMON es complejo!$"

MatchCall_WildBattleText14::
	.string "¡Hola, {PLAYER}{KUN}! ¿Cómo estás?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Hace poco intenté atrapar un\n"
	.string "lindo {STR_VAR_2}.\p"
	.string "¡Pero se escapó!\n"
	.string "¡Imagínate mi decepción!\p"
	.string "¡Adiós!$"

MatchCall_WildBattleText15::
	.string "¡Oye, {PLAYER}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "He pensado en intentar\n"
	.string "atrapar algunos POKéMON.\p"
	.string "Pero no encuentro ninguno.\n"
	.string "¡Es un verdadero misterio!\p"
	.string "¡Ya no sé qué hacer!\n"
	.string "¡Nos vemos!$"

MatchCall_NegativeBattleText1::
	.string "¡Hola! ¡{PLAYER}{KUN}, hola!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Intenté luchar contra otro\n"
	.string "ENTRENADOR, pero perdí.\p"
	.string "Fue muy decepcionante.\n"
	.string "Bueno, ¡nos vemos!$"

MatchCall_NegativeBattleText2::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Reté a alguien más después de\n"
	.string "nuestra batalla.\p"
	.string "Estuve cerca, pero terminé\n"
	.string "perdiendo. ¡Ni modo!$"

MatchCall_NegativeBattleText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Me acaban de barrer en batalla.\p"
	.string "¡Creo que debo entrenar más\n"
	.string "a mi equipo!$"

MatchCall_NegativeBattleText4::
	.string "Hola, {PLAYER}.\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "Ayer intenté otra batalla,\n"
	.string "pero no pude ganar.\p"
	.string "Mi equipo necesita más nivel.\n"
	.string "Bueno, ¡nos vemos!$"

MatchCall_NegativeBattleText5::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va?\p"
	.string "He seguido batallando,\n"
	.string "pero no he ganado mucho.\p"
	.string "No logro coordinarme.\n"
	.string "¡Cuídate mucho!$"

MatchCall_NegativeBattleText6::
	.string "Hola, {PLAYER}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va?\p"
	.string "He luchado duro últimamente,\n"
	.string "pero con poco éxito.\p"
	.string "No logro entrar en ritmo.\n"
	.string "Cuídate.$"

MatchCall_NegativeBattleText7::
	.string "Aquí {STR_VAR_1}.\n"
	.string "¿Cómo va todo?\p"
	.string "Ayer perdí una batalla\n"
	.string "y no dejo de pensar en eso.\p"
	.string "Debo idear un plan...\n"
	.string "Nos vemos.$"

MatchCall_NegativeBattleText8::
	.string "Hola, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\p"
	.string "¿Cómo están tus POKéMON?\n"
	.string "Perdí un combate el otro día.\p"
	.string "¡Debo esforzarme más!\n"
	.string "¡Hasta luego!$"

MatchCall_NegativeBattleText9::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Escucha, tienes que oír\n"
	.string "esto!\p"
	.string "Tuve una batalla de POKéMON,\n"
	.string "pero perdí al último segundo.\p"
	.string "¡Ah, qué rabia me da!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, hola...\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Hace poco estuve en una batalla.\n"
	.string "Pero perdí.\p"
	.string "Debo entrenar más a mis POKéMON.\n"
	.string "¡Nos vemos!$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo están tus POKéMON?\p"
	.string "Acabo de perder otra batalla.\p"
	.string "¡Bueno, nos vemos!$"

MatchCall_NegativeBattleText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Sigues luchando con ganas?\p"
	.string "Yo perdí hace poco, así que he\n"
	.string "entrenado a todo mi equipo.\p"
	.string "Volvamos a vernos.$"

MatchCall_NegativeBattleText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Espero que estés muy bien.\p"
	.string "Estuve en una batalla hace\n"
	.string "muy poco tiempo.\p"
	.string "{PLAYER}{KUN}, sé activo como yo.\n"
	.string "¡Hasta luego!$"

MatchCall_NegativeBattleText14::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Todo va bien?\p"
	.string "Deberías volver a casa de vez en\n"
	.string "cuando.\p"
	.string "¡Adiós!$"

MatchCall_PositiveBattleText1::
	.string "¡Hola! ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Luché contra un ENTRENADOR antes.\n"
	.string "¡Gané! ¡Gané!\p"
	.string "Mi {STR_VAR_2} se esforzó mucho\n"
	.string "por mí. ¡Es genial!$"

MatchCall_PositiveBattleText2::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Tuve una batalla ayer y\n"
	.string "¡gané! ¡Es fantástico!$"

MatchCall_PositiveBattleText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "¡Soy yo, {STR_VAR_1}!\l"
	.string "¿Cómo van tus batallas?\p"
	.string "Yo luché el otro día y mi\n"
	.string "{STR_VAR_2} fue increíble.\p"
	.string "La próxima vez que luchemos,\n"
	.string "{PLAYER}, ¡yo no perderé!$"

MatchCall_PositiveBattleText4::
	.string "Hola, {PLAYER}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Tuve un combate hace poco.\n"
	.string "Gané, pero estuvo reñido.\p"
	.string "Mi {STR_VAR_2} estuvo\n"
	.string "muy inspirado.$"

MatchCall_PositiveBattleText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va todo?\n"
	.string "¿Has luchado mucho?\p"
	.string "¡Acabo de ganar hace poco!\n"
	.string "¡Mi {STR_VAR_2} fue brillante!\p"
	.string "Ya verás. ¡Te ganaré la\n"
	.string "próxima vez! ¡Cuídate!$"

MatchCall_PositiveBattleText6::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te está yendo?\p"
	.string "Llevo una racha increíble.\n"
	.string "De hecho, acabo de ganar.\p"
	.string "En nuestro próximo combate,\n"
	.string "¡seguro que no perderé!$"

MatchCall_PositiveBattleText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¡Mi {STR_VAR_2} es una fuerza!\n"
	.string "¡Me dio otra victoria ahora!\p"
	.string "No puedo esperar a tener la\n"
	.string "revancha contigo.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\p"
	.string "Espero que estés bien.\n"
	.string "Quería decirte que acabo de ganar.\p"
	.string "Mi {STR_VAR_2} se esforzó\n"
	.string "mucho para lograrlo.\p"
	.string "¡Nos vemos luego!$"

MatchCall_PositiveBattleText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Cómo van tus POKéMON?\n"
	.string "¡Los míos acaban de ganar!\p"
	.string "¡Mi {STR_VAR_2} estuvo\n"
	.string "espectacular, debo decir!\p"
	.string "¡Ojalá te lo hubiera mostrado!\n"
	.string "¡Nos vemos!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, hola...\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te ha tratado la vida?\p"
	.string "Mis POKéMON parecen estar\n"
	.string "llenos de energía.\p"
	.string "Acabo de ganar un combate.\n"
	.string "Nos vemos por ahí.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Has tenido combates últimamente?\n"
	.string "¡Hoy gané otro más!\p"
	.string "¡Estoy imparable! ¡Jajaja!\n"
	.string "Bueno, ¡nos vemos!$"

MatchCall_PositiveBattleText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Espero que estés bien?\n"
	.string "¡Sigo lleno de vida!\p"
	.string "Justo ahora gané otro combate.\n"
	.string "¡No me rendiré ante ustedes,\l"
	.string "jóvenes, todavía!$"

MatchCall_PositiveBattleText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Espero que hayas estado bien.\n"
	.string "¡Sigo con mucha energía!\p"
	.string "Acabo de ganar otra batalla.\n"
	.string "¡No perderé contra los jóvenes\l"
	.string "todavía!\p"
	.string "¡Nos vemos!$"

MatchCall_PositiveBattleText14::
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Tuve una batalla hace poco y mi\n"
	.string "{STR_VAR_2} estuvo excepcional!\p"
	.string "Ojalá lo hubieras visto,\n"
	.string "{PLAYER}{KUN}. ¡Adiós!$"

MatchCall_SameRouteBattleRequestText1::
	.string "¡Hola! {PLAYER}, ¡hola!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Eh? Espera, ¿estás cerca\n"
	.string "de {STR_VAR_2}?\p"
	.string "¡Vaya, entonces debemos luchar!\n"
	.string "¡Te esperaré! ¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText2::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Oh? ¿De casualidad estás por\n"
	.string "{STR_VAR_2} ahora mismo?\p"
	.string "¿Quieres luchar ahora?\n"
	.string "¡Te esperaré! ¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Oh, oye, ¿estás cerca de\n"
	.string "{STR_VAR_2} ahora mismo?\p"
	.string "¿Qué tal si luchamos\n"
	.string "ahora mismo?\p"
	.string "¡No volveré a perder!\n"
	.string "¡Te esperaré! ¡Hasta pronto!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Oye, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "¿Por dónde andas ahora?\n"
	.string "¿Eh? ¿En {STR_VAR_2}?\p"
	.string "¿Quieres luchar ahora?\n"
	.string "Te esperaré. ¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "¿Dónde estás ahora?\n"
	.string "¿En {STR_VAR_2}?\p"
	.string "Bueno, ¿qué tal una rápida\n"
	.string "revancha ahora mismo?\p"
	.string "Estaré atento a tu llegada.\n"
	.string "¡Nos vemos pronto!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo están tus POKéMON?\p"
	.string "¿Ah, sí? ¿Estás por\n"
	.string "{STR_VAR_2}?\p"
	.string "Bueno, entonces es mejor que\n"
	.string "tengamos una revancha.\p"
	.string "Puedo esperar, claro.\n"
	.string "¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Este, ¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}…\p"
	.string "Oh, ¿estás por casualidad\n"
	.string "en {STR_VAR_2}?\p"
	.string "Entonces, luchemos.\n"
	.string "Me refiero, ahora mismo.\p"
	.string "Te mostraré mis POKéMON.\n"
	.string "Te esperaré.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\p"
	.string "Espero que estés muy bien.\n"
	.string "Oh, estás cerca de {STR_VAR_2}.\p"
	.string "¿Te gustaría luchar\n"
	.string "conmigo entonces?\p"
	.string "Te esperaré.\n"
	.string "¡Nos vemos pronto!$"

MatchCall_SameRouteBattleRequestText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Cómo te va?\n"
	.string "¿Oh, estás cerca de {STR_VAR_2}?\p"
	.string "Bueno, ¿no crees que\n"
	.string "deberíamos luchar?\p"
	.string "¡No me hagas esperar mucho!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo va todo contigo?\n"
	.string "Oh, estás cerca de {STR_VAR_2}.\p"
	.string "Deberíamos luchar ahora mismo.\p"
	.string "Estoy listo y esperando.\n"
	.string "¡Date prisa!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Ah, ¿así que ahora estás en\n"
	.string "{STR_VAR_2}?\p"
	.string "Bueno, entonces tenemos que\n"
	.string "luchar, ¿no crees?\p"
	.string "¡Te esperaré por aquí!\n"
	.string "¡Nos vemos pronto!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Por dónde andarás ahora?\p"
	.string "{STR_VAR_2}?\n"
	.string "¡Eso está muy cerca!\p"
	.string "¿Qué dices si luchamos\n"
	.string "ahora?\p"
	.string "Puedo esperar.\n"
	.string "¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Espero que hayas estado bien.\n"
	.string "¿Oh, estás cerca de {STR_VAR_2}?\p"
	.string "Ya que no está muy lejos,\n"
	.string "ven a luchar conmigo.\p"
	.string "Te esperaré.\n"
	.string "Adiós por ahora.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué? ¿...{STR_VAR_2}?\n"
	.string "Está muy cerca.\p"
	.string "¿No crees que deberíamos\n"
	.string "tener una batalla?\p"
	.string "¡Te estaré buscando!\n"
	.string "¡Adiós!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Quieres luchar conmigo?\p"
	.string "Te esperaré por\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Quieres luchar conmigo\n"
	.string "otra vez?\p"
	.string "Me hallarás por\n"
	.string "{STR_VAR_2}. ¡Te espero!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Mis POKéMON son mucho más\n"
	.string "fuertes que la última vez.\p"
	.string "Quiero ver su fuerza contra\n"
	.string "tus POKéMON, {PLAYER}.\p"
	.string "¡Así que luchemos!\p"
	.string "Te esperaré por\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\l"
	.string "¿Cómo te va todo?\p"
	.string "Mis POKéMON se han vuelto\n"
	.string "bastante fuertes.\p"
	.string "Oye, ¿te gustaría tener\n"
	.string "otra batalla conmigo?\p"
	.string "Veámonos por\n"
	.string "{STR_VAR_2}, ¿vale?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Mis POKéMON están creciendo\n"
	.string "muy bien.\p"
	.string "Me gustaría luchar\n"
	.string "contigo otra vez.\p"
	.string "Te buscaré por\n"
	.string "{STR_VAR_2}. ¡Nos vemos!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\l"
	.string "Espero que todo vaya bien.\p"
	.string "Quisiera luchar contigo\n"
	.string "otra vez. ¿Qué dices?\p"
	.string "Si quieres luchar,\n"
	.string "ven a {STR_VAR_2}.\p"
	.string "¡Nos vemos!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "...¿Eh, {PLAYER}{KUN}?\n"
	.string "Aquí {STR_VAR_1}...\l"
	.string "¿Y bien? ¿Crecen tus POKéMON?\p"
	.string "Los míos son más fuertes.\n"
	.string "Quiero demostrártelo.\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "Ven a verme para un combate.\p"
	.string "Nos vemos.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\p"
	.string "Espero que estés muy bien.\n"
	.string "Mis POKéMON están muy activos.\p"
	.string "Si pasas por aquí, por favor\n"
	.string "dame una revancha.\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "¡Hasta entonces, adiós!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "¿Cómo están tus POKéMON?\p"
	.string "Mis POKéMON siguen mejorando.\n"
	.string "Quiero mostrártelo, {PLAYER}{KUN}.\p"
	.string "Estoy por {STR_VAR_2} ahora,\n"
	.string "luchemos si estás cerca.\p"
	.string "¡Espero verte pronto!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "Y bien, ¿cómo te va todo?\p"
	.string "Mis POKéMON se han vuelto mucho\n"
	.string "más fuertes que antes.\p"
	.string "Me encantaría otra batalla,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "Ven a verme si estás cerca.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Por dónde andarás ahora?\p"
	.string "Mis POKéMON están llenos de vida.\n"
	.string "Parece que tienen ganas de ver\l"
	.string "a tus POKéMON, {PLAYER}{KUN}.\p"
	.string "Estoy por {STR_VAR_2} ahora.\n"
	.string "Espero que nos busques.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Mis POKéMON se han vuelto\n"
	.string "bastante robustos últimamente.\p"
	.string "Quiero verlos en una batalla\n"
	.string "contigo, {PLAYER}{KUN}.\p"
	.string "Estaremos por {STR_VAR_2}.\n"
	.string "¡Ven a vernos cuando quieras!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "¿Tus POKéMON están bien?\p"
	.string "Mis POKéMON están tan sanos\n"
	.string "que no parecen poder perder!\p"
	.string "Seguro me encantaría tener otra\n"
	.string "batalla contigo.\p"
	.string "Si estás cerca de {STR_VAR_2},\n"
	.string "ven a vernos.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "Espero que estés bien.\p"
	.string "¡Oh, sí! Mis POKéMON son\n"
	.string "mucho más fuertes que antes.\p"
	.string "¿No crees que deberíamos\n"
	.string "luchar, {PLAYER}{KUN}?\p"
	.string "Te esperaremos por\n"
	.string "{STR_VAR_2}.\p"
	.string "Ven cuando quieras, ¿vale?$"

MatchCall_PersonalizedText1::
	.string "Soy yo, el amante de las montañas\n"
	.string "{STR_VAR_1}!\p"
	.string "Bueno, desde que nos vimos, ¿has\n"
	.string "aprendido a amar las montañas?\p"
	.string "Casi nunca te veo por aquí...\p"
	.string "La próxima vez, nos veremos por\n"
	.string "{STR_VAR_2}$."

MatchCall_PersonalizedText2::
	.string "Soy {STR_VAR_1}.\n"
	.string "Hola.\p"
	.string "Le hablaba a un nuevo ENTRENADOR\n"
	.string "sobre ti.\p"
	.string "Le dije que eres un ENTRENADOR\n"
	.string "que cuida mucho a sus POKéMON.\p"
	.string "Espero que seas un ENTRENADOR\n"
	.string "que todos admiren.\p"
	.string "¡Espero que nos veamos pronto!$"

MatchCall_PersonalizedText3::
	.string "¡Hola! Soy {STR_VAR_1}.\p"
	.string "Amo donde estoy ahora.\n"
	.string "¡Huele muy dulce aquí!\p"
	.string "Creo que alguien plantó BAYAS\n"
	.string "y ya han florecido.\p"
	.string "¡Nos vemos en otro momento!$"

MatchCall_PersonalizedText4::
	.string "¡Hola! Treinta años explorando,\n"
	.string "{STR_VAR_1} a tu servicio!\p"
	.string "Parece que viajas con mucha\n"
	.string "energía por todas partes.\p"
	.string "¿Has descubierto nuevas ruinas?\n"
	.string "¡Cuéntame si es así!\p"
	.string "Ahora, si me disculpas,\n"
	.string "tengo ruinas que explorar.$"

MatchCall_PersonalizedText5::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Sabes qué hago hoy?\n"
	.string "¡Miro las olas desde la playa!\p"
	.string "Ay... Las olas brillan tanto.\n"
	.string "El mar es más lindo desde aquí.\l"
	.string "Tengo hambre, ¡adiós!$"

MatchCall_PersonalizedText6::
	.string "Ñam, ñam...\n"
	.string "Ah, hola, soy {STR_VAR_1}.\l"
	.string "Amo comer en la playa.\p"
	.string "Mis POKéMON y yo estamos\n"
	.string "genial. ¡Estamos llenos!\l"
	.string "Iré a nadar. ¡Adiós!$"

MatchCall_PersonalizedText7::
	.string "Hola, soy {STR_VAR_1}...\p"
	.string "Me he cansado un poco de todo\n"
	.string "esto de ser un COOLTRAINER...\p"
	.string "Creen que soy un ENTRENADOR\n"
	.string "perfecto, y trato de cumplir\l"
	.string "con esa expectativa.\p"
	.string "Supongo que es parte de ser\n"
	.string "un COOLTRAINER.\p"
	.string "Tendré que esforzarme...\n"
	.string "y aguantarme con una sonrisa.\p"
	.string "Eres la única persona en quien\n"
	.string "puedo confiar así.\p"
	.string "Pero la próxima vez que nos veamos,\n"
	.string "¡no te preocupes, no lloraré!$"

MatchCall_PersonalizedText8::
	.string "¡Yahoo, soy {STR_VAR_1}!\n"
	.string "¿Cómo estás?\p"
	.string "He entrenado a mis POKéMON\n"
	.string "teniéndote como meta.\p"
	.string "No pienso perder cuando\n"
	.string "luchemos de nuevo.\p"
	.string "¿No es genial tener amigos\n"
	.string "ENTRENADORES? ¡Nos vemos!$"

MatchCall_PersonalizedText9::
	.string "Soy {STR_VAR_1}...\n"
	.string "Ahora mismo, detrás de ti...\l"
	.string "¿No había algo...?\p"
	.string "El poder de los POKéMON que\n"
	.string "duermen en el MT. PYRE...\p"
	.string "Me está hablando de ti...\p"
	.string "Deberías irte rápido y\n"
	.string "no mirar atrás ni una vez...\p"
	.string "Jeje...\n"
	.string "Adiós...$"

MatchCall_PersonalizedText10::
	.string "Soy {STR_VAR_1}.\n"
	.string "¿Cómo estás?\p"
	.string "¿No es práctico que podamos\n"
	.string "charlar así a la distancia?\p"
	.string "Antes, si quería hablar con\n"
	.string "alguien, mi padre tenía que\l"
	.string "llevarme…\p"
	.string "Debo irme ya.\n"
	.string "Me alegra que hayamos hablado.$"

MatchCall_PersonalizedText11::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¿Escucharás esto?\p"
	.string "Me gusta mucho la SAFARI ZONE,\n"
	.string "¡pero siempre me pierdo!\p"
	.string "¡Tanta hierba alta!\n"
	.string "¡Y es demasiado extensa!\p"
	.string "¡Me siento mejor después de\n"
	.string "desahogarme!\p"
	.string "¡Voy otra vez a la SAFARI ZONE!\n"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText12::
	.string "Hola, aquí {STR_VAR_1}.\n"
	.string "Sí, es cierto, soy rico, sí.\p"
	.string "Debo decirte que mi riqueza ha\n"
	.string "crecido desde que nos vimos.\p"
	.string "Además, mis POKéMON también\n"
	.string "se han vuelto más fuertes.\p"
	.string "¡Siento que este mundo existe\n"
	.string "solo para mí!\p"
	.string "¡Oh, no digas nada!\n"
	.string "¡Todos saben que es verdad!\p"
	.string "Discúlpame, tengo una cena\n"
	.string "formal a la que asistir.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "Soy yo, {STR_VAR_1}…\p"
	.string "¿Adivinas qué estoy viendo?\n"
	.string "Dos {STR_VAR_2} en una batalla.\p"
	.string "Quizá intente capturar al ganador…\n"
	.string "Ufufufufufu…\p"
	.string "Estoy algo ocupado ahora.\n"
	.string "Tengo que irme.$"

MatchCall_PersonalizedText14::
	.string "¡Oh, es {STR_VAR_1}!\p"
	.string "Justo pensaba que ya me aburro\n"
	.string "del BARCO ABANDONADO.\p"
	.string "Pero ya que estoy aquí,\n"
	.string "y quiero ganarte una vez,\l"
	.string "me quedaré un rato más.\p"
	.string "Si tienes ganas, ¿por qué no\n"
	.string "vienes a verme?\p"
	.string "Creo que hoy será el día en que\n"
	.string "finalmente retaré al vecino\l"
	.string "a un combate.\p"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText15::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡El hombre del mar!\p"
	.string "¿Sabes qué pienso?\p"
	.string "¡Los TRAINERS del mar son\n"
	.string "los más fuertes de todos!\p"
	.string "Deberías aprender de mí y entrenar\n"
	.string "en el mar…\p"
	.string "¡Uy, sube una ola gigante!\p"
	.string "¡Es una gran oportunidad!\n"
	.string "¡Lo siento, pero debo irme!$"

MatchCall_PersonalizedText16::
	.string "¡Soy {STR_VAR_1}! He estado\n"
	.string "enseñando karate a mis POKéMON.\p"
	.string "¡Pero ahora son mejores que yo!\n"
	.string "¡No he hecho más que perder!\p"
	.string "Aunque pierda contra POKéMON,\n"
	.string "¡no perderé contra otro\l"
	.string "TRAINER, señor!\p"
	.string "¡Tenemos que luchar otra vez!\n"
	.string "¡Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "Soy yo, {STR_VAR_1}.\n"
	.string "¿Cómo van tus viajes?\p"
	.string "…Vaya, ¿en serio?\n"
	.string "¡Suena muy estimulante!\p"
	.string "Creo que podría escribir una canción\n"
	.string "sobre tus aventuras.\p"
	.string "…Oh, ya lo siento.\n"
	.string "Oigo los riffs en mi cabeza.\p"
	.string "Debo escribir bien esta melodía,\n"
	.string "¡así que vuelo! ¡Luego!$"

MatchCall_PersonalizedText18::
	.string "Soy {STR_VAR_1}…\n"
	.string "Escucha mi nueva canción.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "¿Por qué eres tan {STR_VAR_2}?\l"
	.string "¿Por qué no soy como tú, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} y {STR_VAR_1},\l"
	.string "{STR_VAR_1} y {STR_VAR_2}…\p"
	.string "Repite coro, desvanece…$"

MatchCall_PersonalizedText19::
	.string "Soy {STR_VAR_1}, ya sabes,\n"
	.string "¡el experto en campamentos!\p"
	.string "Cuando luchamos, no pude evitar\n"
	.string "perder contra ti.\p"
	.string "Después de todo, mi especialidad\n"
	.string "es acampar.\p"
	.string "Gane o pierda, me gusta luchar\n"
	.string "cuando estoy acampando.\p"
	.string "Lucha con nosotros otra vez, ¿sí?\n"
	.string "¡Ah, y vamos a acampar también!$"

MatchCall_PersonalizedText20::
	.string "¡Soy yo, {STR_VAR_1}!\p"
	.string "Para ser honesto, me gustaría\n"
	.string "escalar otras montañas.\p"
	.string "Pero no sé si habrá chicas\n"
	.string "como en el MT. CHIMNEY.\p"
	.string "Si sabes de otra montaña con\n"
	.string "chicas, ¡avísame!\p"
	.string "Ehehehe, ¡nos vemos!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Soy {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Eso es todo por hoy…$"

MatchCall_PersonalizedText22::
	.string "Soy {STR_VAR_1}. Hoy sentía que\n"
	.string "hablaría contigo.\p"
	.string "Mi deseo de vencerte crece\n"
	.string "día y noche.\p"
	.string "Tienes un rival así, ¿verdad?\n"
	.string "Desearía ser yo...\p"
	.string "Gracias por escucharme.\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText23::
	.string "Soy {STR_VAR_1}.\p"
	.string "Cuando hay un ENTRENADOR fuerte\n"
	.string "cerca, a veces puedo sentirlo\l"
	.string "de alguna forma.\p"
	.string "¿Pasaste por aquí, {PLAYER}{KUN}?\n"
	.string "Tal vez fuiste tú.\p"
	.string "Esperaré tu visita.\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText24::
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Suenas bien, {PLAYER}{KUN}.\p"
	.string "He viajado por todo el mundo,\n"
	.string "pero debo decir que me gusta\l"
	.string "mucho esta región.\p"
	.string "Pienso quedarme aquí un tiempo.\n"
	.string "¿Quizás podamos vernos otra vez?\p"
	.string "No he olvidado tus técnicas\n"
	.string "deslumbrantes.\p"
	.string "Espero una revancha.$"

MatchCall_PersonalizedText25::
	.string "Buaaa… Soy… {STR_VAR_1}…\n"
	.string "…Snif…\p"
	.string "ROXANNE me regañó en clase\n"
	.string "hoy.\p"
	.string "Pero no es que me caiga mal.\p"
	.string "ROXANNE me dice exactamente en\n"
	.string "qué fallé para que aprenda.\p"
	.string "¡Seguro iré a la ESCUELA de\n"
	.string "TRAINERS mañana!\p"
	.string "¡Nos vemos luego!$"

MatchCall_PersonalizedText26::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "ROXANNE me dejó luchar con ella\n"
	.string "ayer.\p"
	.string "Los resultados...\n"
	.string "Terribles, como ya imaginarás.\p"
	.string "¡Pero me encantó que ROXANNE\n"
	.string "me dejara retarla!\p"
	.string "¡No creerás cuánto\n"
	.string "más la admiro ahora!\p"
	.string "¡Me esforzaré y trabajaré duro!\n"
	.string "¡Mejor me voy!$"

MatchCall_PersonalizedText27::
	.string "¡Hola, soy ANNA! Hoy estoy con\n"
	.string "mi compañera MEG otra vez.\p"
	.string "Amo cuidar de MEG y de los\n"
	.string "POKéMON. ¡Son tan lindos!\p"
	.string "¡Desearía cuidarlos como si\n"
	.string "fueran mis hermanos!\p"
	.string "¡Ah, hola, MEG!\n"
	.string "¿Trajiste los bollos?\p"
	.string "¿Eh? ¡No, no te trato como\n"
	.string "mi esclava personal!\p"
	.string "¡Perdiste el combate, así que\n"
	.string "compra el pan como castigo!\p"
	.string "¡No te trataría así, MEG!\n"
	.string "¡Eres muy especial para mí!\p"
	.string "Tengo que irme ya.\n"
	.string "¡Es hora de la merienda!$"

MatchCall_PersonalizedText28::
	.string "¡Amo a los POKéMON!\n"
	.string "¡Soy {STR_VAR_1} del FAN CLUB!\p"
	.string "¡Tienes que oír esto!\n"
	.string "Mi dulce POKéMON...\p"
	.string "¡Snif! ¡Wahaha!\n"
	.string "¡No puedo decir más! ¡Es secreto!\l"
	.string "¡Es demasiado lindo para palabras!\p"
	.string "¡Mi dulce {STR_VAR_2} pide\n"
	.string "un {POKEBLOCK}!\p"
	.string "¡Es la imagen de la ternura!\p"
	.string "¡Lo siento, no puedo hablar ahora!\n"
	.string "¡Cuéntame la próxima vez!$"

MatchCall_PersonalizedText29::
	.string "¡Ohoho!\p"
	.string "¡Soy {STR_VAR_1}! ¡Quiero\n"
	.string "hablarte de mi querido POKéMON!\p"
	.string "Por favor, escucha esto.\n"
	.string "Es sobre mi querido {STR_VAR_2}.\p"
	.string "Cuando alguien lo levanta,\n"
	.string "¡salta directo a mis brazos!\p"
	.string "Oh... Oh... ¿Habrá algo\n"
	.string "más glorioso?\p"
	.string "¡Oh, se siente celestial!\p"
	.string "Me alegra compartir\n"
	.string "mi felicidad contigo.\p"
	.string "Bueno, debo irme.\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText30::
	.string "Soy... {STR_VAR_1}.\n"
	.string "La gente me llama EXPERTO.\p"
	.string "Pero hay algo que sé.\n"
	.string "No podría ser un EXPERTO solo\l"
	.string "por mi propio poder.\p"
	.string "Solo con POKéMON un\n"
	.string "ENTRENADOR puede ser EXPERTO.\p"
	.string "¡Humph! ¡Creo que he dicho\n"
	.string "algo profundo y sabio!\p"
	.string "¡Te dejo con buen ánimo!$"

MatchCall_PersonalizedText31::
	.string "Es {STR_VAR_1}.\n"
	.string "¡Me alegra hablar contigo!\p"
	.string "Me siento llena de vida y renovada\n"
	.string "en estas aguas termales.\p"
	.string "He luchado contra TRAINERS novatos\n"
	.string "desde que nos vimos, pero tú\l"
	.string "sigues siendo el mejor.\p"
	.string "¡Imagino que serás una EXPERTA\n"
	.string "cuando seas mayor! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "¡Sii! ¡Soy {STR_VAR_1}!\n"
	.string "¿Qué pasa?\p"
	.string "Tal vez me lo imagino, pero al\n"
	.string "ganar, mis shorts se sienten\l"
	.string "mejor. De material.\p"
	.string "¿A qué me refiero?\n"
	.string "Es difícil de explicar, pero...\l"
	.string "¿Cómo lo diría...\l"
	.string "¡Mis shorts se sienten más sedosos!\p"
	.string "Y al luchar contigo, {PLAYER}{KUN},\n"
	.string "mis shorts se sintieron ásperos.\p"
	.string "... ... ... ... ... ...\n"
	.string "¿De verdad te lo creíste?\l"
	.string "¡Ehehehe, eso es todo! ¡Adiós!$"

MatchCall_PersonalizedText33::
	.string "¡Ahoy!\n"
	.string "¡Aquí {STR_VAR_1}!\p"
	.string "Como siempre, ¡estoy pescando\n"
	.string "con total libertad!\p"
	.string "¿Habrá otros sitios para pescar\n"
	.string "además del mar y los ríos?\p"
	.string "¡Siento impulsos de pescar\n"
	.string "en cualquier lugar!\p"
	.string "¡Oh, rayos, maldición!\n"
	.string "¡Se enredó mi sedal!\p"
	.string "¡Tengo que irme!\n"
	.string "¡Búscame nuevos sitios de pesca!$"

MatchCall_PersonalizedText34::
	.string "¡Hola! Soy {STR_VAR_1}.\n"
	.string "¿Te lo tomas con calma?\p"
	.string "Desde niño, ya sabes,\n"
	.string "siempre he sido tranquilo, ¿eh?\p"
	.string "Nunca me gustó estresarme\n"
	.string "ni apresurar las cosas.\p"
	.string "Pero quién lo diría,\n"
	.string "¡ahora soy TRIATLETA!\p"
	.string "No sabes a dónde te llevará la\n"
	.string "vida, si me entiendes.\p"
	.string "Ahora eres ENTRENADOR, pero\n"
	.string "¿quién sabe qué pasará, eh?\p"
	.string "Imagínate como profesor,\n"
	.string "o tal vez artista. Genial, ¿no?\p"
	.string "Pero ve tranquilo. Sin prisas.\n"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText35::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "Estoy pedaleando ahora.\p"
	.string "Amo nadar y correr,\n"
	.string "¡pero el ciclismo es mi pasión!\p"
	.string "Siento que todo mi cuerpo es\n"
	.string "uno solo con el viento.\p"
	.string "¡Me emociona como si\n"
	.string "estuviera volando!\p"
	.string "¡Bien! ¡Hoy romperé el récord\n"
	.string "de la CICLOVÍA!\p"
	.string "¡Tú también deberías intentarlo!\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText36::
	.string "¡Hola, soy {STR_VAR_1}! Estoy\n"
	.string "en medio de un triatlón!\p"
	.string "Pero siempre tengo tiempo\n"
	.string "para charlar un rato!\p"
	.string "¡Entrenar con POKéMON se\n"
	.string "siente muy bien!\p"
	.string "Sin palabras, nos sincronizamos\n"
	.string "como si fuéramos un solo corazón.\p"
	.string "¡Es inspirador!\p"
	.string "Ah... Hablar mientras corro...\n"
	.string "Me estoy agotando...\l"
	.string "Ah... Me... tengo... que... ir...$"

MatchCall_PersonalizedText37::
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Para mejorar la resistencia,\l"
	.string "¡entrena en las alturas!\p"
	.string "Prueba a correr en una montaña.\n"
	.string "¡Te quedarás sin aire pronto!\p"
	.string "¡Yo también me estoy asfixiando!\n"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText38::
	.string "Oh, soy {STR_VAR_1}, hola.\p"
	.string "He nadado mucho pero sigo\n"
	.string "sin llegar a EVERGRANDE.\p"
	.string "Quizás solo doy vueltas.\p"
	.string "No, no, no puede ser.\n"
	.string "Jajajaja.\l"
	.string "¡Cuídate!$"

MatchCall_PersonalizedText39::
	.string "Hola, soy {STR_VAR_1}...\n"
	.string "¡Uy!\p"
	.string "¡Splash!\p"
	.string "Blub-blub-blub-blub...\p"
	.string "¡Sploosh!\p"
	.string "¡Fiu-fiu! ¡Fiu-fiu!\p"
	.string "¡Hola! ¡Perdón por eso!\n"
	.string "Me puse aceite bronceador.\p"
	.string "¡Y mi POKéNAV se me resbaló\n"
	.string "de la mano al agua!\p"
	.string "Pero el POKéNAV de DEVON es\n"
	.string "resistente. ¡Sobrevivió!\p"
	.string "En fin, estoy tomando el sol,\n"
	.string "hablemos en otro momento.$"

MatchCall_PersonalizedText40::
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "De las tres pruebas del triatlón,\n"
	.string "la que más me gusta es nadar.\p"
	.string "Pero si estoy mucho en el mar,\n"
	.string "¿no se me arrugará la piel?\p"
	.string "¡El triatlón es una prueba\n"
	.string "muy dura de resistencia! ¡Adiós!$"

MatchCall_PersonalizedText41::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "¿Cómo están tus POKéMON?\p"
	.string "Mis POKéMON tipo DRAGÓN\n"
	.string "están en plena forma. Adiós.$"

MatchCall_PersonalizedText42::
	.string "Aquí {STR_VAR_1}.\p"
	.string "Mi {STR_VAR_2} es más fuerte\n"
	.string "que la última vez.\p"
	.string "No volveré a perder contra ti.\n"
	.string "¡Espera a la próxima vez!\p"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText43::
	.string "Aquí {STR_VAR_1}.\p"
	.string "Sigo estudiando el arte\n"
	.string "del ocultamiento.\p"
	.string "Pero tuve demasiado éxito.\n"
	.string "Nadie ha podido encontrarme.\l"
	.string "Eso me hace sentir solo…\p"
	.string "¡Desaparezco como el humo!\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText44::
	.string "Soy {STR_VAR_1}.\n"
	.string "He entrenado desde que nos vimos.\p"
	.string "Mi {STR_VAR_2} se está volviendo\n"
	.string "muy fuerte.\p"
	.string "Entrenar en la playa funciona,\n"
	.string "tal como pensé. ¡Adiós!$"

MatchCall_PersonalizedText45::
	.string "¿Cómo estás?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cuándo dejará de caer esta\n"
	.string "ceniza volcánica asquerosa?\p"
	.string "Si se acumula, cubrirá el\n"
	.string "diseño de mi sombrilla…\p"
	.string "¡Prometamos vernos otra vez!$"

MatchCall_PersonalizedText46::
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "¿Sabías que es más fácil flotar\n"
	.string "en el mar que en una piscina?\p"
	.string "Si te quedas quieto, tu cuerpo\n"
	.string "flotará solo.\p"
	.string "Pero si flotas mucho tiempo,\n"
	.string "cuidado con que la corriente\l"
	.string "te lleve muy lejos.\p"
	.string "…¿Dónde estoy, por cierto?\n"
	.string "¡Mejor me voy!$"

MatchCall_PersonalizedText47::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "Ahora estoy en las montañas.\p"
	.string "Pero el suelo es muy irregular.\n"
	.string "No puedo armar mi tienda aquí…\p"
	.string "¡Oh, tuve una idea brillante!\p"
	.string "¡Quizás mis POKéMON puedan\n"
	.string "aplanar el suelo aquí!\p"
	.string "¡Voy a intentarlo!\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText48::
	.string "¡Hola, hola, soy {STR_VAR_1}!\p"
	.string "¡Crío POKéMON con LIV!\n"
	.string "¡Nos esforzamos mucho!\p"
	.string "Si nos esforzamos más, ¿seremos\n"
	.string "los número uno? ¡Adiós!$"

MatchCall_PersonalizedText49::
	.string "¡Aquí {STR_VAR_1}!\p"
	.string "Soy MARINERO, pero no estoy\n"
	.string "en un barco ahora.\p"
	.string "Me pregunto... ¿cómo llaman\n"
	.string "a un MARINERO en tierra?\p"
	.string "Eso pienso mientras miro\n"
	.string "hacia las olas.\p"
	.string "¡Está bien, para la próxima!$"

MatchCall_PersonalizedText50::
	.string "Soy {STR_VAR_1}.\n"
	.string "¿Y bien? ¿Atrapaste más POKéMON?\p"
	.string "Si atrapas un POKéMON nuevo,\n"
	.string "tienes que venir a mostrármelo.\p"
	.string "No insistiré, lo prometo.\n"
	.string "Estaré esperando. Nos vemos.$"

MatchCall_PersonalizedText51::
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Entrenas a tus POKéMON\n"
	.string "de la mejor manera?\p"
	.string "El aire es puro donde estoy.\n"
	.string "Es el lugar perfecto para\l"
	.string "criar POKéMON.\p"
	.string "Si quieres enfocarte en criar\n"
	.string "POKéMON, ven a\l"
	.string "{STR_VAR_2}. ¡Cuídate!$"

MatchCall_PersonalizedText52::
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "Le di un {POKEBLOCK} a mi {STR_VAR_2}.\n"
	.string "Pareció disfrutarlo mucho.\p"
	.string "Parece que los POKéMON tienen\n"
	.string "gustos con los {POKEBLOCK}.\p"
	.string "Me parece fascinante.\n"
	.string "Por favor, cuídate.$"

MatchCall_PersonalizedText53::
	.string "Aquí {STR_VAR_1}.\p"
	.string "Si cooperas con los POKéMON,\n"
	.string "estarás cómodo en la naturaleza.\p"
	.string "Todos deberían notar eso y\n"
	.string "cooperar más con los POKéMON.\p"
	.string "Eso sería lo ideal.\n"
	.string "De verdad lo creo.\p"
	.string "¡Creo que vas por buen camino!\n"
	.string "¡Hablamos luego!$"

MatchCall_PersonalizedText54::
	.string "Hola, soy {STR_VAR_1}. Ya sabes,\n"
	.string "¡el ENTRENADOR siempre listo!\p"
	.string "{PLAYER}{KUN}, ¿tienes suficientes objetos?\n"
	.string "¿Tus POKéMON están listos?\p"
	.string "Tener todo perfecto a tu alrededor\n"
	.string "todo el tiempo es el secreto para\l"
	.string "seguir adelante en el viaje.\p"
	.string "¡Iré a revisar mis suministros!\n"
	.string "¡Mantente alerta!$"

MatchCall_PersonalizedText55::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "{STR_VAR_2} es una vía muy\n"
	.string "transitada, así que me retan\l"
	.string "muchos ENTRENADORES cada día.\p"
	.string "¡Hoy gané cinco batallas y solo\n"
	.string "perdí tres!\p"
	.string "¿Cómo te fue a ti hoy?\n"
	.string "Cuéntamelo la próxima, ¿vale?$"

MatchCall_PersonalizedText56::
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Soy popular por tener muchos\n"
	.string "POKéMON tipo bicho, ¿verdad?\p"
	.string "Llevé varios de mis bichos\n"
	.string "favoritos a la escuela hoy.\p"
	.string "¡La chica que me gusta lloró!\n"
	.string "Ríete si quieres.\p"
	.string "Debo enseñarle qué hace a los\n"
	.string "POKéMON bicho tan atractivos.\p"
	.string "Buaaa...\n"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText57::
	.string "¡Jaj! ¡Jaj! ¡Jaj! ¡Jaj!\p"
	.string "¡Hola! ¡Soy {STR_VAR_1}! ¡Jaj!\p"
	.string "Intentar hablar...\n"
	.string "mientras subo...\l"
	.string "es ejercicio duro... ¡Jaj! ¡Jaj!\p"
	.string "¡Uff! ¡Ah!...\n"
	.string "Está más empinado ahora...\l"
	.string "Hablaremos... otra vez...\l"
	.string "¡Jaj! ¡Jaj! ¡Jaj!$"

MatchCall_PersonalizedText58::
	.string "¡Hola!\p"
	.string "¡Sigo buscando tesoros\n"
	.string "con KIRA!\p"
	.string "Tal vez no haya ningún tesoro\n"
	.string "por aquí...\p"
	.string "Pero lo importante es buscar\n"
	.string "junto a KIRA.\p"
	.string "¡Oh, hola, KIRA!\n"
	.string "¿Por qué estás enojada?\p"
	.string "¡No te ignoro, cariño!\n"
	.string "¡Eres mi única y especial!\p"
	.string "...{PLAYER}, me voy, ¡adiós!$"

MatchCall_PersonalizedText59::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Fui al GIMNASIO de DEWFORD\n"
	.string "para entrenar.\p"
	.string "BRAWLY, el LÍDER, parece\n"
	.string "estar más fuerte ahora.\p"
	.string "Algo sobre haberse curtido\n"
	.string "con las olas salvajes...\p"
	.string "Pero sigue siendo genial.\n"
	.string "¡Las chicas lo adoran!\l"
	.string "Francamente, me da envidia.\p"
	.string "Me pregunto... ¿será BRUNO\n"
	.string "igual que BRAWLY?\p"
	.string "Ya sabes, sudoroso, oloroso\n"
	.string "y que llame a la gente\l"
	.string "“gran ola”, cosas así.\p"
	.string "Pero bueno, estos celos no\n"
	.string "están bien, ¿verdad?\p"
	.string "Olvida que hablamos de esto,\n"
	.string "¿te parece? ¡Nos vemos!$"

MatchCall_PersonalizedText60::
	.string "Es un placer charlar con\n"
	.string "un joven ENTRENADOR como tú.\p"
	.string "Imagino que seguirás disfrutando\n"
	.string "de POKéMON sin importar la edad.\p"
	.string "¿No sería genial tener\n"
	.string "una pareja como la nuestra?\p"
	.string "Claro, {PLAYER}{KUN}, ya tienes\n"
	.string "la confianza y compañía\l"
	.string "de tus POKéMON ahora.\p"
	.string "¡Ya tienes madera para crear\n"
	.string "lazos largos y duraderos!\p"
	.string "¡Jajaja!\n"
	.string "¡Nunca te desanimes!$"

MatchCall_PersonalizedText61::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Acabamos de ganar una batalla!\p"
	.string "No ganamos seguido, pero fue\n"
	.string "contra un SWIMMER genial.\p"
	.string "¡Mi hermana estaba furiosa!\p"
	.string "¡Quería fingir que era débil\n"
	.string "para causar impresión!\p"
	.string "¡Siempre me regaña aunque\n"
	.string "ganemos o perdamos!\p"
	.string "{PLAYER}{KUN}, ¿puedes decirle\n"
	.string "algo la próxima vez?\p"
	.string "¡Vale, nos vemos!$"

MatchCall_PersonalizedText62::
	.string "Aquí {STR_VAR_1}, sí.\n"
	.string "Ayer salí navegando al mar.\p"
	.string "Esperaba hallar una nueva\n"
	.string "ruina para explorar.\p"
	.string "Pero las mareas me llevaron\n"
	.string "de vuelta al inicio.\p"
	.string "Sigo siendo débil luchando...\n"
	.string "Puedes burlarte de mí...\l"
	.string "Pero no me rendiré.\p"
	.string "¡Llegará el día en que halle\n"
	.string "una nueva ruina!\p"
	.string "¡Eso es todo lo que diré!\n"
	.string "¡Hasta la próxima!$"

MatchCall_PersonalizedText63::
	.string "¡Ahoy!\n"
	.string "¡Soy yo, {STR_VAR_1}!\l"
	.string "¡Estoy en la RUTA 108 ahora!\l"
	.string "¡O sea, donde siempre estoy!\p"
	.string "¡Hoy una SWIMMER hermosa\n"
	.string "nadó junto a mí!\p"
	.string "¡La asusté con un grito!\p"
	.string "¡Y me lanzó una mirada fea!\p"
	.string "¡Eso es todo de la RUTA 108!\n"
	.string "¡Transmitido por {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Estoy algo ocupado, pero\n"
	.string "quería decirte que hoy\l"
	.string "vencí a cinco ENTRENADORES.\p"
	.string "Si sigo así, probablemente\n"
	.string "te gane la próxima vez.\p"
	.string "Seremos buenos rivales,\n"
	.string "tú y yo. ¡Adiós por ahora!$"

MatchCall_BattleFrontierStreakText1::
	.string "¡Hola! Soy {STR_VAR_1}.\n"
	.string "¡Me enteré de las noticias!\p"
	.string "Dicen que estuviste excelente\n"
	.string "en el {STR_VAR_2}.\p"
	.string "¡Genial, {STR_VAR_3} victorias?\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡He oído hablar de ti!\p"
	.string "Dicen que ganaste {STR_VAR_3} batallas\n"
	.string "seguidas en {STR_VAR_2}.\p"
	.string "¡Es increíble! ¡Yo también\n"
	.string "debo esforzarme más! ¡Adiós!$"

MatchCall_BattleFrontierStreakText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¡Oí que arrasaste en\n"
	.string "el {STR_VAR_2}!\p"
	.string "Una racha de {STR_VAR_3} victorias...\n"
	.string "Es un gran récord, ¿no?\p"
	.string "¡Yo también debo mejorar!\n"
	.string "¡Nos vemos pronto!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}. ¿Qué tal?\p"
	.string "Corre el rumor de que lograste\n"
	.string "{STR_VAR_3} victorias seguidas\l"
	.string "en el {STR_VAR_2}.\p"
	.string "Yo también debo mejorar.\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Estuviste en el {STR_VAR_2}\n"
	.string "y ganaste {STR_VAR_3} batallas seguidas?\l"
	.string "¡Eso es asombroso!\p"
	.string "Debo entrenar más a mis POKéMON.\n"
	.string "¡Nos vemos pronto!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}. ¿Cómo estás?\p"
	.string "Oí que lograste la hazaña de\n"
	.string "{STR_VAR_3} victorias seguidas\l"
	.string "en el {STR_VAR_2}.\p"
	.string "Eso me inspira a centrarme en\n"
	.string "entrenar a mi equipo.$"

MatchCall_BattleFrontierStreakText7::
	.string "...Eh, ¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}...\p"
	.string "Ah, sí, estuviste en\n"
	.string "el {STR_VAR_2}, ¿verdad?\p"
	.string "Y ganaste {STR_VAR_3} batallas seguidas.\p"
	.string "¡Mira, un POKéMON raro!\n"
	.string "¡Tengo que irme!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "Espero que estés muy bien.\p"
	.string "Ah, claro que sí. Oí que ganaste\n"
	.string "{STR_VAR_3} combates seguidos\l"
	.string "en el {STR_VAR_2}.\p"
	.string "¡Es muy impresionante!\n"
	.string "¡Espero que sigas así!$"

MatchCall_BattleFrontierStreakText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Me enteré! ¡Tu racha de {STR_VAR_3}\n"
	.string "victorias en el {STR_VAR_2}!\p"
	.string "¡Eso es genial!\n"
	.string "¡Yo también debo esforzarme más!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Ganaste {STR_VAR_3} batallas seguidas\n"
	.string "en {STR_VAR_2}?\p"
	.string "Es un gran logro.\n"
	.string "Debo esforzarme más.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Oí que eres el terror de\n"
	.string "{STR_VAR_2}?\p"
	.string "¿Ganaste {STR_VAR_3} combates\n"
	.string "seguidos?\p"
	.string "Eres muy bueno.\n"
	.string "¿Cuántos ganaría yo?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Cómo has estado?\p"
	.string "Alguien me habló de ti.\n"
	.string "¿Que ganaste {STR_VAR_3} batallas\l"
	.string "seguidas en {STR_VAR_2}?\p"
	.string "Es una gran historia.\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que estés muy bien.\p"
	.string "Dicen que ganaste {STR_VAR_3} batallas\n"
	.string "seguidas en {STR_VAR_2}.\p"
	.string "¡Admiro tu energía!\n"
	.string "¡Adiós!$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¡He oído hablar de ti!\n"
	.string "¿No ganaste {STR_VAR_3} batallas\l"
	.string "seguidas en {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Adiós!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "¡Hola! Soy {STR_VAR_1}.\n"
	.string "¡Me enteré de la noticia!\p"
	.string "Dicen que te fue excelente en\n"
	.string "{STR_VAR_2}.\p"
	.string "¡Genial! ¿{STR_VAR_3} victorias?\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡He oído hablar de ti!\p"
	.string "Dicen que ganaste {STR_VAR_3} batallas\n"
	.string "seguidas en {STR_VAR_2}.\p"
	.string "¡Es especial! ¡Yo también\n"
	.string "debo esforzarme! ¡Adiós!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¡Oí que arrasaste en\n"
	.string "{STR_VAR_2}!\p"
	.string "Una racha de {STR_VAR_3} victorias…\n"
	.string "Es un gran récord, ¿no?\p"
	.string "¡Yo también debo mejorar!\n"
	.string "¡Hasta pronto!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}. ¿Qué tal?\p"
	.string "Corre el rumor de que lograste\n"
	.string "{STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "Yo también debo mejorar.\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Estuviste en el {STR_VAR_2}\n"
	.string "y ganaste {STR_VAR_3} batallas seguidas?\l"
	.string "¡Eso es increíble!\p"
	.string "¿Yo? Diría que voy progresando.\n"
	.string "¡Hasta pronto!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}. ¿Cómo estás?\p"
	.string "Oye, supe que lograste la hazaña\n"
	.string "de {STR_VAR_3} victorias seguidas en\l"
	.string "el {STR_VAR_2}.\p"
	.string "¡Debo esforzarme más yo también!\n"
	.string "¡Hasta pronto!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "...Eh, ¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}...\p"
	.string "Ah, sí, estuviste en\n"
	.string "el {STR_VAR_2}, ¿verdad?\p"
	.string "Y ganaste {STR_VAR_3} batallas seguidas.\p"
	.string "¡Mira, un POKéMON raro!\n"
	.string "¡Tengo que irme!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "Espero que estés muy bien.\p"
	.string "Ah, claro que sí. Supe que ganaste\n"
	.string "{STR_VAR_3} combates seguidos en\l"
	.string "el {STR_VAR_2}.\p"
	.string "¡Es muy impresionante!\n"
	.string "¡Debo entrenar mis POKéMON también!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Me enteré! ¡Tu racha de {STR_VAR_3}\n"
	.string "victorias en el {STR_VAR_2}!\p"
	.string "¡Eso es genial!\n"
	.string "¡Yo también me esforzaré más!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, hola...\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Ganaste {STR_VAR_3} batallas seguidas\n"
	.string "en el {STR_VAR_2}?\p"
	.string "Es un gran logro.\n"
	.string "Debo trabajar más duro.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Dicen que eres el terror\n"
	.string "del {STR_VAR_2}?\p"
	.string "Ganaste, ¿qué, {STR_VAR_3} combates\n"
	.string "seguidos?\p"
	.string "Eres muy bueno.\n"
	.string "¿Me pregunto cuántos ganaré yo?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo has estado?\p"
	.string "Me contaron algo sobre ti.\n"
	.string "¿Ganaste {STR_VAR_3} batallas seguidas\l"
	.string "en {STR_VAR_2}?\p"
	.string "¡Es una gran historia!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que estés muy bien.\p"
	.string "Dicen que ganaste {STR_VAR_3} batallas\n"
	.string "seguidas en {STR_VAR_2}.\p"
	.string "¡Admiro tu energía!\n"
	.string "¡Adiós!$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡He oído hablar de ti!\p"
	.string "¿No ganaste {STR_VAR_3} batallas\n"
	.string "seguidas en {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Adiós!$"

MatchCall_BattleDomeText1::
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "¡Hola, soy {STR_VAR_1}!\l"
	.string "¡Me enteré de la noticia!\p"
	.string "¿Fuiste el campeón en\n"
	.string "{STR_VAR_2} {STR_VAR_3} veces?\p"
	.string "¡Es genial! ¡Debo mejorar!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleDomeText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡He oído hablar de ti!\p"
	.string "Dijeron que ganaste {STR_VAR_3} títulos\n"
	.string "en {STR_VAR_2}.\p"
	.string "¡Súper! ¿Me pregunto si yo también\n"
	.string "podré ser campeón?$"

MatchCall_BattleDomeText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "¡Oí que ganaste {STR_VAR_3} veces\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Ve por una más la próxima vez!\n"
	.string "¡Hablamos pronto!$"

MatchCall_BattleDomeText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "Supe que fuiste campeón en la\n"
	.string "{STR_VAR_2} {STR_VAR_3} veces.\p"
	.string "Parece que te esfuerzas mucho.\n"
	.string "¡Intentaré alcanzarte!$"

MatchCall_BattleDomeText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Oí que ganaste {STR_VAR_3} veces\n"
	.string "seguidas en {STR_VAR_2}.\p"
	.string "¡Yo también debo ponerme las pilas!\n"
	.string "¡Nos vemos pronto!$"

MatchCall_BattleDomeText6::
	.string "Hola, ¿{PLAYER}{KUN}?\n"
	.string "Aquí {STR_VAR_1}. ¿Cómo estás?\p"
	.string "Por cierto, oí que fuiste\n"
	.string "campeón {STR_VAR_3} veces en\l"
	.string "{STR_VAR_2}.\p"
	.string "Debo entrenar a mis POKéMON antes\n"
	.string "de que me saques más ventaja.$"

MatchCall_BattleDomeText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Estuviste en el {STR_VAR_2}\n"
	.string "y fuiste campeón {STR_VAR_3} veces?\p"
	.string "Qué genial. Por cierto, ¿has\n"
	.string "capturado POKéMON raros hace poco?\p"
	.string "Ah, ¿en serio?\n"
	.string "Vale, adiós.$"

MatchCall_BattleDomeText8::
	.string "Hola, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "Espero que estés muy bien.\l"
	.string "Ah, claro que lo estás.\p"
	.string "Supe que ganaste {STR_VAR_3} títulos\n"
	.string "en el {STR_VAR_2}.\p"
	.string "Debo criar mis POKéMON como tú.\n"
	.string "Nos vemos.$"

MatchCall_BattleDomeText9::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Me enteré! ¡Ganaste el título\n"
	.string "{STR_VAR_3} veces en el {STR_VAR_2}!\p"
	.string "¡Eso es genial!\n"
	.string "¡Yo también debo esforzarme más!$"

MatchCall_BattleDomeText10::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Ganaste {STR_VAR_3} veces seguidas\n"
	.string "en el {STR_VAR_2}?\p"
	.string "Es un gran logro.\n"
	.string "Tengo que trabajar más duro.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Dicen que eres el terror del\n"
	.string "{STR_VAR_2}?\p"
	.string "¿Ganaste {STR_VAR_3} veces seguidas\n"
	.string "ya?\p"
	.string "¿Me pregunto si algún día podré\n"
	.string "ser campeón?\p"
	.string "...¿Será imposible?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattleDomeText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Te encuentras bien?\p"
	.string "¿Ganaste {STR_VAR_3} eventos en un\n"
	.string "lugar llamado {STR_VAR_2}?\p"
	.string "Es una historia increíble.\n"
	.string "¡Adiós!$"

MatchCall_BattleDomeText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que hayas estado bien.\p"
	.string "¿Dicen que ganaste {STR_VAR_3} eventos\n"
	.string "en el {STR_VAR_2}?\p"
	.string "¡Admiro tu energía!\n"
	.string "Adiós.$"

MatchCall_BattleDomeText14::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Oí hablar de ti!\p"
	.string "¿No ganaste {STR_VAR_3} títulos\n"
	.string "en el {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePikeText1::
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "¡Hola, soy {STR_VAR_1}!\l"
	.string "¡Me enteré de las noticias!\p"
	.string "¡Pasaste {STR_VAR_3} salas\n"
	.string "en el {STR_VAR_2}!\p"
	.string "¡Eso es increíble!\n"
	.string "¡Adiós!$"

MatchCall_BattlePikeText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Oí hablar de ti!\p"
	.string "Dicen que ganaste en\n"
	.string "{STR_VAR_3} salas del {STR_VAR_2}.\p"
	.string "¡Debo esforzarme mucho más!\n"
	.string "¡Adiós!$"

MatchCall_BattlePikeText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "¡Oí que pasaste {STR_VAR_3} salas\n"
	.string "en el {STR_VAR_2}!\p"
	.string "¡Intenta mejorar la próxima vez!\n"
	.string "¡Hablamos pronto!$"

MatchCall_BattlePikeText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "Oí que arrasaste en {STR_VAR_3} salas\n"
	.string "en el {STR_VAR_2}.\p"
	.string "¡Mejor entreno a mis POKéMON y\n"
	.string "trato de seguirte el ritmo!$"

MatchCall_BattlePikeText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Oí que pasaste {STR_VAR_3} salas\n"
	.string "en el {STR_VAR_2}.\p"
	.string "¡Yo también debo ponerme las pilas!\n"
	.string "¡Nos vemos pronto!$"

MatchCall_BattlePikeText6::
	.string "¿Hola, {PLAYER}{KUN}?\n"
	.string "Aquí {STR_VAR_1}. ¿Cómo estás?\p"
	.string "Por cierto, oí que pasaste\n"
	.string "{STR_VAR_3} salas en el {STR_VAR_2}.\p"
	.string "Debo criar a mis POKéMON antes de\n"
	.string "que te adelantes más.$"

MatchCall_BattlePikeText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "¿Estuviste en el {STR_VAR_2}\n"
	.string "y ganaste en {STR_VAR_3} salas?\p"
	.string "Eso es genial.\p"
	.string "¡Oh, ahí va un POKéMON raro!\n"
	.string "Vale, adiós.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Te habla {STR_VAR_1}.\l"
	.string "Espero que estés bien.\l"
	.string "Ah, pero sí lo estás.\p"
	.string "Me enteré de que pasaste\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}.\p"
	.string "¡Es impresionante!\n"
	.string "Debo criar mis POKéMON como tú.\l"
	.string "¡Nos vemos!$"

MatchCall_BattlePikeText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Me enteré! ¡Ganaste en\n"
	.string "{STR_VAR_3} salas del {STR_VAR_2}!\p"
	.string "¡Eso es genial!\n"
	.string "¡Yo también debo esforzarme más!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Ganaste en {STR_VAR_3} salas\n"
	.string "en el {STR_VAR_2}?\p"
	.string "Es un gran logro.\n"
	.string "Debo trabajar más duro.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Oí que eres el terror\n"
	.string "del {STR_VAR_2}?\p"
	.string "¿Pasaste, qué, {STR_VAR_3} salas?\n"
	.string "Eso debe valer algo.\p"
	.string "¿Me pregunto si podré llegar a\n"
	.string "ser un campeón?\p"
	.string "...¿Será imposible?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattlePikeText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Te encuentras bien?\p"
	.string "¿Ganaste en {STR_VAR_3} salas en\n"
	.string "un lugar llamado {STR_VAR_2}?\p"
	.string "Es toda una historia.\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePikeText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que hayas estado bien.\p"
	.string "¿Dicen que ganaste en {STR_VAR_3} salas\n"
	.string "en el {STR_VAR_2}?\p"
	.string "¡Admiro tu energía!\n"
	.string "¡Adiós!$"

MatchCall_BattlePikeText14::
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Oí hablar de ti!\p"
	.string "¿No pasaste {STR_VAR_3} salas\n"
	.string "en el {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePyramidText1::
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "¡Hola, soy {STR_VAR_1}!\l"
	.string "¡Me enteré de la noticia!\p"
	.string "Subiste {STR_VAR_3} pisos dentro\n"
	.string "del {STR_VAR_2}, ¿verdad?\p"
	.string "¡Eso es increíble!\n"
	.string "Debería intentar ese reto.$"

MatchCall_BattlePyramidText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡He oído hablar de ti!\p"
	.string "Dicen que venciste en\n"
	.string "{STR_VAR_3} pisos de {STR_VAR_2}.\p"
	.string "¡Guau, es fantástico!\n"
	.string "¡Yo también entrenaré mis POKéMON!$"

MatchCall_BattlePyramidText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "¡Oí que subiste {STR_VAR_3} pisos\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Intenta superarte la próxima vez!\n"
	.string "¡Nos vemos pronto!$"

MatchCall_BattlePyramidText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "Oí que subiste {STR_VAR_3} pisos\n"
	.string "en {STR_VAR_2}.\p"
	.string "¡Debo esforzarme más para\n"
	.string "no quedarme atrás!$"

MatchCall_BattlePyramidText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Oí que subiste {STR_VAR_3} pisos\n"
	.string "en {STR_VAR_2}.\p"
	.string "¡Yo también debo ponerme las pilas!\n"
	.string "¡Nos vemos pronto!$"

MatchCall_BattlePyramidText6::
	.string "¿Hola, {PLAYER}{KUN}?\n"
	.string "Aquí {STR_VAR_1}. ¿Cómo estás?\p"
	.string "Oí que superaste\n"
	.string "{STR_VAR_3} pisos en {STR_VAR_2}.\p"
	.string "Debo entrenar mis POKéMON antes de\n"
	.string "que me saques más ventaja.$"

MatchCall_BattlePyramidText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Aquí {STR_VAR_1}.\p"
	.string "¿Estuviste en {STR_VAR_2}\n"
	.string "y subiste {STR_VAR_3} pisos?\p"
	.string "Genial. ¿Había POKéMON raros\n"
	.string "allí?\p"
	.string "¿No, eh?\n"
	.string "Vale, adiós.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "Espero que estés muy bien.\l"
	.string "Ah, claro que lo estás.\p"
	.string "Oí que superaste\n"
	.string "{STR_VAR_3} pisos en {STR_VAR_2}.\p"
	.string "¡Es muy impresionante!\n"
	.string "Debo entrenar mis POKéMON como tú.\l"
	.string "Hasta luego.$"

MatchCall_BattlePyramidText9::
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Me enteré! ¡Venciste en\n"
	.string "{STR_VAR_3} pisos de {STR_VAR_2}!\p"
	.string "¡Eso es genial!\n"
	.string "¡Yo también debo esforzarme más!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Subiste {STR_VAR_3} pisos dentro\n"
	.string "de {STR_VAR_2}?\p"
	.string "Es un gran logro.\n"
	.string "Debo esforzarme más.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Oí que eres el terror de\n"
	.string "{STR_VAR_2}?\p"
	.string "¿Subiste, qué, {STR_VAR_3} pisos?\n"
	.string "Eso debe valer algo.\p"
	.string "¿Podré llegar a ser\n"
	.string "un campeón?\p"
	.string "...¿Es casi imposible?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattlePyramidText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Te encuentras bien?\p"
	.string "¿Ganaste en {STR_VAR_3} pisos en\n"
	.string "un lugar llamado {STR_VAR_2}?\p"
	.string "Es una gran historia.\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePyramidText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que estés muy bien.\p"
	.string "Dicen que subiste {STR_VAR_3} pisos\n"
	.string "en {STR_VAR_2}?\p"
	.string "¡Admiro tu energía!\n"
	.string "Adiós.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡He oído hablar de ti!\p"
	.string "¿No pasaste {STR_VAR_3} pisos\n"
	.string "en {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Hasta luego!$"

MatchCall_Text_Mom1::
	.string "MAMÁ: Tu padre y tú...\n"
	.string "Todos aman a los POKéMON.\p"
	.string "¿Cuál es el encanto de POKéMON?\p"
	.string "¿Yo?\n"
	.string "Amo a los POKéMON que me ayudan\l"
	.string "con los quehaceres diarios.$"

MatchCall_Text_Mom2::
	.string "MAMÁ: ¡Hola, {PLAYER}!\n"
	.string "Tu padre sigue encerrado\l"
	.string "en el GIMNASIO PETALBURG.\p"
	.string "Viene a casa de vez en cuando.\n"
	.string "Pero vuelve al GIMNASIO cuando\l"
	.string "ya ha comido todo lo posible.\p"
	.string "¡Creo que perder contra ti\n"
	.string "fue un golpe a su orgullo!$"

MatchCall_Text_Mom3::
	.string "MAMÁ: {PLAYER}...\n"
	.string "No te preocupes por mí ni la casa.\p"
	.string "¡Usa esas ZAPATILLAS hasta que\n"
	.string "se rompan, cariño!$"

MatchCall_Text_Baoba1::
	.string "BAOBA: {PLAYER}!\n"
	.string "¡La SAFARI ZONE casi está lista!\p"
	.string "¡Te llamaré en cuanto\n"
	.string "esté terminada!$"

MatchCall_Text_Baoba2::
	.string "BAOBA: {PLAYER}!\n"
	.string "¡La SAFARI ZONE ya abrió! ¡Ven\p"
	.string "cuando quieras!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: ¡Hola, {PLAYER}!\p"
	.string "He entrenado duro desde que\n"
	.string "nos conocimos.\p"
	.string "Aún necesito más tiempo\n"
	.string "para reabrir el GYM.\p"
	.string "Cuando lo haga, ¡visita mi GYM\n"
	.string "para una revancha!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: ¿Eres {PLAYER}?\n"
	.string "¡Felicidades!\l"
	.string "¡He oído hablar de ti!\p"
	.string "Yo necesito más tiempo\n"
	.string "para reabrir el GYM.\p"
	.string "Cuando lo haga, ¡visita mi GYM\n"
	.string "para una revancha!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "¡Mi GYM ya está listo!\p"
	.string "¡Visita RUSTBORO cuando\n"
	.string "puedas!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: En el GYM de RUSTBORO,\n"
	.string "que hayamos luchado, {PLAYER},\l"
	.string "es un orgullo.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Aprendí mucho de la batalla que\n"
	.string "tuvimos.\p"
	.string "Pienso volver a entrenar\n"
	.string "y luego reabrir el GYM.\p"
	.string "Tardaré un tiempo en estar\n"
	.string "listo para dirigir el GYM.\p"
	.string "Pero si logro reabrirlo,\n"
	.string "quiero que nos desafíes de nuevo.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Felicidades!\p"
	.string "¡Tus hazañas llegaron\n"
	.string "con los vientos marinos!\p"
	.string "Parece que debo trabajar más\n"
	.string "en mi entrenamiento.\p"
	.string "Tardaré un tiempo en estar\n"
	.string "listo para dirigir el GYM.\p"
	.string "Pero si logro reabrirlo,\n"
	.string "quiero que nos desafíes de nuevo.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Mi GIMNASIO está listo!\p"
	.string "¡Vuelve a ISLA ROCA cuando quieras\n"
	.string "para otro desafío!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, ¡creo que\n"
	.string "nunca me cansaré de luchar contigo!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: ¡Oh, eres tú!\p"
	.string "Desde que te fuiste, he estado\n"
	.string "entrenando desde cero.\p"
	.string "Creo que necesito un poco más\n"
	.string "de tiempo para abrir mi GIMNASIO.\p"
	.string "¡Tendrás que esperar hasta entonces!\n"
	.string "¡Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: ¡Wahahahaha!\p"
	.string "Lo lograste, ¿verdad?\n"
	.string "¡Me han llegado noticias tuyas!\p"
	.string "Parece que debo entrenar\n"
	.string "un poco más.\p"
	.string "Creo que necesito un poco más\n"
	.string "de tiempo para abrir mi GIMNASIO.\p"
	.string "¡Tendrás que esperar hasta entonces!\n"
	.string "¡Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: ¡Oh, eres tú!\n"
	.string "¡Mi GIMNASIO está listo!\p"
	.string "¡Visita MALVALUZ cuando quieras!\n"
	.string "¡Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: ¡Wahahaha!\p"
	.string "¡Luchar contigo siempre es\n"
	.string "una experiencia electrizante!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}...\p"
	.string "Al luchar, aprendí lo\n"
	.string "inmadura que era.\p"
	.string "¡Pero aún no he terminado!\p"
	.string "Entrenaré más y volveré a\n"
	.string "abrir el GIMNASIO.\p"
	.string "Cuando llegue el momento, {PLAYER},\n"
	.string "por favor, desafíanos de nuevo.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: ¿Hola, {PLAYER}?\n"
	.string "¡Felicidades!\p"
	.string "¡Tus éxitos nos llegaron\n"
	.string "como el calor de un volcán!\p"
	.string "Nuestro entrenamiento va\n"
	.string "muy bien por aquí.\p"
	.string "Cuando el GIMNASIO esté listo, verás\n"
	.string "una marca junto a mi nombre en la\l"
	.string "lista de MATCH CALL.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: ¡Oh, {PLAYER}?\n"
	.string "¡Nuestro GIMNASIO está listo!\p"
	.string "¡Ven a LAVARIDGE a relajarte\n"
	.string "en las aguas termales y luchar!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "Estoy segura de que mejoras\l"
	.string "tu entrenamiento cada vez más.$"

MatchCall_Text_Winona1::
	.string "WINONA: ¡Hola, {PLAYER}!\p"
	.string "¡Gracias a nuestra batalla, ya\n"
	.string "entiendo cuáles son mis fallos!\p"
	.string "¡Cuando abra el GIMNASIO, no\n"
	.string "volveré a ser derrotada!$"

MatchCall_Text_Winona2::
	.string "WINONA: ¡Lo lograste, {PLAYER}!\p"
	.string "¡La noticia del nuevo CAMPEÓN\n"
	.string "llegó hasta FORTREE!\p"
	.string "Pero... la próxima vez que luchemos,\n"
	.string "no terminará de la misma forma.$"

MatchCall_Text_Winona3::
	.string "WINONA: ¿Eres {PLAYER}?\n"
	.string "¡Nuestro GIMNASIO ya opera!\p"
	.string "¡Te esperamos en FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Aunque perdí, mis alas jamás\l"
	.string "se romperán.\p"
	.string "Sí, igual que tú nunca perdiste\n"
	.string "de vista tu sueño.$"

MatchCall_Text_TateLiza1::
	.string "TATE: ¡Oh! Tú eres...\n"
	.string "LIZA: ¡{PLAYER}!\p"
	.string "TATE: Estamos entrenando otra vez...\n"
	.string "LIZA: ¡Para reabrir nuestro GIMNASIO!\p"
	.string "TATE: Cuando el GIMNASIO esté listo...\n"
	.string "LIZA: Cuando el GIMNASIO esté listo...\p"
	.string "TATE: Aparecerá una marca en nuestro\n"
	.string "nombre en la lista MATCH CALL.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, ¡felicidades!\n"
	.string "LIZA: {PLAYER}, ¡felicidades!\p"
	.string "TATE: Nosotros dos...\n"
	.string "LIZA: ¡Seguimos entrenando!\p"
	.string "TATE: Necesitamos más tiempo, pero...\n"
	.string "LIZA: Cuando el GIMNASIO esté listo...\p"
	.string "TATE: Aparecerá una marca en nuestro\n"
	.string "nombre en la lista MATCH CALL.$"

MatchCall_Text_TateLiza3::
	.string "TATE: ¡{PLAYER}!\n"
	.string "LIZA: ¡{PLAYER}!\p"
	.string "TATE: ¡Nuestro GIMNASIO está listo!\n"
	.string "LIZA: ¡Nuestro GIMNASIO está listo!\p"
	.string "TATE: Por favor, visítanos...\n"
	.string "LIZA: ¡en FONDO MAR cuando quieras!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, la batalla que tuvimos…\n"
	.string "LIZA: Es una experiencia invaluable.\p"
	.string "TATE: Sería lindo si…\n"
	.string "LIZA: ¡Pudiéramos luchar otra vez!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm...\n"
	.string "{PLAYER}{KUN}... ¿verdad?\p"
	.string "Nuestra batalla me trajo recuerdos\n"
	.string "de cuando conocí a WALLACE\l"
	.string "por primera vez.\p"
	.string "¡Tal vez seas un genio que pueda\n"
	.string "superar a WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu... {PLAYER}{KUN}...\n"
	.string "Al fin lograste tu objetivo.\p"
	.string "Mi ojo para el talento no se\n"
	.string "equivocó...\p"
	.string "Espero volver a verte, pues has\n"
	.string "alcanzado la cima del poder\l"
	.string "y el prestigio.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho... {PLAYER}{KUN}...\p"
	.string "Nuestro GIMNASIO de CALMAGA\n"
	.string "finalmente reabrió.\p"
	.string "Si quieres verme, eres bienvenido\n"
	.string "a visitarme cuando quieras.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Como la mejor música, las batallas\n"
	.string "que libramos crean acordes\l"
	.string "de inspiración en mi corazón…\p"
	.string "Al cerrar los ojos, te veo volar\n"
	.string "junto a la melodía…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: ¡Ey, {PLAYER}!\p"
	.string "Si quieres luchar conmigo\n"
	.string "otra vez, vuelve cuando quieras\l"
	.string "a la LIGA POKéMON.\p"
	.string "¡Siempre estaré aquí!\n"
	.string "¡Te estaré esperando!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: ¡Hola, {PLAYER}!\p"
	.string "¿Qué tal si vuelves por aquí\n"
	.string "algún día?\p"
	.string "Quisiera ver cuánto ha crecido\n"
	.string "el vínculo con tus\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Hola, {PLAYER}.\p"
	.string "Espero que no te hayas\n"
	.string "estancado en tu poder.\p"
	.string "Si necesitas enfriar un poco tus\n"
	.string "ardientes emociones, ven\l"
	.string "a la LIGA POKéMON…$"

MatchCall_Text_Drake::
	.string "DRAKE: Esa voz... ¿eres {PLAYER}?\n"
	.string "Suenas bien...\p"
	.string "Tengo entendido que ahora hay\n"
	.string "un sitio llamado BATTLE\l"
	.string "FRONTIER que prueba la habilidad\l"
	.string "de los ENTRENADORES.\p"
	.string "Pero si quieres batallas reales,\n"
	.string "¡nada supera a la POKéMON\l"
	.string "LEAGUE!\p"
	.string "¿No estás de acuerdo, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hola, {PLAYER}{KUN}.\n"
	.string "¿Has conocido a STEVEN?\p"
	.string "Él es...\n"
	.string "Realmente muy habilidoso.\p"
	.string "Sin embargo, es un alma rara que\n"
	.string "rara vez batalla.\p"
	.string "En su lugar, prefiere buscar\n"
	.string "piedras raras.\p"
	.string "Seguro excava en alguna cueva o\n"
	.string "montaña escarpada por ahí.\p"
	.string "¿Pero qué es una piedra rara?\n"
	.string "Solo pienso en un METEORITO...$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … ¡Bip!\p"
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Estuve en PACIFIDLOG hace\n"
	.string "poco tiempo.\p"
	.string "Vi un POKéMON verde gigante\n"
	.string "volando alto en el cielo.\p"
	.string "Yo…\n"
	.string "Nunca vi nada igual.\p"
	.string "Me pregunto qué sería.\n"
	.string "¿Será un gran descubrimiento?\p"
	.string "… … … … … …\n"
	.string "… … … … … ¡Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … ¡Bip!\p"
	.string "BRENDAN: ¡Hola, {PLAYER}!\n"
	.string "Estuve en PACIFIDLOG ahora.\p"
	.string "Vi un POKéMON verde enorme\n"
	.string "volando por el cielo.\p"
	.string "Nunca había visto algo tan\n"
	.string "increíble.\p"
	.string "Ojalá lo hubieras visto,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … ¡Click!$"

MatchCall_Text_May1::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "EL SR. BRINEY se retiró como\n"
	.string "MARINERO, pero a veces lo veo\l"
	.string "en el mar con su PEEKO.\p"
	.string "Debe seguir amando el mar.$"

MatchCall_Text_May2::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Sabes que pueblos como\n"
	.string "PETALBURG y DEWFORD tienen GIMNASIOS?\p"
	.string "Por alguna razón, el puerto de\n"
	.string "SLATEPORT no tiene uno.\p"
	.string "Cuando construyan uno allí,\n"
	.string "¡postularé para ser la LÍDER!$"

MatchCall_Text_May3::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Recuerdas al hombre que usa\n"
	.string "CORTE en RUSTBORO?\l"
	.string "Tenía una casa allí, ¿verdad?\p"
	.string "Pues su hermano menor vive\n"
	.string "en MAUVILLE.\p"
	.string "¿Adivinas su nombre?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "¡EL CHICO DE ROCE ROCA!$"

MatchCall_Text_May4::
	.string "MAY: ¿{PLAYER}{KUN}?\p"
	.string "TÚNEL CÉSPED...\n"
	.string "Se llama así porque une a\l"
	.string "RUSTBORO y VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, ¿cómo estás?\p"
	.string "Ahora estoy en la RUTA 111.\p"
	.string "Voy a descansar en la casa de\n"
	.string "una anciana.\p"
	.string "Vive justo al norte del\n"
	.string "desierto.$"

MatchCall_Text_May6::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Sabías de la TORRE ESPEJISMO\n"
	.string "en el desierto?\p"
	.string "Dicen que, como un espejismo,\n"
	.string "aparece y desaparece.\p"
	.string "¡Ojalá pudiera verla!$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, ¡yahoo!\n"
	.string "Ahora estoy en la RUTA 119.\p"
	.string "Hay un río grande aquí y\n"
	.string "llueve a menudo.\p"
	.string "¡Me empapé por completo!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, hola.\p"
	.string "EL MT. PYRE es un memorial de\n"
	.string "POKéMON que han fallecido.\p"
	.string "¡Quizás por eso hay tantos\n"
	.string "POKéMON tipo FANTASMA!$"

MatchCall_Text_May9::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Pensaba ir a las aguas termales\n"
	.string "de LAVARIDGE.\p"
	.string "Pero en JAGGED PASS me topé con\n"
	.string "gente con mala pinta.\l"
	.string "¡El ambiente estaba tenso!$"

MatchCall_Text_May10::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¿Viste las noticias?\p"
	.string "Dicen que el CAPT. STERN halló\n"
	.string "la CAVERNA DEL FONDO MARINO\l"
	.string "en su expedición submarina.$"

MatchCall_Text_May11::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¿No te parece genial?\p"
	.string "Aunque no tengas un barco,\n"
	.string "puedes cruzar el mar usando\l"
	.string "un movimiento POKéMON.\p"
	.string "¿Sabías que hay más?\p"
	.string "¡Hay un movimiento que te deja\n"
	.string "ir al fondo del mar!$"

MatchCall_Text_May12::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Espero que todo esté bien!\p"
	.string "¿Has ido al mar y has visto\n"
	.string "que el camino al otro lado\l"
	.string "está bloqueado?\p"
	.string "Intenta bucear profundo y\n"
	.string "seguir las fosas.\p"
	.string "Al llegar al otro lado,\n"
	.string "sube a la superficie. ¡Fácil!$"

MatchCall_Text_May13::
	.string "MAY: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Cómo va todo?\n"
	.string "¿Estás llenando tu POKéDEX?\p"
	.string "Oí que hay POKéMON\n"
	.string "superantiguos por ahí.\l"
	.string "¡Y que hay tres de ellos!\p"
	.string "Me encantaría ver aunque sea uno…$"

MatchCall_Text_May14::
	.string "MAY: ¡{PLAYER}{KUN}!\n"
	.string "¡Oí los rumores!\p"
	.string "¿Venciste al LÍDER del\n"
	.string "GIMNASIO de CALMASA?\p"
	.string "Eso significa que ya no te falta\n"
	.string "mucho, ¿verdad?$"

MatchCall_Text_May15::
	.string "MAY: ¡No queda un solo ENTRENADOR\n"
	.string "en HOENN que no sepa quién\l"
	.string "eres, {PLAYER}{KUN}!\p"
	.string "Cuando digo que soy tu amiga,\n"
	.string "{PLAYER}{KUN}, ¡todos se\l"
	.string "sorprenden!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: ¡Hola, {PLAYER}!\p"
	.string "EL SR. BRINEY se retiró como MARINERO,\n"
	.string "pero a veces lo veo en el mar\l"
	.string "con su mascota PEEKO.\p"
	.string "Supongo que aún debe\n"
	.string "amar el mar.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: ¡Hola, {PLAYER}!\p"
	.string "No entiendo cómo pueblos como\n"
	.string "PETALBURG y DEWFORD tienen GIMNASIOS.\p"
	.string "El gran puerto de SLATEPORT\n"
	.string "no tiene uno.\p"
	.string "Cuando hagan uno allí,\n"
	.string "postularé para ser el LÍDER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: ¡Oye, {PLAYER}!\p"
	.string "¿Recuerdas al tipo del CORTE\n"
	.string "en RUSTBORO?\l"
	.string "Tenía una casa allí, ¿no?\p"
	.string "Pues resulta que su hermano\n"
	.string "vive en MAUVILLE.\p"
	.string "¿Adivinas su nombre?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "¡EL TIPO DEL ROCE!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Esta voz… ¿{PLAYER}?\p"
	.string "Llamaron al TÚNEL RUSTURF así\n"
	.string "porque une RUSTBORO y\l"
	.string "VERDANTURF.\p"
	.string "¿Lo sabías?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, ¿qué pasa?\p"
	.string "Oye, estoy en la RUTA 111.\p"
	.string "Descansaré en la casa de una señora\n"
	.string "al norte del desierto.\p"
	.string "Si estás por aquí, deberías\n"
	.string "visitarla tú también.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: ¡Hola, {PLAYER}!\p"
	.string "¿Sabías de la TORRE ESPEJISMO\n"
	.string "que hay en el desierto?\p"
	.string "Dicen que, como un espejismo,\n"
	.string "solo se ve a veces.\p"
	.string "¡Me gustaría verla!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: ¿Quién es? ¿{PLAYER}?\n"
	.string "¿Adivina qué? Estoy en la RUTA 119.\p"
	.string "Hay un río grande aquí y\n"
	.string "llueve todo el tiempo.\p"
	.string "¡Me empapé hasta los huesos!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: ¡{PLAYER}!\p"
	.string "EL MT. PYRE es un memorial para\n"
	.string "POKéMON que han fallecido.\p"
	.string "¡Por eso debe estar lleno de\n"
	.string "tantos POKéMON tipo FANTASMA!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hola, {PLAYER}.\p"
	.string "Iba camino a las aguas termales\n"
	.string "de LAVARIDGE.\p"
	.string "Pero en el PASO JAGGED me hallé\n"
	.string "con tipos muy desagradables.\p"
	.string "Esos tipos...\n"
	.string "Creo que eran el TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: ¡Hola, {PLAYER}!\n"
	.string "¿Viste las noticias?\p"
	.string "Dicen que el CAPT. STERN halló la\n"
	.string "CAVERNA DEL FONDO MARINO en su\l"
	.string "expedición en submarino.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: ¡Hola, {PLAYER}!\n"
	.string "¿No te parece increíble?\p"
	.string "Aunque no tengas un barco,\n"
	.string "puedes cruzar el mar usando\l"
	.string "un movimiento POKéMON.\p"
	.string "Y hay uno que te permite viajar\n"
	.string "hasta el fondo del mar.\p"
	.string "¡Los POKéMON pueden hacer todo!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: ¡Hola, {PLAYER}!\n"
	.string "¿Cómo te va?\p"
	.string "¿Te has quedado bloqueado al\n"
	.string "intentar cruzar el mar?\p"
	.string "Prueba buceando profundo y\n"
	.string "siguiendo las fosas del fondo.\p"
	.string "Al llegar al otro lado,\n"
	.string "sube a la superficie. ¡Fácil!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: ¡Hola, {PLAYER}!\p"
	.string "¿Cómo va todo? ¿Llenas tu\n"
	.string "POKéDEX con éxito?\p"
	.string "Oí que hay POKéMON\n"
	.string "superantiguos por ahí.\l"
	.string "¡Y no solo uno, sino tres!\p"
	.string "Me encantaría atrapar uno…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: ¡{PLAYER}!\n"
	.string "¡Escuché los rumores!\p"
	.string "¿Venciste al LÍDER del GIMNASIO\n"
	.string "de SOOTOPOLIS? ¡Genial!\p"
	.string "¡Ya estás muy cerca!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: ¡No hay un ENTRENADOR en\n"
	.string "todo HOENN que no sepa quién\l"
	.string "eres, {PLAYER}!\p"
	.string "Cuando digo que soy amigo\n"
	.string "tuyo, {PLAYER}, ¡se ponen muy\l"
	.string "envidiosos!$"

MatchCall_Text_Wally1::
	.string "WALLY: ¡Oh, {PLAYER}!\p"
	.string "Me he sentido más sano y\n"
	.string "en mejor forma física.\p"
	.string "¡Espero ser un ENTRENADOR como\n"
	.string "tú pronto, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: ¡Hola, {PLAYER}!\p"
	.string "Desde que abrieron el TÚNEL\n"
	.string "RUSTURF, ¡WANDA está feliz!$"

MatchCall_Text_Wally3::
	.string "WALLY: ¡Oh, {PLAYER}!\p"
	.string "Me fui de casa de mi tío en\n"
	.string "PUEBLO VERDANTE sin avisar.\p"
	.string "Me pregunto si estará furioso…\p"
	.string "{PLAYER}, entiendes cómo\n"
	.string "me siento, ¿verdad?$"

MatchCall_Text_Wally4::
	.string "WALLY: ¿{PLAYER}?\n"
	.string "¡Soy yo, WALLY!\p"
	.string "¡El mundo ENTRENADOR es genial!\p"
	.string "Cuando llevo mis POKéMON,\n"
	.string "¡mucha gente me saluda!\p"
	.string "¡Es como si todos se conectaran\n"
	.string "gracias a los POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: ¿{PLAYER}? ¡Es genial!\n"
	.string "¿El RALTS que atrapamos juntos?\l"
	.string "¡Evolucionó, {PLAYER}!\p"
	.string "Tal vez tengo talento…\p"
	.string "¡Pero no debo volverme\n"
	.string "creído!\p"
	.string "¡Después de todo, el POKéMON\n"
	.string "es quien merece el elogio!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY parece estar fuera del\n"
	.string "área de servicio del POKéNAV…$"

MatchCall_Text_Wally7::
	.string "WALLY: ¡Oh, {PLAYER}!\p"
	.string "Antes de conocerte, casi nunca\n"
	.string "salía de mi casa…\p"
	.string "Pero ahora, estoy de aventura con\n"
	.string "mi propio POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Gracias…$"

MatchCall_Text_Scott1::
	.string "SCOTT: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Sabes que hay POKéMON en\n"
	.string "todas partes?\p"
	.string "¿En montañas, en el mar,\n"
	.string "en la hierba alta?\p"
	.string "Igual que ellos, hay\n"
	.string "ENTRENADORES por doquier.\p"
	.string "Por eso, yo también debo\n"
	.string "apresurarme. ¡Qué ajetreo!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Estoy en la RUTA 119.\n"
	.string "¡Está llena de ENTRENADORES!\p"
	.string "Parece que hay hierba alta\n"
	.string "por todas partes.\p"
	.string "¡Caminar aquí en shorts\n"
	.string "me da mucha comezón!$"

MatchCall_Text_Scott3::
	.string "SCOTT: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Has tenido la oportunidad de\n"
	.string "subir al MONTE CENIZA?\p"
	.string "Es un memorial para los POKéMON\n"
	.string "que han fallecido.\p"
	.string "Es un lugar que todo\n"
	.string "ENTRENADOR debe visitar.$"

MatchCall_Text_Scott4::
	.string "SCOTT: ¡Hola, {PLAYER}{KUN}!\p"
	.string "He oído que unas bandas raras\n"
	.string "están causando problemas.\p"
	.string "EL EQUIPO MAGMA y EL EQUIPO AQUA,\n"
	.string "creo que eran ellos.\p"
	.string "Pensaría que hay algunos\n"
	.string "ENTRENADORES hábiles ahí.\p"
	.string "…Pero si son matones…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, hola, {PLAYER}{KUN}.\p"
	.string "¿Habrá ENTRENADORES fuertes\n"
	.string "en el fondo del mar?\p"
	.string "No puedo ir a comprobarlo.\n"
	.string "No sé nadar, para empezar.\l"
	.string "Y no crío POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: ¡Hola, hola, {PLAYER}{KUN}!\p"
	.string "Sabes que puedes desafiar a la\n"
	.string "LIGA POKéMON cuando tengas todas\l"
	.string "las MEDALLAS de GIMNASIO, ¿no?\p"
	.string "Con tu talento, ser el\n"
	.string "CAMPEÓN no es un sueño imposible.\p"
	.string "¿Pero sabías esto?\n"
	.string "Hay un lugar aún mejor.\p"
	.string "Pero eso es todo lo que diré\n"
	.string "por el momento.\p"
	.string "Es algo que puedes\n"
	.string "esperar con ansias.\p"
	.string "¡Cuando ganes en la LIGA POKéMON\n"
	.string "y llegues al SALÓN DE LA FAMA!\l"
	.string "$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT parece estar fuera del\n"
	.string "área de servicio del POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPÁ: En FUNDAQUÉ, hay un hombre\n"
	.string "con el extraño nombre de\l"
	.string "el CORTADOR.\p"
	.string "Si estás por la zona, deberías\n"
	.string "ir a visitarlo.$"

MatchCall_Text_Norman2::
	.string "PAPÁ: Hm... Poco a poco, pero\n"
	.string "con seguridad, te haces más\l"
	.string "fuerte, {PLAYER}.\p"
	.string "Cuanto más fuerte seas, más lejos\n"
	.string "y alto volarás de mamá y de\l"
	.string "mí...\p"
	.string "Es difícil de explicar.$"

MatchCall_Text_Norman3::
	.string "PAPÁ: Ya veo…\n"
	.string "Tienes cuatro MEDALLAS de GYM…\p"
	.string "Ya no hay vuelta atrás.\n"
	.string "Lucharemos como prometí.\p"
	.string "Ven cuando quieras.\n"
	.string "¡Todos te estaremos esperando!$"

MatchCall_Text_Norman4::
	.string "PAPÁ: {PLAYER}! Deberías visitar a\n"
	.string "tu madre de vez en cuando.\p"
	.string "Yo me quedaré aquí para\n"
	.string "redoblar mi entrenamiento.\p"
	.string "¡El camino del combate es profundo\n"
	.string "y despiadado!$"

MatchCall_Text_Norman5::
	.string "PAPÁ: ¡Oh, hola, {PLAYER}!\p"
	.string "¿Qué es eso? ¿EMBLEMA MAGMA?\n"
	.string "No sé qué es eso.\p"
	.string "Pero con ese nombre, ¡podría\n"
	.string "estar ligado a un volcán!$"

MatchCall_Text_Norman6::
	.string "PAPÁ: ¡Hiyah! ¡Haah! ¡Dwah!\p"
	.string "…¿Oh? {PLAYER}!\p"
	.string "¡Me atrapaste justo en medio de\n"
	.string "una sesión de entrenamiento!$"

MatchCall_Text_Norman7::
	.string "PAPÁ: {PLAYER}!\p"
	.string "Quién diría que llegarías a ser\n"
	.string "el CAMPEÓN de la LIGA POKéMON…\p"
	.string "¡Bien!\n"
	.string "¡Yo no me quedaré atrás!$"

MatchCall_Text_Norman8::
	.string "PAPÁ: ¿Hm? ¿{PLAYER}?\n"
	.string "¡Llegas justo a tiempo!\p"
	.string "Esta vez, te desafío a una\n"
	.string "batalla.\p"
	.string "Te espero en el GIMNASIO PETALBURG.\n"
	.string "¡Acepta mi reto cuando quieras!$"

MatchCall_Text_Norman9::
	.string "PAPÁ: ...Me sorprendes, {PLAYER}.\n"
	.string "¿Qué tan alto llegarás a volar?$"

MatchCall_Text_Steven1::
	.string "STEVEN: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Ya has ido a MALDITA\n"
	.string "CIUDAD?\p"
	.string "Ve a la TIENDA DE BICIS\n"
	.string "y consigue una MACH BIKE.\p"
	.string "Luego, explora bien la\n"
	.string "CUEVA GRANITO.\p"
	.string "Podrías hacer un nuevo\n"
	.string "descubrimiento allí.$"

MatchCall_Text_Steven2::
	.string "STEVEN: ¡Hola, {PLAYER}{KUN}!\p"
	.string "He conocido a muchos\n"
	.string "ENTRENADORES hasta ahora.\p"
	.string "Pero tú eres único.\n"
	.string "No te pareces a nadie más.$"

MatchCall_Text_Steven3::
	.string "STEVEN: ¡Hola, {PLAYER}{KUN}!\p"
	.string "En tu aventura con tus POKéMON,\n"
	.string "¿qué piensas?\p"
	.string "¿Crees que son compañeros\n"
	.string "fuertes?\p"
	.string "¿Crees que son amigos\n"
	.string "divertidos?\p"
	.string "Según lo que pienses, el sentido\n"
	.string "de tu aventura cambiará.$"

MatchCall_Text_Steven4::
	.string "STEVEN: ¿Hola?\n"
	.string "¿{PLAYER}{KUN}?\p"
	.string "Tengo un pequeño problema en el\n"
	.string "CENTRO ESPACIAL.\p"
	.string "Lo siento, no puedo hablar ahora.\n"
	.string "¡Adiós!$"

MatchCall_Text_Steven5::
	.string "STEVEN: ¡Oh!\n"
	.string "¡{PLAYER}{KUN}!\p"
	.string "No hace falta hablar.\n"
	.string "Ya pasó el tiempo de hablar.\p"
	.string "Debes creer en ti mismo\n"
	.string "y hacer lo correcto.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "Parece que STEVEN no\n"
	.string "está atendiendo la llamada…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}... ¡Felicidades\n"
	.string "por entrar al SALÓN DE LA FAMA!\p"
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\p"
	.string "¡Espero que nos volvamos a ver\n"
	.string "en algún lugar!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: ¡Oh, {PLAYER}{KUN}!\n"
	.string "¡Ya he oído hablar de ti!\p"
	.string "Parece que tu POKéNAV se ha\n"
	.string "actualizado con MATCH CALL.\p"
	.string "¡Bueno, yo también me registraré!\p"
	.string "Así podré examinar tu POKéDEX\n"
	.string "aunque estés\l"
	.string "en el campo.\p"
	.string "... ... ... ... ... ...$"

MatchCall_Text_RegisteredBirch:
	.string "Se registró al PROF. BIRCH\n"
	.string "en la POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: Con la POKéDEX y la\n"
	.string "POKéNAV, estudiar POKéMON\l"
	.string "es más divertido, ¿verdad?$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: ¿Oh? ¡{PLAYER}{KUN}!\p"
	.string "Si me llamaste, ¡la POKéNAV\n"
	.string "debe estar funcionando bien!\p"
	.string "Otros se registrarán también,\n"
	.string "¡así que intenta llamarlos!\p"
	.string "¡Bien! ¡Bien!\n"
	.string "¡Pareces estar muy feliz!\p"
	.string "Hm...\n"
	.string "¿Cómo podría saberlo?\p"
	.string "¡Porque te miro desde la\n"
	.string "ventana de mi oficina!\p"
	.string "¡Wahahaha!\n"
	.string "¡Nos vemos!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: ¿Oh? ¡{PLAYER}{KUN}!\p"
	.string "¿Qué pasa? ¿Olvidaste el\n"
	.string "pequeño encargo que te di?\p"
	.string "Debes entregar mi carta a\n"
	.string "STEVEN en FUNDA ROCA.\p"
	.string "Luego, lleva el paquete al\n"
	.string "CAPT. STERN en FONDALAGO.\p"
	.string "Lo recuerdas, ¿verdad?\p"
	.string "Soy un PRESIDENTE muy ocupado,\n"
	.string "¡me tengo que ir! ¡Adiós!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: ¡Oh! ¡{PLAYER}{KUN}!\p"
	.string "¡Ah, así que conociste a STEVEN!\n"
	.string "¡Debo darte una recompensa!\p"
	.string "Cuando vuelvas a FUNDA ROCA,\n"
	.string "ven a verme a mi oficina.\p"
	.string "¡Te estaré esperando!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: ¡Oh! ¡{PLAYER}{KUN}!\p"
	.string "¿Sabías que DEVON excavaba el\n"
	.string "TÚNEL RUSTURF?\p"
	.string "Pero paramos la operación para\n"
	.string "proteger a los POKéMON locales.\p"
	.string "Es obvio, la verdad.\p"
	.string "Es más importante que los POKéMON\n"
	.string "vivan en paz que pensar en\l"
	.string "nuestra conveniencia.$"

MatchCall_Text_MrStone5::
	.string "SR. STONE: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Me dijeron en PETALBURG\n"
	.string "que eres hijo de NORMAN!\p"
	.string "¡Con razón eres un ser\n"
	.string "tan capaz!$"

MatchCall_Text_MrStone6::
	.string "SR. STONE: ¿Qué dices?\p"
	.string "¿Luchaste contra tu padre y\n"
	.string "lo derrotaste?\p"
	.string "¡Es asombroso!\p"
	.string "¡No sabía que era amigo de\n"
	.string "alguien tan especial! ¡Jajaja!$"

MatchCall_Text_MrStone7::
	.string "¡Hola!\n"
	.string "Aquí CORPORACIÓN DEVON…\l"
	.string "¡Ah, hola, {PLAYER}!\p"
	.string "El PRESIDENTE estuvo aquí hace\n"
	.string "poco, pero ya salió.\p"
	.string "Él está muy ocupado, pero tú\n"
	.string "pareces igual de ocupado, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…¿Eh? …¿Qué dices?\p"
	.string "GROU… ¿Sí? …¿DON?\p"
	.string "Te escucho mal…\n"
	.string "…no oigo…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…¿Eh? …¿Qué dices?\p"
	.string "Seaflo… ¿Sí? …¿Caver…?\p"
	.string "Te escucho mal…\n"
	.string "…no oigo…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "SR. STONE: {PLAYER}{KUN}! ¡Soy yo!\p"
	.string "Parece que has estado en mil\n"
	.string "cosas, pero yo, por el trabajo,\l"
	.string "¡no sé exactamente en qué!\p"
	.string "Sigue el camino en el que creas\n"
	.string "y camina con firmeza.\p"
	.string "¡Siempre te apoyaré!\n"
	.string "¡Cuídate!$"

MatchCall_Text_MrStone11::
	.string "SR. STONE: … … … … … …\n"
	.string "¿Acaso eres {PLAYER}{KUN}?\p"
	.string "Tu voz suena tan segura que\n"
	.string "¡no te reconocí al momento!\p"
	.string "¡Hm! ¡Debes visitarnos en DEVON\n"
	.string "algún día!$"
