@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "¡Qué lindo!$"

GiddyText_SoDarling::
	.string "¡Qué adorable!$"

GiddyText_SoRelaxed::
	.string "¡Qué relajante!$"

GiddyText_SoSunny::
	.string "¡Qué soleado!$"

GiddyText_SoDesirable::
	.string "¡Qué deseable!$"

GiddyText_SoExciting::
	.string "¡Qué emocionante!$"

GiddyText_SoAmusing::
	.string "¡Qué divertido!$"

GiddyText_SoMagical::
	.string "¡Qué mágico!$"

GiddyText_Is::
	.string " es$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "¿No estás de acuerdo?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Quiero irme de vacaciones.\n"
	.string "¿Conoces algún lugar lindo?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "¡Compré crayones de 120 colores!\n"
	.string "¿No te parece genial?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "¿No sería lindo flotar lejos\n"
	.string "en una nube de burbujas?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Si escribes en la arena de la playa,\n"
	.string "el mar lo borra. Me pone triste.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "¿Cómo será el fondo del mar?\n"
	.string "¡Me encantaría ir solo una vez!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Al ver el sol ponerse, ¿te dan\n"
	.string "ganas de volver a casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Tumbado en la hierba verde...\n"
	.string "¡Oh, es tan agradable!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "¡Las BASES SECRETAS son geniales!\n"
	.string "¿No sientes la emoción?$"
