MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "¿Listo para aprender este movimiento?$"
	.string "Te costará 5.000¥.$"

MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnceFinite:
	.string "Este movimiento solo se puede\n"
	.string "aprender una vez. ¿Está bien?$"

MoveTutor_Text_SwaggerTeach:
	.string "¡Je! ¡Mi POKéMON es el mejor!\n"
	.string "¡Es más genial que cualquier otro!\p"
	.string "Caminaba con mucha actitud\n"
	.string "cuando el PRESIDENTE\l"
	.string "me regañó fuertemente.\p"
	.string "Eso me quitó toda la actitud.\p"
	.string "Si quieres, le enseñaré el movimiento\n"
	.string "ALARDEO a un POKéMON tuyo.$"

MoveTutor_Text_SwaggerDeclined:
	.string "¿Qué, no? ¿Acaso no tienes\n"
	.string "espíritu de lucha?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Muy bien, ¿qué POKéMON quiere\n"
	.string "aprender FARO?$"

MoveTutor_Text_SwaggerTaught:
	.string "De ahora en adelante elogiaré a mi\n"
	.string "POKéMON sin tanta presunción.$"

MoveTutor_Text_RolloutTeach:
	.string "¿Sabías que puedes ir desde aquí\n"
	.string "muy lejos en esa dirección\l"
	.string "sin cambiar el rumbo?\p"
	.string "Incluso yo podría rodar\n"
	.string "por ese camino.\p"
	.string "¿Crees que tu POKéMON también\n"
	.string "querrá rodar?\p"
	.string "Puedo enseñarle el movimiento\n"
	.string "PLACATA si quieres.$"

MoveTutor_Text_RolloutDeclined:
	.string "No tienes por qué ser tímido.\n"
	.string "¡A rodar!$"

MoveTutor_Text_RolloutWhichMon:
	.string "¡Jeje, claro! Sería genial que el\n"
	.string "POKéMON se viera como yo.$"

MoveTutor_Text_RolloutTaught:
	.string "Rodar por el pasto me hace feliz.\n"
	.string "¡Vamos, a rodar!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Hay un movimiento que se vuelve más\n"
	.string "fuerte si se usa varias veces.\p"
	.string "Es de tipo BICHOS y es\n"
	.string "increíblemente genial.\p"
	.string "Se llama Tajo Furia.\n"
	.string "¿Quieres que se lo enseñe a uno?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "No estamos en la misma sintonía.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "¡Súper!\n"
	.string "Dime a qué POKéMON se lo enseño.$"

MoveTutor_Text_FuryCutterTaught:
	.string "¡Me emociona ver si el movimiento\n"
	.string "sigue golpeando sucesivamente!$"

MoveTutor_MimicTeach:
	.string "¡Ah, joven!\p"
	.string "Yo también soy joven, pero imito\n"
	.string "el estilo y habla de los ancianos\l"
	.string "de este pueblo.\p"
	.string "¿Qué dices, joven?\n"
	.string "¿Aceptarías que te enseñe el\l"
	.string "movimiento MIMO?$"

MoveTutor_MimicDeclined:
	.string "¡Oh, no! ¡Quería enseñarle MIMIC\n"
	.string "a tu POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "¡Fwofwo! ¡Y así lo haré!\n"
	.string "Déjame ver el POKéMON\l"
	.string "al que quieres que enseñe.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC es un movimiento profundo.\p"
	.string "¿Podrás ejecutarlo a la perfección\n"
	.string "tan bien como yo...?$"

MoveTutor_Text_MetronomeTeach:
	.string "¡Quiero de todo!\n"
	.string "Pero gasté mi mesada...\p"
	.string "¿No sería genial un hechizo\n"
	.string "que cree dinero al mover\l"
	.string "un dedo?\p"
	.string "Si quieres, le enseño a tu POKéMON\n"
	.string "el movimiento METRONOME.\p"
	.string "No saldrá dinero, pero tu POKéMON\n"
	.string "moverá el dedo. ¿Sí?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Está bien. Estaré aquí si cambias\n"
	.string "de opinión.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "¡Vale! ¡Se lo enseñaré!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_MetronomeTaught:
	.string "Cuando un POKéMON mueve el dedo\n"
	.string "como un METRONOME, pasan cosas\l"
	.string "geniales.\p"
	.string "¿No sería genial que nosotros\n"
	.string "también pudiéramos usarlo?$"

MoveTutor_Text_SleepTalkTeach:
	.string "¡Bah! Mi esposa usa HIDDEN\n"
	.string "POWER para no dormirse.\p"
	.string "Debería tomar una siesta como yo\n"
	.string "y usar SLEEP TALK.\p"
	.string "Puedo enseñar a tu POKéMON a usar\n"
	.string "SLEEP TALK. ¿Te interesa?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, bien, bien. Tú también quieres\n"
	.string "estar despierto con HIDDEN POWER...$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "¡Ah, un niño agradecido!\n"
	.string "¿A qué POKéMON debo enseñarle?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Nunca he logrado hacer bien el\n"
	.string "truco de moneda de mi esposa.\p"
	.string "Sería feliz si lo lograra hacer\n"
	.string "aunque hable DURMIENDO…$"

MoveTutor_Text_SubstituteTeach:
	.string "Cuando viajo por el mundo...\p"
	.string "Pienso que sería lindo que hubiera\n"
	.string "más de un yo mismo\l"
	.string "para vivir todo tipo de vidas.\p"
	.string "Claro que no es posible.\n"
	.string "Jeje…\p"
	.string "¡Ya sé! ¿Te interesa que un\n"
	.string "POKéMON aprenda SUSTITUTO?$"

MoveTutor_Text_SubstituteDeclined:
	.string "¡Oh, no!\p"
	.string "Un POKéMON puede hacer una copia\n"
	.string "de sí mismo con eso, ¿sabes?$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Jeje…\n"
	.string "¿A qué POKéMON quieres que le\l"
	.string "enseñe SUSTITUTO?$"

MoveTutor_Text_SubstituteTaught:
	.string "¡Los humanos debemos disfrutar\n"
	.string "nuestras vidas al máximo!\p"
	.string "¡Espero que tú también lo hagas!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "¡Ya no puedo más!\p"
	.string "¡Es totalmente inútil!\p"
	.string "Soy un ENTRENADOR de tipo LUCHA,\n"
	.string "¡no ganaré en el GIMNASIO DE\l"
	.string "CIUDAD AÑIL aunque lo intente!\p"
	.string "¡Argh! ¡Golpe! ¡Golpe! ¡Golpe!\n"
	.string "¡Golpe! ¡Golpe! ¡Golpe!\p"
	.string "¡Oye, no me mires así!\n"
	.string "¡Solo estoy golpeando el suelo!\p"
	.string "¿O quieres que enseñe a tu\n"
	.string "POKéMON GOLPE DINÁMICO?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "¡Rayos! ¿Te burlas de mí?\n"
	.string "¡Golpe! ¡Golpe! ¡Golpe!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "¿Qué? ¿En serio? ¡Eres muy bueno!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "¡Quiero que ganes en el GIMNASIO de\n"
	.string "ZAFRAN con ese GOLPE DINÁMICO!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Suspiro...\p"
	.string "El LÍDER del GIMNASIO de VERDIANA\n"
	.string "es realmente admirable.\p"
	.string "Pero eso significa que tengo muchas\n"
	.string "rivales por su atención.\p"
	.string "Tiene un atractivo como DOBLE FILO.\n"
	.string "Ni siquiera pude llamar su atención.\p"
	.string "¡Por favor, deja que enseñe a tu\n"
	.string "POKéMON el movimiento DOBLE FILO!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh...\n"
	.string "Tú también me rechazaste...$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Bien, ¿a qué POKéMON debo enseñarle\n"
	.string "DOBLE FILO?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "¡Ya no viviré por amor!\n"
	.string "¡Me volveré fuerte!$"

MoveTutor_Text_ExplosionTeach:
	.string "No pienso quedarme en el campo\n"
	.string "para siempre.\p"
	.string "Ya verás, iré a la ciudad\n"
	.string "y seré un gran éxito.\p"
	.string "En serio, ¡causaré una gran\n"
	.string "EXPLOSIÓN de popularidad!\p"
	.string "Si escuchaste eso, ¡le enseñaré\n"
	.string "EXPLOSIÓN a tu POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "¡Gaah! ¿Me rechazas porque\n"
	.string "vivo en el campo?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "¡Bien! ¡Será una EXPLOSIÓN!\n"
	.string "¿Qué POKéMON quiere explotar?$"

MoveTutor_Text_ExplosionTaught:
	.string "Mucho tiempo enseñé a POKéMON\n"
	.string "a usar EXPLOSIÓN, pero aún no\l"
	.string "he causado mi propia EXPLOSIÓN…\p"
	.string "Quizás es porque, en el fondo,\n"
	.string "prefiero quedarme aquí…$"
