gText_ObtainedTheItem::
	.string "¡Recibiste {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La MOCHILA está llena…$"

gText_PutItemInPocket::
	.string "{PLAYER} guardó {STR_VAR_2}\n"
	.string "en el BOLSILLO {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "¡{PLAYER} halló {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "¡Qué mal!\n"
	.string "La MOCHILA está llena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} guardó {STR_VAR_2}\n"
	.string "en la MOCHILA.$"

gText_ObtainedTheDecor::
	.string "¡Recibiste {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "¡Qué mal! No hay espacio para\n"
	.string "otro {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "El {STR_VAR_2} fue transferido\n"
	.string "a la PC.$"

gText_PutItemInPC::
	.string "{PLAYER} guardó el {STR_VAR_2}\n"
	.string "en la PC porque la mochila está llena.$"

gText_TooBadBagAndPCAreFull::
	.string "¡Qué mal!\n"
	.string "La MOCHILA y la PC están llenas…$"
