Text_BootUpPC:
	.string "{PLAYER} encendió la PC.$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC::
	.string "Accediendo a la PC de alguien.$"

gText_StorageSystemOpened::
	.string "Sistema de Almacenamiento abierto.$"

gText_AccessedPlayersPC::
	.string "Accediendo a la PC de {PLAYER}.$"

gText_AccessedBillsPC::
	.string "Accediendo a la PC de BILL.$"
