gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} fue enviado a la\n"
	.string "PC de ALGUIEN.\p"
	.string "Se colocó en la\n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PkmnTransferredBillsPC::
	.string "{STR_VAR_2} fue enviado a la\n"
	.string "PC de BILL.\p"
	.string "Se colocó en la\n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La BOX “{STR_VAR_3}” de la\n"
	.string "PC de ALGUIEN estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la\n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PkmnTransferredBillsPCBoxFull::
	.string "La BOX “{STR_VAR_3}” de la\n"
	.string "PC de BILL estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la\n"
	.string "BOX “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "¡No hay espacio para POKéMON!\p"
	.string "¡Las BOX de POKéMON están llenas\n"
	.string "y no aceptan más!$"

gText_NicknameThisPokemon::
	.string "¿Quieres darle un mote a\n"
	.string "este {STR_VAR_1}?$"
