gText_WouldYouLikeToRestYourPkmn::
	.string "Hola, bienvenido al\n"
	.string "CENTRO POKéMON.\p"
	.string "Curamos a tus POKéMON\n"
	.string "cansados por completo.\p"
	.string "¿Quieres curar a tus POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Bien, me llevo a tus POKéMON\n"
	.string "unos segundos.$"

gText_RestoredPkmnToFullHealth::
	.string "Gracias por esperar.\p"
	.string "Tus POKéMON han recuperado\n"
	.string "toda su salud.$"

gText_WeHopeToSeeYouAgain::
	.string "¡Esperamos verte pronto!$"

gText_WelcomeCutShort::
	.string "Hola, bienvenido al\n"
	.string "CENTRO POKéMON.\p"
	.string "Curamos a tus POKéMON\n"
	.string "cansados por completo.\p"
	.string "¿Te gustaría...$"

gText_NoticesGoldCard::
	.string "E-esa tarjeta...\n"
	.string "¿No será... la GOLD CARD?!\p"
	.string "¡El color dorado es brillante!\n"
	.string "¡Las cuatro estrellas brillan!\p"
	.string "He visto ENTRENADORES con la\n"
	.string "SILVER CARD, pero, {PLAYER},\l"
	.string "¡eres el primer ENTRENADOR que\l"
	.string "veo con una GOLD CARD!\p"
	.string "¡{PLAYER}, permíteme el honor\n"
	.string "de curar a tus POKéMON!$"

gText_YouWantTheUsual::
	.string "¡Qué alegría verte, {PLAYER}!\n"
	.string "¿Quieres lo de siempre, verdad?$"

gText_IllTakeYourPkmn2::
	.string "Bien, me llevo a tus POKéMON\n"
	.string "unos segundos.$"

gText_ThankYouForWaiting::
	.string "Gracias por esperar.$"

gText_WeHopeToSeeYouAgain2::
	.string "¡Esperamos verte pronto!$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Lo siento, juegas el\n"
    .string "reto del POKéCENTER!\p"
    .string "¡Buena suerte!{PAUSE_UNTIL_PRESS}$"
