gBirchDexRatingText_GoFindMrPokemon::
	.string "PROF.ELM: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Ya hallaste la casa del\n"
	.string "SR. POKéMON? Está en la RUTA 30,\p"
	.string "¡no tiene pérdida!$"

gBirchDexRatingText_Robbery::
	.string "PROF.ELM: ¡{PLAYER}{KUN}!\p"
	.string "¡Ven rápido! ¡Ha pasado\n"
	.string "algo terrible!$"

gBirchDexRatingText_AreYouCurious::
	.string "PROF.ELM: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Tienes curiosidad por saber\n"
	.string "cómo va tu POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "Hm. Aún no has capturado bastantes\n"
	.string "POKéMON para que valga la pena.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm...\p"
	.string "Has visto {STR_VAR_1} POKéMON,\n"
	.string "y has capturado {STR_VAR_2} POKéMON...$"

gBirchDexRatingText_LessThan10::
	.string "Ve más a las zonas de hierba y\n"
	.string "busca POKéMON con más cuidado.$"

gBirchDexRatingText_LessThan20::
	.string "Creo que le estás agarrando el\n"
	.string "truco. Pero ahora será más difícil.$"

gBirchDexRatingText_LessThan30::
	.string "Algunos POKéMON solo aparecen en\n"
	.string "ciertas zonas.\l"
	.string "Debes ser persistente.$"

gBirchDexRatingText_LessThan40::
	.string "Bueno, le falta cantidad,\n"
	.string "pero ahora sí parece una\l"
	.string "POKéDEX real.$"

gBirchDexRatingText_LessThan50::
	.string "Esto va progresando muy bien.\n"
	.string "Sigue esforzándote así.$"

gBirchDexRatingText_LessThan60::
	.string "¿Estás usando alguna CAÑA?\n"
	.string "Hay muchos POKéMON en el mar.$"

gBirchDexRatingText_LessThan70::
	.string "En vez de solo capturar POKéMON,\n"
	.string "¿por qué no los haces evolucionar?$"

gBirchDexRatingText_LessThan80::
	.string "Esta será una POKéDEX\n"
	.string "fantástica.\l"
	.string "Eso es lo que presiento.$"

gBirchDexRatingText_LessThan90::
	.string "Has recolectado tantos...\n"
	.string "¡Tu talento es increíble!$"

gBirchDexRatingText_LessThan100::
	.string "¿Visitaste la ZONA SAFARI?\p"
	.string "Oigo que hay POKéMON que solo\n"
	.string "se capturan allí.$"

gBirchDexRatingText_LessThan110::
	.string "Finalmente llegaste a la\n"
	.string "marca de 100 especies.\p"
	.string "¡Es una POKéDEX impresionante!$"

gBirchDexRatingText_LessThan120::
	.string "Puede haber POKéMON que se pueden\n"
	.string "hallar usando ROCA ROMPE.$"

gBirchDexRatingText_LessThan130::
	.string "Oí de POKéMON que evolucionan\n"
	.string "cuando aman plenamente a sus\l"
	.string "ENTRENADORES.$"

gBirchDexRatingText_LessThan140::
	.string "Oí de POKéMON que evolucionan\n"
	.string "cuando aman plenamente a sus\l"
	.string "ENTRENADORES.$"

gBirchDexRatingText_LessThan150::
	.string "No sabía que había tantas especies\n"
	.string "de POKéMON en la región de JOHTO.\l"
	.string "Es increíble.$"

gBirchDexRatingText_LessThan160::
	.string "A veces, algunos POKéMON aparecen\n"
	.string "en masa como brotes.\p"
	.string "No pierdas oportunidades como\n"
	.string "esas.$"

gBirchDexRatingText_LessThan170::
	.string "Se puede saber mucho sobre los\n"
	.string "POKéMON de JOHTO mirando tu\l"
	.string "POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Diría que ya calificas como un\n"
	.string "PROFESOR POKéMON, ¡y uno muy\l"
	.string "bueno además!$"

gBirchDexRatingText_LessThan190::
	.string "¡Con una POKéDEX tan completa,\n"
	.string "eres un verdadero profesional!$"

gBirchDexRatingText_LessThan200::
	.string "Estás muy cerca de completar\n"
	.string "esta POKéDEX.\l"
	.string "¡Puedo sentirlo en mis huesos!$"

gBirchDexRatingText_DexCompleted::
	.string "¡Felicidades!\n"
	.string "¡Tu POKéDEX está completa!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm...\n"
	.string "A nivel nacional...\p"
	.string "Has visto {STR_VAR_1} POKéMON,\n"
	.string "y has capturado {STR_VAR_2} POKéMON...$"

gBirchDexRatingText_CaughtAllNational::
	.string "Hmhm...\n"
	.string "A nivel nacional...\p"
	.string "Has visto {STR_VAR_1} POKéMON,\n"
	.string "y has capturado {STR_VAR_2} POKéMON...\p"
	.string "¡Es increíble, {PLAYER}!\p"
	.string "¡Completaste la POKéDEX\n"
	.string "NACIONAL! ¡Felicidades!$"
