Questionnaire_Text_FillOut::
	.string "Hay un cuestionario.\n"
	.string "¿Quieres completarlo?$"

Questionnaire_Text_ThankYou::
	.string "Gracias por tomarte el tiempo de\n"
	.string "llenar nuestro cuestionario.\p"
	.string "Tus respuestas servirán de\n"
	.string "referencia futura.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "¡Hola!\n"
	.string "¿Conoces esas palabras?\p"
	.string "Eso significa que sabes sobre el\n"
	.string "REGALO MISTERIOSO.\p"
	.string "¡Desde ahora podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Tras guardar tu partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "¡Hola!\n"
	.string "¿Conoces esas palabras?\p"
	.string "Eso significa que sabes sobre el\n"
	.string "EVENTO MISTERIOSO.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Tras guardar tu partida, podrás\n"
	.string "acceder al EVENTO MISTERIOSO.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Gracias por usar el sistema de\n"
	.string "EVENTO MISTERIOSO.\p"
	.string "Debes ser {PLAYER}.\n"
	.string "Tengo un boleto aquí para ti.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Parece ser para usarlo en el\n"
	.string "puerto de CIUDAD VERAZUEL.\p"
	.string "¿Por qué no lo pruebas para ver\n"
	.string "de qué se trata?$"
