	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOff::
	.string "GUARDANDO...\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "¡ADVERTENCIA!\p"
	.string "Ya existe un archivo de partida\n"
	.string "diferente guardado.\p"
	.string "Si guardas ahora, la aventura\n"
	.string "del otro archivo, incluyendo\l"
	.string "objetos y POKéMON, se perderá.\p"
	.string "¿Seguro que quieres guardar y\n"
	.string "sobrescribir la otra partida?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Por favor, cambia la\n"
	.string "memoria de respaldo.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO...\n"
	.string "NO APAGUES LA CONSOLA.$"
