SecretBase_Text_Trainer0Intro:
	.string "¿Ya tienes una BASE SECRETA?\p"
	.string "Busqué por todo lado antes de\n"
	.string "elegir este lugar.\p"
	.string "Ya que estás aquí, ¿quieres\n"
	.string "una batalla?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "¡Está bien!\n"
	.string "¡Aquí vamos!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "¿Eh?\n"
	.string "Oh, ahora no puedes...$"

SecretBase_Text_Trainer0Defeated::
	.string "¡Aaargh! ¡Eres muy fuerte!\n"
	.string "¡No digas que perdí, por favor!$"

SecretBase_Text_Trainer0PostBattle:
	.string "¿Qué te parece mi BASE SECRETA?\n"
	.string "Vuelve a visitarme mañana.$"

SecretBase_Text_Trainer0PreChampion:
	.string "¿Ya tienes una BASE SECRETA?\p"
	.string "Busqué por todo lado antes de\n"
	.string "elegir este lugar.\p"
	.string "¡Siéntete libre de quedar aquí!$"

SecretBase_Text_Trainer5Intro:
	.string "Hay muchos lugares donde\n"
	.string "puedes hacer una BASE SECRETA.\p"
	.string "Pero este es mi favorito.\n"
	.string "¿No crees que es lindo?\p"
	.string "Oh, ¿quieres una batalla?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "¡Bien, allá voy!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh...\n"
	.string "Ahora no puedes, ¿está bien?$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmmm... Es nuestra pérdida...\n"
	.string "¡Pero no se lo digas a nadie!\l"
	.string "¡Es un secreto confidencial!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Si vuelves por esta zona,\n"
	.string "espero que me visites.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Hay muchos lugares donde puedes\n"
	.string "hacer una BASE SECRETA.\p"
	.string "Pero este es mi favorito.\n"
	.string "¿No crees que es lindo?$"

SecretBase_Text_Trainer1Intro:
	.string "Este lugar es muy popular.\n"
	.string "Siempre está ocupado.\p"
	.string "¡Oh! ¿Tú también querías\n"
	.string "quedarte con este sitio?\p"
	.string "Te propongo algo: será tuyo\n"
	.string "si logras vencerme.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "¡Bien!\n"
	.string "¡Defenderé mi BASE SECRETA!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "¿Eh? ¿En serio?\n"
	.string "¿No te interesa este lugar?$"

SecretBase_Text_Trainer1Defeated::
	.string "¡No puedo seguir!\n"
	.string "¡Me rindo!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Bien, cuando me mude un día,\n"
	.string "¡este lugar será tuyo!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Este sitio es muy popular.\n"
	.string "Siempre está ocupado.\p"
	.string "Esperé mucho a que se liberara.\n"
	.string "¡Al fin pude usarlo!$"

SecretBase_Text_Trainer6Intro:
	.string "Bienvenido a mi LAB. POKéMON.\p"
	.string "Investigo las batallas en\n"
	.string "secreto.\p"
	.string "¿Quieres ver qué tan fuerte soy?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "¡Voy a darlo todo!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "¡Entonces será en otro momento!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm... Aún debo aprender mucho.\n"
	.string "Tengo que estudiar más.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Gracias por luchar conmigo.\n"
	.string "Por favor, vuelve mañana.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Bienvenido a mi LAB. POKéMON.\p"
	.string "Investigo las batallas en\n"
	.string "secreto.$"

SecretBase_Text_Trainer2Intro:
	.string "Una mansión es linda, pero prefiero\n"
	.string "este tipo de lugar.\p"
	.string "Me gusta porque todo tipo de gente\n"
	.string "viene a visitarme.\p"
	.string "¿Qué tal una batalla?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "¡Así se hace!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "¡Avísame cuando estés listo!$"

SecretBase_Text_Trainer2Defeated::
	.string "¡Ay! ¡Me vencieron!\n"
	.string "¡Pero luchar sigue siendo divertido!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Bueno, debo ir a comprar algunos\n"
	.string "muebles y adornos.\p"
	.string "Quiero que mi SECRET BASE sea un lugar\n"
	.string "que otros disfruten.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Una mansión es linda, pero prefiero\n"
	.string "este tipo de lugar.\p"
	.string "Me gusta porque todo tipo de gente\n"
	.string "viene a visitarme.$"

SecretBase_Text_Trainer7Intro:
	.string "Me encanta comprar adornos\n"
	.string "y muebles.\p"
	.string "También amo criar POKéMON\n"
	.string "por igual.\p"
	.string "¿Serías tan amable de luchar\n"
	.string "contra mis POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Gracias.\n"
	.string "¿Empezamos?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Qué decepción…$"

SecretBase_Text_Trainer7Defeated::
	.string "Me rindo…$"

SecretBase_Text_Trainer7PostBattle:
	.string "¡Fue muy divertido!\n"
	.string "Iré a disfrutar las compras ahora.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Me encanta comprar decoraciones\n"
	.string "y muebles.\p"
	.string "También amo criar POKéMON por\n"
	.string "igual.$"

SecretBase_Text_Trainer3Intro:
	.string "Algunos hacen sus BASES SECRETAS en\n"
	.string "sitios difíciles de hallar.\l"
	.string "¿Querrán pasar desapercibidos?\p"
	.string "Pero ya que me hallaste, ¿qué tal\n"
	.string "una batalla?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "¡No caeré tan fácilmente!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… ¿Quizás estés cansado de buscar\n"
	.string "este lugar?$"

SecretBase_Text_Trainer3Defeated::
	.string "He perdido…$"

SecretBase_Text_Trainer3PostBattle:
	.string "¿Dónde está tu BASE SECRETA?\n"
	.string "Debería ir a visitarte allá.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Algunos hacen sus BASES SECRETAS en\n"
	.string "lugares difíciles de hallar.\l"
	.string "¿Querrán pasar desapercibidos?$"

SecretBase_Text_Trainer8Intro:
	.string "Me dijeron que hay varias formas de\n"
	.string "conseguir decoraciones.\p"
	.string "¡Hagamos una carrera para ver quién\n"
	.string "consigue mejores muebles!\p"
	.string "Mientras tanto, ¿quieres luchar?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Esta es mi BASE SECRETA.\n"
	.string "¡No puedo perder!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Lucharé contigo cuando quieras.$"

SecretBase_Text_Trainer8Defeated::
	.string "¿Eh?\n"
	.string "¿Acabo de perder?$"

SecretBase_Text_Trainer8PostBattle:
	.string "No perderé recolectando adornos.\n"
	.string "¡Vuelve a visitarme!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Me dijeron que hay varias formas de\n"
	.string "conseguir decoraciones.\p"
	.string "¡Hagamos una carrera para ver quién\n"
	.string "consigue mejores muebles!$"

SecretBase_Text_Trainer4Intro:
	.string "Hallé un lugar que me gustó y lo puse\n"
	.string "con mis adornos favoritos.\p"
	.string "Entreno a mi POKéMON favorito y me\n"
	.string "hago fuerte con él.\p"
	.string "Eso es lo que hago.\n"
	.string "¿Quieres luchar conmigo?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "¡Demuéstrame de qué estás hecho!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Supongo que hay veces que no\n"
	.string "tienes ganas.$"

SecretBase_Text_Trainer4Defeated::
	.string "Ya sé exactamente de qué estás hecho.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Ambos podemos ser más fuertes.\n"
	.string "¡Sigamos esforzándonos!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Hallé un lugar que me gustó y lo puse\n"
	.string "con mis adornos favoritos.\p"
	.string "Entreno a mi POKéMON favorito y me\n"
	.string "hago fuerte con él.\p"
	.string "Cada día es un gran día.$"

SecretBase_Text_Trainer9Intro:
	.string "Puedes saber mucho del gusto\n"
	.string "y sentido de la gente por sus\l"
	.string "decoraciones y cómo las\l"
	.string "acomodan.\p"
	.string "¿Qué te parece mi gusto?\n"
	.string "¿Te has quedado sin palabras?\p"
	.string "¿Quieres ver mi gusto al luchar?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "¡No me contendré!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Estaré feliz de mostrar mi estilo\n"
	.string "cuando quieras.$"

SecretBase_Text_Trainer9Defeated::
	.string "¡Tienes un talento supremo!\n"
	.string "Tu poder parece no tener límites…$"

SecretBase_Text_Trainer9PostBattle:
	.string "¿Qué te pareció mi estilo?\n"
	.string "¡Seguiré puliéndolo!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Se aprende mucho del gusto\n"
	.string "y sentido de la gente por sus\l"
	.string "decoraciones y cómo las\l"
	.string "acomodan.\p"
	.string "¿Qué te parece mi gusto?\n"
	.string "¿Te quedaste sin palabras?$"
