ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "¿Piensas entrar hasta el fondo?\n"
	.string "en ese lugar?\p"
	.string "¿Me traerías algo de SAL MARINA\n"
	.string "y CONCHAS MARINAS?\p"
	.string "Haré algo bueno si me traes los\n"
	.string "ingredientes.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si traes cuatro de SAL MARINA\n"
	.string "y cuatro de CONCHAS MARINAS,\l"
	.string "haré un CAMPANA CONCHA…\p"
	.string "Puedes conseguir esos elementos\n"
	.string "cada día.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "¡Oh, mira! ¡SAL Y CONCHAS!\n"
	.string "¡Y hay bastantes también!\p"
	.string "¿Quieres que te haga un\n"
	.string "CAMPANA CONCHA con ellas?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "¡Muy bien! Te haré una\n"
	.string "CAMPANA CONCHA ahora mismo.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "¡Listo! ¡Ya está!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Que un POKéMON lo lleve puesto.\n"
	.string "Seguro que le encantará.\p"
	.string "Vaya, el sonido de la CAMPANA\n"
	.string "CONCHA… ¡es sublime!\p"
	.string "Trae los ingredientes cada día\n"
	.string "y te haré más.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh... ¿Es así...\n"
	.string "Yo quería hacer una CAMPANA CONCHA...$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "No tienes espacio en tu BOLSA\n"
	.string "para que yo lo fabrique.\p"
	.string "Haz espacio y vuelve por tu\n"
	.string "CAMPANA CONCHA.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Aquí había SAL MARINA.\n"
	.string "Pero ahora ya no queda nada.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Había una CONCHA DE CORAL aquí.\n"
	.string "Pero ahora ya no hay nada.$"
