Route102_Text_CalvinIntro:
	.string "Si tienes POKéMON contigo,\n"
	.string "¡eres un ENTRENADOR POKéMON oficial!\l"
	.string "¡No puedes rechazar mi reto!$"

Route102_Text_CalvinDefeated:
	.string "¡Arg, perdí...\n"
	.string "Debí entrenar más a los míos...$"

Route102_Text_CalvinPostBattle:
	.string "Escucha. Si eres tan fuerte,\n"
	.string "¡debiste decírmelo antes!$"

Route102_Text_CalvinRegister:
	.string "He trabajado duro desde que\n"
	.string "te vi la primera vez.\p"
	.string "Quiero luchar contigo, ¿me\n"
	.string "registras en tu POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "Quiero luchar contigo, ¿me\n"
	.string "registras en tu POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Desde que perdí, entrené a mis\n"
	.string "POKéMON desesperadamente.\l"
	.string "¡No puedes rechazar mi reto!$"

Route102_Text_CalvinRematchDefeated:
	.string "¡Arg, perdí...\n"
	.string "¿Mi método de entrenamiento falla?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si tú te vuelves más fuerte,\n"
	.string "yo también lo haré.$"

Route102_Text_AllenIntro:
	.string "¿Acabas de ser ENTRENADOR?\n"
	.string "¡Ambos somos novatos!$"

Route102_Text_AllenDefeated:
	.string "Te llamé porque pensé que\n"
	.string "podría ganarte…$"

Route102_Text_AllenPostBattle:
	.string "Aún no he ganado ni una vez…\n"
	.string "¡Ojalá gane pronto…!$"

Route102_Text_RickIntro:
	.string "¡Jaja! ¡Cruzamos miradas!\n"
	.string "¡Lucharé con mis BUG POKéMON!$"

Route102_Text_RickDefeated:
	.string "¡Ay! ¡Me derrotaron!$"

Route102_Text_RickPostBattle:
	.string "Si miras a un ENTRENADOR,\n"
	.string "¡debes retarlo! ¡Es la regla!$"

Route102_Text_TianaIntro:
	.string "Seguiré ganando para ser el\n"
	.string "mejor ENTRENADOR.\p"
	.string "¡Ayúdame a mejorar!$"

Route102_Text_TianaDefeated:
	.string "Al final, yo te ayudé a mejorar…$"

Route102_Text_TianaPostBattle:
	.string "Para seguir ganando, veo que\n"
	.string "debo capturar más POKéMON.$"

Route103_Text_DaisyIntro:
	.string "¿Sentiste la atracción de nuestra\n"
	.string "fragancia relajante?$"

Route103_Text_DaisyDefeated:
	.string "Nuestro aroma no te confundió...$"

Route103_Text_DaisyPostBattle:
	.string "La aromaterapia es una cura mental\n"
	.string "que usa fragancias.$"

Route103_Text_AmyIntro:
	.string "AMY: Soy AMY.\n"
	.string "Y ella es mi hermana LIV.\l"
	.string "¡Luchamos juntas!$"

Route103_Text_AmyDefeated:
	.string "AMY: Oh no, perdimos.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Debes pensar en muchas cosas\n"
	.string "al luchar contra dos ENTRENADORES.\l"
	.string "$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Oh no, solo tienes un\n"
	.string "POKéMON contigo.\l"
	.string "No puedes luchar así.$"

Route103_Text_LivIntro:
	.string "LIV: Luchamos juntas como un solo\n"
	.string "equipo.$"

Route103_Text_LivDefeated:
	.string "LIV: Oh, perdimos, hermana mayor…$"

Route103_Text_LivPostBattle:
	.string "LIV: Trabajamos perfecto juntas,\n"
	.string "mi hermana y yo…\p"
	.string "Pero aun así perdimos…$"

Route103_Text_AmyLivRegister:
	.string "LIV: De verdad, somos mejores...\n"
	.string "¡Es cierto! ¡Te lo mostraremos!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Si quieres luchar con nosotras,\n"
	.string "¡debes tener dos POKéMON!\l"
	.string "¡Si no, no es justo!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Soy AMY.\n"
	.string "Y ella es mi hermanita LIV.\l"
	.string "¡Luchamos juntas!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: ¡Ay, no!\n"
	.string "No pudimos ganar otra vez…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Debes pensar en muchas cosas\n"
	.string "al luchar contra dos\l"
	.string "ENTRENADORES.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Oh no, solo tienes un\n"
	.string "POKéMON contigo.\l"
	.string "No puedes luchar así.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Luchamos juntas como un\n"
	.string "solo equipo.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Aww, perdimos otra vez...\n"
	.string "Hermana mayor...$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Trabajamos perfecto juntas,\n"
	.string "mi hermana y yo...\p"
	.string "¿Pero por qué perdimos otra vez?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: ¡Si quieres luchar, debes\n"
	.string "tener dos POKéMON!\l"
	.string "¡No es justo si no los tienes!$"

Route103_Text_AndrewIntro:
	.string "¡Gah! ¡Mi sedal se enredó todo!\n"
	.string "¡Me estoy frustrando mucho!\l"
	.string "¡Ya basta! ¡Lucha conmigo!$"

Route103_Text_AndrewDefeated:
	.string "¡Gah! ¡Lo perdí!\n"
	.string "¡Ahora estoy más molesto!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, sigo hirviendo de rabia...\n"
	.string "Grrrrr...$"

Route103_Text_MiguelIntro:
	.string "¡Mi POKéMON es adorable!\n"
	.string "¡No seas tímido, te lo mostraré!$"

Route103_Text_MiguelDefeated:
	.string "¡Cielos!\n"
	.string "¡Mi querido POKéMON!$"

Route103_Text_MiguelPostBattle:
	.string "¡Mi lindo POKéMON se ve adorable\n"
	.string "aunque esté debilitado!$"

Route103_Text_MiguelRegister:
	.string "¡Haré que vuelvas a salir y a ver\n"
	.string "a mi adorable POKéMON!$"

Route103_Text_MiguelRematchIntro:
	.string "¡Hola! ¡Mi adorable POKéMON\n"
	.string "se ha vuelto aún más lindo!$"

Route103_Text_MiguelRematchDefeated:
	.string "¡Oh!\n"
	.string "¡Mi querido POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Cuanto más tiempo paso con él,\n"
	.string "más adorable se vuelve mi POKéMON.$"

Route103_Text_PeteIntro:
	.string "A esta distancia...\n"
	.string "¡Deberías simplemente nadar!$"

Route103_Text_PeteDefeated:
	.string "¡Oh, eso es genial!$"

Route103_Text_PetePostBattle:
	.string "Oh, ya entiendo de dónde\n"
	.string "vienes.\p"
	.string "Si tuviera un POKéMON así,\n"
	.string "¡yo también querría SURFear!$"

Route103_Text_IsabelleIntro:
	.string "¡Mira por dónde vas!\n"
	.string "¡Vamos a chocar!$"

Route103_Text_IsabelleDefeated:
	.string "Ugh…$"

Route103_Text_IsabellePostBattle:
	.string "Nado mal, así que practicaba…\n"
	.string "Perdón por casi chocar contigo.$"

Route103_Text_RhettIntro:
	.string "¡Vaya!\n"
	.string "¿Cómo entraste en un sitio así?$"

Route103_Text_RhettDefeated:
	.string "¡Vaya!\n"
	.string "¡Este chico es increíble!$"

Route103_Text_RhettPostBattle:
	.string "¿Te gustan los lugares estrechos\n"
	.string "como este?$"

Route103_Text_MarcosIntro:
	.string "¿Te atrajo el llanto de mi guitarra?$"

Route103_Text_MarcosDefeated:
	.string "Mi show unipersonal se arruinó…$"

Route103_Text_MarcosPostBattle:
	.string "Tocaba mi guitarra donde no había\n"
	.string "mucha gente, pero llegaron muchos\l"
	.string "fans.\p"
	.string "Je, tal vez debería ser profesional.$"

Route104_Text_GinaIntro:
	.string "GINA: ¡Bien, luchemos con nuestros\n"
	.string "POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: ¡Me molesta perder!$"

Route104_Text_GinaPostBattle:
	.string "GINA: ¡Eres fuerte!\n"
	.string "¡Tenemos que entrenar mucho más!$"

Route104_Text_GinaNotEnoughMons:
	.string "¿Oh? ¿Solo un POKéMON?\n"
	.string "Entonces no lucharemos contigo.\p"
	.string "Si hay solo un POKéMON, estará\n"
	.string "solo. Eso no es agradable.$"

Route104_Text_MiaIntro:
	.string "MIA: Somos gemelas, así que luchamos\n"
	.string "con POKéMON juntas.$"

Route104_Text_MiaDefeat:
	.string "MIA: Peleamos juntos, pero\n"
	.string "ambos perdimos…$"

Route104_Text_MiaPostBattle:
	.string "MIA: Entrenaremos más a nuestros\n"
	.string "POKéMON para ser fuertes como tú.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: ¿Quieres luchar con nosotras?\p"
	.string "No puedes si no tienes dos\n"
	.string "POKéMON contigo.\l"
	.string "¡Somos muy fuertes para ti!$"

Route104_Text_IvanIntro:
	.string "¿Por qué mantener el secreto?\n"
	.string "¡Soy la experta en POKéMON AGUA!\p"
	.string "¿Eh?\n"
	.string "¿No me conoces?$"

Route104_Text_IvanDefeat:
	.string "Pensé que no era tan mala, si se\n"
	.string "puede decir, pero creo que no…$"

Route104_Text_IvanPostBattle:
	.string "Me obsesioné con la pesca.\n"
	.string "Olvidé que debía criar mis POKéMON…$"

Route104_Text_BillyIntro:
	.string "¡Dejar huellas en la arena es\n"
	.string "muy divertido!$"

Route104_Text_BillyDefeat:
	.string "¡Waah! ¡Tengo arena en mis tenis!\n"
	.string "¡Están todos rasposos!$"

Route104_Text_BillyPostBattle:
	.string "Quiero dejar mis huellas en la\n"
	.string "arena, pero desaparecen\l"
	.string "muy rápido…$"

Route104_Text_HaleyIntro:
	.string "¿Debería…\n"
	.string "O no debería?\p"
	.string "¡Está bien, lucharé!$"

Route104_Text_HaleyDefeat:
	.string "No debí haber luchado…$"

Route104_Text_HaleyPostBattle:
	.string "Si tienes que decidir y dejas que\n"
	.string "otro elija por ti,\l"
	.string "te arrepentirás, sin importar\l"
	.string "el resultado.$"

Route104_Text_HaleyRegister1:
	.string "Eres fuerte, ¿te registro en mi\n"
	.string "POKéNAV?\l"
	.string "Tal vez no deba…\p"
	.string "¡Está bien, te registraré!$"

Route104_Text_HaleyRegister2:
	.string "Eres fuerte, ¿te registro en mi\n"
	.string "POKéNAV?\l"
	.string "Tal vez no deba…\p"
	.string "¡Está bien, te registraré!$"

Route104_Text_HaleyRematchIntro:
	.string "¡Vamos, lucha conmigo!$"

Route104_Text_HaleyRematchDefeat:
	.string "Oh…\n"
	.string "Pensé que podría ganar…$"

Route104_Text_HaleyPostRematch:
	.string "Decidí luchar, así que\n"
	.string "acepto esta derrota con honor.\p"
	.string "¡Aun así, me molesta perder!$"

Route104_Text_WinstonIntro:
	.string "Oh, claro, acepto tu desafío.\n"
	.string "Tengo mucho dinero.$"

Route104_Text_WinstonDefeat:
	.string "¿Por qué no pude ganar?$"

Route104_Text_WinstonPostBattle:
	.string "Hay cosas que el dinero no compra.\n"
	.string "Eso son los POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "¿Hm?\n"
	.string "Ah, conseguiste un POKéNAV.\p"
	.string "Te registraré con gusto.\n"
	.string "Después de todo, tengo dinero.$"

Route104_Text_WinstonRegister2:
	.string "¿Hm?\n"
	.string "Ah, conseguiste un POKéNAV.\p"
	.string "Te registraré con gusto.\n"
	.string "Después de todo, tengo dinero.$"

Route104_Text_WinstonRematchIntro:
	.string "Tras perder contigo, aprendí mucho\n"
	.string "sobre los POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "¿Perdí otra vez?\n"
	.string "¿Por qué no pude ganar?$"

Route104_Text_WinstonPostRematch:
	.string "Soy fabulosamente rico, pero no\n"
	.string "gano en POKéMON...\p"
	.string "Es tan profundo el mundo POKéMON...$"

Route104_Text_CindyIntro:
	.string "Debió ser el destino reunirnos.\n"
	.string "¿Me darías una batalla?$"

Route104_Text_CindyDefeat:
	.string "¡Cielos!$"

Route104_Text_CindyPostBattle:
	.string "El “hola” es el inicio del “adiós”.\n"
	.string "Espero que nos veamos pronto.$"

Route104_Text_CindyRegister1:
	.string "Hola, nos vemos otra vez.\p"
	.string "Parece que nos atraemos. Vamos a\n"
	.string "registrarnos en los POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "Debemos conmemorar que parecemos\n"
	.string "atraernos el uno al otro.\p"
	.string "Registrémonos mutuamente en los\n"
	.string "POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Hola, nos vemos otra vez.\n"
	.string "¿Me darías una batalla?$"

Route104_Text_CindyRematchDefeat:
	.string "Cielos...\n"
	.string "Hice lo mejor que pude...$"

Route104_Text_CindyPostRematch:
	.string "“Hola” es el inicio de un “adiós”.\n"
	.string "Espero que nos veamos pronto.$"

Route104_Text_DarianIntro:
	.string "¡Pesqué un POKéMON fuerte!\p"
	.string "¡Tiene una cualidad mágica!\n"
	.string "¡Se ve muy fuerte, sí que lo está!$"

Route104_Text_DarianDefeat:
	.string "Pero qué…$"

Route104_Text_DarianPostBattle:
	.string "Oye, MAGIKARP, no haces honor\n"
	.string "a tu nombre, ¿verdad?$"

Route105_Text_FosterIntro:
	.string "Se supone que hay una roca mística\n"
	.string "por aquí.\l"
	.string "¿Sabes algo sobre ella?$"

Route105_Text_FosterDefeated:
	.string "Pensé demasiado en esa roca\n"
	.string "mientras mi POKéMON seguía débil…$"

Route105_Text_FosterPostBattle:
	.string "Puedo pasar horas mirando una roca\n"
	.string "linda sin aburrirme.$"

Route105_Text_LuisIntro:
	.string "¡Uff! Pensé que un niño se ahogaba\n"
	.string "cuando te vi.\p"
	.string "Pareces estar bien, ¿qué dices de\n"
	.string "una batalla?$"

Route105_Text_LuisDefeated:
	.string "Glub... Glub...$"

Route105_Text_LuisPostBattle:
	.string "Si te ahogas, la señal es mover\n"
	.string "un brazo hacia la playa.$"

Route105_Text_DominikIntro:
	.string "Nadar en el mar azul profundo...\n"
	.string "¡Es lo mejor del mundo!$"

Route105_Text_DominikDefeated:
	.string "Perdí...\n"
	.string "Ahora me siento triste...$"

Route105_Text_DominikPostBattle:
	.string "¿Por qué el mar es azul?\p"
	.string "Lo aprendí en el MUSEO de\n"
	.string "PORTALUAR, pero lo olvidé.$"

Route105_Text_BeverlyIntro:
	.string "Me siento más ligero en el agua.\n"
	.string "¡Es como si hubiera adelgazado!$"

Route105_Text_BeverlyDefeated:
	.string "Estoy flotando...$"

Route105_Text_PostBattle:
	.string "Tu peso se reduce a solo una\n"
	.string "décima parte en el agua.\p"
	.string "Eso me haría...\n"
	.string "¡Ups! ¡No te diré mi peso!$"

Route105_Text_ImaniIntro:
	.string "El cielo azul, tan azul...\n"
	.string "El vasto mar...\l"
	.string "Es tan tranquilo...$"

Route105_Text_ImaniDefeated:
	.string "¡Perdí mientras descansaba!$"

Route105_Text_ImaniPostBattle:
	.string "Quiero que me digan que soy alguien\n"
	.string "con quien relajarse. Jiji.$"

Route105_Text_AndresIntro:
	.string "Estoy convencida de que el mar nos\n"
	.string "guarda secretos.$"

Route105_Text_AndresDefeated:
	.string "Sí...\n"
	.string "No soy buena batallando...$"

Route105_Text_AndresPostBattle:
	.string "Seguro hay muchos secretos por\n"
	.string "descubrir en los mares del mundo.\p"
	.string "¡Pienso hallarlos todos!$"

Route105_Text_AndresRegister:
	.string "¿Eh? Soy muy débil, ¿pero quieres\n"
	.string "registrarme en tu POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "Ya te dije que soy débil...\n"
	.string "¿Seguro que quieres hacer esto?$"

Route105_Text_AndresRematchDefeated:
	.string "Sí...\n"
	.string "No creí que pudiera ganar.$"

Route105_Text_AndresRematchPostBattle:
	.string "Seré débil luchando, pero mi\n"
	.string "ganas de explorar son únicas.\p"
	.string "¡Viajaré por todos los mares\n"
	.string "del mundo!$"

Route105_Text_JosueIntro:
	.string "Estoy agotado de nadar.\n"
	.string "No estoy acostumbrado.\p"
	.string "¡Quiero luchar para distraerme!$"

Route105_Text_JosueDefeated:
	.string "Perdí por luchar en el mar.$"

Route105_Text_JosuePostBattle:
	.string "Sí, para mí el cielo es un lugar\n"
	.string "mejor que el mar.$"

Route106_Text_ElliotIntro:
	.string "¿Qué prefieres, pescar en el\n"
	.string "mar o en un arroyo?$"

Route106_Text_ElliotDefeated:
	.string "¡Como en la pesca profunda, perdí\n"
	.string "espectacularmente!$"

Route106_Text_ElliotPostBattle:
	.string "Pescar es lo mejor, sea en el\n"
	.string "mar o en un arroyo.\l"
	.string "Estás de acuerdo, ¿verdad?$"

Route106_Text_ElliotRegister:
	.string "Pescar es genial, pero luchar también.\n"
	.string "¿Podemos vernos otra vez?$"

Route106_Text_ElliotRematchIntro:
	.string "Atrapé muchos POKéMON pescando.\n"
	.string "¡Te mostraré una gran batalla!$"

Route106_Text_ElliotRematchDefeated:
	.string "¡Perdí otra vez espectacularmente!$"

Route106_Text_ElliotRematchPostBattle:
	.string "¡Ganes o pierdas, los POKéMON son lo\n"
	.string "máximo! ¿Estás de acuerdo?$"

Route106_Text_NedIntro:
	.string "¿Qué hace la gente si necesita ir\n"
	.string "al baño?\p"
	.string "¿Y si mi CAÑA atrapa uno grande\n"
	.string "mientras voy al baño? No puedo ir…$"

Route106_Text_NedDefeated:
	.string "Perdí porque estoy intentando no ir\n"
	.string "al baño…$"

Route106_Text_NedPostBattle:
	.string "¡Oh, no! ¡Tengo el presentimiento de\n"
	.string "que pescaré uno grande!$"

Route106_Text_DouglasIntro:
	.string "¡Jajaja! Soy mal corredor, ¡pero en\n"
	.string "el agua no me atraparás!$"

Route106_Text_DouglasDefeated:
	.string "¡Me rindo!$"

Route106_Text_DouglasPostBattle:
	.string "No perdería en una carrera...$"

Route106_Text_KylaIntro:
	.string "El mar es mi patio. ¡No me voy a\n"
	.string "contener solo porque eres un niño!$"

Route106_Text_KylaDefeated:
	.string "¿Por casualidad te contuviste\n"
	.string "conmigo?$"

Route106_Text_KylaPostBattle:
	.string "Dejarse llevar por las olas...\n"
	.string "¡Me encanta! ¿Por qué no lo intentas?$"

Route107_Text_DarrinIntro:
	.string "Bostezo...\p"
	.string "Debo haberme quedado dormido mientras\n"
	.string "flotaba en las olas.$"

Route107_Text_DarrinDefeated:
	.string "Ajaja, perdí...\n"
	.string "Creo que tomaré una siesta...$"

Route107_Text_DarrinPostBattle:
	.string "Flotar y que las olas me mezan\n"
	.string "es como dormir en una cama\l"
	.string "suave y cómoda.$"

Route107_Text_TonyIntro:
	.string "El mar es como mi patio trasero.\n"
	.string "¡Luchemos!$"

Route107_Text_TonyDefeated:
	.string "Perdí en mi propio terreno...\n"
	.string "¡Estoy en shock!$"

Route107_Text_TonyPostBattle:
	.string "Nado en el mar con el corazón lleno\n"
	.string "de sueños...\p"
	.string "¡Es una canción!\n"
	.string "En fin, seguiré nadando.$"

Route107_Text_TonyRegister:
	.string "¡Me has dejado helado!\n"
	.string "Bueno, para que no me olvides...$"

Route107_Text_TonyRematchIntro:
	.string "¡Nadando en el inmenso mar,\n"
	.string "mi POKéMON se ha vuelto más fuerte!$"

Route107_Text_TonyRematchDefeated:
	.string "¡Qué impacto!\p"
	.string "Mi POKéMON se hizo más fuerte, ¡pero\n"
	.string "yo sigo siendo un mal ENTRENADOR!$"

Route107_Text_TonyRematchPostBattle:
	.string "Lo que aprendes en batalla te hace\n"
	.string "un ENTRENADOR más fuerte.\l"
	.string "Las olas me enseñaron eso.$"

Route107_Text_DeniseIntro:
	.string "¿Conoces un pueblito llamado\n"
	.string "DEWFORD?$"

Route107_Text_DeniseDefeated:
	.string "¡Odio esto!$"

Route107_Text_DenisePostBattle:
	.string "Un dicho raro se ha vuelto muy\n"
	.string "popular en EL SALÓN DE ROCA.$"

Route107_Text_BethIntro:
	.string "¿Querías luchar conmigo?\n"
	.string "¡Claro, acepto el reto!$"

Route107_Text_BethDefeated:
	.string "No fui lo suficiente para ti.$"

Route107_Text_BethPostBattle:
	.string "Creo que seguirás mejorando.\n"
	.string "¡Yo también me esforzaré!$"

Route107_Text_LisaIntro:
	.string "LISA: ¡Te retamos como hermana\n"
	.string "y hermano!$"

Route107_Text_LisaDefeated:
	.string "LISA: Increíble.\n"
	.string "Estás en otro nivel de fuerza.$"

Route107_Text_LisaPostBattle:
	.string "LISA: ¿Tienes amigos que quieran\n"
	.string "ir a la playa contigo?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Si quieres luchar con nosotros,\n"
	.string "trae más POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Siempre luchamos con POKéMON,\n"
	.string "mi hermana y yo.\p"
	.string "Siempre pierdo, ¡pero te ganaremos\n"
	.string "2 contra 2!$"

Route107_Text_RayDefeated:
	.string "RAY: ¡Vaya, tienes un nivel más alto\n"
	.string "que nosotros!$"

Route107_Text_RayPostBattle:
	.string "RAY: Mi hermana me dio mi POKéMON.\n"
	.string "Lo crié, ¡y ahora es mi gran\l"
	.string "compañero!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Si quieres luchar con nosotros,\n"
	.string "¡ve a traer más POKéMON!$"

Route107_Text_CamronIntro:
	.string "Estoy en medio de un triatlón,\n"
	.string "¡pero no estoy nada cansado!$"

Route107_Text_CamronDefeated:
	.string "Eso me agotó...$"

Route107_Text_CamronPostBattle:
	.string "Aún me quedan la natación y el trote\n"
	.string "después de esto.\p"
	.string "¿Estaré bien?$"

Route108_Text_JeromeIntro:
	.string "¡Mi sueño es nadar los siete\n"
	.string "mares del mundo!$"

Route108_Text_JeromeDefeated:
	.string "No podré nadar los siete mares\n"
	.string "así…$"

Route108_Text_JeromePostBattle:
	.string "¡Jugar con POKéMON marinos es un\n"
	.string "placer al nadar!$"

Route108_Text_MatthewIntro:
	.string "¡Hola! ¿Tú también vas al\n"
	.string "BARCO ABANDONADO?$"

Route108_Text_MatthewDefeated:
	.string "¡Me hundo!\n"
	.string "Glub... Glub...$"

Route108_Text_MatthewPostBattle:
	.string "Hay gente que incluso entra en\n"
	.string "ese BARCO ABANDONADO.$"

Route108_Text_TaraIntro:
	.string "Mi novio mentiroso me dijo que\n"
	.string "me veo genial en bikini…$"

Route108_Text_TaraDefeated:
	.string "¡Ay, qué mal!$"

Route108_Text_TaraPostBattle:
	.string "Aunque sea mentira, amo que me digan\n"
	.string "que me veo genial...\l"
	.string "Somos complejas las chicas...$"

Route108_Text_MissyIntro:
	.string "¡Amo el mar!\n"
	.string "¡Olvido mis penas cuando nado!$"

Route108_Text_MissyDefeated:
	.string "Cuando pierdo una batalla, ¡me\n"
	.string "estreso mucho!$"

Route108_Text_MissyPostBattle:
	.string "¡Quita el estrés nadando!\n"
	.string "¡Es muy saludable!$"

Route108_Text_CoryIntro:
	.string "Amo los POKéMON de tipo AGUA.\n"
	.string "¡Amo a otros POKéMON también!$"

Route108_Text_CoryDefeated:
	.string "¡Buaaa! ¡Perdí!\n"
	.string "¡Buaaa! ¡Buaaa!$"

Route108_Text_CoryPostBattle:
	.string "¡Gritar me hace bien!\n"
	.string "¡Me anima mucho!$"

Route108_Text_CoryRegister:
	.string "¡Amo a los ENTRENADORES fuertes!\n"
	.string "¡Regístrame en tu POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "¡Gane o pierda, amo luchar en el mar!$"

Route108_Text_CoryRematchDefeated:
	.string "¡Buaaa! ¡Perdí otra vez!\n"
	.string "¡Buaaa! ¡Buaaa!$"

Route108_Text_CoryRematchPostBattle:
	.string "Si enfrentas un desafío,\n"
	.string "¡intenta gritarle al mar!$"

Route108_Text_CarolinaIntro:
	.string "Amo mucho a mis POKéMON.\n"
	.string "¡Verás una batalla veloz!$"

Route108_Text_CarolinaDefeated:
	.string "Eso no fue nada tierno.$"

Route108_Text_CarolinaPostBattle:
	.string "Estando en el mar, no me importaría\n"
	.string "usar un traje de baño rosa y lindo…$"

Route109_Text_DavidIntro:
	.string "¡Hiyah! ¡Mira mis abdominales!\n"
	.string "¡A esto se le llama “estilo”!$"

Route109_Text_DavidDefeated:
	.string "¡Aiyah!\n"
	.string "¡Me vencieron!$"

Route109_Text_DavidPostBattle:
	.string "¡Hiyah!\p"
	.string "¡Mis abdominales no tienen nada\n"
	.string "que ver con las batallas POKéMON!$"

Route109_Text_AliceIntro:
	.string "¿Te proteges bien contra\n"
	.string "el sol?$"

Route109_Text_AliceDefeated:
	.string "¡Ay, ay, ay!$"

Route109_Text_AlicePostBattle:
	.string "¡Las mejillas se queman más fácil!$"

Route109_Text_HueyIntro:
	.string "He anclado en puertos del mundo,\n"
	.string "pero PORTALUANA es el mejor.$"

Route109_Text_HueyDefeated:
	.string "¡Eres el mejor!$"

Route109_Text_HueyPostBattle:
	.string "En el mejor puerto estaba el mejor\n"
	.string "ENTRENADOR…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "¿Batalla? ¿Conmigo?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "¡Suelo ser más fuerte!\n"
	.string "¡Es que estoy mareado!\p"
	.string "Soy MARINERO, pero…$"

Route109_Text_RickyIntro:
	.string "Tengo sed… Me vendría bien un REFRESCO\n"
	.string "en la CASA DE LA PLAYA…$"

Route109_Text_RickyDefeated:
	.string "Gemido…$"

Route109_Text_RickyPostBattle:
	.string "Tengo hambre… Mi flotador\n"
	.string "parece una dona gigante…$"

Route109_Text_RickyRegister:
	.string "¿Luchamos otra vez\n"
	.string "cuando ya no tenga sed?$"

Route109_Text_RickyRematchIntro:
	.string "Tengo hambre, ¡pero aún tengo energía\n"
	.string "para una batalla!$"

Route109_Text_RickyRematchDefeated:
	.string "Perdí…\n"
	.string "Es porque tengo hambre…$"

Route109_Text_RickyRematchPostBattle:
	.string "Comer en la playa hace que todo\n"
	.string "sepa un poco mejor.$"

Route109_Text_LolaIntro:
	.string "¿No parece que una sombrilla es\n"
	.string "como una flor gigante?$"

Route109_Text_LolaDefeated:
	.string "¡Mami!$"

Route109_Text_LolaPostBattle:
	.string "¡Desde el cielo, la playa parece\n"
	.string "un gran jardín de flores!$"

Route109_Text_LolaRegister:
	.string "¿Yo?\n"
	.string "¡Vengo aquí todos los días!$"

Route109_Text_LolaRematchIntro:
	.string "¡No perderé contra ti otra vez!\n"
	.string "¡Por eso traigo mi flotador!$"

Route109_Text_LolaRematchDefeated:
	.string "¡Mami!$"

Route109_Text_LolaRematchPostBattle:
	.string "¡Con mi flotador, mi ternura y la\n"
	.string "de mi POKéMON suben mucho!$"

Route109_Text_AustinaIntro:
	.string "No nado sin mi flotador,\n"
	.string "¡pero no perderé en POKéMON!$"

Route109_Text_AustinaDefeated:
	.string "¿Perdí por culpa de mi\n"
	.string "flotador?$"

Route109_Text_AustinaPostBattle:
	.string "Mi flotador es un accesorio de moda.\n"
	.string "No puedo salir sin él.$"

Route109_Text_GwenIntro:
	.string "Hola, gran ENTRENADOR.\n"
	.string "¿Luchas conmigo?$"

Route109_Text_GwenDefeated:
	.string "Oh, eres fuerte.$"

Route109_Text_GwenPostBattle:
	.string "¿Cómo te volviste tan fuerte?$"

Route109_Text_CarterIntro:
	.string "¡Jajaja! ¡Este tipo va a atrapar\n"
	.string "algo muy grande!$"

Route109_Text_CarterDefeated:
	.string "Este tipo acaba de perder...$"

Route109_Text_CarterPostBattle:
	.string "Este tipo cree que eres un grande.\n"
	.string "¡No, tú serás el más grande!$"

Route109_Text_PaulIntro:
	.string "PAUL: Vaya, esto arruina el momento.\p"
	.string "Ojalá no interrumpieras nuestro\n"
	.string "precioso tiempo juntos.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Bueno, me rindo.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: No le digas a nadie que\n"
	.string "estamos aquí.\l"
	.string "¡Este es nuestro mundo privado!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Estamos total y profundamente\n"
	.string "enamorados. Por eso luchamos con\l"
	.string "nuestros POKéMON juntos.$"

Route109_Text_MelIntro:
	.string "MEL: Estamos, tipo, muy enamorados.\n"
	.string "¡Nuestro romance calienta HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: ¡Perdimos y es mi culpa!\n"
	.string "¡PAUL me va a odiar!$"

Route109_Text_MelPostBattle:
	.string "MEL: Eh, PAUL, ¿estás enojado conmigo?\n"
	.string "Por favor, no te enojes.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Estamos muy enamorados.\n"
	.string "Por eso hacemos que nuestros POKéMON\l"
	.string "luchen juntos.$"

Route109_Text_ChandlerIntro:
	.string "¡Tadaaa! ¿Ves?\n"
	.string "¡Mi flotador es redondo!$"

Route109_Text_ChandlerDefeated:
	.string "¡Oh, oh!\n"
	.string "¡Qué mal!$"

Route109_Text_ChandlerPostBattle:
	.string "Después de que te enseñara mi\n"
	.string "flotador redondo también...$"

Route109_Text_HaileyIntro:
	.string "No sé nadar, así que finjo\n"
	.string "que sé nadar.$"

Route109_Text_HaileyDefeated:
	.string "¡Lo sabía!\n"
	.string "No creía que pudiéramos ganar.$"

Route109_Text_HaileyPostBattle:
	.string "Cuando aprenda a nadar, creo que\n"
	.string "mis POKéMON serán más fuertes.$"

Route109_Text_ElijahIntro:
	.string "¡Para un tipo tan macho como yo,\n"
	.string "estos POKéMON son ideales!$"

Route109_Text_ElijahDefeated:
	.string "Sigo siendo genial aunque pierda, ¿no?$"

Route109_Text_ElijahPostBattle:
	.string "Para alguien tan macho como yo, un\n"
	.string "puerto es el lugar ideal!\p"
	.string "Iré hacia SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "¡Cuidado! ¡Fíjate!\n"
	.string "Parece que no sabes usar la BIKE.$"

Route110_Text_JacobDefeated:
	.string "¡Cielos!\n"
	.string "¡Me fallaron los frenos!$"

Route110_Text_JacobPostBattle:
	.string "Llantas planas y frenos mal pueden\n"
	.string "causar heridas graves!\l"
	.string "¡Revisa bien tu BIKE!$"

Route110_Text_AnthonyIntro:
	.string "¡Oye, tú!\n"
	.string "¿Podrás seguir mi velocidad?$"

Route110_Text_AnthonyDefeated:
	.string "¡Te estrellaste y quemaste!$"

Route110_Text_AnthonyPostBattle:
	.string "La velocidad no basta en POKéMON.\n"
	.string "Debo reconsiderar esto...$"

Route110_Text_BenjaminIntro:
	.string "¡No te asustes si tu BIKE va rápido!$"

Route110_Text_BenjaminDefeated:
	.string "No debo entrar en pánico en las\n"
	.string "batallas POKéMON…$"

Route110_Text_BenjaminPostBattle:
	.string "No hay por qué entrar en pánico.\n"
	.string "Tranquilo. Hay tiempo de sobra.$"

Route110_Text_BenjaminRegister:
	.string "Seguiré adelante sin estresarme.\n"
	.string "Avísame si te animas a luchar.$"

Route110_Text_BenjaminRematchIntro:
	.string "¿No vas un poco demasiado rápido?\n"
	.string "Relájate y vamos a luchar.$"

Route110_Text_BenjaminRematchDefeated:
	.string "No entré en pánico, pero perdí…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "No hay por qué entrar en pánico.\n"
	.string "Tranquilo. Hay tiempo de sobra.$"

Route110_Text_AbigailIntro:
	.string "El triatlón es muy difícil.\p"
	.string "Debes completar natación, ciclismo\n"
	.string "y carrera.$"

Route110_Text_AbigailDefeated:
	.string "¡Las batallas POKéMON son difíciles!$"

Route110_Text_AbigailPostBattle:
	.string "Estoy agotado, necesito un descanso.\n"
	.string "Es importante descansar bien.$"

Route110_Text_AbigailRegister:
	.string "¡Sabes, me caes bien!\n"
	.string "¡Revancha en la CICLOVÍA!$"

Route110_Text_AbigailRematchIntro:
	.string "¿No es genial luchar mientras\n"
	.string "vas en bici?$"

Route110_Text_AbigailRematchDefeated:
	.string "Vaya...\n"
	.string "¿Cómo puedes ser tan fuerte?$"

Route110_Text_AbigailRematchPostBattle:
	.string "¿Buscabas un récord?\p"
	.string "¡Perdón si te retrasé!$"

Route110_Text_JasmineIntro:
	.string "He pedaleado sin parar.\n"
	.string "¡Mis muslos parecen rocas!$"

Route110_Text_JasmineDefeated:
	.string "Me preocupan los calambres...$"

Route110_Text_JasminePostBattle:
	.string "Oh, ¿tienes MEDALLAS de GIMNASIO?\n"
	.string "¡Con razón eres tan fuerte!$"

Route110_Text_EdwardIntro:
	.string "¡He previsto tus intenciones!\n"
	.string "¡Es imposible que pierda!$"

Route110_Text_EdwardDefeated:
	.string "¡No predije mi propia derrota!$"

Route110_Text_EdwardPostBattle:
	.string "Veo tu futuro...\p"
	.string "Hmm...\n"
	.string "Veo una luz brillante...$"

Route110_Text_JaclynIntro:
	.string "¡Ahajajaja!\n"
	.string "¡Te deslumbraré con mis prodigios!$"

Route110_Text_JaclynDefeated:
	.string "¡He perdido prodigiosamente!$"

Route110_Text_JaclynPostBattle:
	.string "Ganaste solo porque fue un\n"
	.string "milagro! ¡Sí, un milagro!\l"
	.string "¡No creas que ganarás siempre!$"

Route110_Text_EdwinIntro:
	.string "¿Puedo ver tus POKéMON?\n"
	.string "Solo una mirada, por favor?$"

Route110_Text_EdwinDefeated:
	.string "Quería completar\n"
	.string "mi colección…$"

Route110_Text_EdwinPostBattle:
	.string "¡Si veo un POKéMON desconocido,\n"
	.string "mi pasión de coleccionista despierta!$"

Route110_Text_EdwinRegister:
	.string "También me gusta coleccionar\n"
	.string "registros de MATCH CALL…$"

Route110_Text_EdwinRematchIntro:
	.string "Hola, ¿atrapaste algún POKéMON?\p"
	.string "¿Puedo ver tus POKéMON?\n"
	.string "¿Solo una mirada, por favor?$"

Route110_Text_EdwinRematchDefeated:
	.string "Tus POKéMON…\n"
	.string "Te envidio.$"

Route110_Text_EdwinRematchPostBattle:
	.string "¡Ay, anhelo que todos los POKéMON\n"
	.string "raros sean míos!$"

Route110_Text_DaleIntro:
	.string "¡Oye!\n"
	.string "¡No me sorprendas así por detrás!$"

Route110_Text_DaleDefeated:
	.string "¡Perdí!\n"
	.string "¡Rayos!$"

Route110_Text_DalePostBattle:
	.string "Pescar es cuestión de concentración.\n"
	.string "Debes enfocarte en el flotador.$"

Route110_Text_IsabelIntro:
	.string "¡Ahahaha! Iría a cualquier lugar para\n"
	.string "lucir a mis lindos POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Ay, cielo, esto no servirá.$"

Route110_Text_IsabelPostBattle:
	.string "En vez de luchar, quizá debería\n"
	.string "lucir mis POKéMON en el FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Eso no se compara a cómo puedo\n"
	.string "lucir a mis POKéMON.\p"
	.string "¡Te tendré como mi público cautivo\n"
	.string "lo más seguido posible!$"

Route110_Text_IsabelRematchIntro:
	.string "¡Ahahahaha! ¡Estaré feliz de lucir\n"
	.string "mis POKéMON cuantas veces quieras!$"

Route110_Text_IsabelRematchDefeated:
	.string "Ay, cielo, esto no servirá.$"

Route110_Text_IsabelRematchPostBattle:
	.string "No creo que pueda dejar de lucir\n"
	.string "a mis POKéMON.\p"
	.string "¡Pero también me gusta luchar!$"

Route110_Text_TimmyIntro:
	.string "¡Hallé POKéMON geniales en la\n"
	.string "hierba de por aquí!$"

Route110_Text_TimmyDefeated:
	.string "Ser genial no basta para ganar…$"

Route110_Text_TimmyPostBattle:
	.string "Es difícil luchar con POKéMON que\n"
	.string "acabas de capturar.$"

Route110_Text_AlyssaIntro:
	.string "Caí de la CICLOVÍA…\p"
	.string "¡Superaré mi vergüenza luchando\n"
	.string "contra ti!$"

Route110_Text_AlyssaDefeated:
	.string "¡Ups!\n"
	.string "¡Terminé perdiendo!$"

Route110_Text_AlyssaPostBattle:
	.string "Caer… Perder…\n"
	.string "¡Esto es muy humillante para mí!$"

Route110_Text_JosephIntro:
	.string "¡Bien! ¡A tope! ¡Si no tienes\n"
	.string "ritmo, te quedarás atrás!$"

Route110_Text_JosephDefeated:
	.string "Vaya que tienes ritmo…$"

Route110_Text_JosephPostBattle:
	.string "¡Esto no me detendrá!\n"
	.string "¡Perder me hizo mejor persona!$"

Route110_Text_KalebIntro:
	.string "Cuando POKéMON lindos se ayudan...\n"
	.string "¡No hay vista más adorable!$"

Route110_Text_KalebDefeated:
	.string "¿No tienes compasión ni piedad?$"

Route110_Text_KalebPostBattle:
	.string "Está bien, hicieron lo mejor que\n"
	.string "pudieron, mis lindos.$"

Route111_Text_DrewIntro:
	.string "¡Hola! Esas GO-GOGGLES te quedan bien.\n"
	.string "Pero creo que me lucen más a mí.\p"
	.string "¡Decidamos quién luce mejor con\n"
	.string "una batalla!$"

Route111_Text_DrewDefeat:
	.string "No veía los lados por culpa de las\n"
	.string "GO-GOGGLES.$"

Route111_Text_DrewPostBattle:
	.string "Las GO-GOGGLES permiten cruzar las\n"
	.string "tormentas de arena.\l"
	.string "¡Eso me hace feliz!$"

Route111_Text_HeidiIntro:
	.string "Hago un picnic en el desierto.\p"
	.string "Siempre hay un ENTRENADOR,\n"
	.string "¡así que puedo luchar aquí también!$"

Route111_Text_HeidiDefeat:
	.string "¡Ohhh! ¡Eres malo!$"

Route111_Text_HeidiPostBattle:
	.string "En batallas con tormenta de arena,\n"
	.string "cuida los PS de tus POKéMON.\p"
	.string "¡Pueden debilitarse si no los\n"
	.string "vigilas bien!$"

Route111_Text_BeauIntro:
	.string "Con estas GO-GOGGLES me siento\n"
	.string "como un superhéroe.\l"
	.string "¡Ahora nadie puede vencerme!$"

Route111_Text_BeauDefeat:
	.string "No puedo ganar solo con espíritu…$"

Route111_Text_BeauPostBattle:
	.string "Seré un héroe de verdad algún día.\n"
	.string "Me esforzaré más para que mis\l"
	.string "POKéMON y yo seamos fuertes.$"

Route111_Text_BeckyIntro:
	.string "Oí que hay fósiles en el desierto.\n"
	.string "¿Dónde podrían estar?$"

Route111_Text_BeckyDefeat:
	.string "No fue suficiente…$"

Route111_Text_BeckyPostBattle:
	.string "Si hay fósiles en el desierto,\n"
	.string "antes debió ser un mar.$"

Route111_Text_DustyIntro:
	.string "¡Por treinta años busqué ruinas\n"
	.string "antiguas!\l"
	.string "¿Acaso quieres retarme?$"

Route111_Text_DustyDefeat:
	.string "Mientras buscaba las ruinas,\n"
	.string "no busqué POKéMON fuertes.$"

Route111_Text_DustyPostBattle:
	.string "¡Por treinta años busqué ruinas\n"
	.string "antiguas!\p"
	.string "No, espera, ¿fueron cuarenta años?\n"
	.string "¿Cuál de los dos era?$"

Route111_Text_DustyRegister:
	.string "No he buscado POKéMON\n"
	.string "fuertes.\p"
	.string "Pero, por alguna razón, me gustan\n"
	.string "los POKéNAV.$"

Route111_Text_DustyRematchIntro:
	.string "¡Llevo treinta años buscando\n"
	.string "ruinas antiguas!\p"
	.string "No, espera, ¿eran cuarenta años?\n"
	.string "En fin, ¿quieres luchar?$"

Route111_Text_DustyRematchDefeat:
	.string "No he hallado ruinas, ni he hallado\n"
	.string "ningún POKéMON fuerte…$"

Route111_Text_DustyPostRematch:
	.string "¡Llevo treinta años buscando\n"
	.string "ruinas antiguas!\p"
	.string "No, espera, ¿eran cuarenta años\n"
	.string "de búsqueda?\p"
	.string "Hmm… Podrían ser cincuenta…\n"
	.string "¿Cuánto tiempo llevo en esto?$"

Route111_Text_TravisIntro:
	.string "¡Estoy lleno de energía!\n"
	.string "¡Y mi POKéMON también lo está!$"

Route111_Text_TravisDefeat:
	.string "Mi POKéMON perdió su energía…$"

Route111_Text_TravisPostBattle:
	.string "Cuando veo a un ENTRENADOR con\n"
	.string "mucha energía, no puedo evitar mirar.$"

Route111_Text_IreneIntro:
	.string "No sé a dónde vas,\n"
	.string "¿pero quieres luchar?$"

Route111_Text_IreneDefeat:
	.string "¡Vaya, eres demasiado bueno!$"

Route111_Text_IrenePostBattle:
	.string "Pienso ir al MONTE HUMEANTE,\n"
	.string "pero la vista por aquí\l"
	.string "también es muy linda.$"

Route111_Text_DaisukeIntro:
	.string "Para entrenar, ¡desafío a todos\n"
	.string "los que me encuentro!$"

Route111_Text_DaisukeDefeat:
	.string "¡Tío! ¡Me rindo!$"

Route111_Text_DaisukePostBattle:
	.string "Solo me queda seguir entrenando\n"
	.string "hasta vencer a ENTRENADORES\l"
	.string "fuertes como tú.$"

Route111_Text_WiltonIntro:
	.string "Muéstrame cuánto has fortalecido\n"
	.string "a tus POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Ya veo, los has fortalecido\n"
	.string "considerablemente.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON y ENTRENADORES aprenden\n"
	.string "luchando.\p"
	.string "Lo importante es no rendirse\n"
	.string "aunque pierdas.$"

Route111_Text_WiltonRegister:
	.string "Hay mucho que aprender de tu\n"
	.string "estilo de entrenamiento.\p"
	.string "Te pido una revancha si\n"
	.string "estás de acuerdo.$"

Route111_Text_WiltonRematchIntro:
	.string "Entrenamos aquí para llevar nuestro\n"
	.string "nivel al siguiente paso.\l"
	.string "¡Quédate y entrena con nosotros!$"

Route111_Text_WiltonRematchDefeat:
	.string "¡Ooh, eres decente!$"

Route111_Text_WiltonPostRematch:
	.string "Ya que eres tan fuerte, deberías\n"
	.string "ir por la LIGA POKéMON.$"

Route111_Text_BrookeIntro:
	.string "Tus POKéMON parecen actores\n"
	.string "serios.\l"
	.string "Tengo que pedirte un compromiso.$"

Route111_Text_BrookeDefeat:
	.string "No solo parecían fuertes,\n"
	.string "¡realmente lo son!$"

Route111_Text_BrookePostBattle:
	.string "Creí que criaba a mis POKéMON\n"
	.string "con esmero, pero no, aún queda\l"
	.string "mucho por hacer.$"

Route111_Text_BrookeRegister:
	.string "¡Desearía ser amigo de más\n"
	.string "gente fuerte como tú!$"

Route111_Text_BrookeRematchIntro:
	.string "Puedes hacer que tus POKéMON sean más\n"
	.string "fuertes o débiles según los ataques\l"
	.string "que les enseñes.\p"
	.string "¿Qué tipo de ataques conocen tus\n"
	.string "POKéMON?$"

Route111_Text_BrookeRematchDefeat:
	.string "¡Les has enseñado buenos ataques!$"

Route111_Text_BrookePostRematch:
	.string "Quizá debí evitar que mis\n"
	.string "POKéMON evolucionaran hasta que\l"
	.string "aprendieran mejores ataques…$"

Route111_Text_CeliaIntro:
	.string "¡No debí venir a un lugar así\n"
	.string "para un picnic!$"

Route111_Text_CeliaDefeat:
	.string "¡Ay!\n"
	.string "¡Realmente no debí venir!$"

Route111_Text_CeliaPostBattle:
	.string "Con esta tormenta, no puedo armar\n"
	.string "el picnic ni con mis\l"
	.string "GO-GOGGLES puestos…$"

Route111_Text_BryanIntro:
	.string "¿Qué tan fuerte eres?\n"
	.string "¡Revelaremos ese secreto!$"

Route111_Text_BryanDefeat:
	.string "¡Oh! ¡Tu fuerza!\n"
	.string "¡Está envuelta en misterio!$"

Route111_Text_BryanPostBattle:
	.string "¡Este desierto guarda misterios en\n"
	.string "sus arenas movedizas!$"

Route111_Text_BrandenIntro:
	.string "Te daré algo de mi sándwich\n"
	.string "si pierdes.$"

Route111_Text_BrandenDefeat:
	.string "¡Tch! Pensé que un sándwich\n"
	.string "sería un soborno suficiente…$"

Route111_Text_BrandenPostBattle:
	.string "A mi SANDSHREW le encanta comer\n"
	.string "mis sándwiches.$"

Route111_Text_TyronIntro:
	.string "¡Este es mi tipo de POKéMON favorito!$"

Route111_Text_TyronDefeat:
	.string "¡Espera!\n"
	.string "¿Viste bien a mi POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "En las batallas, me encanta\n"
	.string "presumir mis POKéMON.\p"
	.string "¡Seguro todos se sienten así al\n"
	.string "entrar en combate!$"

Route111_Text_CelinaIntro:
	.string "Enséñame cómo darle algo de\n"
	.string "emoción a mi vida.$"

Route111_Text_CelinaDefeat:
	.string "Oh... Dios...\n"
	.string "Eso fue demasiada emoción.$"

Route111_Text_CelinaPostBattle:
	.string "Mi pulso sigue acelerado.\n"
	.string "Eres un TRAINER fabuloso.$"

Route111_Text_HaydenIntro:
	.string "Cuando tienes tanta hambre como yo,\n"
	.string "¡no hay lugar para la piedad!$"

Route111_Text_HaydenDefeat:
	.string "Ugh...$"

Route111_Text_HaydenPostBattle:
	.string "¡Mi estómago ruge!\n"
	.string "Tal vez pueda asar algunas BAYAS...$"

Route111_Text_BiancaIntro:
	.string "¿Vienes de FUNDA CIUDAD?\n"
	.string "¡Debes tener mucha energía!$"

Route111_Text_BiancaDefeat:
	.string "¡Ooh lala!\n"
	.string "¡Es demasiado para soportar!$"

Route111_Text_BiancaPostBattle:
	.string "Este camino...\n"
	.string "Aún te falta mucho por viajar.$"

Route112_Text_BriceIntro:
	.string "¡Jajajaja!\n"
	.string "¿Qué tal una batalla?\l"
	.string "¡Tú y yo!\l"
	.string "¡Jajajaja!$"

Route112_Text_BriceDefeat:
	.string "¡Perdí!\n"
	.string "¡Jajajaja!$"

Route112_Text_BricePostBattle:
	.string "¡Jajaja! ¡Algo entró en mi nariz!\n"
	.string "¡Jajaja-achís!$"

Route112_Text_TrentIntro:
	.string "Mis piernas son fuertes de subir\n"
	.string "y bajar montañas.\p"
	.string "¡No cederán fácilmente,\n"
	.string "amigo!$"

Route112_Text_TrentDefeat:
	.string "¡Ay! ¡Me dieron calambres!$"

Route112_Text_TrentPostBattle:
	.string "Prueba el senderismo, y me refiero a\n"
	.string "recorrer estas rutas de montaña\l"
	.string "con una mochila de decenas de\l"
	.string "kilos.\p"
	.string "Eso, amigo, pondrá tu cuerpo\n"
	.string "en muy buena forma.$"

Route112_Text_TrentRegister:
	.string "¡Ay, se me acalamparon las piernas!\n"
	.string "¿Me traes unas vendas de\l"
	.string "mi mochila?\p"
	.string "¡No, ese es mi POKéNAV!\n"
	.string "Está bien, te registraré.$"

Route112_Text_TrentRematchIntro:
	.string "Me mantengo en forma caminando.\n"
	.string "¡Tengo fuerza de sobra!$"

Route112_Text_TrentRematchDefeat:
	.string "¿Me ganaron en fuerza?$"

Route112_Text_TrentRematchPostBattle:
	.string "Oí que hay ENTRENADORES muy fuertes\n"
	.string "en la cima del MT. CHIMNEY.\p"
	.string "¡Pienso subir y darles\n"
	.string "una buena batalla!$"

Route112_Text_LarryIntro:
	.string "Soy fuerte.\n"
	.string "No lloraré si pierdo.$"

Route112_Text_LarryDefeat:
	.string "¡Buaaaa!$"

Route112_Text_LarryPostBattle:
	.string "¡No lloro porque extrañe a mamá!\n"
	.string "Snif...$"

Route112_Text_CarolIntro:
	.string "En un picnic, ¡simplemente\n"
	.string "hay que cantar!\l"
	.string "¡Vamos, canta conmigo!$"

Route112_Text_CarolDefeat:
	.string "¡Vaya, eres muy fuerte!$"

Route112_Text_CarolPostBattle:
	.string "No importa si eres bueno o malo\n"
	.string "cantando o con POKéMON.\p"
	.string "¡Si te diviertes, ganas!$"

Route112_Text_BryantIntro:
	.string "¡Atrapé POKéMON de fuego en\n"
	.string "Senda Ardiente! ¡Mira!$"

Route112_Text_BryantDefeat:
	.string "¡Qué viaje tan movido fue!$"

Route112_Text_BryantPostBattle:
	.string "Me gusta cómo luchas.\n"
	.string "Tiene un estilo especial.$"

Route112_Text_ShaylaIntro:
	.string "¡Qué ENTRENADOR tan adorable!\n"
	.string "¡Busco una batalla romántica!\l"
	.string "¡Soy bastante decente!$"

Route112_Text_ShaylaDefeat:
	.string "¡Oh, qué fuerte eres!\n"
	.string "¡Me has dado una gran sorpresa!$"

Route112_Text_ShaylaPostBattle:
	.string "¿Estás ocupado ahora?\n"
	.string "Pensaba que tal vez podríamos\l"
	.string "tener una revancha ahora...\l"
	.string "Pero no pasa nada si estás ocupado.$"

Route113_Text_JaylenIntro:
	.string "¿Adivinas por qué hace tanto frío\n"
	.string "por aquí?$"

Route113_Text_JaylenDefeat:
	.string "¡Puaj!\n"
	.string "¡Qué peste!$"

Route113_Text_JaylenPostBattle:
	.string "La ceniza volcánica tapa el sol,\n"
	.string "así que no hace mucho calor.\p"
	.string "¡Es bueno para mí, odio el calor!$"

Route113_Text_DillonIntro:
	.string "La erupción del volcán prueba que\n"
	.string "la tierra está viva.$"

Route113_Text_DillonDefeat:
	.string "¡Eres bastante fuerte!$"

Route113_Text_DillonPostBattle:
	.string "¡Ay! ¡Auh! ¡No veo nada!\n"
	.string "¡Tengo ceniza en las pestañas!\p"
	.string "¿Entiendes? ¿Ceniza y pestañas?\p"
	.string "Vale, estuvo mal, lo siento...$"

Route113_Text_MadelineIntro:
	.string "Uso esta sombrilla para evitar que\n"
	.string "la asquerosa ceniza volcánica caiga\l"
	.string "sobre mi querido NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Huff, huff...\n"
	.string "Estoy agotada...$"

Route113_Text_MadelinePostBattle:
	.string "Eres muy bueno en esto.\n"
	.string "¡Debo decir que estoy impresionada!$"

Route113_Text_MadelineRegister:
	.string "Ven, ponte bajo mi sombrilla.\n"
	.string "Te registraré en mi POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Hola, ¿no ha pasado mucho tiempo?\n"
	.string "¿Te invito a una batalla?$"

Route113_Text_MadelineRematchDefeat:
	.string "¡Oh, qué súper!$"

Route113_Text_MadelinePostRematch:
	.string "Sigues siendo muy bueno en esto.\n"
	.string "¡Debo decir que estoy impresionada!$"

Route113_Text_LaoIntro:
	.string "¡Surjo de las cenizas! ¡Hiyah!\n"
	.string "¡Te desafío!$"

Route113_Text_LaoDefeat:
	.string "¡Admito mi derrota con honor!$"

Route113_Text_LaoPostBattle:
	.string "Debo perfeccionar el arte del sigilo.\n"
	.string "Me despido de ti.$"

Route113_Text_LaoRegister:
	.string "¡Yiiyaah! ¡Mira la técnica ninja\n"
	.string "de registro de POKéNAV!$"

Route113_Text_LaoRematchIntro:
	.string "¡Salto desde las cenizas! ¡Hiyah!\n"
	.string "¡Te desafío!$"

Route113_Text_LaoRematchDefeat:
	.string "¡Admito mi derrota con honor!$"

Route113_Text_LaoPostRematch:
	.string "Mi ocultamiento fue perfecto, pero\n"
	.string "fallé por mi falta de habilidad...\p"
	.string "Me despido de ti.$"

Route113_Text_LungIntro:
	.string "¡Gracias por encontrarme!\n"
	.string "¡Pero aún debemos luchar!$"

Route113_Text_LungDefeat:
	.string "Usaré mi ninjutsu contigo...\n"
	.string "¡MANTO DE CENIZA VOLCÁNICA!\p"
	.string "...¿Qué?\n"
	.string "¿Ya terminó?$"

Route113_Text_LungPostBattle:
	.string "¿Sabes qué es lo malo de esconderse?\n"
	.string "Que es solitario si nadie viene.$"

Route113_Text_ToriIntro:
	.string "TORI: Los dos juntamos cenizas.\n"
	.string "También luchamos POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI: Perdimos... Es aburrido, así que\n"
	.string "iré por más cenizas.$"

Route113_Text_ToriPostBattle:
	.string "TORI: ¿Cuánta ceniza tenemos?\n"
	.string "Espero que baste para una WHITE FLUTE.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Queremos luchar 2 contra 2.\n"
	.string "¡Si no, perderíamos!$"

Route113_Text_TiaIntro:
	.string "TIA: Los dos juntamos cenizas.\n"
	.string "También luchamos POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA: No pudimos ganar... Es aburrido,\n"
	.string "así que buscaré más cenizas.$"

Route113_Text_TiaPostBattle:
	.string "TIA: ¡Tenemos mucha ceniza!\n"
	.string "¡Creo que basta para una WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: Queremos luchar 2 contra 2.\n"
	.string "¡Si no, no ganaremos!$"

Route113_Text_CobyIntro:
	.string "¡Pfft, con estas alas puedo\n"
	.string "mandarte a volar!$"

Route113_Text_CobyDefeat:
	.string "A... ¿Qué?$"

Route113_Text_CobyPostBattle:
	.string "No sé qué decir cuando me\n"
	.string "vencen tan fácil...$"

Route113_Text_SophieIntro:
	.string "Este calor me da sueño.\n"
	.string "¡Lucha conmigo para no dormirme!$"

Route113_Text_SophieDefeat:
	.string "Esto es un sueño.\n"
	.string "Estoy seguro...$"

Route113_Text_SophiePostBattle:
	.string "Perder me quema...\n"
	.string "¡Me dormiré justo aquí!\l"
	.string "¡Zzz!$"

Route113_Text_LawrenceIntro:
	.string "¿Tal vez estabas recolectando\n"
	.string "cenizas volcánicas?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "Nos vencieron limpiamente.$"

Route113_Text_LawrencePostBattle:
	.string "Yo también debería ocultarme aquí.$"

Route113_Text_WyattIntro:
	.string "¿Q-quieres luchar conmigo?\n"
	.string "¿Aunque acabo de atrapar mi POKéMON?$"

Route113_Text_WyattDefeat:
	.string "¿T-tan feliz estás por ganar?\n"
	.string "¿Aunque solo sea contra mí?$"

Route113_Text_WyattPostBattle:
	.string "Oh, ¿ahora quieres decirle algo\n"
	.string "al perdedor?\p"
	.string "¿No te crees el más genial?\n"
	.string "¡Hmph!$"

Route114_Text_LennyIntro:
	.string "¡Yodelayhihoo!\p"
	.string "… …\p"
	.string "Se supone que debes gritar\n"
	.string "“yodelayhihoo” ya que aquí no\l"
	.string "hay eco!$"

Route114_Text_LennyDefeat:
	.string "¡Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "De niño creía que alguien me\n"
	.string "copiaba y gritaba de vuelta:\l"
	.string "“Yodelayhihoo”.$"

Route114_Text_LucasIntro:
	.string "¡Si no estás preparado, no deberías\n"
	.string "estar en las montañas!$"

Route114_Text_LucasDefeat:
	.string "Las montañas son implacables…$"

Route114_Text_LucasPostBattle:
	.string "En invierno, las montañas son letales\n"
	.string "por ventiscas y avalanchas.$"

Route114_Text_ShaneIntro:
	.string "¡Acampar es genial! Puedes pescar,\n"
	.string "asar malvaviscos y contar historias!\p"
	.string "¡Pero lo mejor son las batallas\n"
	.string "POKéMON!$"

Route114_Text_ShaneDefeat:
	.string "¡Demasiado fuerte!$"

Route114_Text_ShanePostBattle:
	.string "Me encanta poder ir de camping\n"
	.string "con mis POKéMON.$"

Route114_Text_NancyIntro:
	.string "Debo hacer ejercicio tras comer.\n"
	.string "¡Tengamos un combate!$"

Route114_Text_NancyDefeat:
	.string "¡Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "Acabo de comer algo rico.\n"
	.string "Me estoy quedando dormido…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "¿Quieres luchar contra mis POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M-Mis POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un cuerpo grande, duro y rugoso,\n"
	.string "cuernos enormes y colmillos feroces…\p"
	.string "Ufufufufu…\n"
	.string "Quisiera un POKéMON así…$"

Route114_Text_SteveRegister:
	.string "¡No olvides lo que me hiciste!\n"
	.string "¡Haré que sea imposible olvidarlo!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Vamos, lucha contra mis POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "Me siento muy afortunada de ver a tus\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Cuando veo luchar POKéMON, empiezo a\n"
	.string "temblar de emoción…$"

Route114_Text_BernieIntro:
	.string "Si vas a encender una fogata,\n"
	.string "ten agua a la mano.$"

Route114_Text_BernieDefeat:
	.string "¡Gracias por apagar mi fuego!$"

Route114_Text_BerniePostBattle:
	.string "Hay que tener mucho cuidado con\n"
	.string "el fuego en un bosque.\p"
	.string "Nunca subestimes el poder\n"
	.string "del fuego.$"

Route114_Text_BernieRegister:
	.string "Encendiste mi espíritu.\n"
	.string "¡Registrémonos mutuamente!$"

Route114_Text_BernieRematchIntro:
	.string "¿Aprendiste a tener agua a mano\n"
	.string "para las fogatas?$"

Route114_Text_BernieRematchDefeat:
	.string "Me mojaron antes de que pudiera\n"
	.string "estallar, supongo.$"

Route114_Text_BerniePostRematch:
	.string "Hay que tener mucho cuidado con\n"
	.string "el fuego en un bosque.\p"
	.string "Nunca subestimes el poder\n"
	.string "del fuego.$"

Route114_Text_ClaudeIntro:
	.string "Si pescáramos, no tendrías\n"
	.string "oportunidad contra mí.\l"
	.string "¡Lanza tu POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "Si pescáramos, yo habría ganado…$"

Route114_Text_ClaudePostBattle:
	.string "Probaré mi suerte pescando algo\n"
	.string "grande en CASCADA METEORO.\p"
	.string "Debe haber algo ahí.\n"
	.string "Lo sé.$"

Route114_Text_NolanIntro:
	.string "Me gusta pescar. ¡Pero también me\n"
	.string "gusta luchar!\p"
	.string "Si alguien me reta, aceptaré,\n"
	.string "aunque esté pescando.$"

Route114_Text_NolanDefeat:
	.string "Me gusta luchar, pero eso no\n"
	.string "significa que sea bueno...$"

Route114_Text_NolanPostBattle:
	.string "¡Esta vez lo lograré!\p"
	.string "Siempre pienso eso, así que no dejo\n"
	.string "la pesca ni los POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Bueno, claro.\n"
	.string "Tengo ganas de hacerlo.\l"
	.string "Te enseñaré algo de POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: ¡Qué estilo de lucha tan genial!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Le enseñaba a mi pequeña IVY\n"
	.string "sobre los POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Jiji...\n"
	.string "Si quieres luchar con nosotras, ¡un\l"
	.string "solo POKéMON no basta!$"

Route114_Text_IvyIntro:
	.string "IVY: ¿Quién te enseñó sobre POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: ¡Qué estilo de batalla!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Empecé a entrenar POKéMON\n"
	.string "porque TYRA, mi mentora,\l"
	.string "¡me enseñó!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: ¿Solo tienes un POKéMON?\n"
	.string "Creo que debe sentirse solo.$"

Route114_Text_KaiIntro:
	.string "¡Atrapé uno grande!\n"
	.string "¡Uno enorme, te lo digo!$"

Route114_Text_KaiDefeat:
	.string "¿A qué vino eso?\n"
	.string "¿El mío era más chico?$"

Route114_Text_KaiPostBattle:
	.string "¡Está bien!\n"
	.string "¡Pescaré uno más grande!$"

Route114_Text_CharlotteIntro:
	.string "¡Yo!\n"
	.string "¡No soy solo una cara bonita!$"

Route114_Text_CharlotteDefeat:
	.string "¡Eso no fue nada tierno!$"

Route114_Text_CharlottePostBattle:
	.string "No quiero un POKéMON que sea\n"
	.string "solo lindo.\p"
	.string "¡Amo los lindos que tienen alguna\n"
	.string "maña!$"

Route114_Text_AngelinaIntro:
	.string "¿Has hecho evolucionar mucho a tu\n"
	.string "POKéMON?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, ya veo.\n"
	.string "Es bueno saberlo.$"

Route114_Text_AngelinaPostBattle:
	.string "¡Algunos POKéMON cambian tanto al\n"
	.string "evolucionar que asustan!$"

Route115_Text_TimothyIntro:
	.string "Hm...\n"
	.string "Pareces muy capaz...\l"
	.string "¡Deja que te acompañe!$"

Route115_Text_TimothyDefeat:
	.string "¡Eres mucho más fuerte de lo\n"
	.string "que imaginé!$"

Route115_Text_TimothyPostBattle:
	.string "No existen los genios natos.\n"
	.string "¡Todo depende del esfuerzo!\l"
	.string "Eso es lo que creo...$"

Route115_Text_TimothyRegister:
	.string "Hmm... Una derrota así de total era\n"
	.string "un recuerdo lejano.\p"
	.string "Si me lo permites, deseo otra\n"
	.string "oportunidad de luchar.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm... Como siempre, tu agilidad\n"
	.string "habla por sí sola.\l"
	.string "¡Ven, hazme compañía!$"

Route115_Text_TimothyRematchDefeat:
	.string "¡Tan fuerte como siempre!$"

Route115_Text_TimothyPostRematch:
	.string "¡Solo hace falta esfuerzo!\p"
	.string "¡Perdí porque no me he esforzado\n"
	.string "lo suficiente!$"

Route115_Text_KoichiIntro:
	.string "¡Tú!\p"
	.string "¡Mi MACHOP!\p"
	.string "¡Exige una batalla!$"

Route115_Text_KoichiDefeat:
	.string "¡Ay, ay, ay!$"

Route115_Text_KoichiPostBattle:
	.string "¡Mi equipo de MACHOP!\p"
	.string "¡Mientras busquen poder, seré\n"
	.string "fuerte junto a ellos!$"

Route115_Text_NobIntro:
	.string "¡Mi mejor habilidad es romper\n"
	.string "ladrillos con la frente!$"

Route115_Text_NobDefeat:
	.string "¡Ugwaaaah!\n"
	.string "¡Me duele la cabeza!$"

Route115_Text_NobPostBattle:
	.string "Enseño karate a mis POKéMON.\p"
	.string "Parece que serán mucho mejores\n"
	.string "que yo. ¡Eso me emociona!$"

Route115_Text_NobRegister:
	.string "¡Me impresionas! ¡Dame otra\n"
	.string "oportunidad tras mi entrenamiento!$"

Route115_Text_NobRematchIntro:
	.string "Tras perder, entrenamos duro para\n"
	.string "mejorar nuestras habilidades.\l"
	.string "¡Vamos, lucha contra nosotros!$"

Route115_Text_NobRematchDefeat:
	.string "¡Ugwaaah!\n"
	.string "¡Perdimos otra vez!$"

Route115_Text_NobPostRematch:
	.string "¡Mis POKéMON serán más fuertes!\n"
	.string "¡Redoblaré mi entrenamiento!$"

Route115_Text_CyndyIntro:
	.string "¡Esta playa es mi sitio secreto!\n"
	.string "¡No te metas aquí!$"

Route115_Text_CyndyDefeat:
	.string "¡No he entrenado lo suficiente!$"

Route115_Text_CyndyPostBattle:
	.string "La arena amortigua los golpes\n"
	.string "para evitar lesiones.\l"
	.string "Es el lugar perfecto para entrenar.$"

Route115_Text_CyndyRegister:
	.string "Está bien, puedes venir aquí.\n"
	.string "A cambio, quiero luchar contigo.$"

Route115_Text_CyndyRematchIntro:
	.string "¡Bien, que empiece la batalla!$"

Route115_Text_CyndyRematchDefeat:
	.string "Puedo luchar, pero mi POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Aunque pierda, sigo disfrutando\n"
	.string "mucho de esto.\l"
	.string "Es que amo a los POKéMON.$"

Route115_Text_HectorIntro:
	.string "¡Tengo un POKéMON raro!\n"
	.string "¿Quieres que te lo enseñe?$"

Route115_Text_HectorDefeat:
	.string "Tú…\n"
	.string "Quieres mi POKéMON, ¿verdad?$"

Route115_Text_HectorPostBattle:
	.string "Tengo este POKéMON raro.\n"
	.string "Es suficiente para hacerme feliz.$"

Route115_Text_KyraIntro:
	.string "¡Lucharé mientras corro!\n"
	.string "¡Intenta seguirme el ritmo!$"

Route115_Text_KyraDefeat:
	.string "¡Ah... ah...!$"

Route115_Text_KyraPostBattle:
	.string "¡ Cometí el error de luchar\n"
	.string "mientras corría!\p"
	.string "Debo correr para calmarme...$"

Route115_Text_JaidenIntro:
	.string "¡Toma esto!\n"
	.string "¡Ataque ninja de POKéMON Ultra!$"

Route115_Text_JaidenDefeat:
	.string "¡Waaah!\n"
	.string "¡Nuestra estrategia falló!$"

Route115_Text_JaidenPostBattle:
	.string "Pero mis POKéMON eran ultra,\n"
	.string "¿verdad?$"

Route115_Text_HeleneIntro:
	.string "¡Mis POKéMON tienen fuerza de\n"
	.string "cinturón negro!$"

Route115_Text_HeleneDefeat:
	.string "¡Esto es demasiado humillante!$"

Route115_Text_HelenePostBattle:
	.string "Rara vez alguien es mejor\n"
	.string "que yo...\p"
	.string "¡Ya entiendo!\n"
	.string "Eres un LÍDER de GIMNASIO, ¿no?$"

Route115_Text_AlixIntro:
	.string "¡Nuestras miradas se cruzaron!\n"
	.string "¡Ya no puedes escapar!$"

Route115_Text_AlixDefeat:
	.string "¡Gah!\n"
	.string "¡Nada mal!$"

Route115_Text_AlixPostBattle:
	.string "Oh, bueno.\n"
	.string "Usaré TELETRANSPORTA a casa.$"

Route115_Text_MarleneIntro:
	.string "Interrumpiste mi meditación…\n"
	.string "Serás castigado por ello.$"

Route115_Text_MarleneDefeat:
	.string "¡Rompiste mi concentración!$"

Route115_Text_MarlenePostBattle:
	.string "Meditaba con mis POKéMON.\n"
	.string "Pero este lugar no es muy pacífico…$"

Route116_Text_ClarkIntro:
	.string "Si el túnel no sirve, entonces\n"
	.string "iré por arriba.$"

Route116_Text_ClarkDefeat:
	.string "Jadeo... Jadeo...\n"
	.string "Perder me cansó...$"

Route116_Text_ClarkPostBattle:
	.string "No importa que no haya túnel.\n"
	.string "¡Para un HIKER, el monte es un camino!$"

Route116_Text_JoeyIntro:
	.string "¡Mis POKéMON mandan!\n"
	.string "¡Míralos bien!$"

Route116_Text_JoeyDefeat:
	.string "¡Ay! ¡Un rasguño!\n"
	.string "¡Tengo que ponerme una venda!$"

Route116_Text_JoeyPostBattle:
	.string "¡Las vendas son signo de fuerza!\n"
	.string "¡Tengo otra más!$"

Route116_Text_JoseIntro:
	.string "¡Mis POKéMON BUG son fuertes!\n"
	.string "¡A luchar!$"

Route116_Text_JoseDefeat:
	.string "¡Perdí!\n"
	.string "¡Pensé que te ganaría!$"

Route116_Text_JosePostBattle:
	.string "Los POKéMON BUG evolucionan rápido.\n"
	.string "Así que se hacen fuertes rápido.$"

Route116_Text_JaniceIntro:
	.string "¡Déjame enseñarte lo fuerte que es\n"
	.string "mi adorable POKéMON!$"

Route116_Text_JaniceDefeat:
	.string "Estás un nivel por encima de mí…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON con ternura y poder...\n"
	.string "creo que eso es lo ideal.$"

Route116_Text_JerryIntro:
	.string "Aprendemos de todo en la\n"
	.string "ESCUELA de ENTRENADORES.\p"
	.string "¡Quiero probarlo todo en serio!$"

Route116_Text_JerryDefeat:
	.string "No estudié mucho en la escuela…\n"
	.string "Por eso perdí.$"

Route116_Text_JerryPostBattle:
	.string "Debo repetir cursos en la\n"
	.string "ESCUELA de ENTRENADORES.\l"
	.string "Si no, ROXANNE se enfadará.$"

Route116_Text_JerryRegister1:
	.string "En la ESCUELA de ENTRENADORES vi\n"
	.string "que el POKéNAV registra ENTRENADORES.\p"
	.string "No entiendo bien cómo es,\n"
	.string "¿puedo probarlo ahora?$"

Route116_Text_JerryRegister2:
	.string "En la ESCUELA de ENTRENADORES vi\n"
	.string "que el POKéNAV registra ENTRENADORES.\p"
	.string "No entiendo bien cómo es,\n"
	.string "¿puedo probarlo ahora?$"

Route116_Text_JerryRematchIntro:
	.string "He estudiado en serio en la\n"
	.string "ESCUELA DE ENTRENADORES.\l"
	.string "No perderé como la vez pasada.$"

Route116_Text_JerryRematchDefeat:
	.string "¿Eh?\n"
	.string "Estudié con mucha diligencia.$"

Route116_Text_JerryPostRematch:
	.string "Debo repetir cursos en la\n"
	.string "ESCUELA DE ENTRENADORES.\l"
	.string "O ROXANNE se pondrá furiosa.$"

Route116_Text_KarenIntro:
	.string "Estudio en la escuela y también\n"
	.string "estudio camino a casa!$"

Route116_Text_KarenDefeat:
	.string "Estoy en shock... ¿perdí?$"

Route116_Text_KarenPostBattle:
	.string "¡Ay, así nunca seré una\n"
	.string "ENTRENADORA elegante como ROXANNE!$"

Route116_Text_KarenRegister1:
	.string "¡Vaya! ¿Eso es un POKéNAV?\n"
	.string "¡Yo también tengo uno! ¡Regístrame!$"

Route116_Text_KarenRegister2:
	.string "¡Vaya! ¿Eso es un POKéNAV?\n"
	.string "¡Yo también tengo uno! ¡Regístrame!$"

Route116_Text_KarenRematchIntro:
	.string "Estudié mucho desde que te vi.\n"
	.string "¡Mira mis logros!$"

Route116_Text_KarenRematchDefeat:
	.string "Estoy en shock.\n"
	.string "¿Perdí otra vez?$"

Route116_Text_KarenPostRematch:
	.string "¿Venciste a ROXANNE?\n"
	.string "No puedo ganarte. Aún no.$"

Route116_Text_SarahIntro:
	.string "Para que sepas, jamás me han\n"
	.string "ganado en nada.$"

Route116_Text_SarahDefeat:
	.string "Cielos.\n"
	.string "Esto es nuevo para mí.$"

Route116_Text_SarahPostBattle:
	.string "Mi lujo me da todo lo que\n"
	.string "podría desear.\p"
	.string "Pero con los POKéMON,\n"
	.string "mi riqueza no sirve de nada.$"

Route116_Text_DawsonIntro:
	.string "Al ver el hermoso pelaje de mis\n"
	.string "POKéMON, ¡su belleza te dejará\l"
	.string "sin palabras!$"

Route116_Text_DawsonDefeat:
	.string "¡Ay, no puede ser!$"

Route116_Text_DawsonPostBattle:
	.string "¡Oh, no, no, no!\n"
	.string "¡Despeinaste a mi POKéMON!\l"
	.string "¡Y arruinaste mi peinado también!\l"
	.string "¡Llamaré a mi estilista ahora!$"

Route116_Text_DevanIntro:
	.string "¡Te daremos una paliza!$"

Route116_Text_DevanDefeat:
	.string "¡Aiyiyi!\n"
	.string "¡No hubo competencia!$"

Route116_Text_DevanPostBattle:
	.string "Debo probar otros tipos de\n"
	.string "POKéMON, eso es lo que haré.$"

Route116_Text_JohnsonIntro:
	.string "Es un callejón sin salida.\n"
	.string "Estoy aburrido, ¿batallamos?$"

Route116_Text_JohnsonDefeat:
	.string "Fue divertido aunque perdí.$"

Route116_Text_JohnsonPostBattle:
	.string "¿Quieres quedarte aquí y\n"
	.string "hacerme compañía?$"

Route117_Text_IsaacIntro:
	.string "Oye, ¿podrías batallar contra\n"
	.string "los POKéMON que estoy criando?$"

Route117_Text_IsaacDefeat:
	.string "Los has criado superbamente…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON no es solo poder.\p"
	.string "Pulir un aspecto único del\n"
	.string "carácter es otra forma de disfrutar\l"
	.string "POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Redoblaré mi entrenamiento.\n"
	.string "¿Vendrías a vernos?$"

Route117_Text_IsaacRematchIntro:
	.string "Los POKéMON que he criado se\n"
	.string "ven bien, igual que antes.$"

Route117_Text_IsaacRematchDefeat:
	.string "Sabes cómo criarlos bien.\n"
	.string "Tienes madera de GUARDERÍA…$"

Route117_Text_IsaacPostRematch:
	.string "¡Tus POKéMON crecen bien!\n"
	.string "Deberías llevarlos a CONCURSOS.$"

Route117_Text_LydiaIntro:
	.string "Permíteme evaluar si has criado\n"
	.string "bien a tus POKéMON.$"

Route117_Text_LydiaDefeat:
	.string "Sí, están creciendo bien.$"

Route117_Text_LydiaPostBattle:
	.string "Cría POKéMON prestando más\n"
	.string "atención a su carácter.$"

Route117_Text_LydiaRegister:
	.string "Me alegra haber conocido a un\n"
	.string "TRAINER tan increíble como tú.$"

Route117_Text_LydiaRematchIntro:
	.string "Permíteme evaluar si has criado\n"
	.string "bien a tus POKéMON.$"

Route117_Text_LydiaRematchDefeat:
	.string "Están creciendo admirablemente.$"

Route117_Text_LydiaPostRematch:
	.string "Los POKéMON prefieren distintos\n"
	.string "{POKEBLOCK} según su naturaleza.$"

Route117_Text_DylanIntro:
	.string "Estoy en un triatlón, pero\n"
	.string "¡da igual, luchemos!$"

Route117_Text_DylanDefeat:
	.string "¡Me quedé sin energía!$"

Route117_Text_DylanPostBattle:
	.string "Lo he arruinado...\p"
	.string "Puede que haya quedado último\n"
	.string "en esa batalla...$"

Route117_Text_DylanRegister:
	.string "¿Los POKéMON deben ser fuertes?\n"
	.string "¡Quiero que me entrenes!$"

Route117_Text_DylanRematchIntro:
	.string "Estoy en medio de un triatlón,\n"
	.string "pero voy cómodamente adelante.\l"
	.string "¡Hagamos una batalla rápida!$"

Route117_Text_DylanRematchDefeat:
	.string "¡Me quedé sin energía otra vez!$"

Route117_Text_DylanPostRematch:
	.string "Fui el mejor en nado y ciclismo,\n"
	.string "pero no estoy tan seguro con los\l"
	.string "POKéMON todavía.$"

Route117_Text_MariaIntro:
	.string "Entreno el triatlón con POKéMON,\n"
	.string "así que confío mucho en mi velocidad.$"

Route117_Text_MariaDefeat:
	.string "Supongo que necesito practicar\n"
	.string "un poco más.$"

Route117_Text_MariaPostBattle:
	.string "Entrenar solo sirve si lo haces\n"
	.string "con regularidad.\p"
	.string "¡Bien! ¡Retomaré mi entrenamiento!\n"
	.string "¡Mañana!$"

Route117_Text_MariaRegister:
	.string "Parece que entrenas adecuadamente...\n"
	.string "¡Si quieres, peleamos más tarde!$"

Route117_Text_MariaRematchIntro:
	.string "¿Sigues entrenando duro?\n"
	.string "¡Claro que sí!\l"
	.string "¡Mira los resultados!$"

Route117_Text_MariaRematchDefeat:
	.string "Creo que necesito practicar\n"
	.string "un poco más.$"

Route117_Text_MariaPostRematch:
	.string "Seguiré entrenando mañana.\n"
	.string "¡Luchemos otra vez luego!$"

Route117_Text_DerekIntro:
	.string "¡Antes CAPTURABICHOS!\n"
	.string "¡Ahora MANIACO BICHOS!\p"
	.string "¡Pero mi amor por POKéMON sigue\n"
	.string "siendo el mismo!$"

Route117_Text_DerekDefeat:
	.string "Mi ineptitud también sigue\n"
	.string "siendo la misma…$"

Route117_Text_DerekPostBattle:
	.string "Seguí mi corazón y ahora\n"
	.string "me llaman MANIACO BICHOS…\p"
	.string "Soy experto en POKéMON BICHOS,\n"
	.string "así que es natural que me llamen\l"
	.string "MANIACO BICHOS.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Estoy con mi linda alumna\n"
	.string "socia. ¡Debo hacerlo bien!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: ¡Estoy con mi linda alumna\n"
	.string "socia! ¡Déjame ganar!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Tus POKéMON tienen buenas\n"
	.string "combinaciones.\p"
	.string "¡Casi están a nuestro nivel!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: ¡No podemos aceptar esto!\n"
	.string "Volverás, ¿verdad?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Si quieres luchar,\n"
	.string "trae dos POKéMON contigo.$"

Route117_Text_MegIntro:
	.string "MEG: ¡Me uniré a mi gran compañera\n"
	.string "y te derrotaré!$"

Route117_Text_MegDefeat:
	.string "MEG: ¡Oh, no!\n"
	.string "¡Lo siento, ANNA! Te fallé…$"

Route117_Text_MegPostBattle:
	.string "MEG: Arrastré a ANNA conmigo…\n"
	.string "¡Si no, ella habría ganado!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: ¿Solo tienes un POKéMON?\n"
	.string "Así no podemos luchar.\p"
	.string "Queremos una batalla 2 contra 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: No puedo seguir perdiendo frente\n"
	.string "a mi compañera menor, ¿verdad?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: No pude entrar en ritmo.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Tus POKéMON tienen buenas\n"
	.string "combinaciones.\p"
	.string "¡Casi están a nuestro nivel!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Si quieres luchar,\n"
	.string "trae dos POKéMON contigo.$"

Route117_Text_MegRematchIntro:
	.string "MEG: ¡Me uniré a mi compañera\n"
	.string "mayor y ganaré esta vez!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: ¡Demasiado fuerte!$"

Route117_Text_MegPostRematch:
	.string "MEG: Luché con mi compañera mayor,\n"
	.string "pero perdimos...\p"
	.string "Qué desanimador...$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: ¿Solo tienes un POKéMON?\n"
	.string "No podemos luchar así.\p"
	.string "Queremos una batalla 2 contra 2.$"

Route117_Text_MelinaIntro:
	.string "¿No es lindo? Luchar mientras\n"
	.string "miramos flores hermosas?$"

Route117_Text_MelinaDefeat:
	.string "¡Oh, eso es impresionante!$"

Route117_Text_MelinaPostBattle:
	.string "Es genial trotar\n"
	.string "viendo las flores.$"

Route117_Text_BrandiIntro:
	.string "¡Mira el poder oculto de un\n"
	.string "POKéMON PSÍQUICO!$"

Route117_Text_BrandiDefeat:
	.string "¡Asombroso!$"

Route117_Text_BrandiPostBattle:
	.string "Los POKéMON PSÍQUICOS son complejos.\n"
	.string "Deberías atrapar algunos.$"

Route117_Text_AishaIntro:
	.string "Concéntrate en ganar.\n"
	.string "¡Así es como lucho yo!$"

Route117_Text_AishaDefeat:
	.string "No pierdo tiempo enojándome por\n"
	.string "perder; prefiero entrenar.$"

Route117_Text_AishaPostBattle:
	.string "Si te preocupa perder,\n"
	.string "es más probable que pase.$"

Route118_Text_RoseIntro:
	.string "El aroma de las flores tiene un\n"
	.string "poder mágico. Limpia cuerpo y alma.$"

Route118_Text_RoseDefeat:
	.string "Ay, cielos.\n"
	.string "Parece que he perdido.$"

Route118_Text_RosePostBattle:
	.string "Flores, POKéMON...\n"
	.string "Amo todo lo que huela bien.\p"
	.string "Cosas apestosas...\n"
	.string "Paso de ellas.$"

Route118_Text_RoseRegister:
	.string "Huelo... ¡ese olor es un POKéNAV!\n"
	.string "¡Debemos registrarnos!$"

Route118_Text_RoseRematchIntro:
	.string "¿Te atrajo el dulce aroma\n"
	.string "de este lugar?$"

Route118_Text_RoseRematchDefeat:
	.string "El poder del aroma...\n"
	.string "No parece haber servido de mucho.$"

Route118_Text_RosePostRematch:
	.string "Si usas un aroma dulce bien,\n"
	.string "los POKéMON se sentirán atraídos.$"

Route118_Text_PerryIntro:
	.string "POKéMON voladores que vuelan\n"
	.string "con elegancia... ¡Son los mejores!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "Choqué…$"

Route118_Text_PerryPostBattle:
	.string "Tienes POKéMON geniales.\n"
	.string "Debo entrenar mejor los míos.$"

Route118_Text_ChesterIntro:
	.string "¡Vuelen!\n"
	.string "¡Mis POKéMON VOLADORES!$"

Route118_Text_ChesterDefeat:
	.string "Sí que volaron…$"

Route118_Text_ChesterPostBattle:
	.string "Si fueran más fuertes, podrían\n"
	.string "volar con más libertad…$"

Route118_Text_BarnyIntro:
	.string "Soy PESCADOR, pero también TRAINER.\n"
	.string "Crío los POKéMON que capturo.$"

Route118_Text_BarnyDefeat:
	.string "Pensé que me iba bien con el\n"
	.string "entrenamiento…$"

Route118_Text_BarnyPostBattle:
	.string "No pude ganar entrenando POKéMON\n"
	.string "mientras pescaba…\p"
	.string "¿Lo hice a medias?$"

Route118_Text_WadeIntro:
	.string "Para PESCADORES, el equipo es clave.\p"
	.string "Pero para ENTRENADORES, lo vital\n"
	.string "¡son POKéMON y corazón, claro!$"

Route118_Text_WadeDefeat:
	.string "¿Me vencieron en corazón?$"

Route118_Text_WadePostBattle:
	.string "Pensándolo bien, pescar es una lucha\n"
	.string "entre un PESCADOR y un POKéMON.$"

Route118_Text_DaltonIntro:
	.string "¡Que mi melodía mueva tu alma!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Una guitarra eléctrica no siempre\n"
	.string "tiene que ser ruidosa…\p"
	.string "Se puede tocar para extraer\n"
	.string "esta melodía conmovedora…$"

Route118_Text_DaltonRegister:
	.string "Cuando componga mejores melodías,\n"
	.string "tienes que venir a oírlas, ¿sí?$"

Route118_Text_DaltonRematchIntro:
	.string "Una melodía de mi POKéMON y yo…\n"
	.string "Deja que llegue hasta tu alma.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Al tocar, mis emociones deben llegar\n"
	.string "a ti con mi guitarra eléctrica…$"

Route118_Text_DeandreIntro:
	.string "¡Vamos, vamos, vamos!\n"
	.string "¡POKéMON 1, 2 y 3!$"

Route118_Text_DeandreDefeat:
	.string "¡Vuelvan, POKéMON! ¿Están bien?\n"
	.string "¡¿POKéMON 1, 2 y 3?!$"

Route118_Text_DeandrePostBattle:
	.string "¿No es genial tener un equipo de\n"
	.string "batalla POKéMON?\p"
	.string "¡Puedes copiarme, no me importa!$"

Route119_Text_BrentIntro:
	.string "¡Somos el CÍRCULO MIMETIZADOR!\n"
	.string "¡Imitamos todo lo que haces!$"

Route119_Text_BrentDefeat:
	.string "¡Vaya!\n"
	.string "¡He perdido!$"

Route119_Text_BrentPostBattle:
	.string "¿Qué tiene de bueno imitar?\p"
	.string "Fufufu…\n"
	.string "Nunca lo entenderás…$"

Route119_Text_DonaldIntro:
	.string "¡Al fin nos encontramos!\n"
	.string "¡Mis BUG POKéMON te harán compañía!$"

Route119_Text_DonaldDefeat:
	.string "Desearía no haberte conocido…$"

Route119_Text_DonaldPostBattle:
	.string "Quiero MIMICte un poco más.\n"
	.string "¿Puedes moverte rápido?$"

Route119_Text_TaylorIntro:
	.string "Si avanzas, avanzamos.\p"
	.string "Si giras a la derecha, también…$"

Route119_Text_TaylorDefeat:
	.string "Pero si tú ganas, yo pierdo…$"

Route119_Text_TaylorPostBattle:
	.string "No puedo MIMICtu victoria.\n"
	.string "Eso es simplemente imposible…\l"
	.string "Me quema por dentro…$"

Route119_Text_DougIntro:
	.string "¡Sí, al fin me atrapaste!\n"
	.string "¿O intentabas evitarme?$"

Route119_Text_DougDefeat:
	.string "¡Vaya, fue un gran combate!$"

Route119_Text_DougPostBattle:
	.string "¡Somos el CÍRCULO MIMETISTA!\n"
	.string "Espero que disfrutaras el show.$"

Route119_Text_GregIntro:
	.string "No sabes quién soy, ¿verdad?\p"
	.string "Pero yo tampoco te conozco.\n"
	.string "¡Así que lucharemos!$"

Route119_Text_GregDefeat:
	.string "¡Eres bastante fuerte!$"

Route119_Text_GregPostBattle:
	.string "Hasta que te vayas, seguiremos\n"
	.string "imitando cada uno de tus pasos.$"

Route119_Text_KentIntro:
	.string "El CÍRCULO MIMETISTA se formó con\n"
	.string "gente que ama imitar.\p"
	.string "¡Luchamos en cuanto nos vemos!$"

Route119_Text_KentDefeat:
	.string "¡Me rindo!$"

Route119_Text_KentPostBattle:
	.string "¿Te unes a nuestro CÍRCULO MIMETICO?$"

Route119_Text_JacksonIntro:
	.string "¿Quién tiene el saber y la\n"
	.string "técnica para sobrevivir?\p"
	.string "¡Los POKéMON RANGERS!$"

Route119_Text_JacksonDefeat:
	.string "No tenía suficiente experiencia\n"
	.string "con los POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "¡Dejar la civilización y despertar\n"
	.string "el espíritu salvaje interior!\p"
	.string "Esa es nuestra visión.$"

Route119_Text_JacksonRegister:
	.string "Espero que me des otra revancha sin\n"
	.string "burlarte de mi falta de saber.$"

Route119_Text_JacksonRematchIntro:
	.string "Recuperaré mi espíritu salvaje al\n"
	.string "estar junto a los POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "¡Te has mantenido fuerte!$"

Route119_Text_JacksonPostRematch:
	.string "Cree en tus POKéMON.\n"
	.string "Cree en ti mismo.\p"
	.string "El camino se revelará ante ti.$"

Route119_Text_CatherineIntro:
	.string "¿Oh? Mírate.\p"
	.string "Para alguien en una aventura,\n"
	.string "viajas con muy poco equipaje.$"

Route119_Text_CatherineDefeat:
	.string "¡Los accidentes pasan cuando no\n"
	.string "estás preparado!$"

Route119_Text_CatherinePostBattle:
	.string "Viajas ligero, pero tienes\n"
	.string "todo lo necesario.\p"
	.string "Estás al máximo tanto mental\n"
	.string "como físicamente.$"

Route119_Text_CatherineRegister:
	.string "¿Tienes un POKéNAV?\n"
	.string "Es vital para cualquier TRAINER.\p"
	.string "¡Ah, sí que tienes uno!\n"
	.string "¡Registrémonos entonces!$"

Route119_Text_CatherineRematchIntro:
	.string "¿Cómo va tu viaje con los\n"
	.string "POKéMON?$"

Route119_Text_CatherineRematchDefeat:
	.string "Aún me falta algo...$"

Route119_Text_CatherinePostRematch:
	.string "Así como tú, como TRAINER,\n"
	.string "confías en tus POKéMON, ellos\l"
	.string "confían en ti.$"

Route119_Text_HughIntro:
	.string "¡El cielo es pura promesa!\p"
	.string "¡Nada se compara a la gran\n"
	.string "emoción de volar!$"

Route119_Text_HughDefeat:
	.string "¡K.O. total!$"

Route119_Text_HughPostBattle:
	.string "¡Mi POKéMON ave cumplió mi sueño\n"
	.string "de volar!$"

Route119_Text_PhilIntro:
	.string "¡Te mostraré el potencial mío\n"
	.string "y de mis POKéMON AVE!$"

Route119_Text_PhilDefeat:
	.string "Nos faltó potencial…$"

Route119_Text_PhilPostBattle:
	.string "Desde niño, siempre he\n"
	.string "admirado a los POKéMON AVE…$"

Route119_Text_YasuIntro:
	.string "Vivir en las sombras y la\n"
	.string "oscuridad… Ese es mi destino.\p"
	.string "¡Salgo para retarte!$"

Route119_Text_YasuDefeat:
	.string "¡Admito mi derrota!$"

Route119_Text_YasuPostBattle:
	.string "Los vencidos regresan\n"
	.string "en silencio a las sombras.\l"
	.string "Eso también es el destino…$"

Route119_Text_TakashiIntro:
	.string "¡Si no estás atento,\n"
	.string "vas a sufrir un poco!$"

Route119_Text_TakashiDefeat:
	.string "¡Eres sorprendentemente bueno!$"

Route119_Text_TakashiPostBattle:
	.string "Mi ataque sorpresa terminó en\n"
	.string "fracaso…$"

Route119_Text_HideoIntro:
	.string "¡Para ocultar un árbol, usa un bosque!$"

Route119_Text_HideoDefeat:
	.string "Me rindo ante tu superioridad.$"

Route119_Text_HideoPostBattle:
	.string "¡Para ocultar un árbol, usa un bosque!\n"
	.string "¡Para ocultar un POKéMON, usa uno!\p"
	.string "No hay ningún significado profundo\n"
	.string "en eso.$"

Route119_Text_ChrisIntro:
	.string "Me hablaste…\n"
	.string "¡Así que quieres retarme!\p"
	.string "¡Claro! Probaré los POKéMON que\n"
	.string "atrapé usando SURF!$"

Route119_Text_ChrisDefeat:
	.string "No tengo idea de qué se necesita\n"
	.string "para ganar.$"

Route119_Text_ChrisPostBattle:
	.string "Usa SURF sobre mi POKéMON…\p"
	.string "Luego pesca desde su espalda…\p"
	.string "¡Es un momento muy lujoso!$"

Route119_Text_FabianIntro:
	.string "¡Atácame con un acorde potente!\n"
	.string "¡La victoria es mía!\l"
	.string "¡Es hora de brillar, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "¡Me mostraste quién manda!\n"
	.string "¡Tengo que aceptar la derrota!$"

Route119_Text_FabianPostBattle:
	.string "¡Dame otro acorde potente!\n"
	.string "¡Déjame en paz!\l"
	.string "¡Tu victoria es un castigo!$"

Route119_Text_DaytonIntro:
	.string "¡Jo, jo, jo!\n"
	.string "¡Me gustan los TRAINERS niños!\l"
	.string "¡Que sea una buena batalla!$"

Route119_Text_DaytonDefeat:
	.string "¡Eres increíble!\n"
	.string "¡Jo, jo, jo!$"

Route119_Text_DaytonPostBattle:
	.string "¡Jo, jo, jo!\n"
	.string "¡Intentaré imitar el ánimo de los\l"
	.string "TRAINERS niños como tú!$"

Route119_Text_RachelIntro:
	.string "Donde sea y cuando sea,\n"
	.string "siempre llevo mi sombrilla.$"

Route119_Text_RachelDefeat:
	.string "Oh, pero...\n"
	.string "Eso no es justo.$"

Route119_Text_RachelPostBattle:
	.string "¿Preguntas si mi sombrilla pesa?\n"
	.string "Tu MOCHILA tiene más basura de la\l"
	.string "que yo cargo jamás.$"

Route120_Text_ColinIntro:
	.string "¿Tienes algún movimiento que pueda\n"
	.string "golpear a un POKéMON volador?$"

Route120_Text_ColinDefeat:
	.string "¡Volaste sobre mí!$"

Route120_Text_ColinPostBattle:
	.string "El movimiento VUELO es útil,\n"
	.string "¿no crees?\p"
	.string "Mientras el POKéMON vuela,\n"
	.string "casi ningún ataque le da.$"

Route120_Text_RobertIntro:
	.string "¡Mi POKéMON es fuerte!\n"
	.string "¿Qué tal el tuyo?$"

Route120_Text_RobertDefeat:
	.string "Tus POKéMON fueron más fuertes…$"

Route120_Text_RobertPostBattle:
	.string "Un POKéMON que crece constante es\n"
	.string "uno en quien puedes confiar.$"

Route120_Text_RobertRegister:
	.string "Sé que mejorarás.\n"
	.string "¡Quiero registrarte en mi POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "Un POKéMON que crece constante es\n"
	.string "uno en quien puedes confiar.$"

Route120_Text_RobertRematchDefeat:
	.string "Tus POKéMON son muy fuertes.$"

Route120_Text_RobertPostRematch:
	.string "Mis POKéMON son cada vez más fuertes.\n"
	.string "Yo también debo mejorar.$"

Route120_Text_LorenzoIntro:
	.string "Revisaré tus POKéMON para ver si\n"
	.string "están listos para el exterior.$"

Route120_Text_LorenzoDefeat:
	.string "¡Con POKéMON así de fuertes, no\n"
	.string "necesitarás que te rescaten!$"

Route120_Text_LorenzoPostBattle:
	.string "Viajar a donde quieras con tus\n"
	.string "POKéMON...\l"
	.string "Esa es la alegría de ser TRAINER.$"

Route120_Text_JennaIntro:
	.string "¿Cómo está tu condición física?\n"
	.string "Si no estás en forma, podrías\l"
	.string "sufrir en situaciones críticas.$"

Route120_Text_JennaDefeat:
	.string "Estoy en plena forma, pero...$"

Route120_Text_JennaPostBattle:
	.string "Entrenar es parte de mi rutina.\n"
	.string "Siempre corro con mis POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "¿Quieres luchar?$"

Route120_Text_JeffreyDefeat:
	.string "Perdí…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Me esforzaré más…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "¿Tienes un POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "¿Luchamos otra vez?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Perdí otra vez…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Me esforzaré más…\l"
	.string "¡Por mis BUG POKéMON…!$"

Route120_Text_JenniferIntro:
	.string "Los POKéMON tienen habilidades.\n"
	.string "Si quieres ser un TRAINER de élite,\l"
	.string "estúdialas.$"

Route120_Text_JenniferDefeat:
	.string "Obviamente estás pensando.$"

Route120_Text_JenniferPostBattle:
	.string "Las habilidades de los POKéMON\n"
	.string "cambiarán el estilo de combate.$"

Route120_Text_ChipIntro:
	.string "¿Quién eres?\p"
	.string "¿Buscas las ruinas antiguas que\n"
	.string "según la leyenda podrían\l"
	.string "existir?$"

Route120_Text_ChipDefeat:
	.string "Qué contratiempo tan lamentable…$"

Route120_Text_ChipPostBattle:
	.string "Esa roca gigante… creo que\n"
	.string "podría contener ruinas antiguas.\l"
	.string "Pero no veo ninguna entrada.$"

Route120_Text_ClarissaIntro:
	.string "¿Por qué llevo esta sombrilla?\p"
	.string "Te lo diré si me vences.$"

Route120_Text_ClarissaDefeat:
	.string "Una sombrilla no detiene los\n"
	.string "ataques POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "El sol fuerte no es bueno\n"
	.string "para mis POKéMON.\l"
	.string "Por eso los cubro con mi sombrilla.$"

Route120_Text_AngelicaIntro:
	.string "Yo, POKéMON y mi sombrilla…\p"
	.string "Si falta cualquiera de ellos,\n"
	.string "la belleza se arruinaría.$"

Route120_Text_AngelicaDefeat:
	.string "Arruinaste mi belleza por completo…$"

Route120_Text_AngelicaPostBattle:
	.string "Una sombrilla no te quedaría bien.\p"
	.string "Algo así solo te estorbaría\n"
	.string "en el camino.$"

Route120_Text_KeigoIntro:
	.string "Imitaré los movimientos POKéMON\n"
	.string "para crear nuevas técnicas ninja.$"

Route120_Text_KeigoDefeat:
	.string "Crear nuevas técnicas ninja\n"
	.string "es solo un sueño lejano…$"

Route120_Text_KeigoPostBattle:
	.string "Tal vez debería ser el aprendiz de\n"
	.string "un sensei ninja.$"

Route120_Text_RileyIntro:
	.string "Los ninja nos ocultamos bajo capas\n"
	.string "de camuflaje.\l"
	.string "¡Seguro no sabías dónde estaba!$"

Route120_Text_RileyDefeat:
	.string "¡Perdí!\n"
	.string "¡Debo camuflar mi vergüenza!$"

Route120_Text_RileyPostBattle:
	.string "Nuestras capas de camuflaje son\n"
	.string "hechas a mano.$"

Route120_Text_CallieIntro:
	.string "¡Si no prestas atención,\n"
	.string "podrías lastimarte!$"

Route120_Text_CallieDefeat:
	.string "¡Ay!\n"
	.string "Yo fui quien resultó herido.$"

Route120_Text_CalliePostBattle:
	.string "Me pregunto... ¿Evoluciono a mi\n"
	.string "POKéMON? Así son muy lindos.$"

Route120_Text_LeonelIntro:
	.string "Tus POKéMON del equipo...\n"
	.string "¿Tienes de diferentes tipos?$"

Route120_Text_LeonelDefeat:
	.string "¡He visto tu estrategia en acción!$"

Route120_Text_LeonelPostBattle:
	.string "Es genial que seas tan fuerte\n"
	.string "luchando con tu POKéMON favorito.$"

Route121_Text_VanessaIntro:
	.string "¿Jugarás con mi encantador y\n"
	.string "lindo POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "¡No me refería a eso!$"

Route121_Text_VanessaPostBattle:
	.string "Voy a un CONTEST en LILYCOVE.\p"
	.string "Mi POKéMON no tendrá problemas\n"
	.string "en ganar la MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "Con mi POKéMON, he viajado\n"
	.string "por los cuatro rincones del mundo.\p"
	.string "Diría que tengo mucha confianza\n"
	.string "en mis habilidades.$"

Route121_Text_WalterDefeat:
	.string "Ah, bien jugado.$"

Route121_Text_WalterPostBattle:
	.string "Me gustaría dar la vuelta al mundo\n"
	.string "otra vez con mi POKéMON.$"

Route121_Text_WalterRegister:
	.string "Tu destreza con POKéMON es notable.\n"
	.string "Permíteme registrarte de recuerdo.$"

Route121_Text_WalterRematchIntro:
	.string "Con mi POKéMON, he viajado\n"
	.string "por los cuatro rincones del mundo.\p"
	.string "Diría que tengo mucha confianza\n"
	.string "en mis habilidades.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bien jugado.$"

Route121_Text_WalterPostRematch:
	.string "Tú y tu POKéMON…\p"
	.string "Su destreza juntos será\n"
	.string "fuerte, incluso en el extranjero.$"

Route121_Text_TammyIntro:
	.string "Hay poderes en el mundo que\n"
	.string "están más allá de nuestro saber…$"

Route121_Text_TammyDefeat:
	.string "He perdido…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "Hay un poder misterioso\l"
	.string "actuando allí…$"

Route121_Text_KateIntro:
	.string "KATE: ¡Juntos no tememos a nada!\n"
	.string "¡Verás lo fuertes que somos!$"

Route121_Text_KateDefeat:
	.string "KATE: Quedé mal frente a mi\n"
	.string "compañera menor…$"

Route121_Text_KatePostBattle:
	.string "KATE: Si alguien confía en mí,\n"
	.string "siento la urgencia de lucirme\l"
	.string "ante esa persona…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Si solo tienes un POKéMON,\n"
	.string "no podemos luchar.\p"
	.string "Eso sería hacer bullying.$"

Route121_Text_JoyIntro:
	.string "JOY: ¡Juntas no tememos a nada!\n"
	.string "¡Verás lo fuertes que somos!$"

Route121_Text_JoyDefeat:
	.string "JOY: ¡Perdóname, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Jeje, tendré que entrenar con\n"
	.string "KATE, mi compañera veterana, otra vez.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: ¡Necesitas al menos dos POKéMON\n"
	.string "para retarnos a nosotras!$"

Route121_Text_JessicaIntro:
	.string "¡Detente! ¡Mira bien a mis preciosos\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "¡Oh, cómo te atreves!\n"
	.string "¡No te lo tomes tan en serio!$"

Route121_Text_JessicaPostBattle:
	.string "Tal vez vaya a capturar más POKéMON al\n"
	.string "SAFARI.$"

Route121_Text_JessicaRegister:
	.string "¡Fui blanda contigo esta vez!\n"
	.string "¡La próxima no será así!$"

Route121_Text_JessicaRematchIntro:
	.string "¡Mi querido POKéMON creció!\n"
	.string "¡Míralo bien!$"

Route121_Text_JessicaRematchDefeat:
	.string "¡Oh, cómo te atreves!\n"
	.string "¡Sigues sin darme tregua!$"

Route121_Text_JessicaPostRematch:
	.string "Quizá vaya a capturar más POKéMON al\n"
	.string "SAFARI.$"

Route121_Text_CristinIntro:
	.string "Tengo una rutina.\n"
	.string "Vencer a cinco TRAINERS al día.\l"
	.string "¡Adivina qué! ¡Eres el quinto!$"

Route121_Text_CristinDefeat:
	.string "¡No!\n"
	.string "¡Eres horrible!$"

Route121_Text_CristinPostBattle:
	.string "No esperaba perder tan fácil...\n"
	.string "¡Ganaré la próxima vez!$"

Route121_Text_CristinRegister:
	.string "¡Fue una humillación total!\n"
	.string "No te olvidaré...\l"
	.string "¡Dame tu POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "Tengo una nueva rutina.\n"
	.string "Vencer a diez TRAINERS al día.\l"
	.string "¡Adivina qué! ¡Eres el décimo!$"

Route121_Text_CristinRematchDefeat:
	.string "¡Espera! ¡Qué asco!\n"
	.string "¡Exijo una revancha!$"

Route121_Text_CristinPostRematch:
	.string "Un rival que no puedo vencer...\n"
	.string "Buaaa...\l"
	.string "No puedo creer que pase esto...$"

Route121_Text_CaleIntro:
	.string "¿No ves que llevo todas estas\n"
	.string "cosas conmigo?\p"
	.string "Aun así, ¿insistes en que\n"
	.string "luchemos?$"

Route121_Text_CaleDefeat:
	.string "¡Claro que perdí!\n"
	.string "¡Llevo cosas en ambas manos!$"

Route121_Text_CalePostBattle:
	.string "Compré demasiado en los\n"
	.string "ALMACENES DE CIUDAD VERAZ.\p"
	.string "Están siguiendo el camino.\n"
	.string "Quisiera una MOCHILA como la tuya.$"

Route121_Text_MylesIntro:
	.string "¡No hay nada que me guste más que\n"
	.string "ver los POKéMON de otros!$"

Route121_Text_MylesDefeat:
	.string "¡Súper asombroso!$"

Route121_Text_MylesPostBattle:
	.string "¡Tus POKéMON son geniales!\n"
	.string "¿Cómo los entrenas?$"

Route121_Text_PatIntro:
	.string "¡Quiero que todos vean los POKéMON\n"
	.string "que he criado!$"

Route121_Text_PatDefeat:
	.string "¡Guau!\n"
	.string "¡Espectacular!$"

Route121_Text_PatPostBattle:
	.string "Crio a cada POKéMON con el mismo\n"
	.string "amor y cuidado; no tengo favoritos.$"

Route121_Text_MarcelIntro:
	.string "¡Mis POKéMON jamás han perdido!\n"
	.string "Tras su próxima victoria, los llevaré\l"
	.string "a los CONTESTS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, ¿ahora qué pasó aquí?$"

Route121_Text_MarcelPostBattle:
	.string "Debo entrenar más a mi grupo\n"
	.string "antes de entrar a un CONCURSO.$"

Route123_Text_WendyIntro:
	.string "¿Quieres saber qué tan fuerte eres?\n"
	.string "¡Yo seré la prueba!$"

Route123_Text_WendyDefeat:
	.string "¡Pasaste la prueba con éxito!$"

Route123_Text_WendyPostBattle:
	.string "Para vencerme a mí...\n"
	.string "¡Tu fuerza es maravillosa!$"

Route123_Text_BraxtonIntro:
	.string "Parece que tienes una gran colección\n"
	.string "de MEDALLAS de GIMNASIO.\p"
	.string "¡Veré si eres digno de esas\n"
	.string "MEDALLAS!$"

Route123_Text_BraxtonDefeat:
	.string "¡Oh, eres digno, sin duda!$"

Route123_Text_BraxtonPostBattle:
	.string "¡Hiciste honor a tus MEDALLAS en\n"
	.string "ese combate!$"

Route123_Text_VioletIntro:
	.string "Dicen que los buenos momentos están\n"
	.string "llenos de buenos aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh...\n"
	.string "Huelo el aroma amargo de la miseria...$"

Route123_Text_VioletPostBattle:
	.string "El jardín del MAESTRO BAYA está lleno\n"
	.string "de fragancias estimulantes.$"

Route123_Text_CameronIntro:
	.string "Ser psíquico es cuestión de voluntad.\p"
	.string "He decidido no perder contra nadie.\n"
	.string "¡Eso me hace fuerte!$"

Route123_Text_CameronDefeat:
	.string "Me siento triste…$"

Route123_Text_CameronPostBattle:
	.string "Ser psíquico es cuestión de voluntad.\n"
	.string "Creí que no perdería contra ti…$"

Route123_Text_CameronRegister:
	.string "¡Lo presiento!\n"
	.string "¡Tú y yo lucharemos otra vez!\l"
	.string "Aunque no sé si ganaré…\p"
	.string "Déjame ver tu POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Me convencí de que ya no perderé.\n"
	.string "¡Eso me hace fuerte!$"

Route123_Text_CameronRematchDefeat:
	.string "Me siento triste…$"

Route123_Text_CameronPostRematch:
	.string "Debo entrenar en el MONTE CENIZA…\n"
	.string "Así jamás te venceré…$"

Route123_Text_JackiIntro:
	.string "No te alegres si tu POKéMON\n"
	.string "desarrolla poderes psíquicos.\p"
	.string "Debes pulirlos para que sean\n"
	.string "realmente útiles.$"

Route123_Text_JackiDefeat:
	.string "¡Abrumado!$"

Route123_Text_JackiPostBattle:
	.string "Todos tenemos poderes psíquicos.\n"
	.string "Solo olvidamos cómo usarlos.$"

Route123_Text_JackiRegister:
	.string "Me gustaría enfrentarte otra vez.\n"
	.string "¿Te parece bien?$"

Route123_Text_JackiRematchIntro:
	.string "¿Has despertado los poderes psíquicos\n"
	.string "que hay en ti?$"

Route123_Text_JackiRematchDefeat:
	.string "¡Asombroso!$"

Route123_Text_JackiPostRematch:
	.string "Tu poder con los POKéMON...\n"
	.string "Eso también podría ser psíquico.$"

Route123_Text_MiuIntro:
	.string "MIU: Hola, ENTRENADOR. Espero que tus\n"
	.string "POKéMON no lloren al perder.$"

Route123_Text_MiuDefeat:
	.string "MIU: Oh, oh, perdimos.$"

Route123_Text_MiuPostBattle:
	.string "MIU: ENTRENADOR, tus POKéMON son\n"
	.string "fuertes porque son amigos.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: No es divertido luchar si no\n"
	.string "tienes dos POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: ¡Bien!\n"
	.string "¡Venceremos al POKéMON del TRAINER!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Oh no, perdimos.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: ¿Por qué eres tan fuerte?\n"
	.string "Nunca habíamos perdido.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: No es divertido luchar si no\n"
	.string "tienes dos POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Donde duermen los espíritus POKéMON…\l"
	.string "¿Dormirá tu POKéMON?$"

Route123_Text_KindraDefeat:
	.string "Desbordante de vitalidad…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Donde duermen los espíritus POKéMON…\p"
	.string "Debe rebosar un poder que\n"
	.string "calma a los espíritus…$"

Route123_Text_FernandoIntro:
	.string "¡Apagaré tus luces mientras\n"
	.string "toco esta melodía!$"

Route123_Text_FernandoDefeat:
	.string "¡Oye, espera!\n"
	.string "¡Aún estaba tocando la intro!$"

Route123_Text_FernandoPostBattle:
	.string "Eres muy firme.\n"
	.string "Quiero escribir una canción sobre ti.$"

Route123_Text_FernandoRegister:
	.string "La próxima vez, escucha la\n"
	.string "canción completa, ¿sí?$"

Route123_Text_FernandoRematchIntro:
	.string "¡Hoy es el día en que lo lograré!\n"
	.string "¡Apagaré tus luces antes de\l"
	.string "terminar mi canción!$"

Route123_Text_FernandoRematchDefeat:
	.string "¡Oye, espera!\n"
	.string "¡Ni siquiera llegué al coro!$"

Route123_Text_FernandoPostRematch:
	.string "Pensé que quedarías tan cautivado\n"
	.string "por mi música que perderías.$"

Route123_Text_DavisIntro:
	.string "¡Este es mi genial BUG POKéMON!\n"
	.string "Mi hermano mayor me lo dio.$"

Route123_Text_DavisDefeat:
	.string "¡Buaaaa!\n"
	.string "¡Eres malo!$"

Route123_Text_DavisPostBattle:
	.string "No le digas a mi hermano que perdí.\n"
	.string "¡Tienes que guardarlo en secreto!$"

Route123_Text_JazmynIntro:
	.string "¡Mi confianza subirá al vencer a\n"
	.string "alguien obviamente fuerte!$"

Route123_Text_JazmynDefeat:
	.string "Ahí se va mi confianza...$"

Route123_Text_JazmynPostBattle:
	.string "Dicen que no hay que juzgar a alguien\n"
	.string "por su apariencia.\p"
	.string "Pero a veces, no mienten...$"

Route123_Text_FrederickIntro:
	.string "¡Hola, niño!\n"
	.string "¿Tienes un momento?$"

Route123_Text_FrederickDefeat:
	.string "¡Ah, un niño muy capaz!\n"
	.string "Déjame darte algo de dinero.$"

Route123_Text_FrederickPostBattle:
	.string "¿Aportar a tu mesada?\n"
	.string "¿No bastó el premio en dinero?$"

Route123_Text_AlbertoIntro:
	.string "¡Debo decirte que los POKéMON\n"
	.string "AVES son mi obsesión!\p"
	.string "¡Las aves son geniales!\n"
	.string "¡Son los mejores!$"

Route123_Text_AlbertoDefeat:
	.string "¡Derrotados, los POKéMON PÁJARO molan!$"

Route123_Text_AlbertoPostBattle:
	.string "Junto plumas de POKéMON AVES que\n"
	.string "caen en las batallas.\p"
	.string "Haré un sombrero con plumas de\n"
	.string "POKéMON AVES.$"

Route123_Text_EdIntro:
	.string "Si no hay ENTRENADORES cerca,\n"
	.string "hago que mis POKéMON luchen.\l"
	.string "Los observo.$"

Route123_Text_EdDefeat:
	.string "Me gustan un poco tus POKéMON.$"

Route123_Text_EdPostBattle:
	.string "¡Jeje, robo tus ideas de combate!\n"
	.string "Creo que me harán mejor.$"

Route123_Text_JonasIntro:
	.string "¡Estaba al acecho y un ENTRENADOR\n"
	.string "cayó en mi trampa!$"

Route123_Text_JonasDefeat:
	.string "Si no pierdes, ¿cómo voy a\n"
	.string "divertirme jugando al ninja?$"

Route123_Text_JonasPostBattle:
	.string "La próxima emboscaré a un\n"
	.string "ENTRENADOR más débil.$"

Route123_Text_KayleyIntro:
	.string "Acabo de comprar esta sombrilla.\n"
	.string "¡Mi ternura subirá un tercio!$"

Route123_Text_KayleyDefeat:
	.string "¡Eres como cinco veces\n"
	.string "mejor que yo!$"

Route123_Text_KayleyPostBattle:
	.string "Usar accesorios es el secreto\n"
	.string "del atractivo de la moda.$"

Route124_Text_SpencerIntro:
	.string "Oye, ¿estás perdido en el mar?\p"
	.string "Si vences a mi POKéMON,\n"
	.string "seré tu piloto.$"

Route124_Text_SpencerDefeat:
	.string "¡Perdí el rumbo en la batalla!$"

Route124_Text_SpencerPostBattle:
	.string "Muchos pierden el rumbo en el mar.\p"
	.string "Si es tu caso, usa el MAPA\n"
	.string "del POKéNAV.$"

Route124_Text_RolandIntro:
	.string "¡Hm! Vas sobre un POKéMON en vez\n"
	.string "de nadar tú mismo...\p"
	.string "¡Qué envidia!$"

Route124_Text_RolandDefeat:
	.string "¡Oh!\n"
	.string "No puedo…$"

Route124_Text_RolandPostBattle:
	.string "Tengo mucho frío…\n"
	.string "Llevo demasiado tiempo en el agua…\p"
	.string "Quisiera montar un POKéMON como tú…$"

Route124_Text_JennyIntro:
	.string "Si flotas en el mar así,\n"
	.string "los POKéMON vienen a jugar.$"

Route124_Text_JennyDefeat:
	.string "Oh, rayos.\n"
	.string "He perdido.$"

Route124_Text_JennyPostBattle:
	.string "Al nadar, noté que algunos\n"
	.string "POKéMON atacan y otros miran.\p"
	.string "Creo que los POKéMON tienen su\n"
	.string "propia personalidad.$"

Route124_Text_JennyRegister:
	.string "Es un capricho, pero tal vez\n"
	.string "me registres en tu POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Si flotas así en el mar,\n"
	.string "¡los ENTRENADORES te retarán!$"

Route124_Text_JennyRematchDefeat:
	.string "Qué extraño...\n"
	.string "Perdí otra vez...$"

Route124_Text_JennyPostRematch:
	.string "Esto no tiene nada que ver,\n"
	.string "pero iré a la CASA DE LAS TRAMPAS.$"

Route124_Text_GraceIntro:
	.string "Me aburro de nadar...\n"
	.string "¿Qué tal una batalla?$"

Route124_Text_GraceDefeat:
	.string "¡No sabía que eras\n"
	.string "tan fuerte!$"

Route124_Text_GracePostBattle:
	.string "Todo tu esfuerzo te ha\n"
	.string "vuelto así de fuerte.$"

Route124_Text_ChadIntro:
	.string "Fufufufu... Me sumerjo profundo\n"
	.string "para pasar desapercibido.\l"
	.string "¡Soy experto en las profundidades!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub...\n"
	.string "Me hundo...$"

Route124_Text_ChadPostBattle:
	.string "Me dijeron que hay un lugar\n"
	.string "para BUCEAR por aquí.\p"
	.string "Me dan ganas de bajar al fondo\n"
	.string "otra vez...$"

Route124_Text_LilaIntro:
	.string "LILA: Suspiro...\p"
	.string "Estoy en el mar, ¿pero con quién?\n"
	.string "¡Con mi hermanito!\p"
	.string "¡Luchemos para no pensar\n"
	.string "en eso!$"

Route124_Text_LilaDefeat:
	.string "LILA: ¡ROY! ¡Perdimos por tu culpa!\n"
	.string "¡Ya verás cuando lleguemos!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Suspiro...\p"
	.string "Si en vez de mi hermano tuviera\n"
	.string "a un lindo novio a mi lado...$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: ¿Quieres luchar contra nosotros?\n"
	.string "Solo si tienes dos POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: ¡Mi hermana es fuerte en POKéMON!\p"
	.string "¡No llores cuando pierdas!$"

Route124_Text_RoyDefeat:
	.string "ROY: Oh, oh...\n"
	.string "Mi hermana me va a regañar...$"

Route124_Text_RoyPostBattle:
	.string "ROY: Mi hermana da mucho miedo\n"
	.string "cuando se enoja.\p"
	.string "Por eso no tiene\n"
	.string "novio.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: ¿Lucharás con nosotros otra vez?\n"
	.string "Pero ve con calma la próxima, ¿sí?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: ¿Quieres luchar contra nosotros?\n"
	.string "Trae dos POKéMON entonces.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Suspiro...\p"
	.string "Estoy en el mar, ¿pero con quién?\n"
	.string "¡Con mi hermanito!\p"
	.string "Hola, hace tiempo. ¡Luchamos para\n"
	.string "no pensar en mis problemas!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ¡ROY!\n"
	.string "¡Es tu culpa que perdiéramos otra vez!\p"
	.string "¡Habrá entrenamiento más tarde!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Suspiro...\p"
	.string "Si tuviera un novio lindo, ganaríamos\n"
	.string "con combinaciones encantadoras...$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: ¿Planeas luchar contra nosotros?\n"
	.string "Solo si tienes dos POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: Si perdemos, me va a ir mal.\n"
	.string "¡Voy a darlo todo en esta batalla!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Oh, no...\n"
	.string "Mi hermana me va a regañar otra vez.$"

Route124_Text_RoyPostRematch:
	.string "ROY: Mi hermana da mucho miedo\n"
	.string "cuando se enoja.\p"
	.string "Me hará entrenar muy duro con los\n"
	.string "POKéMON más tarde...$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: ¿Quieres luchar contra nosotros?\n"
	.string "Entonces trae dos POKéMON.$"

Route124_Text_DeclanIntro:
	.string "Nado aquí solito\n"
	.string "en este mar tan bello.\p"
	.string "No hay otra palabra.\n"
	.string "¡Esto es patético!$"

Route124_Text_DeclanDefeat:
	.string "Me siento triste.\n"
	.string "Triste como el cielo…$"

Route124_Text_DeclanPostBattle:
	.string "Debería hablar con nadadoras\n"
	.string "e invitarlas a nadar.$"

Route124_Text_IsabellaIntro:
	.string "No voy a perder contra un\n"
	.string "ENTRENADOR surfista.$"

Route124_Text_IsabellaDefeat:
	.string "¡Solo es sudor en mis ojos!\n"
	.string "¡No estoy llorando!$"

Route124_Text_IsabellaPostBattle:
	.string "Puedes hallar fragmentos de colores\n"
	.string "por estos rumbos.$"

Route125_Text_NolenIntro:
	.string "Te oí venir, ¡así que te\n"
	.string "estuve esperando!$"

Route125_Text_NolenDefeat:
	.string "¡Me rindo!$"

Route125_Text_NolenPostBattle:
	.string "El sonido viaja más rápido en agua\n"
	.string "que a través del aire.$"

Route125_Text_StanIntro:
	.string "¡Hola!\n"
	.string "¡Mira mi genial POKéMON!$"

Route125_Text_StanDefeat:
	.string "Me hundí...$"

Route125_Text_StanPostBattle:
	.string "El encanto de HORSEA me cautivó,\n"
	.string "así que yo también nadé.$"

Route125_Text_TanyaIntro:
	.string "Me cansé de nadar.\n"
	.string "¿Quieres luchar conmigo?$"

Route125_Text_TanyaDefeat:
	.string "¡Eres demasiado!$"

Route125_Text_TanyaPostBattle:
	.string "Uff...\n"
	.string "¿Hacia dónde queda CIUDAD COLMENA?$"

Route125_Text_SharonIntro:
	.string "¿Quieres enfrentar a los POKéMON\n"
	.string "de AGUA que he criado?$"

Route125_Text_SharonDefeat:
	.string "Lo perdí...$"

Route125_Text_SharonPostBattle:
	.string "Tu poder... Eres el verdadero.\n"
	.string "¡Estoy asombrado!$"

Route125_Text_ErnestIntro:
	.string "¡Ahoy! ¡Soy un fuerte MARINERO!\n"
	.string "¡He desafiado los mares del mundo!$"

Route125_Text_ErnestDefeat:
	.string "¡Gwrroooar!\n"
	.string "¡No pude ganar!$"

Route125_Text_ErnestPostBattle:
	.string "La marea sube y baja dentro de la\n"
	.string "CUEVA CORAL.\p"
	.string "Pasan unas seis horas entre la\n"
	.string "marea alta y baja. ¿Lo sabías?$"

Route125_Text_ErnestRegister:
	.string "Regístrame en tu POKéNAV,\n"
	.string "y te diré algo bueno.$"

Route125_Text_ErnestRematchIntro:
	.string "¡Ya es hora de que me vengue\n"
	.string "de ti! ¡Vamos, a luchar!$"

Route125_Text_ErnestRematchDefeat:
	.string "¡No pude ganar!\n"
	.string "¡Simplemente no pude ganar!$"

Route125_Text_ErnestRematchPostBattle:
	.string "La CUEVA CORAL…\p"
	.string "Hay sitios a los que puedes o no\n"
	.string "entrar según suba o baje\l"
	.string "la marea.\p"
	.string "Por cierto, pasan seis horas de\n"
	.string "pleamar a bajamar. ¡No lo olvides!$"

Route125_Text_KimIntro:
	.string "KIM: Un viejo gracioso vive en la\n"
	.string "CUEVA CORAL. Me lo dijeron.\l"
	.string "¿Tú también irás a verlo?$"

Route125_Text_KimDefeat:
	.string "KIM: Pensé que ganaríamos.$"

Route125_Text_KimPostBattle:
	.string "KIM: Un viejo gracioso vive en la\n"
	.string "CUEVA CORAL, ¿verdad?\p"
	.string "¡Vamos a verlo, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: ¡No, no, no! Necesitas dos\n"
	.string "POKéMON, ¡o no servirá!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, ¿puedes decirme qué\n"
	.string "estamos buscando aquí fuera?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, estuvimos muy cerca.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, ¿de verdad entraremos en\n"
	.string "la CUEVA CORAL?\l"
	.string "Nos mojaremos todos.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, jamás podríamos hacer\n"
	.string "una batalla de 2 contra 1.$"

Route125_Text_PresleyIntro:
	.string "¿Por qué una BIRDKEEPER como yo\n"
	.string "vendría hasta el mar?$"

Route125_Text_PresleyDefeat:
	.string "Está bien.\n"
	.string "Te diré por qué estoy aquí.$"

Route125_Text_PresleyPostBattle:
	.string "Puse un mensaje en una botella y\n"
	.string "la lancé al mar.\p"
	.string "¡Seguro que una SWIMMER la\n"
	.string "encontrará!$"

Route125_Text_AuronIntro:
	.string "¡Oye! ¿Fuiste tú quien tiró basura\n"
	.string "al mar?$"

Route125_Text_AuronDefeat:
	.string "Oh, no estabas tirando basura al\n"
	.string "mar.$"

Route125_Text_AuronPostBattle:
	.string "Vi una botella fea flotando en las\n"
	.string "olas hace poco.\p"
	.string "¡Me enfurece que alguien contamine\n"
	.string "el mar!$"

Route126_Text_BarryIntro:
	.string "¡Nadar ejercita todo el cuerpo!\n"
	.string "¡Te pondrás en forma!$"

Route126_Text_BarryDefeat:
	.string "¡Lo admito!\n"
	.string "¡Tú ganas!$"

Route126_Text_BarryPostBattle:
	.string "Gracias a mi rutina de natación...\n"
	.string "¡Mira! ¡Admira este físico!$"

Route126_Text_DeanIntro:
	.string "Esta blanca montaña de roca\n"
	.string "es CIUDAD ARCOIRIS.$"

Route126_Text_DeanDefeat:
	.string "¿Me han derrotado?$"

Route126_Text_DeanPostBattle:
	.string "No hallo la entrada a\n"
	.string "CIUDAD ARCOIRIS. ¿Dónde estará?$"

Route126_Text_NikkiIntro:
	.string "¡Ufufufufu!\n"
	.string "¡Soy una sirena!$"

Route126_Text_NikkiDefeat:
	.string "¡Mi fantasía explotó como una burbuja!\n"
	.string "Blub, blub, blub...$"

Route126_Text_NikkiPostBattle:
	.string "Me aplastaste... Quiero\n"
	.string "desaparecer en la desesperación...$"

Route126_Text_BrendaIntro:
	.string "¡Hola, chico!\n"
	.string "¿Quieres luchar conmigo?$"

Route126_Text_BrendaDefeat:
	.string "¡Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "¡Amo jugar con POKéMON en\n"
	.string "el mar así!$"

Route126_Text_PabloIntro:
	.string "¡Mira este cuerpo esculpido!\n"
	.string "¡Estoy más fit que un BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "¡Ups! ¡Demasiado fuerte!\n"
	.string "¡Nada mal! ¡Nada mal!$"

Route126_Text_PabloPostBattle:
	.string "¡Perder despertó mis sentidos!\n"
	.string "¡Entrenaré más a mis POKéMON!$"

Route126_Text_PabloRegister:
	.string "¡Sí, no estás nada mal!\n"
	.string "¡Me gustaría conocerte más!$"

Route126_Text_PabloRematchIntro:
	.string "¡Mira este cuerpo hermoso!\n"
	.string "¡Tengo más curvas que un SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "¡Vaya! ¡Eres muy fuerte!\n"
	.string "¡Nada mal! ¡Nada mal!$"

Route126_Text_PabloPostRematch:
	.string "¡Entrenaré aún más duro!\n"
	.string "¡Me motivaste mucho!\l"
	.string "¡Tienes que volver pronto!$"

Route126_Text_LeonardoIntro:
	.string "El año pasado ni sabía nadar,\n"
	.string "pero ahora soy un NADADOR.\p"
	.string "Siento que puedo con todo ahora.$"

Route126_Text_LeonardoDefeat:
	.string "Cielos, ser codicioso no me\n"
	.string "sirvió de nada.$"

Route126_Text_LeonardoPostBattle:
	.string "Si practicas algo,\n"
	.string "mejorarás en ello.\p"
	.string "Eres joven, ¡no temas intentar\n"
	.string "todo tipo de cosas!$"

Route126_Text_IsobelIntro:
	.string "Si el agua de mar te entra en la\n"
	.string "nariz, ¿no se siente fatal?$"

Route126_Text_IsobelDefeat:
	.string "¡Ah! Pero tú...\n"
	.string "¡Glub!$"

Route126_Text_IsobelPostBattle:
	.string "¡Uf, tragué un poco de agua!\n"
	.string "¡Sabe amarga! ¡Sabe salada!!$"

Route126_Text_SiennaIntro:
	.string "¡Pondré todo mi corazón\n"
	.string "en esto!$"

Route126_Text_SiennaDefeat:
	.string "¡Tuviste más corazón!$"

Route126_Text_SiennaPostBattle:
	.string "Debo calmarme ahora...\n"
	.string "Iré a dar un clavado.$"

Route127_Text_CamdenIntro:
	.string "Lo veo en tu cara.\n"
	.string "Quieres desafiarme.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa...$"

Route127_Text_CamdenPostBattle:
	.string "Un buen combate me hace sentir\n"
	.string "renovado y sereno.$"

Route127_Text_DonnyIntro:
	.string "¿Tienes un rival al que odias\n"
	.string "perderle?$"

Route127_Text_DonnyDefeat:
	.string "¡Arrrgh!\n"
	.string "¡Odio perder!$"

Route127_Text_DonnyPostBattle:
	.string "Si tienes un rival, ¿no sientes que\n"
	.string "debes seguir mejorando?\l"
	.string "¿Verdad?$"

Route127_Text_JonahIntro:
	.string "Pescando he alcanzado un estado de\n"
	.string "serenidad absoluta...\p"
	.string "Permíteme demostrarlo...$"

Route127_Text_JonahDefeat:
	.string "Aunque haya perdido, mi corazón\n"
	.string "está tranquilo...$"

Route127_Text_JonahPostBattle:
	.string "No importa no pescar nada.\n"
	.string "El sedal sigue en el agua...$"

Route127_Text_HenryIntro:
	.string "¡Vaya! ¿No me digas que pesqué a\n"
	.string "un POKéMON que SURFEA?$"

Route127_Text_HenryDefeat:
	.string "¡No puedo seguir el ritmo!$"

Route127_Text_HenryPostBattle:
	.string "¡Sería un problema si pescara a\n"
	.string "tu fuerte POKéMON!$"

Route127_Text_RogerIntro:
	.string "¡Oye! ¡Es un duelo entre un fan\n"
	.string "de POKéMON y un experto pescador!$"

Route127_Text_RogerDefeat:
	.string "¡No! ¡Mi sedal se enredó!\n"
	.string "¡Se acabó la fiesta!$"

Route127_Text_RogerPostBattle:
	.string "¡Mi sedal está bailando!\n"
	.string "¡El tango del nudo! ¡Jaja, grrr!$"

Route127_Text_AidanIntro:
	.string "Los POKéMON ave ven muy bien.\n"
	.string "Ven presas desde muy alto.$"

Route127_Text_AidanDefeat:
	.string "Uff... Me rindo.$"

Route127_Text_AidanPostBattle:
	.string "Hay muchos sitios para bucear en\n"
	.string "el mar por aquí.\p"
	.string "Se ven fácil desde el cielo por\n"
	.string "su color más oscuro.$"

Route127_Text_KojiIntro:
	.string "Corre descalzo.\n"
	.string "¡Eso endurecerá tus plantas!$"

Route127_Text_KojiDefeat:
	.string "¡Ay!\n"
	.string "¡Se me metió una piedra en la uña!$"

Route127_Text_KojiPostBattle:
	.string "Ir descalzo es genial.\n"
	.string "Pero tus ZAPATOS DE CORRER molan.$"

Route127_Text_KojiRegister:
	.string "¡Esto les pasa a los que me vencen!\n"
	.string "Espero que podamos repetir esto.$"

Route127_Text_KojiRematchIntro:
	.string "Sigo corriendo descalzo a diario.\n"
	.string "¡Mis plantas son fuertes!$"

Route127_Text_KojiRematchDefeat:
	.string "¡Ay!\n"
	.string "¡Las piedras se clavaron en mis pies!$"

Route127_Text_KojiPostRematch:
	.string "¿Quieres andar descalzo un rato?\n"
	.string "¿Para que use tus ZAPATOS CORRER?$"

Route127_Text_AthenaIntro:
	.string "Deberíamos tener un combate\n"
	.string "lento y metódico.$"

Route127_Text_AthenaDefeat:
	.string "No me diste oportunidad de\n"
	.string "armar una estrategia.$"

Route127_Text_AthenaPostBattle:
	.string "Rodeado del mar y el cielo azul,\n"
	.string "siento que el tiempo se detiene.$"

Route128_Text_IsaiahIntro:
	.string "CIUDAD VERIDIANO aún queda\n"
	.string "muy lejos...$"

Route128_Text_IsaiahDefeat:
	.string "Mi primera victoria parece estar\n"
	.string "muy lejos también…$"

Route128_Text_IsaiahPostBattle:
	.string "Toda mi vida he perdido,\n"
	.string "¡pero nunca me rendiré!$"

Route128_Text_IsaiahRegister:
	.string "Sé que no soy bueno, pero creo que\n"
	.string "algún día ganaré.\p"
	.string "Regístrame en tu POKéNAV, por favor.$"

Route128_Text_IsaiahRematchIntro:
	.string "Aún me siento bien. Seguiré\n"
	.string "nadando hacia CIUDAD VERIDIANO.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Aún no he probado mi primera victoria…$"

Route128_Text_IsaiahPostRematch:
	.string "Llegaré a CIUDAD VERIDIANO\n"
	.string "donde algún día podré ganar…$"

Route128_Text_KatelynIntro:
	.string "Debes nadar, pedalear y luego correr\n"
	.string "un maratón en un triatlón.\p"
	.string "Es una carrera agotadora de\n"
	.string "tres eventos.$"

Route128_Text_KatelynDefeat:
	.string "Una batalla POKéMON también agota…$"

Route128_Text_KatelynPostBattle:
	.string "Ahora debo usar la BIKE, pero...\n"
	.string "estoy a punto de rendirme...$"

Route128_Text_KatelynRegister:
	.string "Bueno, mejor saco provecho de esto.\n"
	.string "Quiero una revancha algún día.$"

Route128_Text_KatelynRematchIntro:
	.string "Un triatlón es largo. Pero creo que el\n"
	.string "camino al CAMPEÓN POKéMON\l"
	.string "también es largo y agotador.$"

Route128_Text_KatelynRematchDefeat:
	.string "Una batalla POKéMON es realmente\n"
	.string "dura e implacable...$"

Route128_Text_KatelynPostRematch:
	.string "Piensa seriamente en los retos de la\n"
	.string "RUTA VICTORIA.$"

Route128_Text_AlexaIntro:
	.string "Hemos trabajado duro para ir a la\n"
	.string "LIGA POKéMON...\p"
	.string "¡No podemos perder ahora!$"

Route128_Text_AlexaDefeat:
	.string "¡Oh!\n"
	.string "¡¿Cómo pudo pasar esto?!$"

Route128_Text_AlexaPostBattle:
	.string "Tras todo lo que hice para llegar,\n"
	.string "no me rendiré por un tropiezo.$"

Route128_Text_RubenIntro:
	.string "¡No hay ENTRENADOR más fuerte que yo!$"

Route128_Text_RubenDefeat:
	.string "¡No puede ser!$"

Route128_Text_RubenPostBattle:
	.string "¡Probablemente no haya ENTRENADOR\n"
	.string "más fuerte que tú!$"

Route128_Text_WayneIntro:
	.string "Quiero ir a EVER GRANDE, así que\n"
	.string "atrapé un POKéMON que sabe\l"
	.string "CASCADA para subir la caída.$"

Route128_Text_WayneDefeat:
	.string "¡Estoy desolado!$"

Route128_Text_WaynePostBattle:
	.string "¡Ay, qué mal!\p"
	.string "Mi POKéMON sabe CASCADA, pero\n"
	.string "¡no tengo la MEDALLA de SOOTOPOLIS!$"

Route128_Text_HarrisonIntro:
	.string "Te ves muy fuerte.\n"
	.string "¿Me pregunto si podré ganar?$"

Route128_Text_HarrisonDefeat:
	.string "¡Ay!\n"
	.string "Supongo que era imposible ganar.$"

Route128_Text_HarrisonPostBattle:
	.string "Hay muchos TRAINERS fuertes\n"
	.string "en ISLA FARO.\p"
	.string "¿Crees que esto es demasiado\n"
	.string "para mí?$"

Route128_Text_CarleeIntro:
	.string "El sol parece ser más fuerte\n"
	.string "en esta zona.$"

Route128_Text_CarleeDefeat:
	.string "No podía ver bien por el\n"
	.string "resplandor del sol.$"

Route128_Text_CarleePostBattle:
	.string "Debo volver pronto.\n"
	.string "Tengo que ponerme más bloqueador.$"

Route129_Text_ChaseIntro:
	.string "Es mi primer triatlón.\n"
	.string "¡Estoy tenso y nervioso!$"

Route129_Text_ChaseDefeat:
	.string "¡Wroooaaar!\n"
	.string "¡No pude ganar!$"

Route129_Text_ChasePostBattle:
	.string "Si estoy tan tenso, no podré\n"
	.string "darlo todo.$"

Route129_Text_AllisonIntro:
	.string "Estoy en medio de un triatlón,\n"
	.string "pero claro, ¡luchemos!$"

Route129_Text_AllisonDefeat:
	.string "¡Estaba seguro de que ganaría!$"

Route129_Text_AllisonPostBattle:
	.string "¿Sabes qué es lo mejor\n"
	.string "de los triatlones?\p"
	.string "¡Probar tus límites de fuerza\n"
	.string "y resistencia contra\l"
	.string "la naturaleza!$"

Route129_Text_ReedIntro:
	.string "¡Oye, oye!\n"
	.string "¡Vamos a empezar ya!$"

Route129_Text_ReedDefeat:
	.string "Me vencieron.\n"
	.string "¡Eso es todo, terminé!$"

Route129_Text_ReedPostBattle:
	.string "No hay nada para un perdedor.\n"
	.string "Es hora de volver a casa.$"

Route129_Text_TishaIntro:
	.string "¿Cuál es la prisa?\n"
	.string "Hagámoslo con calma y tranquilidad.$"

Route129_Text_TishaDefeat:
	.string "Vaya.\n"
	.string "Quería relajarme un poco más…$"

Route129_Text_TishaPostBattle:
	.string "¿No odias cometer errores al\n"
	.string "tener prisa?\p"
	.string "Por eso intento hacer las cosas\n"
	.string "lentamente.$"

Route129_Text_ClarenceIntro:
	.string "Surfear no es tan fácil como parece,\n"
	.string "¿verdad?$"

Route129_Text_ClarenceDefeat:
	.string "Ganar no es nada fácil.$"

Route129_Text_ClarencePostBattle:
	.string "¿Apuntas a la LIGA POKéMON?\n"
	.string "¡Sigue así!$"

Route130_Text_RodneyIntro:
	.string "¡Qué sorpresa! No esperaba ver a un\n"
	.string "ENTRENADOR en el mar.\p"
	.string "¡Creo que debemos luchar!$"

Route130_Text_RodneyDefeat:
	.string "Este chico es muy fuerte...$"

Route130_Text_RodneyPostBattle:
	.string "Tus ojos son de alguien que ha\n"
	.string "superado retos difíciles\l"
	.string "y ganó. ¡Te queda muy bien!$"

Route130_Text_KatieIntro:
	.string "En el mar azul profundo,\n"
	.string "mi roto corazón azul halla\l"
	.string "consuelo entre las olas.$"

Route130_Text_KatieDefeat:
	.string "Como el vasto mar azul,\n"
	.string "el mundo POKéMON tiene\l"
	.string "profundidades increíbles.$"

Route130_Text_KatiePostBattle:
	.string "Los niños del mundo sueñan\n"
	.string "con ser algún día\l"
	.string "el CAMPEÓN POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Flotar así en mar abierto...\n"
	.string "Es muy tranquilo.$"

Route130_Text_SantiagoDefeat:
	.string "¡Necesitaba estar menos tranquilo!$"

Route130_Text_SantiagoPostBattle:
	.string "Nadar y luchar así...\n"
	.string "Soy un tipo muy feliz...$"

Route131_Text_RichardIntro:
	.string "El mar rebosa de POKéMON.\n"
	.string "No es fácil nadar, te lo digo.$"

Route131_Text_RichardDefeat:
	.string "Los POKéMON de los ENTRENADORES\n"
	.string "son realmente fuertes...$"

Route131_Text_RichardPostBattle:
	.string "¡Ah... ah...\n"
	.string "Estoy agotado...\p"
	.string "Ir es fácil. Lo difícil es\n"
	.string "el camino de vuelta.\p"
	.string "¿Tendré energía para hacer\n"
	.string "el viaje de regreso?$"

Route131_Text_HermanIntro:
	.string "¡El mar... el mar... el mar...\n"
	.string "Mar hasta donde alcanza la vista!\l"
	.string "¡Estoy harto del mar!$"

Route131_Text_HermanDefeat:
	.string "¡Puaj!$"

Route131_Text_HermanPostBattle:
	.string "Me aburre el mar, pero debo nadar.\p"
	.string "¡Nací para nadar!\n"
	.string "Eso soy yo.$"

Route131_Text_SusieIntro:
	.string "¡Hola, cielo, espera!\n"
	.string "¡Deberíamos luchar tú y yo!$"

Route131_Text_SusieDefeat:
	.string "¡Eres fuerte a pesar de tu\n"
	.string "apariencia!$"

Route131_Text_SusiePostBattle:
	.string "¿Viste a un chico que se queja de\n"
	.string "estar aburrido del mar?\p"
	.string "Solo habla.\n"
	.string "¡Ama el mar desesperadamente!$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "¡Esto me supera!$"

Route131_Text_KaraPostBattle:
	.string "Tal vez no es mi traje de baño lo que\n"
	.string "atrae a los hombres. ¡Es mi belleza!$"

Route131_Text_ReliIntro:
	.string "RELI: ¡Trabajaremos como hermanos\n"
	.string "para derrotarte!$"

Route131_Text_ReliDefeat:
	.string "RELI: No pudimos ganar aunque\n"
	.string "trabajamos juntos…$"

Route131_Text_ReliPostBattle:
	.string "RELI: La gente de PACIFIDLOG vive\n"
	.string "con el mar y los POKéMON desde\l"
	.string "que nacen.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: ¿No tienes dos POKéMON?\n"
	.string "Así no podemos disfrutar la batalla.$"

Route131_Text_IanIntro:
	.string "IAN: ¡Doy lo mejor de mí junto a\n"
	.string "mi hermana!$"

Route131_Text_IanDefeat:
	.string "IAN: Lo di todo con mi hermana,\n"
	.string "pero aun así no ganamos…$"

Route131_Text_IanPostBattle:
	.string "IAN: ¿Sabes que PACIFIDLOG es\n"
	.string "un pueblo flotante?\p"
	.string "¡Así que donde haya mar,\n"
	.string "es parte de PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: ¡Si tienes dos POKéMON,\n"
	.string "te enfrentaremos!$"

Route131_Text_TaliaIntro:
	.string "¡Si me vences, te daré una\n"
	.string "información genial!$"

Route131_Text_TaliaDefeat:
	.string "¿Oh?\n"
	.string "¿Acaso perdí?$"

Route131_Text_TaliaPostBattle:
	.string "Hay un lugar raro cerca.\n"
	.string "Hay una torre enorme allí.\l"
	.string "¿Por qué no vas a ver?$"

Route131_Text_KevinIntro:
	.string "La gente de PACIFIDLOG es\n"
	.string "muy pacífica.\p"
	.string "Nunca se enojan.\n"
	.string "Eso incluye a mí también.$"

Route131_Text_KevinDefeat:
	.string "¡Ups!$"

Route131_Text_KevinPostBattle:
	.string "¡Tch! ...Oh, espera.\n"
	.string "No estoy enojado. ¡En serio!\p"
	.string "¡Pero vaya que eres fuerte!\n"
	.string "¡Jajaja!$"

Route132_Text_GilbertIntro:
	.string "De niño me resfriaba siempre,\n"
	.string "pero me puse muy fit tras\l"
	.string "empezar a nadar.$"

Route132_Text_GilbertDefeat:
	.string "Anhelo más poder...$"

Route132_Text_GilbertPostBattle:
	.string "Los ENTRENADORES viajan por campos y\n"
	.string "montes, así que deben estar fit.$"

Route132_Text_DanaIntro:
	.string "Trato de no nadar donde las corrientes\n"
	.string "son muy fuertes.$"

Route132_Text_DanaDefeat:
	.string "¡Oh, por favor, no!$"

Route132_Text_DanaPostBattle:
	.string "Si me arrastra la corriente, perderé\n"
	.string "la noción de dónde estoy…$"

Route132_Text_RonaldIntro:
	.string "Ganes o pierdas, ¡no lo sabrás hasta\n"
	.string "que lo intentes!$"

Route132_Text_RonaldDefeat:
	.string "¡Waaa!\n"
	.string "¡Me hundí en la derrota!$"

Route132_Text_RonaldPostBattle:
	.string "No lucho si sé que voy a ganar.\n"
	.string "¡Prefiero luchar al límite entre la\l"
	.string "victoria y la derrota!$"

Route132_Text_KiyoIntro:
	.string "Pienso en POKéMON todo el día.\n"
	.string "¿Cómo podrías vencerme?$"

Route132_Text_KiyoDefeat:
	.string "Perdí.\n"
	.string "Acepto mi derrota.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh...\n"
	.string "Eres fan de los POKéMON, ¿no?\p"
	.string "Seguro piensas en POKéMON las 24\n"
	.string "horas del día, ¿verdad?$"

Route132_Text_MakaylaIntro:
	.string "Siempre estoy con mi esposo,\n"
	.string "pero puedo ganar sin él.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, creo que no fui lo bastante buena.$"

Route132_Text_MakaylaPostBattle:
	.string "Ese joven se parece mucho a mi\n"
	.string "esposo cuando era joven.\p"
	.string "¡Me hace sonrojar!$"

Route132_Text_JonathanIntro:
	.string "Alguien me ha estado mirando.\n"
	.string "¿Fuiste tú?$"

Route132_Text_JonathanDefeat:
	.string "¡Guau!\n"
	.string "¡Eso sí que es muy fuerte!$"

Route132_Text_JonathanPostBattle:
	.string "No me quito la sensación de que\n"
	.string "alguien me observa.\p"
	.string "¡No puedo concentrarme!$"

Route132_Text_PaxtonIntro:
	.string "¿A dónde habrá ido mi esposa?\n"
	.string "Siempre estoy con ella.\l"
	.string "¿Podré ganar yo solo?$"

Route132_Text_PaxtonDefeat:
	.string "Ah, ya veo que después de todo\n"
	.string "no pude ganar por mi cuenta.$"

Route132_Text_PaxtonPostBattle:
	.string "Mi esposa debe buscarme.\n"
	.string "Será mejor que vaya a buscarla.$"

Route132_Text_DarcyIntro:
	.string "Me gustaba entrenar solo aquí.\n"
	.string "¡Es horrible que venga tanta gente!$"

Route132_Text_DarcyDefeat:
	.string "¡Está bien! No me quejaré de que\n"
	.string "haya más gente aquí.$"

Route132_Text_DarcyPostBattle:
	.string "Supongo que puedo unir fuerzas con\n"
	.string "ese anciano y retar al otro equipo.$"

Route133_Text_FranklinIntro:
	.string "¿Las corrientes te trajeron aquí?\n"
	.string "Debe ser el destino.\l"
	.string "¡Luchemos!$"

Route133_Text_FranklinDefeat:
	.string "¡Fuerte!\n"
	.string "¡Demasiado fuerte!$"

Route133_Text_FranklinPostBattle:
	.string "Qué mala suerte que un TRAINER\n"
	.string "tan fuerte llegara aquí...\l"
	.string "Debo estar maldito...$"

Route133_Text_DebraIntro:
	.string "He vivido en la pena y la miseria...\n"
	.string "Fui abandonado y aquí es donde\l"
	.string "he terminado...$"

Route133_Text_DebraDefeat:
	.string "Otra derrota...$"

Route133_Text_DebraPostBattle:
	.string "Una vida a la deriva...\n"
	.string "¡Ya no lo quiero más!$"

Route133_Text_LindaIntro:
	.string "¡Bienvenido!\n"
	.string "¡Te estaba esperando!$"

Route133_Text_LindaDefeat:
	.string "¡No! ¡Por favor!$"

Route133_Text_LindaPostBattle:
	.string "Un niño TRAINER tan fuerte...\n"
	.string "¡Qué molesto es!$"

Route133_Text_WarrenIntro:
	.string "Quiero ganar como todos, pero no\n"
	.string "entrenaré POKéMON como todos.$"

Route133_Text_WarrenDefeat:
	.string "¡Rayos!\n"
	.string "¡Sigo siendo muy floja!$"

Route133_Text_WarrenPostBattle:
	.string "Es más divertido hacer las cosas a\n"
	.string "mi modo que ser como los demás.\l"
	.string "¡O sea, es obvio!$"

Route133_Text_BeckIntro:
	.string "Vine hasta acá con mis\n"
	.string "POKéMON VOLADORES.$"

Route133_Text_BeckDefeat:
	.string "Tú...\n"
	.string "¡Eres increíblemente genial!$"

Route133_Text_BeckPostBattle:
	.string "Quisiera volver a FORTREE,\n"
	.string "pero este lugar también me gusta.$"

Route133_Text_MollieIntro:
	.string "Debo haber luchado miles\n"
	.string "de veces. Ya perdí la cuenta.$"

Route133_Text_MollieDefeat:
	.string "Habré perdido miles de veces,\n"
	.string "pero perder aún duele.$"

Route133_Text_MolliePostBattle:
	.string "Sigue así, joven. Para que seas\n"
	.string "como mi esposo y yo.$"

Route133_Text_ConorIntro:
	.string "Los jóvenes se dejan llevar\n"
	.string "demasiado. No tienen rumbo.$"

Route133_Text_ConorDefeat:
	.string "Tienes un sentido del propósito firme.$"

Route133_Text_ConorPostBattle:
	.string "No dejes que otros te desvíen.\n"
	.string "No pierdas el rumbo al crecer.$"

Route134_Text_JackIntro:
	.string "Aun los POKéMON que nadan son\n"
	.string "arrastrados por la corriente.$"

Route134_Text_JackDefeat:
	.string "¡Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Creo que los POKéMON disfrutan\n"
	.string "las corrientes de esta zona.$"

Route134_Text_LaurelIntro:
	.string "Mis LUVDISC buscan un combate\n"
	.string "divertido. ¿Te unes?$"

Route134_Text_LaurelDefeat:
	.string "¡Ups!$"

Route134_Text_LaurelPostBattle:
	.string "Hay un coleccionista que busca\n"
	.string "las ESCAMAS de LUVDISC.$"

Route134_Text_AlexIntro:
	.string "¡Muy bien! ¡Ya descansaron mucho!\n"
	.string "¡Es hora de luchar!$"

Route134_Text_AlexDefeat:
	.string "Agotado otra vez...$"

Route134_Text_AlexPostBattle:
	.string "Mis POKéMON AVE se cansan rápido\n"
	.string "tras un vuelo largo...$"

Route134_Text_HitoshiIntro:
	.string "Eres un ENTRENADOR POKéMON.\n"
	.string "No hace falta hablar. ¡Luchamos!$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Yo te desafié y aun así perdí.\n"
	.string "Siento una gran vergüenza...$"

Route134_Text_AaronIntro:
	.string "La marea salvaje de esta zona nos\n"
	.string "hace más fuertes que nunca.$"

Route134_Text_AaronDefeat:
	.string "Acepto mi derrota.$"

Route134_Text_AaronPostBattle:
	.string "Volveremos a entrenar a\n"
	.string "CASCADA METEORO.\p"
	.string "Si quieres, ve tú también.\n"
	.string "¡Seguro que te hará más fuerte!$"

Route134_Text_KelvinIntro:
	.string "¡N-nuestro bote!\n"
	.string "¡La marea se lo llevó!$"

Route134_Text_KelvinDefeat:
	.string "¡Awawawawah!\n"
	.string "¡Por favor, basta! ¡Para!$"

Route134_Text_KelvinPostBattle:
	.string "Si no podemos usar SURF, ¿cómo\n"
	.string "volveremos a casa?\p"
	.string "Sé que un POKéMON debilitado puede\n"
	.string "usar SURF, pero no se siente bien.$"

Route134_Text_MarleyIntro:
	.string "¿Podrán tus POKéMON esquivar\n"
	.string "nuestros ataques veloces?$"

Route134_Text_MarleyDefeat:
	.string "¡No sabía que existía esa técnica!\n"
	.string "Nos has derrotado por completo.$"

Route134_Text_MarleyPostBattle:
	.string "No he perdido mi pasión por la\n"
	.string "velocidad. Me esforzaré más.$"

Route134_Text_ReynaIntro:
	.string "¡Mis POKéMON no caerán\n"
	.string "fácilmente!$"

Route134_Text_ReynaDefeat:
	.string "¡No puede ser!\n"
	.string "¡Explícame cómo perdí!$"

Route134_Text_ReynaPostBattle:
	.string "¡Jaja!\n"
	.string "¡Ganaste, es cierto!\p"
	.string "¡Subiré de nivel luchando contra\n"
	.string "ENTRENADORES que encuentre!$"

Route134_Text_HudsonIntro:
	.string "Oye, ¿has visto a otro MARINERO\n"
	.string "por aquí cerca?$"

Route134_Text_HudsonDefeat:
	.string "¡Vaya, eso es increíble!$"

Route134_Text_HudsonPostBattle:
	.string "Nuestro bote derivó hacia el mar.\p"
	.string "Mi amigo es muy tímido, así que\n"
	.string "estoy preocupado por él.$"
