LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "¡Hola! Estuviste en un CONCURSO\n"
	.string "POKéMON, ¿verdad?\l"
	.string "Se nota al ver a tu POKéMON.\p"
	.string "Soy reportera. Escribo una historia\n"
	.string "sobre los CONCURSOS POKéMON.\p"
	.string "Si puedes, ¿responderías\n"
	.string "unas preguntas?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "¡Oh, lo harás!\n"
	.string "Gracias.\p"
	.string "Brevemente, ¿cómo describirías el\n"
	.string "CONCURSO en el que entraste?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, ya veo.\n"
	.string "Es un comentario muy edificante.\p"
	.string "Da una buena idea de cómo\n"
	.string "fue el CONCURSO.\p"
	.string "Tengo una última pregunta.\p"
	.string "Al oír la palabra “{STR_VAR_2}”,\n"
	.string "¿qué imagen te viene a la mente?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "¡Ya veo!\p"
	.string "Así que así imaginas el concepto\n"
	.string "de “{STR_VAR_2}”.\p"
	.string "¡Gracias!\n"
	.string "Me has dado buenas ideas.\p"
	.string "Creo que ya puedo escribir una buena\n"
	.string "historia sobre CONCURSOS POKéMON.\p"
	.string "Tal vez, solo tal vez, esto llegue\n"
	.string "hasta la televisión.\l"
	.string "¡Espero que estés atento!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, qué mal...\p"
	.string "Si encuentras una buena historia,\n"
	.string "por favor, cuéntamela.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Estaré esperando tu próximo\n"
	.string "CONCURSO POKéMON.$"

gTVBravoTrainerText00::
	.string "¡Sí!\n"
	.string "¡Es hora del BRAVO TRAINER!\p"
	.string "Hoy analizaremos un POKéMON\n"
	.string "de {STR_VAR_1}.\p"
	.string "Este POKéMON tiene un rango {STR_VAR_3}\n"
	.string "en la categoría {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "¡Presentamos a {STR_VAR_2} el\n"
	.string "{STR_VAR_1}!\p"
	.string "El apodo {STR_VAR_2}…\p"
	.string "¡Hasta el apodo emana un aire que\n"
	.string "proclama “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "En fin, cuando el ENTRENADOR {STR_VAR_1}\n"
	.string "inscribió al POKéMON en un CONCURSO,\l"
	.string "logramos obtener frases apasionadas\l"
	.string "sobre su fiel compañero.$"

gTVBravoTrainerText03::
	.string "Al preguntarle luego por el CONCURSO,\n"
	.string "{STR_VAR_1} respondió feliz con un enorme\l"
	.string "grin, “{STR_VAR_2}!”\p"
	.string "Well, sure, {STR_VAR_1}'s POKéMON came in\n"
	.string "número {STR_VAR_3} en el CONCURSO.\p"
	.string "Esa frase le queda perfecta a {STR_VAR_1}\n"
	.string "justo ahora, ¡diría!$"

gTVBravoTrainerText04::
	.string "Al preguntarle sobre el CONCURSO,\n"
	.string "{STR_VAR_1} respondió con un toque de\l"
	.string "amargura: “{STR_VAR_2}.”\p"
	.string "Bueno, el POKéMON de {STR_VAR_1} quedó\n"
	.string "en el puesto {STR_VAR_3} del CONCURSO.\p"
	.string "¡La decepción de {STR_VAR_1} se nota\n"
	.string "con total claridad!$"

gTVBravoTrainerText05::
	.string "¿No quieres saber qué imagina\n"
	.string "{STR_VAR_1} que es {STR_VAR_2}?\p"
	.string "¡Claro que nosotros quisimos!\n"
	.string "¡Así que se lo preguntamos!\p"
	.string "La respuesta fue muy resumida:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "¡Eso es lo que {STR_VAR_2} representa\n"
	.string "para {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "El último movimiento {STR_VAR_2} usado\n"
	.string "por {STR_VAR_1} se trata totalmente\l"
	.string "de “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "¡Bravo, {STR_VAR_1}!\n"
	.string "¡Bravo, {STR_VAR_2}!\p"
	.string "Espero que podamos ver a\n"
	.string "{STR_VAR_1} llegar más alto!\p"
	.string "¡Se nos acabó el tiempo!\n"
	.string "¡Hasta la próxima, adiós!$"

gTVBravoTrainerText08::
	.string "¡Presentamos al {STR_VAR_1} del ENTRENADOR!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "¡Hola! Eres el ENTRENADOR que acaba\n"
	.string "de luchar, ¿verdad?\p"
	.string "Hago entrevistas a ENTRENADORES\n"
	.string "de todas partes.\p"
	.string "¿Me darías tu opinión sobre\n"
	.string "las batallas?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "¿Lo harás? ¿En serio?\n"
	.string "¡Gracias!\l"
	.string "Entonces, eh...\p"
	.string "¿Cómo te fue hoy en la\n"
	.string "BATTLE TOWER?\p"
	.string "¿Estás satisfecho con la batalla?\n"
	.string "¿O no te gustó?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh...\n"
	.string "Siento haberte molestado.\p"
	.string "Danós una entrevista la próxima\n"
	.string "vez que visites la BATTLE TOWER.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "¡Bueno, claro!\p"
	.string "Esa expresión de satisfacción\n"
	.string "en tu rostro...\p"
	.string "Es obvio que tuviste una\n"
	.string "gran batalla.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, ya veo...\p"
	.string "Bueno, es difícil que una batalla\n"
	.string "salga exactamente como planeaste.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, ¿puedo hacer una pregunta más?\p"
	.string "Si describieras tu impresión de la\n"
	.string "batalla con una frase,\l"
	.string "¿cuál sería?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "¡Oh, eso es genial!\p"
	.string "¡Qué gran frase!\n"
	.string "Espero que te vaya bien la próxima.\p"
	.string "¡Espero verte pronto!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, ya veo...\p"
	.string "Aun así, ser del tipo silencioso\n"
	.string "también es genial, ¿no?\p"
	.string "¡Espero que me des la oportunidad\n"
	.string "de saber qué piensas otra vez!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "¡Estaré esperando tu\n"
	.string "próxima batalla!$"

BravoTrainerBattleTower_Text_Intro::
	.string "¡Sí!\n"
	.string "¡Es hora del BRAVO TRAINER!\p"
	.string "Hoy analizaremos a {STR_VAR_1},\n"
	.string "¡quien fue al BATTLE TOWER!\p"
	.string "Para el reto, {STR_VAR_1} usó\n"
	.string "un increíble {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "¡La pareja logró un récord de {STR_VAR_2}\n"
	.string "victorias seguidas en {STR_VAR_1}!\l"
	.string "¡Bravo, TRAINER!$"

BravoTrainerBattleTower_Text_Lost::
	.string "El dúo cayó finalmente ante\n"
	.string "{STR_VAR_1} en la lucha {STR_VAR_2}.\l"
	.string "¡Buen intento, TRAINER!\p"
	.string "Pero bueno, es mala suerte hallar a\n"
	.string "{STR_VAR_1} tan pronto en el reto.\p"
	.string "Pedimos al TRAINER su opinión\n"
	.string "sobre la lucha con {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "El dúo ganó al derrotar por completo\n"
	.string "al {STR_VAR_2} de {STR_VAR_1}.\l"
	.string "¡Bravo, TRAINER!\p"
	.string "Vencer incluso a {STR_VAR_1}…\n"
	.string "¡Es increíble! ¡Simplemente asombroso!\p"
	.string "Pedimos al TRAINER su opinión\n"
	.string "sobre su momento de gloria.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Tras ganar varias veces, el dúo cayó\n"
	.string "ante {STR_VAR_1} y {STR_VAR_2},\l"
	.string "su último obstáculo.\p"
	.string "¡Buen intento, TRAINER!\p"
	.string "Aun así, hay que reconocerlo.\n"
	.string "No hay muchas parejas famosas\l"
	.string "como {STR_VAR_1} y {STR_VAR_2}.\p"
	.string "Pedimos al TRAINER su opinión\n"
	.string "sobre luchar contra el dúo famoso.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Esto fue lo que dijo el TRAINER:\n"
	.string "“¡Estoy satisfecho!”\p"
	.string "¿No es una respuesta refrescante?\n"
	.string "¡Bravo, TRAINER!\p"
	.string "¿No es genial poder luchar\n"
	.string "hasta quedar totalmente satisfecho?\p"
	.string "Supe qué tan satisfecho estaba\n"
	.string "cuando escuché al TRAINER decir:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Esto fue lo que dijo el TRAINER:\n"
	.string "“No estoy satisfecho…”\p"
	.string "Nuestro TRAINER estaba algo triste\n"
	.string "al decir esas palabras.\p"
	.string "Pero no es fácil luchar con\n"
	.string "satisfacción completa, ¿verdad?\p"
	.string "En fin, supe qué tan insatisfecho\n"
	.string "estaba el TRAINER al escuchar esto:$"

BravoTrainerBattleTower_Text_None1::
	.string "Ninguno$"

BravoTrainerBattleTower_Text_None2::
	.string "Ninguno$"

BravoTrainerBattleTower_Text_None3::
	.string "Ninguno$"

BravoTrainerBattleTower_Text_None4::
	.string "Ninguno$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "¿A que es genial?\p"
	.string "Expresa la alegría de {STR_VAR_2},\n"
	.string "¿verdad?\p"
	.string "Esa batalla final con {STR_VAR_3}...\n"
	.string "¡Fue lo que se dice un auténtico\l"
	.string "“{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "¿No es muy apropiado?\p"
	.string "Esa batalla contra {STR_VAR_3} al\n"
	.string "final... ¡No se puede describir\l"
	.string "si no es como “{STR_VAR_1}”!\p"
	.string "¡La decepción de {STR_VAR_2} quedó\n"
	.string "muy clara, diría yo!$"

BravoTrainerBattleTower_Text_Outro::
	.string "¡Bravo, {STR_VAR_1}!\n"
	.string "¡Bravo, {STR_VAR_2}!\p"
	.string "Espero que podamos ver a\n"
	.string "{STR_VAR_1} llegar más lejos!\p"
	.string "¡Se nos acabó el tiempo!\n"
	.string "¡Hasta la próxima, adiós!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "¡Vaya!\p"
	.string "Se nota que le das mucho amor a\n"
	.string "tu {STR_VAR_1}.\p"
	.string "Veo que se llama {STR_VAR_2}.\p"
	.string "¿Me harías un favor?\p"
	.string "Soy reportero de TV y hago una\n"
	.string "encuesta sobre POKéMON.\p"
	.string "¿Responderías unas preguntas\n"
	.string "sencillas para mí?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "¡Genial! ¡Gracias!\p"
	.string "Bien, aquí voy.\n"
	.string "Solo quiero respuestas rápidas, ¿sí?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Cuando conociste a {STR_VAR_1},\n"
	.string "¿qué sentiste?\p"
	.string "¿Cómo describirías tus sentimientos\n"
	.string "en ese momento?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Cuidas a {STR_VAR_1} con amor.\p"
	.string "Si lo compararas con algo que te\n"
	.string "guste, ¿qué sería?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Esta pregunta también va sobre\n"
	.string "tu amado {STR_VAR_1}.\p"
	.string "¿Qué fue de {STR_VAR_1} lo que\n"
	.string "te atrajo?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Bien, eso tiene sentido.\p"
	.string "La siguiente pregunta puede ser un\n"
	.string "poco difícil.\p"
	.string "Aquí va…\p"
	.string "¿Qué significan los POKéMON para ti?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "¡Ya veo!\p"
	.string "Hmhm…\p"
	.string "¡Listo!\n"
	.string "Gracias por ayudarme.\p"
	.string "Fue divertido e iluminador\n"
	.string "charlar contigo.\p"
	.string "Puede que la entrevista salga en TV.\n"
	.string "¡Sintoniza y mira!\p"
	.string "Bien, eso es todo.\n"
	.string "¡Adiós!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, entiendo…\p"
	.string "Bueno, si te dan ganas de hablarme\n"
	.string "de POKéMON, ¡aquí estaré!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Amo mi trabajo; aprendo sobre los\n"
	.string "POKéMON haciendo entrevistas.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Hola, pareces muy unido a tu\n"
	.string "{STR_VAR_1}.\p"
	.string "¿Sabes qué?\n"
	.string "Soy reportero de TV.\p"
	.string "Viajo entrevistando a la gente\n"
	.string "sobre POKéMON.\p"
	.string "¿Estarías dispuesto a contarme\n"
	.string "algo sobre tu {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "¡Vaya, gracias!\p"
	.string "Bien, entonces, cuéntame lo que\n"
	.string "quieras sobre tu {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Vaya...\n"
	.string "Es un relato interesante.\p"
	.string "Eres muy cercano a {STR_VAR_1},\n"
	.string "¿verdad?\p"
	.string "Siento que tu historia\n"
	.string "será genial para la TV.\p"
	.string "Prometo convertir esto en\n"
	.string "un programa entretenido.\l"
	.string "Estate atento a la pantalla.\p"
	.string "Bien, eso es todo.\n"
	.string "¡Adiós!$"

gTVFanClubOpinionsText00::
	.string "¡SOMOS EL CLUB DE FANS POKéMON!\p"
	.string "¡Estamos al aire!\p"
	.string "¡Damos vuestras opiniones\n"
	.string "y yo las grito por vosotros!\l"
	.string "¿No es un concepto fantástico?\p"
	.string "Hoy traemos un reporte de\n"
	.string "nuestro reportero en el\l"
	.string "CLUB DE FANS POKéMON.\p"
	.string "Entonces, ¿quién es el fan\n"
	.string "POKéMON destacado de hoy?\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "{STR_VAR_1}!\p"
	.string "Veamos qué dice {STR_VAR_1}\n"
	.string "sobre {STR_VAR_3}, el {STR_VAR_2}.\p"
	.string "¡Gritaré esas palabras de amor\n"
	.string "en voz alta por la TV!\p"
	.string "¡Hoo-hah!\p"
	.string "¡A gritar!$"

gTVFanClubOpinionsText01::
	.string "Le preguntamos a {STR_VAR_1}: “Al ver\n"
	.string "por primera vez a tu {STR_VAR_2},\l"
	.string "¿qué pensaste?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "¡Sí! ¡Ese es un grito potente!\p"
	.string "¿No trae recuerdos de aquellos\n"
	.string "días ya pasados?$"

gTVFanClubOpinionsText02::
	.string "Le preguntamos a {STR_VAR_1}: “Si\n"
	.string "compararas a tu {STR_VAR_2} con\l"
	.string "algo, sería...”\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "¡Vaya, qué idea tan original!\p"
	.string "Se siente la intensidad del\n"
	.string "sentimiento del ENTRENADOR por\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Veamos...\n"
	.string "¿Qué tenía ese {STR_VAR_2}\l"
	.string "que tanto atrajo a {STR_VAR_1}?\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "¡{STR_VAR_3}!\p"
	.string "¡Vaya! ¡Qué declaración tan genial!\p"
	.string "¡El amor del ENTRENADOR por el {STR_VAR_2}\n"
	.string "se siente fuerte y claro!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, aún hay más.\n"
	.string "¡Vamos a verlo!\p"
	.string "Veamos, ahora...\p"
	.string "Le preguntamos a {STR_VAR_1}: “¿Qué\n"
	.string "significan los POKéMON para ti?”\p"
	.string "... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "¡Bravo!\p"
	.string "¡Es el mejor grito del día!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "¡Dan ganas de gritarlo\n"
	.string "una y otra vez!\p"
	.string "Tras este gran grito, es hora de\n"
	.string "despedirnos hasta la próxima!\p"
	.string "¡Tengamos un último grito!\n"
	.string "Todos juntos ahora...\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "¡SOMOS EL CLUB DE FANS POKéMON!\p"
	.string "¡Estamos al aire!\p"
	.string "Hoy empezaremos con el\n"
	.string "RINCÓN DE ENCUESTAS POKéMON.\p"
	.string "De todas las historias de POKéMON\n"
	.string "y ENTRENADORES, ¿qué drama\l"
	.string "nos sorprenderá hoy?\p"
	.string "Veamos...\p"
	.string "¡Esta!\p"
	.string "¡Empezaremos con esta carta!\p"
	.string "Es una carta de {STR_VAR_1} sobre un\n"
	.string "querido {STR_VAR_2}.\p"
	.string "¡Veamos cuánto amor siente el autor\n"
	.string "por ese {STR_VAR_2}!\l"
	.string "Jeje...$"

gTVFanClubText01::
	.string "¡Vaya!\n"
	.string "¡Qué carta tan increíble!$"

gTVFanClubText02::
	.string "¡Me encantó, así que aquí está!$"

gTVFanClubText03::
	.string "¡Una gran carta merece leerse\n"
	.string "una y otra vez!$"

gTVFanClubText04::
	.string "La parte de “{STR_VAR_3}” le da\n"
	.string "un gran impacto emocional.\p"
	.string "¡Es una carta genial y con mucha\n"
	.string "profundidad sentimental!$"

gTVFanClubText05::
	.string "¡Sobre todo la parte de “{STR_VAR_3}”!\p"
	.string "¡Me encanta cómo usa “{STR_VAR_3}”!$"

gTVFanClubText06::
	.string "Por cierto, no es importante,\n"
	.string "pero “{STR_VAR_3}” es gran frase.\p"
	.string "He usado mucho “{STR_VAR_3}”\n"
	.string "en mis charlas últimamente.$"

gTVFanClubText07::
	.string "Si tuviera que puntuar la carta,\n"
	.string "le daría {STR_VAR_3} puntos.\p"
	.string "¡Espero una carta aún mejor la\n"
	.string "próxima vez, {STR_VAR_1}!\p"
	.string "¡Ay! ¿Vieron qué hora es?\n"
	.string "¡Es hora de decir adiós por ahora!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "¿Te gustan los POKéMON?\p"
	.string "Estoy en una misión para la TV.\p"
	.string "Busco historias recientes de POKéMON\n"
	.string "y de ENTRENADORES.\p"
	.string "Si no te importa, ¿podrías contarme\n"
	.string "algo sobre ti?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Busco historias recientes de POKéMON\n"
	.string "y de ENTRENADORES.\p"
	.string "Si no te importa, ¿podrías contarme\n"
	.string "algo sobre ti?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, ¿lo harás?\n"
	.string "¡Gracias!\p"
	.string "Por favor, cuéntame algo interesante\n"
	.string "que hayas vivido hace poco\l"
	.string "con POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, ya veo...\p"
	.string "Bueno, si tienes alguna historia\n"
	.string "interesante, por favor avísame.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "¡Oh, qué historia tan inspiradora!\p"
	.string "Me aseguraré de que salga\n"
	.string "en la televisión.\p"
	.string "Se emitirá pronto, creo,\n"
	.string "¡así que estate atento!$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm...\n"
	.string "Tengo una gran historia para la TV.\p"
	.string "¡Mejor la escribo rápido!$"

gTVRecentHappeningsText00::
	.string "Hola, es hora de SUCESOS RECIENTES.\p"
	.string "Para los ENTRENADORES POKéMON, cada\n"
	.string "día es un cuento de hadas.\p"
	.string "Queremos presentarles algunos de\n"
	.string "estos relatos POKéMON.\p"
	.string "Hoy traemos la historia del\n"
	.string "ENTRENADOR {STR_VAR_1}.\p"
	.string "¿Qué vivió {STR_VAR_1} hace poco?\n"
	.string "Vamos a descubrirlo.\p"
	.string "Veamos...$"

gTVRecentHappeningsText01::
	.string "¿No fue esclarecedor?\p"
	.string "La historia te da una idea clara de lo\n"
	.string "que {STR_VAR_1} vivió hace poco.\l"
	.string "¡Es como si hubiéramos estado ahí!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Eso\n"
	.string "acentúa el relato y le da profundidad.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Eso le da sentido de lugar al relato.\l"
	.string "Nos permite imaginar el escenario.$"

gTVRecentHappeningsText04::
	.string "La sección “{STR_VAR_3}”\n"
	.string "del relato es muy expresiva.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} ha contado un relato\n"
	.string "maravilloso sobre POKéMON.\p"
	.string "Y ahora el relato de {STR_VAR_1} ha\n"
	.string "quedado grabado en tu alma.\p"
	.string "Eso es todo por hoy.\n"
	.string "Sintonízanos la próxima vez.$"

gTVMassOutbreakText00::
	.string "¡Saludos!\n"
	.string "Es hora de POKéMON NEWS.\p"
	.string "Acabamos de recibir noticias de un\n"
	.string "suceso muy raro.\p"
	.string "Hay reportes de una plaga masiva\n"
	.string "de {STR_VAR_2} cerca de\l"
	.string "{STR_VAR_1}.\p"
	.string "{STR_VAR_2}, como ya sabrán,\n"
	.string "es un POKéMON raro y\l"
	.string "difícil de encontrar.\p"
	.string "Es una gran oportunidad para ver\n"
	.string "la misteriosa plaga de\l"
	.string "{STR_VAR_2} salvaje.\p"
	.string "Eso es todo en POKéMON NEWS.$"

gTV3CheersForPokeblocksText00::
	.string "MC: ¡Esperamos que estén felices!\n"
	.string "¡Llegó “3 VIVAS POR {POKEBLOCK}S”!\p"
	.string "Hoy probamos el {POKEBLOCK} hecho\n"
	.string "por {STR_VAR_1} y sus socios.\p"
	.string "Sin demora, se lo daré de comer\n"
	.string "a mi POKéMON gourmet GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: ¡Gubi! ¡Gubii!\p"
	.string "MC: ¡Y el veredicto es muy {STR_VAR_1}!\n"
	.string "GULPIN dice que sabe a “{STR_VAR_2}!”\p"
	.string "¡Muchas gracias, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "La mezcla de {STR_VAR_1}\n"
	.string "dejó algo que desear.\p"
	.string "Si este ENTRENADOR mezclara mejor,\n"
	.string "el {POKEBLOCK} sabría mucho mejor.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: ¡Gubi! ¡Gubii!\p"
	.string "MC: Hmm... Está muy {STR_VAR_1}.\n"
	.string "GULPIN dice que sabe a “{STR_VAR_2}!”\p"
	.string "Parece que los errores de {STR_VAR_3}\n"
	.string "dañaron la calidad de la mezcla...$"

gTV3CheersForPokeblocksText04::
	.string "Qué pena que el esfuerzo de\n"
	.string "{STR_VAR_1} se desperdiciara.\p"
	.string "Esperemos que {STR_VAR_2} logre\n"
	.string "una mejor presentación la próxima vez!$"

gTV3CheersForPokeblocksText05::
	.string "¡Sintonícennos la próxima vez!\n"
	.string "Nuestro lema es “¡VIVA {POKEBLOCK}!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "¡Hola!\p"
	.string "Soy un gran fan de {STR_VAR_1}.\n"
	.string "¿Qué opinas de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ya veo. Eso es lo que piensas\n"
	.string "sobre el ENTRENADOR.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "¿Acaso olvidaste por completo\n"
	.string "un {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Soy un gran fan de {STR_VAR_1}.\n"
	.string "¿Qué opinas de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "¿Qué puntuación le darías a {STR_VAR_1}\n"
	.string "en una escala del uno al cien?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string " ¿Olvidaste por completo\n"
	.string "sobre {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "¡Ah, ya veo!\n"
	.string "Deberías conocer a {STR_VAR_1}.\l"
	.string "¡Seguro que serás fan también!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ya veo, ya veo.\p"
	.string "¡Gracias!\n"
	.string "Es muy útil saberlo.\p"
	.string "Compartiré esto con otros fans de\n"
	.string "{STR_VAR_1} para discutirlo.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Pronto habrá un especial de TV\n"
	.string "sobre {STR_VAR_1}.\p"
	.string "¡Espero que lo veas!$"

gTVTrainerFanClubSpecialText00::
	.string "TRAINER FAN CLUB\n"
	.string "{STR_VAR_1} SPECIAL!\p"
	.string "Esta es una presentación especial para\n"
	.string "los fans de {STR_VAR_1} de todo HOENN!\p"
	.string "Hoy preguntamos: “¿Qué opina\n"
	.string "la gente de {STR_VAR_1}?”\p"
	.string "Le hicimos la pregunta a {STR_VAR_2}\n"
	.string "como representante de ENTRENADORES.\p"
	.string "Preguntamos: “¿En una palabra, cómo\n"
	.string "describirías a {STR_VAR_1}?”\p"
	.string "La respuesta: “{STR_VAR_3}”.\p"
	.string "¡Felicitaciones a {STR_VAR_2}!\n"
	.string "¡Qué opinión tan aguda!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "It has such a nice ring to it!\p"
	.string "{STR_VAR_2} también se ganó el\n"
	.string "fuerza del 0 al 100.$"

gTVTrainerFanClubSpecialText01::
	.string "¡La puntuación fue {STR_VAR_3}!\n"
	.string "¡Es una puntuación muy alta!\p"
	.string "{STR_VAR_2} obviamente tiene a\n"
	.string "{STR_VAR_1} en alta estima.$"

gTVTrainerFanClubSpecialText02::
	.string "¡La puntuación fue {STR_VAR_3}!\n"
	.string "Es una puntuación bastante buena.\p"
	.string "{STR_VAR_2} debe considerar a\n"
	.string "{STR_VAR_1} como un rival.$"

gTVTrainerFanClubSpecialText03::
	.string "¡La puntuación fue {STR_VAR_3}!\n"
	.string "Es una puntuación algo débil.\p"
	.string "{STR_VAR_2} debe considerar a\n"
	.string "{STR_VAR_1} como un simple ayudante.$"

gTVTrainerFanClubSpecialText04::
	.string "¡El puntaje fue de {STR_VAR_3}!\n"
	.string "Es un puntaje terrible.\p"
	.string "{STR_VAR_2} debe considerar a\n"
	.string "{STR_VAR_1} como un inferior.$"

gTVTrainerFanClubSpecialText05::
	.string "¡Ahí lo tienen, amigos!\p"
	.string "Creo que todos aprendimos algo\n"
	.string "nuevo sobre {STR_VAR_1}.\p"
	.string "Para cerrar, los dejo con las\n"
	.string "palabras de {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "And now, it's time for…\n"
	.string "EL SHOW DE LOS APODOS.\p"
	.string "I tell your POKéMON's fortune from\n"
	.string "el apodo que le has puesto.\p"
	.string "Consejos doy, y son\n"
	.string "consejos útiles los que ofrezco.\p"
	.string "Hoy voy a leer\n"
	.string "the nickname {STR_VAR_3} of {STR_VAR_1}'s\l"
	.string "POKéMON {STR_VAR_2}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Este mote es…$"

gTVNameRaterText01::
	.string "Un apodo que sugiere talento de\n"
	.string "muchas formas distintas.\p"
	.string "Insto a este ENTRENADOR a tener\n"
	.string "valor y aceptar los retos.$"

gTVNameRaterText02::
	.string "Un apodo que complementa perfecto\n"
	.string "el nombre del ENTRENADOR {STR_VAR_1}.\p"
	.string "Sugiere que formarán una gran\n"
	.string "pareja con el tiempo exacto.$"

gTVNameRaterText03::
	.string "¡Un apodo digno de un POKéMON\n"
	.string "único en su especie!\p"
	.string "Si se cría bien, ¡la singularidad\n"
	.string "de este POKéMON florecerá!$"

gTVNameRaterText04::
	.string "Un apodo que nutrirá el lado más\n"
	.string "cariñoso y compasivo del POKéMON.\p"
	.string "Si se cría bien, ¡este POKéMON\n"
	.string "mostrará un calor real!$"

gTVNameRaterText05::
	.string "Un apodo muy fino que sugiere\n"
	.string "una gran grandeza futura.\p"
	.string "Me intriga saber qué le depara\n"
	.string "el futuro a este POKéMON.$"

gTVNameRaterText06::
	.string "¡Un buen apodo que hará que el\n"
	.string "POKéMON esté sano y fuerte!\p"
	.string "Ese POKéMON se mantendrá en forma\n"
	.string "y robusto por mucho, mucho tiempo.$"

gTVNameRaterText07::
	.string "¡Un buen apodo que hará que el\n"
	.string "POKéMON esté muy activo!\p"
	.string "Creo que este POKéMON será un\n"
	.string "gran luchador en las batallas.$"

gTVNameRaterText08::
	.string "¡Un apodo atractivo que hará que el\n"
	.string "POKéMON sea muy encantador!\p"
	.string "No dudo que este POKéMON sea un\n"
	.string "galán en los POKéMON CONTESTS.$"

gTVNameRaterText09::
	.string "El apodo {STR_VAR_1} se basa en la\n"
	.string "letra “{STR_VAR_3}”.\p"
	.string "Esa letra es apoyada por la primera\n"
	.string "letra “{STR_VAR_2}”, dándole una sólida\l"
	.string "presencia como apodo.$"

gTVNameRaterText10::
	.string "El apodo {STR_VAR_1} tiene una\n"
	.string "forma muy agradable.\p"
	.string "La presencia de las letras “{STR_VAR_2}”\n"
	.string "y “{STR_VAR_3}” ¡es notablemente buena!$"

gTVNameRaterText11::
	.string "El apodo {STR_VAR_1} tiene un\n"
	.string "sentir sublime y fluido.\p"
	.string "El flujo de la letra “{STR_VAR_2}” a la\n"
	.string "“{STR_VAR_3}” es especialmente genial.$"

gTVNameRaterText12::
	.string "Veamos otros ejemplos de buenos\n"
	.string "apodos, ¿te parece?$"

gTVNameRaterText13::
	.string "Prueba esto. Toma parte del nombre\n"
	.string "del ENTRENADOR {STR_VAR_1}, y obtén\l"
	.string "el gran apodo {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "El apodo {STR_VAR_2}{STR_VAR_3} también\n"
	.string "funcionaría muy bien.$"

gTVNameRaterText15::
	.string "El nombre de la especie del\n"
	.string "POKéMON {STR_VAR_2} pudo ser la base\l"
	.string "para el apodo {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} también sería un\n"
	.string "apodo efectivo.$"

gTVNameRaterText17::
	.string "Se debe evitar usar el nombre de otra\n"
	.string "especie de POKéMON.\p"
	.string "Por ejemplo, no uses el nombre de\n"
	.string "{STR_VAR_2} para el apodo {STR_VAR_1}{STR_VAR_3}.\l"
	.string "Eso es inaceptable.$"

gTVNameRaterText18::
	.string "Debo decir que {STR_VAR_1} es un\n"
	.string "apodo muy bueno.\p"
	.string "Espero que el ENTRENADOR siga\n"
	.string "tratando a {STR_VAR_1} con amor.\p"
	.string "Eso es todo por el show de hoy.\n"
	.string "Espero que nos veamos pronto.$"

gTVPokemonAnglerText00::
	.string "PESCADOR DE {STR_VAR_2}\p"
	.string "LOCUTOR: ¡Hola! Hoy daremos tips\n"
	.string "para pescar {STR_VAR_2}.\p"
	.string "GURU, ¿qué consejo da para\n"
	.string "atrapar a {STR_VAR_2}?\p"
	.string "GURU: ¿Hm? ¿Atrapar {STR_VAR_2}?\n"
	.string "Bueno, les diré: tengan paciencia\l"
	.string "y esperen. Eso es lo fundamental.\p"
	.string "¿Ven a {STR_VAR_1} allá?\n"
	.string "Ese ENTRENADOR es un buen ejemplo.\p"
	.string "A ese ENTRENADOR ya se le han\n"
	.string "escapado {STR_VAR_3} POKéMON.\p"
	.string "Pero {STR_VAR_1} espera. No se rinde.\n"
	.string "Esa es la ley para pescar {STR_VAR_2}.\p"
	.string "LOCUTOR: Ya veo...\p"
	.string "¡Oh! ¡{STR_VAR_1} finalmente atrapó\n"
	.string "al esquivo {STR_VAR_2}!\p"
	.string "¡El ENTRENADOR parece llorar\n"
	.string "de pura alegría!\p"
	.string "¡Al ver esa cara, yo también tengo\n"
	.string "ganas de ir a pescar!\p"
	.string "Espectadores, ¿por qué no intentan\n"
	.string "pescar algunos {STR_VAR_2}?\p"
	.string "Hasta nuestra próxima emisión, ¡adiós\n"
	.string "y buena pesca para todos!$"

gTVPokemonAnglerText01::
	.string "PESCADOR DE {STR_VAR_2}\p"
	.string "LOCUTOR: ¡Hola! Hoy daremos tips\n"
	.string "para pescar {STR_VAR_2}.\p"
	.string "GURU, ¿qué consejo da para\n"
	.string "atrapar a {STR_VAR_2}?\p"
	.string "GURU: ¿Hm? ¿Atrapar {STR_VAR_2}?\n"
	.string "Bueno, les diré: ¡usen la CAÑA\l"
	.string "con vigor!\p"
	.string "¿Ven a {STR_VAR_1} allá?\n"
	.string "¿Ven cómo maneja la CAÑA?\p"
	.string "Ese ENTRENADOR ya atrapó\n"
	.string "{STR_VAR_3} seguidos.\p"
	.string "LOCUTOR: ¡Es increíble!\n"
	.string "Parece una tormenta...\p"
	.string "Al ver tal técnica, yo también tengo\n"
	.string "ganas de ir a pescar.\p"
	.string "Espectadores, ¿por qué no intentan\n"
	.string "pescar algunos {STR_VAR_2}?\p"
	.string "Hasta nuestra próxima emisión, ¡adiós\n"
	.string "y buena pesca para todos!$"

gTVPokemonTodayFailedText00::
	.string "Hello!\p"
	.string "It's time for POKéMON TODAY!\p"
	.string "HERMANA MAYOR: ¡Hola! ¿Todos bien y\n"
	.string "perky today?\p"
	.string "Hoy vamos a ver el\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "HERMANO MAYOR: ¡Sí! ¡Eso es lo que vamos\n"
	.string "a hacer!$"

gTVPokemonTodayFailedText01::
	.string "¡Oh!\n"
	.string "Hablando de {STR_VAR_1}…\p"
	.string "¡HERMANA, vi al ENTRENADOR con mis\n"
	.string "propios ojos!\p"
	.string "HERMANA: Oh, ¿qué viste?\p"
	.string "HERMANO: Bueno, tuve que viajar a\n"
	.string "{STR_VAR_2}.\p"
	.string "Ahí me encontré con\n"
	.string "{STR_VAR_1}, que intentaba capturar al\l"
	.string "POKéMON {STR_VAR_3}, pero…$"

gTVPokemonTodayFailedText02::
	.string "¡El POKéMON logró escapar!\p"
	.string "¡Gastó todas estas\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "¡Debiste ver la cara de frustración\n"
	.string "de {STR_VAR_1} cuando el\l"
	.string "POKéMON huyó!$"

gTVPokemonTodayFailedText03::
	.string "¡Pero {STR_VAR_1} falló y dejó al\n"
	.string "POKéMON debilitado!\p"
	.string "¡Gastó todas estas\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "¡Debiste ver la cara de asombro\n"
	.string "de {STR_VAR_1} cuando el\l"
	.string "POKéMON cayó!$"

gTVPokemonTodayFailedText04::
	.string "HERMANA: ¡Oye, tú!\n"
	.string "¡Eso no está bien!\p"
	.string "¡No debes reírte de la mala\n"
	.string "suerte de los demás!\p"
	.string "Oh, pobre {STR_VAR_1}.\n"
	.string "¡Qué lástima!\p"
	.string "HERMANO: ¡Es cierto!\n"
	.string "Perdón por reírme.$"

gTVPokemonTodayFailedText05::
	.string "HERMANA: Bufufu…\p"
	.string "HERMANO: ¡Oye!\n"
	.string "¡Tú también te reíste!\p"
	.string "HERMANA: ¡¿Eh?!\p"
	.string "¡Yo no me reí!\n"
	.string "¡De verdad, no lo hice!\p"
	.string "Oh, pobre {STR_VAR_1}.\n"
	.string "¡Qué lástima!\p"
	.string "HERMANO: …$"

gTVPokemonTodayFailedText06::
	.string "HERMANA: ¡Basta de tonterías!\n"
	.string "Veamos el POKéMON de hoy…\p"
	.string "¿Eh?\n"
	.string "¿Ya se acabó el tiempo?\p"
	.string "¡Aww!\n"
	.string "¡No pudimos analizar un POKéMON!\p"
	.string "HERMANO: ¡Nos vemos la próxima!\p"
	.string "HERMANA: ¡Oye, no cortes el show\n"
	.string "sin mí!$"

gTVPokemonTodaySuccessfulText00::
	.string "Hello!\p"
	.string "It's time for POKéMON TODAY!\p"
	.string "HERMANA MAYOR: ¡Hola! ¿Todos bien y\n"
	.string "perky today?\p"
	.string "Hoy vamos a ver el\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "HERMANO MAYOR: ¡Sí! ¡Eso es lo que vamos\n"
	.string "a hacer!$"

gTVPokemonTodaySuccessfulText01::
	.string "HERMANA: {STR_VAR_1} le puso el\n"
	.string "apodo {STR_VAR_3} al {STR_VAR_2}!\p"
	.string "¡Parece que {STR_VAR_3} recibe\n"
	.string "mucho amor y cuidado!$"

gTVPokemonTodaySuccessfulText02::
	.string "HERMANO: El ENTRENADOR lanzó\n"
	.string "tantas POKé BALLS: {STR_VAR_3}!\p"
	.string "¡Al final bastó una {STR_VAR_2}\n"
	.string "para capturarlo!$"

gTVPokemonTodaySuccessfulText03::
	.string "HERMANA: Si fue tan fácil atraparlo,\n"
	.string "¡debe ser el destino quien unió a\l"
	.string "{STR_VAR_1} y al {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "HERMANA: ¡Guau! ¡Qué genial!\p"
	.string "Pero ya sabes, ¡un POKéMON que\n"
	.string "cuesta mucho capturar\l"
	.string "gana el amor de su ENTRENADOR!$"

gTVPokemonTodaySuccessfulText05::
	.string "HERMANA: El {STR_VAR_2} de {STR_VAR_1}\n"
	.string "es memorable, ¡pues costó una\l"
	.string "valiosa MASTER BALL capturarlo!\p"
	.string "HERMANO: ¡Guau! ¡Eso es increíble!\p"
	.string "HERMANA: {STR_VAR_1} debió querer\n"
	.string "mucho a ese {STR_VAR_2}, ¡seguro!$"

gTVPokemonTodaySuccessfulText06::
	.string "HERMANO: Ponerle el apodo\n"
	.string "{STR_VAR_3} a ese {STR_VAR_2}…\p"
	.string "Da una buena idea del sentido\n"
	.string "de ENTRENADOR de {STR_VAR_1}.\p"
	.string "HERMANA: ¡Opino lo mismo!$"

gTVPokemonTodaySuccessfulText07::
	.string "Si fuera yo, le pondría ese apodo\n"
	.string "a algo como este {STR_VAR_3}!\p"
	.string "HERMANO: ¡Vaya! ¡Eso podría ser el\n"
	.string "inicio de algo nuevo!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} el {STR_VAR_1}?\n"
	.string "¿No suena perfecto?\p"
	.string "Las letras y todo...\n"
	.string "suenan justo bien para el POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "HERMANO: Sí, ¡es verdad!$"

gTVPokemonTodaySuccessfulText09::
	.string "Que yo sepa, ningún ENTRENADOR le\n"
	.string "ha puesto el apodo {STR_VAR_2} a su\l"
	.string "{STR_VAR_1}!\p"
	.string "HERMANO: ¡Eso demuestra el gran\n"
	.string "gusto del ENTRENADOR al elegir\l"
	.string "apodos!$"

gTVPokemonTodaySuccessfulText10::
	.string "La próxima vez que atrape un\n"
	.string "POKéMON, lo llamaré {STR_VAR_2}.\p"
	.string "HERMANO: ¿Eh? ¡Yo también!\n"
	.string "¡Usaré el apodo {STR_VAR_2} yo también!$"

gTVPokemonTodaySuccessfulText11::
	.string "HERMANA: ¡Oh, no!\n"
	.string "¡Mira la hora!\p"
	.string "Bueno, chicos, eso es todo por hoy.\n"
	.string "¡Nos vemos la próxima vez!\p"
	.string "HERMANO: ¡Recuerden, su POKéMON\n"
	.string "podría ser la estrella la próxima vez!$"

SmartShopper_Text_Intro::
	.string "¡Hola!\p"
	.string "Es hora de COMPRADOR INTELIGENTE.\p"
	.string "ENTREVISTADOR: ¿Cómo están todos?\p"
	.string "Hoy visitamos una tienda\n"
	.string "en {STR_VAR_2}.\p"
	.string "Veamos qué es lo que más se ha\n"
	.string "vendido últimamente.$"

SmartShopper_Text_ClerkNormal::
	.string "Entrevistemos al empleado para\n"
	.string "saber más.\p"
	.string "Hola, ¿cómo va el negocio?\p"
	.string "EMPLEADO: Oh, nos va excelente.\p"
	.string "Últimamente, {STR_VAR_2} se ha\n"
	.string "vendido muy bien.\p"
	.string "Hace poco, un ENTRENADOR llamado\n"
	.string "{STR_VAR_1} compró {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "ENTREVISTADOR: ¿El ENTRENADOR\n"
	.string "compró {STR_VAR_3} {STR_VAR_2}S? ¡Vaya!\p"
	.string "Diría que {STR_VAR_1} se preparaba\n"
	.string "para un viaje largo a lugares\l"
	.string "lejanos.\p"
	.string "Para viajar, ¡los {STR_VAR_2}S son\n"
	.string "muy importantes!$"

SmartShopper_Text_RandomComment2::
	.string "ENTREVISTADOR: Hablando del\n"
	.string "{STR_VAR_2}, hace poco compré {STR_VAR_3}\l"
	.string "de ellos.\p"
	.string "Después de todo, ¡{STR_VAR_2} es genial!$"

SmartShopper_Text_RandomComment3::
	.string "ENTREVISTADOR: ¡¿{STR_VAR_2}?!\n"
	.string "¡¿Pero {STR_VAR_3} de ellos?!\p"
	.string "No creí que alguien comprara\n"
	.string "tantos.\p"
	.string "Cielos, yo solo puedo pagar uno o\n"
	.string "dos a la vez…$"

SmartShopper_Text_RandomComment4::
	.string "ENTREVISTADOR: Una vez compré\n"
	.string "muchos {STR_VAR_2}.\p"
	.string "Pero resultaron ser demasiados.\n"
	.string "Al final me arrepentí…\p"
	.string "Desde entonces, solo compro lo que\n"
	.string "realmente necesito…\p"
	.string "¡Ups!\p"
	.string "¡No tiene sentido hablar de mí!$"

SmartShopper_Text_SecondItem::
	.string "VENDEDOR: {STR_VAR_1} también compró\n"
	.string "{STR_VAR_2} al por mayor, llevó {STR_VAR_3}.\p"
	.string "ENTREVISTADOR: Oh, qué inteligente.\n"
	.string "{STR_VAR_2} es un gran objeto también.$"

SmartShopper_Text_ThirdItem::
	.string "VENDEDOR: Y el ENTRENADOR también\n"
	.string "compró {STR_VAR_3} de {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "VENDEDOR: Además, fue en una gran\n"
	.string "oferta. Eso es comprar con tino.$"

SmartShopper_Text_OutroNormal::
	.string "ENTREVISTADOR: Hmm... {STR_VAR_1} parece\n"
	.string "¡un cazador de ofertas experto!\p"
	.string "En total, las compras de {STR_VAR_1} fueron...\p"
	.string "¡¿¥{STR_VAR_2}?!\n"
	.string "¡Qué suma tan increíble!\p"
	.string "¡Ups! ¡Se nos acabó el tiempo!\n"
	.string "¡Nos vemos en la próxima emisión!$"

SmartShopper_Text_IsVIP::
	.string "VENDEDOR: {STR_VAR_1} es un cliente VIP,\n"
	.string "no hay ninguna duda de ello.$"

SmartShopper_Text_ClerkMax::
	.string "Entrevistemos al vendedor para saber\n"
	.string "los detalles.\p"
	.string "Hola, ¿cómo va el negocio?\p"
	.string "VENDEDOR: Oh, tenemos ventas\n"
	.string "increíbles. Es abrumador.\p"
	.string "Hace poco, un ENTRENADOR llamado {STR_VAR_1}\n"
	.string "compró {STR_VAR_2} al por mayor.\p"
	.string "Casi agota todo nuestro stock de\n"
	.string "{STR_VAR_2}.\p"
	.string "Jamás soñé que alguien necesitara\n"
	.string "tantos {STR_VAR_2}.\l"
	.string "¡Es algo inaudito!\p"
	.string "ENTREVISTADOR: ¿Entonces vendió\n"
	.string "unas 100 o 200 unidades?\p"
	.string "VENDEDOR: ¡Oh, no, mucho más!\p"
	.string "ENTREVISTADOR: ¡Cielos!\n"
	.string "¡{STR_VAR_1} es un comprador especial!\p"
	.string "VENDEDOR: {STR_VAR_1} es un cliente VIP,\n"
	.string "no hay duda de ello.$"

SmartShopper_Text_OutroMax::
	.string "ENTREVISTADOR: Hmm...\n"
	.string "Eso es asombroso.\p"
	.string "¿Pero por qué el ENTRENADOR querría\n"
	.string "comprar tantos?\p"
	.string "... ...\p"
	.string "El misterio crece, pero es todo el\n"
	.string "tiempo que tenemos hoy.\l"
	.string "¡Nos vemos en la próxima emisión!\p"
	.string "Aun así, {STR_VAR_1} es un enigma...$"

gTVWorldOfMastersText00::
	.string "EL MUNDO DE LOS MAESTROS\p"
	.string "Hola, espectadores.\p"
	.string "Tal vez conozcan a un ENTRENADOR\n"
	.string "llamado {STR_VAR_1}.\p"
	.string "{STR_VAR_1} es famoso por ser un maestro\n"
	.string "capturando POKéMON.\p"
	.string "La búsqueda de {STR_VAR_1} depende\n"
	.string "de una cuidadosa búsqueda a pie.\p"
	.string "Un día memorable, el ENTRENADOR\n"
	.string "caminó {STR_VAR_2} pasos.\p"
	.string "El total de POKéMON capturados\n"
	.string "ese día llegó a {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Esa hazaña fue posible gracias a la\n"
	.string "confianza entre el ENTRENADOR\l"
	.string "y {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "El maestro capturó el último\n"
	.string "{STR_VAR_3} del día cerca de {STR_VAR_2}.\p"
	.string "Ese POKéMON tiene el estatus\n"
	.string "especial de poseedor del récord.\p"
	.string "Los ENTRENADORES expertos deben\n"
	.string "intentar superar este récord.\p"
	.string "Eso es todo por hoy.\n"
	.string "Sintonícennos la próxima vez.$"

gTVTodaysRivalTrainerText00::
	.string "¡EL RIVAL DE HOY!\p"
	.string "¡Hola, ENTRENADORES POKéMON!\n"
	.string "¿Cómo están todos hoy?\p"
	.string "Hoy, como cualquier otro día,\n"
	.string "¡analizaremos a uno de los rivales!$"

gTVTodaysRivalTrainerText07::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que está por {STR_VAR_3} ahora.\p"
	.string "{STR_VAR_1} ha registrado hasta\n"
	.string "ahora {STR_VAR_2} POKéMON en la POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que está en una BASE SECRETA.\p"
	.string "{STR_VAR_1} ha registrado hasta\n"
	.string "ahora {STR_VAR_2} POKéMON en la POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "El rival de hoy es {STR_VAR_1}.\p"
	.string "Hasta ahora, {STR_VAR_1} ha registrado\n"
	.string "{STR_VAR_2} POKéMON en la POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que está en un ferry ahora.\p"
	.string "{STR_VAR_1} ha registrado hasta\n"
	.string "ahora {STR_VAR_2} POKéMON en la POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "¿Y cuántas MEDALLAS tiene nuestro\n"
	.string "rival? ¡El número es {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "¡Pero nuestro rival aún no ha\n"
	.string "obtenido ni una sola MEDALLA!$"

gTVTodaysRivalTrainerText03::
	.string "Nuestro rival aún no ha obtenido\n"
	.string "ningún Símbolo de la FRONTERA!$"

gTVTodaysRivalTrainerText04::
	.string "Veamos cuántos Símbolos de la\n"
	.string "FRONTERA tiene nuestro rival.\p"
	.string "Símbolos Oro: {STR_VAR_1}!\n"
	.string "Símbolos Plata: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Nuestro rival ha reunido {STR_VAR_1}\n"
	.string "Puntos de Batalla en la FRONTERA.$"

gTVTodaysRivalTrainerText06::
	.string "Entonces, ¿cómo te comparas con\n"
	.string "{STR_VAR_1}?\p"
	.string "¡La aventura continúa!\p"
	.string "¡Compañeros ENTRENADORES!\p"
	.string "¡Sigamos avanzando para ir\n"
	.string "siempre delante de nuestros rivales!$"

TrendWatcher_Text_Intro::
	.string "¡RED DE MODAS DE CIUDAD ROCA!\p"
	.string "MC: ¿Qué onda?\n"
	.string "Traemos lo último sobre lo que\l"
	.string "está de moda en CIUDAD ROCA.\p"
	.string "Nuestro invitado es este señor que\n"
	.string "es la autoridad máxima\l"
	.string "en todo lo de CIUDAD ROCA.\p"
	.string "Anciano: Gusto en estar aquí.\p"
	.string "MC: Al grano, sin rodeos.\p"
	.string "¿Qué es lo que más mola entre\n"
	.string "la gente de CIUDAD ROCA?\p"
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "¿dices?\p"
	.string "Anciano: No.\p"
	.string "{STR_VAR_1} {STR_VAR_2} nunca\n"
	.string "se volvió popular.\p"
	.string "¿Quieres que te cuente más?\p"
	.string "MC: Eh, no. Queremos saber\n"
	.string "qué es lo que mola ahora mismo…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "fue lo que {STR_VAR_3} de PUEBLO\l"
	.string "RAÍCES me dijo que estaba de moda…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "fue lo que {STR_VAR_3} de PUEBLO\l"
	.string "RAÍCES me dijo que estaba de moda…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Pero fue totalmente inútil.\p"
	.string "¡Festival {STR_VAR_1} {STR_VAR_2}!\p"
	.string "¡Concurso {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Traté de enseñarles lo mejor\n"
	.string "que pude, pero...\p"
	.string "Quizás la parte de {STR_VAR_1}\n"
	.string "no era la correcta...\p"
	.string "MC: Eh, disculpe, compadre, necesito\n"
	.string "saber qué es lo que se usa ahora...$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Anciano: {STR_VAR_3}!\n"
	.string "¡Dime algo más grande que\l"
	.string "ese {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Anciano: {STR_VAR_3}!\n"
	.string "¡Dime algo más grande que\l"
	.string "ese {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: ...Eh... ¡Así están las cosas,\n"
	.string "gente moderna y con estilo!\p"
	.string "{STR_VAR_1} {STR_VAR_2}... eh...\n"
	.string "¡No fue muy moderno en DEWFORD!\p"
	.string "Se acabó mi tiempo. ¡Nos vemos!\p"
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "¡INVESTIGADORES DE HOENN!\p"
	.string "¡Hola a todos!\n"
	.string "¿Hallaron objetos secretos hace poco?\p"
	.string "Como siempre, veremos reportes de\n"
	.string "secretos de todas partes.\p"
	.string "Empecemos con una carta.\n"
	.string "Dice: “¡{STR_VAR_1} hallado!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "¡Vaya, mejor revisamos esta carta!\n"
	.string "Permítanme leerla.\p"
	.string "...Queridos INVESTIGADORES,\n"
	.string "Espero que estén bien.\p"
	.string "Vi a {STR_VAR_2} hace poco\n"
	.string "cerca de {STR_VAR_3}.\p"
	.string "El ENTRENADOR halló el objeto\n"
	.string "{STR_VAR_1}. Me dio envidia.\p"
	.string "...Bueno, ¡bien hecho, {STR_VAR_2}!\p"
	.string "¡Que esto los motive a usar sus\n"
	.string "ITEMFINDER y a buscar!\p"
	.string "¡Esperaré noticias emocionantes\n"
	.string "de todos ustedes!$"

gTVHoennTreasureInvestigatorsText02::
	.string "¡Vaya, mejor revisamos esta carta!\n"
	.string "Permítanme leerla.\p"
	.string "...Queridos INVESTIGADORES,\n"
	.string "Espero que estén bien.\p"
	.string "Vi a {STR_VAR_2} en un ferry.\p"
	.string "El ENTRENADOR halló el objeto\n"
	.string "{STR_VAR_1}. Me dio envidia.\p"
	.string "...Bueno, ¡bien hecho, {STR_VAR_2}!\p"
	.string "¡Que esto los motive a usar sus\n"
	.string "ITEMFINDER y a buscar!\p"
	.string "¡Esperaré noticias emocionantes\n"
	.string "de todos ustedes!$"

gTVFindThatGamerText00::
	.string "¡BUSQUEN A ESE GAMER!\p"
	.string "¡Hola, gamers!\n"
	.string "¿Cómo gira su {STR_VAR_2}?\p"
	.string "Como siempre, destacaremos a un\n"
	.string "ENTRENADOR raro que visitó el\l"
	.string "GAME CORNER.\p"
	.string "Hoy, nuestro gamer n.º 1 es...\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} jugó al {STR_VAR_2}\n"
	.string "y ganó {STR_VAR_3} MONEDAS raras.\p"
	.string "“Cuando venga {STR_VAR_1}, debemos\n"
	.string "tener suficientes MONEDAS”.\p"
	.string "¡Eso dicen los empleados del CASINO\n"
	.string "cuando nuestro jugador participa!\p"
	.string "Es mejor cuidar sus MONEDAS como\n"
	.string "{STR_VAR_1} si visitan el CASINO\l"
	.string "y juegan al {STR_VAR_2}.\p"
	.string "¡En vivo desde el CASINO, donde\n"
	.string "se siente la emoción!\p"
	.string "¡Eso es todo por hoy!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} jugó al {STR_VAR_2}\n"
	.string "y perdió {STR_VAR_3} MONEDAS.\p"
	.string "“Cuando {STR_VAR_1} viene, las ventas\n"
	.string "de MONEDAS parecen subir”.\p"
	.string "¡Eso dicen los empleados del GAME\n"
	.string "CORNER cuando juega nuestro gamer!$"

gTVFindThatGamerText03::
	.string "Es mejor cuidar sus MONEDAS como\n"
	.string "{STR_VAR_1} si visitan el CASINO\l"
	.string "y juegan al {STR_VAR_2}.\p"
	.string "¡En vivo desde el CASINO, donde\n"
	.string "se siente la emoción!\p"
	.string "¡Eso es todo por hoy!$"

gTVBreakingNewsText00::
	.string "¡NOTICIAS DE ÚLTIMA HORA!$"

gTVBreakingNewsText01::
	.string "¡Un raro {STR_VAR_2} capturado por\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Estamos en vivo cerca de\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} capturó con éxito\n"
	.string "un raro {STR_VAR_2} hace poco!$"

gTVBreakingNewsText02::
	.string "Cuando {STR_VAR_1} halló al raro\n"
	.string "{STR_VAR_2}, el ENTRENADOR lanzó\l"
	.string "al POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "En la batalla, el ENTRENADOR lanzó\n"
	.string "{STR_VAR_1} POKé BALLS.\p"
	.string "Al final, el raro POKéMON fue\n"
	.string "atrapado por la {STR_VAR_2} final.$"

gTVBreakingNewsText04::
	.string "En ese instante, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s roars of\l"
	.string "triumphant joy.\p"
	.string "Debo decir que envidio un poco\n"
	.string "a {STR_VAR_1}. También quiero rugir.\p"
	.string "…Ahí termina la transmisión desde\n"
	.string "la escena feliz!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} no pudo capturar a un\n"
	.string "raro {STR_VAR_2}!\p"
	.string "¡Transmitimos en vivo desde\n"
	.string "{STR_VAR_3}!\p"
	.string "¡Aquí fue donde {STR_VAR_1} no\n"
	.string "pudo capturar al raro {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Cuando {STR_VAR_1} halló al raro\n"
	.string "{STR_VAR_2}, el ENTRENADOR lanzó\l"
	.string "al POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "El ENTRENADOR hizo que {STR_VAR_2}\n"
	.string "usara el movimiento {STR_VAR_1}.\p"
	.string "Sin querer, el ENTRENADOR hizo\n"
	.string "que el raro POKéMON se debilitara…$"

gTVBreakingNewsText12::
	.string "Pero {STR_VAR_1} entró en pánico al\n"
	.string "ver al raro {STR_VAR_2}.\p"
	.string "Confuso, el ENTRENADOR ordenó a\n"
	.string "{STR_VAR_3} atacar.\p"
	.string "Sin querer, el ENTRENADOR hizo\n"
	.string "que el raro POKéMON se debilitara.$"

gTVBreakingNewsText08::
	.string "En ese instante, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText09::
	.string "Sin embargo, {STR_VAR_1} pareció dar\n"
	.string "out of POKé BALLS.\p"
	.string "El ENTRENADOR tuvo que retirarse\n"
	.string "del combate con el raro {STR_VAR_2}.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText10::
	.string "Sin embargo, el {STR_VAR_2} huyó sin\n"
	.string "warning.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText11::
	.string "Siento mucho lo de {STR_VAR_1}.\n"
	.string "¡Hasta a mí me dan ganas de gritar!\p"
	.string "…¡Así termina la transmisión de\n"
	.string "esta melancólica escena!$"

gTVSecretBaseVisitText00::
	.string "¡Hola a todos!\n"
	.string "Es hora de hacer\l"
	.string "una VISITA A BASE SECRETA.\p"
	.string "Hoy visitamos la BASE SECRETA\n"
	.string "de {STR_VAR_1}.\p"
	.string "¿Cómo ha personalizado {STR_VAR_1}\n"
	.string "su BASE SECRETA?\p"
	.string "¡Vamos a verlo!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "¡Oh!\n"
	.string "¡Qué maravilloso!\p"
	.string "Este {STR_VAR_2}…\n"
	.string "¡No es lo que uno esperaría\l"
	.string "encontrar aquí!$"

gTVSecretBaseVisitText02::
	.string "¡Oh!\n"
	.string "¡Qué notable!\p"
	.string "¡No hay ni un solo mueble\n"
	.string "ni objeto decorativo!\p"
	.string "¡Los mortales no podrían\n"
	.string "imitar tal audacia!\p"
	.string "Es simple, pero rebosa, sí,\n"
	.string "¡rebosa salvajismo!\p"
	.string "Me quito el sombrero, {STR_VAR_1}.\n"
	.string "¡Tenías que ser tú!$"

gTVSecretBaseVisitText03::
	.string "¡Oh! ¡Ya veo!\n"
	.string "¡Lo veo con total claridad!\p"
	.string "Que este {STR_VAR_2} esté aquí…\n"
	.string "¡Envía un mensaje efectivo!$"

gTVSecretBaseVisitText04::
	.string "¡Oh! ¡Ya veo!\n"
	.string "¡Lo veo con total claridad!\p"
	.string "¡Este espacio se mantiene\n"
	.string "vacío de objetos a propósito!\p"
	.string "¡Envía un mensaje efectivo!$"

gTVSecretBaseVisitText05::
	.string "¡Uau!\p"
	.string "¡La pareja del {STR_VAR_2}\n"
	.string "con el {STR_VAR_3}!\p"
	.string "¡Es la combinación de ensueño\n"
	.string "por excelencia!$"

gTVSecretBaseVisitText06::
	.string "¡Uau!\p"
	.string "Poner este {STR_VAR_2}\n"
	.string "justo aquí…\p"
	.string "¡Tiene una presencia que llena\n"
	.string "toda la BASE SECRETA!$"

gTVSecretBaseVisitText07::
	.string "¡Uau!\p"
	.string "No hay nada puesto aquí.\p"
	.string "Este espacio vacío afecta a\n"
	.string "toda la BASE SECRETA.$"

gTVSecretBaseVisitText08::
	.string "¡Oh!\n"
	.string "¡Aquí viene {STR_VAR_1}!\l"
	.string "¡Retemos al ENTRENADOR!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Sigh…\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON were truly\n"
	.string "digno del título de CAMPEÓN.\p"
	.string "Dieron sobrada prueba de la\n"
	.string "dureza de {STR_VAR_1} como ENTRENADOR.\p"
	.string "Que el {STR_VAR_2} conociera el movimiento\n"
	.string "{STR_VAR_3}…\p"
	.string "Muestra qué clase de ENTRENADOR\n"
	.string "es {STR_VAR_1}.\p"
	.string "¡Sin duda, toda una lección!$"

gTVSecretBaseVisitText10::
	.string "¡Ayy!\n"
	.string "Hay que felicitar a {STR_VAR_1}.\p"
	.string "Los POKéMON del ENTRENADOR\n"
	.string "eran durísimos.\p"
	.string "Demostraron que {STR_VAR_1}\n"
	.string "es un ENTRENADOR tenaz.\p"
	.string "Que el {STR_VAR_2} conociera\n"
	.string "el movimiento {STR_VAR_3}…\p"
	.string "Dice mucho del ENTRENADOR\n"
	.string "que es {STR_VAR_1}.\p"
	.string "¡Fue toda una lección!$"

gTVSecretBaseVisitText11::
	.string "¡Uf!\n"
	.string "Hay que felicitar a {STR_VAR_1}.\p"
	.string "Los POKéMON del ENTRENADOR\n"
	.string "están bien criados.\p"
	.string "Demostraron que {STR_VAR_1}\n"
	.string "es un ENTRENADOR sabio.\p"
	.string "Que el {STR_VAR_2} conociera\n"
	.string "el movimiento {STR_VAR_3}…\p"
	.string "Dice mucho del ENTRENADOR\n"
	.string "que es {STR_VAR_1}.\p"
	.string "¡Fue toda una lección!$"

gTVSecretBaseVisitText12::
	.string "Well, well!\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON showed\n"
	.string "gran promesa de futuro.\p"
	.string "Representaban las esperanzas\n"
	.string "y sueños de {STR_VAR_1}.\p"
	.string "Que el {STR_VAR_2} conociera el movimiento\n"
	.string "{STR_VAR_3}…\p"
	.string "Muestra qué clase de ENTRENADOR\n"
	.string "es {STR_VAR_1}.\p"
	.string "¡Ciertamente, fue toda una lección!$"

gTVSecretBaseVisitText13::
	.string "¡Debo decir que fue una BASE SECRETA\n"
	.string "estupenda!\p"
	.string "Si pueden, visiten la BASE SECRETA\n"
	.string "de {STR_VAR_1}.\p"
	.string "¡Hasta la próxima, adiós!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "¡Es emocionante!\n"
	.string "¡Es dramático!\p"
	.string "¡Es el REPORTE RELÁMPAGO del\n"
	.string "GANADOR DE LA LOTERÍA POKéMON!\p"
	.string "¡Hola! Transmitimos en vivo desde\n"
	.string "el RINCÓN DE LA LOTERÍA POKéMON en\l"
	.string "la planta baja de los ALMACENES\l"
	.string "DE CIUDAD PORTALIA!\p"
	.string "¡Como siempre, hoy apareció otro\n"
	.string "ENTRENADOR con suerte!\p"
	.string "El nombre de ese ENTRENADOR es…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} ganó el premio {STR_VAR_2}\n"
	.string "¡y se llevó a casa el {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "¡Felicidades!\p"
	.string "¡No se queden mirando,\n"
	.string "únanse a la acción!\p"
	.string "¡En los ALMACENES DE CIUDAD PORTALIA\n"
	.string "esperamos su próxima visita!\p"
	.string "Ha sido una transmisión en vivo de\n"
	.string "los ALMACENES DE CIUDAD PORTALIA,\l"
	.string "¡con la mejor selección de todo\l"
	.string "HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "THE POKéMON BATTLE SEMINAR!\p"
	.string "Analizamos combates para ver qué\n"
	.string "lecciones sacamos de otros.\p"
	.string "El caso de hoy trata sobre el\n"
	.string "battle.\p"
	.string "El {STR_VAR_2} de {STR_VAR_1} fue\n"
	.string "battling one {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "Y usó el movimiento {STR_VAR_3}\n"
	.string "contra {STR_VAR_2}…\p"
	.string "Hmm… ¡{STR_VAR_1}!\n"
	.string "¡Eso no es lo correcto!$"

gTVThePokemonBattleSeminarText02::
	.string "Además del movimiento fallido,\n"
	.string "el {STR_VAR_1} del ENTRENADOR sabía$"

gTVThePokemonBattleSeminarText03::
	.string "los movimientos {STR_VAR_1}, {STR_VAR_2},\n"
	.string "y {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "los movimientos {STR_VAR_1} y\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "el movimiento {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "En esa situación, ¿qué debería\n"
	.string "haber usado el ENTRENADOR?\p"
	.string "… … … … … …\n"
	.string "¡El movimiento {STR_VAR_1}!\p"
	.string "{STR_VAR_1} habría sido\n"
	.string "mucho mejor que {STR_VAR_2}.\p"
	.string "¡Aprendan de este caso y luchen\n"
	.string "con inteligencia!\p"
	.string "¡Hasta la próxima, adiós!$"

gTVTrainerFanClubText00::
	.string "¡Todos juntos ahora!\n"
	.string "¡CLUB DE FANS DEL ENTRENADOR!\p"
	.string "MC: ¿Cómo va ese ritmo?\n"
	.string "Hoy reunimos a los fans del\l"
	.string "popular ENTRENADOR {STR_VAR_1}!\p"
	.string "FANS: ¡Wrooooooaaaaah!\p"
	.string "FANS: ¡{STR_VAR_1}!\p"
	.string "MC: ¡Atención todos!\n"
	.string "¿Qué les parece {STR_VAR_1}?!\p"
	.string "FANS: ¡Amamos a {STR_VAR_1}!\p"
	.string "MC: ¿Qué es lo que más aman de\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: ¡Su estilo al lanzar\n"
	.string "las POKé BALLS!$"

gTVTrainerFanClubText02::
	.string "FANS: ¡Su adorable forma de correr!$"

gTVTrainerFanClubText03::
	.string "FANS: ¡Cómo el ENTRENADOR se hace\n"
	.string "fuerte en los momentos difíciles!$"

gTVTrainerFanClubText04::
	.string "FANS: ¡El conocimiento de POKéMON\n"
	.string "del ENTRENADOR!$"

gTVTrainerFanClubText05::
	.string "FANS: ¡La bondad del ENTRENADOR con\n"
	.string "todos los POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: ¡Las increíbles técnicas de\n"
	.string "BIKE del ENTRENADOR!$"

gTVTrainerFanClubText07::
	.string "FANS: ¡El impresionante estilo de\n"
	.string "compras del ENTRENADOR!$"

gTVTrainerFanClubText08::
	.string "FANS: ¡El encanto del ENTRENADOR al\n"
	.string "poner apodos a los POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: ¡El genial estilo del\n"
	.string "ENTRENADOR al decorar su BASE SECRETA!$"

gTVTrainerFanClubText10::
	.string "FANS: ¡La audacia del ENTRENADOR\n"
	.string "al usar las MT!$"

gTVTrainerFanClubText11::
	.string "MC: ¡Como vieron, {STR_VAR_1}\n"
	.string "está on fire! ¡Quema, ayayay!\p"
	.string "¡Entre los FANS de {STR_VAR_1}\n"
	.string "hay un eslogan especial!\p"
	.string "MC: Cuando diga {STR_VAR_1},\n"
	.string "ustedes digan...\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Así es, cuando alguien diga,\n"
	.string "“{STR_VAR_1}”...\p"
	.string "Respondan: “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "¡Tiene un ritmo único!\n"
	.string "¡Entiendo por qué son FANS\l"
	.string "de {STR_VAR_1}!\p"
	.string "¡Tú, frente a la TV, únete!\n"
	.string "¡Todos juntos ahora!\p"
	.string "MC: Cuando diga {STR_VAR_1},\n"
	.string "ustedes digan...\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: ¡Gracias por unirte, FANS\n"
	.string "salvajes de {STR_VAR_1}!\l"
	.string "¡Eso es todo! ¡Nos vemos!\p"
	.string "MC: Cuando diga {STR_VAR_1},\n"
	.string "ustedes digan...\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "¡BUSCA A LOS LINDOS!\n"
	.string "¡POKéMON CON CINTAS!\p"
	.string "¡Hola, mis dulces televidentes!\p"
	.string "Sé que estarán de acuerdo, ¡un POKéMON\n"
	.string "con CINTAS es simplemente divino!\p"
	.string "Hoy quiero compartir con ustedes\n"
	.string "un lindo POKéMON que vi mientras\l"
	.string "paseaba por el pueblo.\p"
	.string "El POKéMON lindo de hoy\n"
	.string "es el {STR_VAR_2} de {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "La cantidad de CINTAS que\n"
	.string "{STR_VAR_2} lleva es {STR_VAR_3}.\p"
	.string "Dice mucho de cuánto\n"
	.string "{STR_VAR_1} adora a su POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} lleva un increíble\n"
	.string "{STR_VAR_3} RIBBONS!\p"
	.string "Habla mucho de la\n"
	.string "compromiso con los POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} lleva un increíble\n"
	.string "{STR_VAR_3} RIBBONS!\p"
	.string "¡Muestra la total\n"
	.string "dedicación de {STR_VAR_1}!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Veamos más de cerca las muchas\n"
	.string "CINTAS que lleva {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "La CINTA CAMPEÓN es especialmente\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la recibió al entrar al\n"
	.string "SALA DE LA FAMA.\p"
	.string "Realmente resalta la valentía\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA CAMPEÓN!\n"
	.string "¡La combinación es súper efectiva!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "La CINTA GENIAL es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la ganó en un\n"
	.string "CONCURSO GENIAL.\p"
	.string "Resalta la genialidad\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA GENIAL!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "La CINTA BELLEZA es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la ganó en un\n"
	.string "CONCURSO BELLEZA.\p"
	.string "Resalta la belleza\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA BELLEZA!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "La CINTA LINDA es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la ganó en un\n"
	.string "CONCURSO LINDO.\p"
	.string "Resalta lo lindo\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA LINDA!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "La CINTA INTELIGENTE es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la ganó en un\n"
	.string "CONCURSO INTELIGENTE.\p"
	.string "Resalta la inteligencia\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA INTELIGENTE!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "La CINTA DURA es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la ganó en un\n"
	.string "CONCURSO DURO.\p"
	.string "Resalta la fortaleza\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA DURA!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "La CINTA GANADORA es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la ganó por sus hazañas\n"
	.string "en la TORRE DE COMBATE.\p"
	.string "Resalta el gran poder\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA GANADORA!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "La CINTA VICTORIA es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} la ganó por sus hazañas\n"
	.string "en la TORRE DE COMBATE.\p"
	.string "Resalta el increíble poder\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA VICTORIA!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "La CINTA ARTISTA es muy\n"
	.string "atractiva.\p"
	.string "{STR_VAR_2} fue el modelo\n"
	.string "de un artista.\p"
	.string "Resalta el encanto de estrella\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA ARTISTA!\n"
	.string "¡Es una combinación súper eficaz!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "La CINTA Trabajador es\n"
	.string "muy atractiva.\p"
	.string "{STR_VAR_2} la recibió por ser\n"
	.string "un trabajador muy dedicado.\p"
	.string "Resalta la determinación\n"
	.string "de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA Trabajador!\n"
	.string "¡Es una combinación efectiva!$"

TVSpotTheCuties_Text_Outro::
	.string "…Suspiro…\p"
	.string "CINTAS y POKéMON…\n"
	.string "¡Combinan tan maravillosamente!\p"
	.string "Antes de que me desmaye,\n"
	.string "¡me despido de todos!$"

gTVPokemonNewsBattleFrontierText00::
	.string "¡Saludos!\n"
	.string "Es hora de las NOTICIAS POKéMON.\p"
	.string "Tenemos noticias alentadoras de la\n"
	.string "BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "El ENTRENADOR {STR_VAR_1} logró un\n"
	.string "récord de {STR_VAR_2} victorias en\l"
	.string "el modo SINGLE BATTLE de la\l"
	.string "BATTLE TOWER.\p"
	.string "¡Felicidades a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "El ENTRENADOR {STR_VAR_1} logró un\n"
	.string "récord de {STR_VAR_2} victorias en\l"
	.string "el modo DOUBLE BATTLE de la\l"
	.string "BATTLE TOWER.\p"
	.string "¡Felicidades a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "El ENTRENADOR {STR_VAR_1} logró un\n"
	.string "récord de {STR_VAR_2} victorias en\l"
	.string "el modo MULTI BATTLE de la\l"
	.string "BATTLE TOWER.\p"
	.string "¡Felicidades a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "El ENTRENADOR {STR_VAR_1} logró un\n"
	.string "récord de {STR_VAR_2} victorias en\l"
	.string "el modo LINK MULTI BATTLE de la\l"
	.string "BATTLE TOWER.\p"
	.string "¡Felicidades a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "El ENTRENADOR {STR_VAR_1} logró un\n"
	.string "récord de {STR_VAR_2} campeonatos\l"
	.string "en los torneos SINGLE BATTLE del\l"
	.string "BATTLE DOME.\p"
	.string "¡Felicidades a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} victorias\l"
	.string "en los Torneos de DOBLE BATALLA\l"
	.string "del BATTLE DOME.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} victorias\l"
	.string "en el desafío de Intercambio\l"
	.string "Sencillo del BATTLE FACTORY.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} victorias\l"
	.string "en el desafío de Intercambio\l"
	.string "Doble del BATTLE FACTORY.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} salas\l"
	.string "en el desafío de Elección del\l"
	.string "BATTLE PIKE.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} victorias\l"
	.string "en los Torneos de KO del\l"
	.string "BATTLE ARENA.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} victorias\l"
	.string "en el SALÓN de BATALLA SENCILLA\l"
	.string "del BATTLE PALACE.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} victorias\l"
	.string "en el SALÓN de BATALLA DOBLE\l"
	.string "del BATTLE PALACE.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "El ENTRENADOR {STR_VAR_1} logró\n"
	.string "un récord de {STR_VAR_2} pisos\l"
	.string "en el desafío de Búsqueda del\l"
	.string "BATTLE PYRAMID.\p"
	.string "¡Bravo, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Y a los tres POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2} y {STR_VAR_3}!\p"
	.string "¡Felicidades por su\n"
	.string "récord imbatible!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Y a los dos POKéMON, {STR_VAR_1}\n"
	.string "y {STR_VAR_2}!\p"
	.string "¡Felicidades por su\n"
	.string "récord imbatible!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Y a los cuatro POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "¡Y a {STR_VAR_1}!\p"
	.string "¡Felicidades por su\n"
	.string "récord imbatible!$"

gTVPokemonNewsBattleFrontierText18::
	.string "¡Esperemos más récords\n"
	.string "de {STR_VAR_1} y sus leales\l"
	.string "POKéMON!\p"
	.string "¡Esto fue POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "¿QUIÉN ES EL NO. 1 DE HOENN HOY?\n"
	.string "¡Sí, llegó el momento otra vez!\p"
	.string "¡Hola! ¿Están dando lo mejor de sí\n"
	.string "en todo lo que hacen?\p"
	.string "¡Veamos al ENTRENADOR que fue el\n"
	.string "mejor el día de hoy!\p"
	.string "¡El ENTRENADOR no. 1 de hoy es\n"
	.string "nada menos que {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Hoy, {STR_VAR_1} usó las TRAGAPERRAS\n"
	.string "del GAME CORNER {STR_VAR_2} veces.\p"
	.string "Se oyó a {STR_VAR_1} murmurar:\n"
	.string "“Para mí, los rodillos ni\l"
	.string "se mueven...”\l"
	.string "¿No es interesante?$"

gTVWhatsNo1InHoennTodayText02::
	.string "En un día, {STR_VAR_1} jugó\n"
	.string "la RULETA del GAME\l"
	.string "CORNER {STR_VAR_2} veces.\p"
	.string "Mientras jugaba, {STR_VAR_1} gritó:\n"
	.string "¡Que las bolas decidan!\p"
	.string "El ENTRENADOR estaba enfocado\n"
	.string "y muy concentrado.$"

gTVWhatsNo1InHoennTodayText03::
	.string "En un día, {STR_VAR_1} luchó\n"
	.string "{STR_VAR_2} veces contra POKéMON!\p"
	.string "Parece que los POKéMON de {STR_VAR_1}\n"
	.string "son mucho más fuertes.\p"
	.string "¡Están ansiosos por luchar donde sea,\n"
	.string "cuando sea y como sea!$"

gTVWhatsNo1InHoennTodayText04::
	.string "En un día, {STR_VAR_1} usó la\n"
	.string "BATIDORA DE BAYAS {STR_VAR_2} veces!\p"
	.string "Al final, hasta {STR_VAR_1}\n"
	.string "parecía estar mareado.\p"
	.string "¡El ENTRENADOR tambaleaba\n"
	.string "como un SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "En un día, {STR_VAR_1} plantó\n"
	.string "{STR_VAR_2} BAYAS!\p"
	.string "Por eso, la ropa de {STR_VAR_1}\n"
	.string "quedó llena de tierra.\p"
	.string "Donde plantó, brotaron muchísimas\n"
	.string "flores hermosas.\p"
	.string "Dicen que esas flores calman\n"
	.string "las emociones de la gente.$"

gTVWhatsNo1InHoennTodayText06::
	.string "En un día, {STR_VAR_1} recogió\n"
	.string "{STR_VAR_2} BAYAS!\p"
	.string "La MOCHILA de {STR_VAR_1} se llenó\n"
	.string "de BAYAS, ¡que el ENTRENADOR\l"
	.string "apenas podía caminar después!$"

gTVWhatsNo1InHoennTodayText07::
	.string "En un día, {STR_VAR_1} obtuvo\n"
	.string "{STR_VAR_2} Puntos de Batalla!\p"
	.string "{STR_VAR_1} luego fue visto dudando\n"
	.string "si canjear los Puntos de Batalla\l"
	.string "por un objeto genial o por\l"
	.string "una decoración interior bonita.\p"
	.string "Dicen que el ENTRENADOR sonreía\n"
	.string "al pensar sus opciones.$"

gTVWhatsNo1InHoennTodayText08::
	.string "¡Vaya, qué increíble!\p"
	.string "{STR_VAR_1}!\n"
	.string "¡Eres el ENTRENADOR nro. 1 hoy!\p"
	.string "¡Tomen ejemplo de {STR_VAR_1}!\n"
	.string "¡Ustedes también pueden ser el nro. 1!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRET BASE SECRETS!\p"
	.string "¿Qué hacen los ENTRENADORES en el secreto\n"
	.string "de las BASES SECRETAS?\p"
	.string "Hoy investigamos la\n"
	.string "SECRET BASE.\p"
	.string "Oh? It looks like {STR_VAR_2} has come\n"
	.string "de visita.\p"
	.string "¡Vamos a echar un vistazo!\p"
	.string "¿Qué hará {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "¿Qué hará {STR_VAR_2} ahora?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "¿Y ahora, qué hará {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Al final, {STR_VAR_2} dio {STR_VAR_3} pasos\n"
	.string "en la BASE SECRETA de {STR_VAR_1}\l"
	.string "antes de irse.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Parece que la BASE SECRETA de\n"
	.string "{STR_VAR_1} no interesó a {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} parece haber disfrutado\n"
	.string "mucho la BASE SECRETA de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} parece haberse vuelto\n"
	.string "a huge fan of {STR_VAR_1}'s\l"
	.string "SECRET BASE.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Ustedes también deberían visitar la\n"
	.string "BASE SECRETA de {STR_VAR_1}.\p"
	.string "¡Sintonícennos para ver otra\n"
	.string "BASE SECRETA! ¡Gracias por vernos!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "¡El visitante se detuvo!\p"
	.string "¡El visitante no se mueve!\p"
	.string "¿La BASE SECRETA de {STR_VAR_1}\n"
	.string "era tan poco interesante?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "¡El visitante se detuvo!\p"
	.string "¡El visitante no se mueve nada!\p"
	.string "¿Será el cansancio?\n"
	.string "¿Se habrá agotado el visitante?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "¡El visitante se sentó!\n"
	.string "¡El visitante está sentado!\p"
	.string "¡Mira esa cara de alegría!\p"
	.string "¡Esa silla debe ser muy cómoda\n"
	.string "para reaccionar así!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "¡El visitante atacó un globo!\p"
	.string "¡Explotó!\n"
	.string "¡Cielos, se reventó!\p"
	.string "¡El visitante parece asustado por\n"
	.string "el ruido repentino!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "¡El visitante entró a una TIENDA!\p"
	.string "¡El visitante corre por doquier!\p"
	.string "¡Vaya, el visitante juega feliz!\p"
	.string "¡El visitante parece sorprendido por\n"
	.string "el tamaño de la TIENDA!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "¡El visitante examina\n"
	.string "una planta en maceta!\p"
	.string "¡El visitante tiene un gusto\n"
	.string "sorprendentemente maduro!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "¡El visitante examina\n"
	.string "un ESCUDO DE ORO!\p"
	.string "¡Los ojos del visitante brillan\n"
	.string "de pura admiración!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "¡El visitante examina\n"
	.string "un ESCUDO DE PLATA!\p"
	.string "¡El visitante abrió mucho los ojos!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "¡El visitante examina\n"
	.string "un ADORNO DE VIDRIO!\p"
	.string "¡Oh, no!\p"
	.string "¡El visitante lo está tocando!\p"
	.string "Se está llenando de\n"
	.string "huellas dactilares…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "¡El visitante ve la televisión!\p"
	.string "¡Parece que es un gran fan de la TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "¡El visitante pisó una BOLA DE LODO!\p"
	.string "¡El visitante se ve feliz!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…¿Oh?\p"
	.string "¡El visitante busca en su propia\n"
	.string "MOCHILA y revuelve todo!\p"
	.string "¡El visitante sacó\n"
	.string "un {STR_VAR_2}!\p"
	.string "¡Mira al visitante sonreír al\n"
	.string "mostrar el {STR_VAR_2}!\p"
	.string "¡Parece un comercial de TV!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "El visitante toma un cojín y…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…¡empieza a golpearlo!\p"
	.string "¿Tendrá el visitante mucho estrés?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…¡lo abraza fuerte!\p"
	.string "¿Estará el visitante feliz\n"
	.string "por algo?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "¡El visitante charla con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a\n"
	.string "tener una batalla!\p"
	.string "Y…\p"
	.string "¡Fue el visitante!\n"
	.string "¡Ganó un combate fuera de casa!\p"
	.string "¡El visitante hace\n"
	.string "un baile de victoria!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "¡El visitante charla con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a\n"
	.string "tener una batalla!\p"
	.string "Y…\p"
	.string "¡Fue {STR_VAR_1}!\n"
	.string "¡El visitante ha perdido!\p"
	.string "¡El visitante se ve abatido!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "¡El visitante charla con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a\n"
	.string "tener una batalla!\p"
	.string "Y…\p"
	.string "¡No, el visitante se negó!\p"
	.string "¡Al final no habrá batalla!\p"
	.string "¿Le pareció {STR_VAR_1}\n"
	.string "poco atractivo?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "¡El visitante mira fijamente\n"
	.string "un póster!\p"
	.string "¿Le gustará el póster\n"
	.string "al visitante?\p"
	.string "...Pero... hay algo inquietante\n"
	.string "en su mirada.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "¡Pisó un TAPETE MUSICAL!\p"
	.string "...Hmm...\n"
	.string "¡Compuso una melodía graciosa!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "¡El visitante charla con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a\n"
	.string "tener una batalla!\p"
	.string "Y...\p"
	.string "¡Es un empate!\n"
	.string "¡No se resolvió nada!\p"
	.string "¡Ambos ENTRENADORES parecen\n"
	.string "muy decepcionados!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "¡El visitante pisó\n"
	.string "un TAPETE GIRATORIO!\p"
	.string "¡Parece que está mareado!\p"
	.string "¡El visitante tambalea!\n"
	.string "¡Cuidado!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "¡El visitante intenta alcanzar\n"
	.string "un ADORNO DE ARENA!\p"
	.string "¡Oh!\p"
	.string "¡Se desmoronó!\n"
	.string "¡Se ha roto en pedazos!\p"
	.string "¡El visitante se ve apenado\n"
	.string "y culpable!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "¡El visitante frota la mesa\n"
	.string "con el dedo!\p"
	.string "¡Parece que no tolera\n"
	.string "el polvo!\p"
	.string "¡Le preocupa sorprendentemente\n"
	.string "la limpieza!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "¡El visitante mira un LADRILLO!\p"
	.string "Quizás piensa en el objeto\n"
	.string "que hay sobre el LADRILLO.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "El visitante camina sobre\n"
	.string "la TABLA SÓLIDA.\p"
	.string "No deja de mirar hacia abajo.\p"
	.string "¡Parece ser sorprendentemente\n"
	.string "tímido y cauteloso!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "¡El visitante mira fijamente\n"
	.string "una CERCA!\p"
	.string "¿Se le ocurrió una idea para\n"
	.string "una trampa al visitante?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "¡El visitante pisó un\n"
	.string "TAPETE BRILLANTE!\p"
	.string "¡El visitante hace varias\n"
	.string "poses!\p"
	.string "¡Parece que el visitante fantasea\n"
	.string "con ser un ídolo!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "¡El visitante mira fijamente\n"
	.string "una LLANTA!\p"
	.string "¿Pensará en qué tipo de auto\n"
	.string "usaría una así?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "¡El visitante subió a un pedestal!\p"
	.string "¡El visitante mira la BASE de\n"
	.string "{STR_VAR_1} desde lo alto!\p"
	.string "Y...\p"
	.string "¡Lanza un rugido!\n"
	.string "¡El visitante está rugiendo!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "¡El visitante chocó de frente\n"
	.string "contra una PUERTA FRÁGIL!\p"
	.string "¡El visitante ríe a carcajadas!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "¡El visitante habla con un MUÑECO!\p"
	.string "...Da un poco de miedo...$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "¡El visitante sube la escalera\n"
	.string "de un TOBOGÁN!\p"
	.string "Y...\p"
	.string "¡El visitante se deslizó!\p"
	.string "¡Parece que el visitante se\n"
	.string "está divirtiendo mucho!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "¡El visitante sube la escalera\n"
	.string "de un TOBOGÁN!\p"
	.string "Y...\p"
	.string "¡El visitante bajó por\n"
	.string "la escalera!\p"
	.string "¿Acaso el visitante tuvo miedo?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "El visitante pisó\n"
	.string "¡un TAPETE DE SALTO!\p"
	.string "¡El visitante saltó una vez!\p"
	.string "¡Saltó dos veces!\p"
	.string "¡Y aterrizó con éxito!\p"
	.string "¡El visitante aplaude!\n"
	.string "¡Qué gran actuación solo!$"

gTVSafariFanClubText00::
	.string "¡CLUB DE FANS SAFARI!\p"
	.string "REPORTERO: ¡Muy bien, amigos!\n"
	.string "¿Lanzando SAFARI BALLS, eh?\p"
	.string "¡Estoy aquí en la ZONA SAFARI\n"
	.string "llena de POKéMON increíbles!\p"
	.string "¡Hablemos con este buen amigo,\n"
	.string "el GUÍA SAFARI!\p"
	.string "Dime, amigo, ¿cómo van los\n"
	.string "ENTRENADORES visitantes?$"

gTVSafariFanClubText01::
	.string "GUÍA: Todos parecen estar\n"
	.string "esforzándose mucho.\p"
	.string "{STR_VAR_1} lo hace muy bien.\p"
	.string "Mira, antes, {STR_VAR_1} atrapó\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "El ENTRENADOR es hábil con {POKEBLOCK}S.\n"
	.string "Usó {STR_VAR_2} esta vez, creo.$"

gTVSafariFanClubText03::
	.string "El ENTRENADOR no usó ni un solo\n"
	.string "{POKEBLOCK}! ¡Ni uno solo!\p"
	.string "Eso sí que es un experto.$"

gTVSafariFanClubText04::
	.string "REPORTERO: ¿De verdad?\p"
	.string "¡Parece que nuestro amigo {STR_VAR_1}\n"
	.string "es un gran maestro SAFARI!\p"
	.string "GUÍA: Espero que el ENTRENADOR vuelva\n"
	.string "y nos muestre esa gran técnica.$"

gTVSafariFanClubText05::
	.string "GUÍA: Nadie parece estar\n"
	.string "yendo muy bien.\p"
	.string "{STR_VAR_1} lo pasó peor.\p"
	.string "Mira, antes, el ENTRENADOR solo\n"
	.string "atrapó {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUÍA: Nadie parece estar\n"
	.string "yendo muy bien.\p"
	.string "{STR_VAR_1} lo pasó peor.\p"
	.string "Mira, antes, el ENTRENADOR no\n"
	.string "atrapó ni un POKéMON. ¡Ni uno!$"

gTVSafariFanClubText07::
	.string "El ENTRENADOR usa {POKEBLOCK}S.\n"
	.string "Creo que usó {STR_VAR_2} esa vez.\p"
	.string "Pero ojalá el ENTRENADOR sea\n"
	.string "un poco mejor en esto.$"

gTVSafariFanClubText08::
	.string "Creo que el ENTRENADOR tendría más\n"
	.string "suerte usando {POKEBLOCK}S, que no\l"
	.string "se usaron para nada esa vez.$"

gTVSafariFanClubText09::
	.string "REPORTERO: ¿Es así entonces?\p"
	.string "Parece que nuestro amigo {STR_VAR_1}\n"
	.string "necesita más práctica en el SAFARI.\p"
	.string "GUÍA: Espero que el ENTRENADOR\n"
	.string "vuelva hasta que le salga bien.$"

gTVSafariFanClubText10::
	.string "REPORTERO: ¡Exactamente!\n"
	.string "¡Enfrentar retos es importante!\p"
	.string "¡Espectadores, vengan al SAFARI\n"
	.string "y acepten el reto ustedes mismos!\p"
	.string "¡Hasta la próxima, adiós!$"

ContestLiveUpdates_Text_Intro::
	.string "“¡NOTICIAS DE CONCURSOS POKéMON!”\p"
	.string "MC: ¡Gracias por acompañarnos!\p"
	.string "Estamos en vivo desde el sitio de\n"
	.string "{STR_VAR_1} que acaba de terminar.\p"
	.string "El salón sigue lleno de gente\n"
	.string "que no se quiere marchar.\p"
	.string "Fan: ¡{STR_VAR_2}!\p"
	.string "Fan: ¡{STR_VAR_3}!\p"
	.string "MC: Como oyeron, el CONCURSO\n"
	.string "lo ganó el POKéMON {STR_VAR_2}\l"
	.string "de {STR_VAR_3}.\p"
	.string "Fan: ¡{STR_VAR_2}!\n"
	.string "¡Eres el mejor!\p"
	.string "Fan: ¡{STR_VAR_3}!\n"
	.string "¡Así se hace!\p"
	.string "MC: Veamos qué dicen los fans\n"
	.string "sobre este CONCURSO.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Fan: ¡El {STR_VAR_2} fue el mejor en\n"
	.string "el juicio primario y secundario!\p"
	.string "¡Ese {STR_VAR_2} seguirá ganando!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Fan: El {STR_VAR_2} no fue muy bien\n"
	.string "en el juicio primario, ¡pero arrasó\l"
	.string "en el juicio secundario!\p"
	.string "Fue un regreso milagroso para\n"
	.string "ese {STR_VAR_2}. ¡Yupi!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Espectador: El {STR_VAR_2} fue\n"
	.string "constante en el juicio primario\l"
	.string "y secundario.\p"
	.string "{STR_VAR_3} y el {STR_VAR_2},\n"
	.string "¡no son un combo ordinario!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Espectador: En cuanto a {STR_VAR_1},\n"
	.string "ese {STR_VAR_2} fue increíble.\p"
	.string "Espero que haga mejores poses\n"
	.string "la próxima vez.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Espectador: Cuando {STR_VAR_2} se\n"
	.string "puso nervioso, no pude evitar\l"
	.string "animarlo a gritos.\p"
	.string "Quisiera decirle a ese\n"
	.string "{STR_VAR_2}: ¡Felicidades!$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Espectador: ¡La pose de ese {STR_VAR_2}\n"
	.string "me sorprendió hasta a mí!\p"
	.string "{STR_VAR_2}, ¡estuviste genial!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Espectador: ¡El combo de {STR_VAR_2}\n"
	.string "fue impresionante!\p"
	.string "¡Me ha dejado impactado!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Espectador: ¡La pose del {STR_VAR_2}\n"
	.string "ganador hizo latir mi corazón!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "¡Estuviste genial!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "¡Estuviste hermoso!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "¡Estuviste lindo!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "¡Fuiste muy inteligente!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "¡Fuiste muy fuerte!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Espectador: ¡El atractivo del {STR_VAR_2}\n"
	.string "ganador aún hace latir mi corazón!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "¡Eres lo más genial de todo!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "¡Eres la más hermosa!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "¡Eres simplemente la más linda!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "¡Eres la más inteligente de todos!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "¡Eres la más fuerte de todas!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Espectador: Aunque el {STR_VAR_2}\n"
	.string "dejó de hacer exhibiciones,\l"
	.string "no pude dejar de mirarlo.\p"
	.string "Ese {STR_VAR_2} me cautivó.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Espectador: Cuando el {STR_VAR_2} se\n"
	.string "asustó por otro POKéMON,\l"
	.string "casi lloro de la emoción.\p"
	.string "{STR_VAR_2}, ¡fuiste fuerte!\n"
	.string "¡Así se hace!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Espectador: Oh...\n"
	.string "¡El {STR_VAR_3} de ese {STR_VAR_2}!\l"
	.string "¡El {STR_VAR_3} de {STR_VAR_2}!\l"
	.string "¡El {STR_VAR_3} de {STR_VAR_2}!\l"
	.string "¿Cómo puede ser tan maravilloso?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Bueno, ya lo ves. ¡Este lugar\n"
	.string "está lleno de fans de {STR_VAR_1}!\p"
	.string "También debo decir que otro\n"
	.string "POKéMON, el {STR_VAR_3} de {STR_VAR_2}, \l"
	.string "me llamó la atención.\p"
	.string "El {STR_VAR_3} de {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "No logró hacer ni una exhibición\n"
	.string "por los nervios en la segunda ronda.\p"
	.string "La próxima vez, quisiera ver a este\n"
	.string "{STR_VAR_1} hacer al menos una.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Quedó último en la primera y\n"
	.string "segunda ronda de calificación.\p"
	.string "Espero que {STR_VAR_1} reentrene a este\n"
	.string "{STR_VAR_2} y borre la vergüenza de\l"
	.string "haber quedado en último lugar.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "No aprovechó la emoción del\n"
	.string "público para hacer una exhibición\l"
	.string "adecuada.\p"
	.string "Ojalá {STR_VAR_1} aprenda a sentir al\n"
	.string "público y a elevar la emoción al\l"
	.string "máximo la próxima vez.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Aunque quedó primero en la primera\n"
	.string "fase, sus gestos en la segunda\l"
	.string "no funcionaron.\p"
	.string "Sufrió una derrota humillante\n"
	.string "al final del concurso.\p"
	.string "Seguro que {STR_VAR_1} estudia ahora\n"
	.string "cómo hacer mejores gestos.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "El público no se emocionó con sus\n"
	.string "estampidas en la segunda ronda.\p"
	.string "Ojalá deje de pensar en otros\n"
	.string "POKéMON y aprenda a atraer más\l"
	.string "al público con sus ataques.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Perdió ante {STR_VAR_2} de {STR_VAR_1}\n"
	.string "por un margen muy pequeño.\p"
	.string "Debe ser triste estar tan cerca\n"
	.string "de la victoria y fallar así.\p"
	.string "No me sorprendería que {STR_VAR_3}\n"
	.string "esté llorando por el resultado.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Decepcionó al JUEZ al repetir\n"
	.string "los mismos ataques.\p"
	.string "Es un error imperdonable en cualquier\n"
	.string "CONTEST, y el POKéMON pagó.\p"
	.string "{STR_VAR_1} debe sentirse culpable\n"
	.string "por este mal desempeño.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} hizo un gran esfuerzo,\n"
	.string "pero...\p"
	.string "Fue en vano, terminó en último lugar.\p"
	.string "{STR_VAR_1} debe aprender de esto\n"
	.string "y usar ese conocimiento bien.$"

ContestLiveUpdates_Text_Outro::
	.string "Terminemos el programa con la\n"
	.string "despedida habitual a los ganadores.\p"
	.string "¡Esta vez son {STR_VAR_1} y\n"
	.string "el {STR_VAR_2}!\p"
	.string "MC: ¿Están todos listos?\n"
	.string "¡Todos juntos ahora!\p"
	.string "Público: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "¡Felicidades!\l"
	.string "¡Ganaron el CONTEST!$"

gTVPokemonBattleUpdateText00::
	.string "¡NOTICIAS DE BATALLA POKéMON!\p"
	.string "¡Traemos los resultados de las\n"
	.string "batallas POKéMON al instante!$"

gTVPokemonBattleUpdateText01::
	.string "Los ENTRENADORES {STR_VAR_1} y\n"
	.string "{STR_VAR_2} se enfrentaron en\l"
	.string "una BATALLA {STR_VAR_3}.\p"
	.string "¡Este combate terminó en victoria\n"
	.string "para {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "En la batalla, el {STR_VAR_1} de\n"
	.string "{STR_VAR_2} fue formidable\l"
	.string "¡usando {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "El {STR_VAR_2} de {STR_VAR_1} tuvo\n"
	.string "un desempeño muy pobre.$"

gTVPokemonBattleUpdateText04::
	.string "¡Felicidades por tu victoria,\n"
	.string "{STR_VAR_1}!\p"
	.string "Y para el {STR_VAR_2} derrotado,\n"
	.string "¡esperamos mejores resultados!\p"
	.string "Aquí termina este episodio de\n"
	.string "“¡NOTICIAS DE BATALLA POKéMON!”$"

gTVPokemonBattleUpdateText05::
	.string "Los equipos de {STR_VAR_1} y\n"
	.string "{STR_VAR_2} tuvieron un MULTI BATTLE.\p"
	.string "El combate terminó en victoria para\n"
	.string "el equipo de {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "En la batalla, el {STR_VAR_2} del\n"
	.string "equipo de {STR_VAR_1} fue una fuerza\l"
	.string "formidable usando {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "El mal desempeño del {STR_VAR_3}\n"
	.string "de {STR_VAR_2} fue muy costoso.\p"
	.string "¡Felicidades por la victoria de tu\n"
	.string "equipo, {STR_VAR_1}!\p"
	.string "Para el equipo derrotado de {STR_VAR_2},\n"
	.string "¡esperamos mejores resultados!\p"
	.string "Aquí termina este episodio de\n"
	.string "“¡NOTICIAS DE BATALLA POKéMON!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: ¡Oh! ¡Vimos a un ENTRENADOR\n"
	.string "que parece fuerte justo aquí!\p"
	.string "¡Bien, graben!\n"
	.string "Hagamos esta entrevista.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: ¡Oh! ¡Eres {PLAYER}! ¡Hola!\n"
	.string "¿Nos recuerdas de la última vez?\p"
	.string "¿Nos muestras cuánto más fuerte\n"
	.string "te has vuelto? ¡Que empiece todo!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: ¡Mis ojos no mintieron!\n"
	.string "¡Encontré a un ENTRENADOR asombroso!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: ¡Genial! ¡Genial!\n"
	.string "¡¿Quién eres?!\p"
	.string "¡Sabía que encontraríamos algo\n"
	.string "salvaje al verte!\p"
	.string "Oh, deja que te explique. Viajamos\n"
	.string "por doquier entrevistando a todo\l"
	.string "tipo de ENTRENADORES.\p"
	.string "¿Nos darías un poco de tu tiempo\n"
	.string "para una entrevista?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}”\p"
	.string "¿Recuerdas? Esa fue la frase que\n"
	.string "dijiste al ganar la última vez.\p"
	.string "¡Jamás olvido cosas así!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "La última vez que luchamos, nos\n"
	.string "venciste antes de reaccionar...\p"
	.string "En fin, ¿qué te parece?\n"
	.string "¿Quieres otra entrevista?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "La última vez, ¿no nos lanzaste\n"
	.string "una POKé BALL?\p"
	.string "¡Nos impactó! ¡Se lo contamos a\n"
	.string "todo el mundo!\p"
	.string "En fin, ¿qué te parece?\n"
	.string "¿Quieres otra entrevista?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "La última vez, tu habilidad con\n"
	.string "los objetos nos derrotó.\p"
	.string "En fin, ¿qué te parece?\n"
	.string "¿Quieres otra entrevista?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "La última vez que luchamos, logramos\n"
	.string "vernos respetables.\p"
	.string "En fin, ¿qué te parece?\n"
	.string "¿Quieres otra entrevista?$"

GabbyAndTy_Text_InterviewAgain:
	.string "En fin, ¿qué te parece?\n"
	.string "¿Quieres otra entrevista?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "¿En serio?\n"
	.string "¡Gracias!\p"
	.string "Bien, describe tus sentimientos\n"
	.string "sobre la batalla, pero que sea\l"
	.string "corto y conciso. ¡Dale!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: ¡Mmm, sí!\n"
	.string "¡Es el cierre perfecto!\p"
	.string "Siento que esto será un\n"
	.string "gran programa de TV.\p"
	.string "Puede que lo pasen por TV,\n"
	.string "¡así que búscanos!\p"
	.string "¡Bien!\n"
	.string "¡Nos vemos!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh...\p"
	.string "Está bien, ¡no te rindas!\n"
	.string "¡Estaremos pendientes de ti!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: ¡Estaremos pendientes\n"
	.string "de ti!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: ¿Hay algún ENTRENADOR fuerte\n"
	.string "con muchos POKéMON por aquí?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: ¡Vaya, eres increíble!\p"
	.string "Te has vuelto mucho más fuerte\n"
	.string "desde nuestra última batalla.\p"
	.string "Teníamos razón al verte como\n"
	.string "un ENTRENADOR prometedor.\p"
	.string "En fin, ¿qué te parece?\n"
	.string "¿Nos darías una entrevista\l"
	.string "esta vez?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: ¡Fue una batalla intensa!\n"
	.string "¿Grabaste todo con la cámara?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: ¡Oye, mira! ¡Un ENTRENADOR\n"
	.string "que parece fuerte, justo aquí!\l"
	.string "¡Cámara rodando!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: ¡Oye, mira!\n"
	.string "¡Te recuerdo!\p"
	.string "¡Grabaré toda esta batalla\n"
	.string "con esta cámara!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: ¡Tienes un don!\n"
	.string "¡Tengo unas imágenes increíbles!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: ¿Solo tienes un POKéMON\n"
	.string "y ya está?\p"
	.string "Si tuvieras más POKéMON, sería\n"
	.string "mejor para el video, pero…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Sí, hallamos a un gran ENTRENADOR.\n"
	.string "¡Esto es una primicia enorme!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Sí, lo grabé todo.\n"
	.string "Toda la batalla quedó en cámara.$"

gTVInSearchOfTrainersText00::
	.string "BUSCANDO ENTRENADORES…\p"
	.string "GABBY: ¡Hola! Hoy visito una zona\n"
	.string "cerca de {STR_VAR_1}.\p"
	.string "Buscamos nuevos talentos en el\n"
	.string "campo de batalla.\p"
	.string "Hoy enfocamos nuestra lente en el\n"
	.string "ENTRENADOR {PLAYER}.\p"
	.string "Hay algo en este ENTRENADOR que\n"
	.string "despertó nuestro interés.$"

gTVInSearchOfTrainersText01::
	.string "Ya luchamos contra {PLAYER}, pero\n"
	.string "atestiguamos que el ENTRENADOR ha\l"
	.string "mejorado mucho desde entonces.\p"
	.string "¡Supe que era alguien especial al\n"
	.string "ver a este ENTRENADOR!$"

gTVInSearchOfTrainersText02::
	.string "La mejor forma de saber qué tan\n"
	.string "fuerte es un ENTRENADOR…\p"
	.string "Bueno, lo más rápido es luchar.\n"
	.string "¡Así empezamos la investigación!\p"
	.string "… …\p"
	.string "Así fue como terminamos luchando\n"
	.string "contra {PLAYER}.\p"
	.string "En un despliegue dominante, ¡nos\n"
	.string "aplastaron y nos hicieron trizas!\p"
	.string "{PLAYER} es despiadadamente fuerte…\p"
	.string "Aquí están nuestras impresiones\n"
	.string "tras luchar con el ENTRENADOR.$"

gTVInSearchOfTrainersText03::
	.string "¡La combinación de {STR_VAR_1} y\n"
	.string "{STR_VAR_3} fue divina!\p"
	.string "Verlos a ellos: {STR_VAR_1} y\n"
	.string "{STR_VAR_3}--selflessly supporting\l"
	.string "entre sí en pleno combate…\p"
	.string "¡Fue un espectáculo maravilloso!\p"
	.string "{STR_VAR_2} fue el movimiento que el ENTRENADOR\n"
	.string "usó último en nuestro combate.\p"
	.string "El movimiento {STR_VAR_2} es {STR_VAR_1}\n"
	.string "y muestra de amistad de {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "…Perdí la confianza en mí mismo\n"
	.string "tras nuestro encuentro.\p"
	.string "Nos vencieron antes de que pudiéramos\n"
	.string "lanzar un solo ataque.\l"
	.string "Ohhh… Buaaa…\p"
	.string "Aun así, las batallas de {PLAYER}\n"
	.string "valen la pena verlas.\p"
	.string "Recomiendo a ENTRENADORES seguros\n"
	.string "que desafíen a {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Solo hay una cosa que decir.\n"
	.string "¡No te atrevas a lanzar una POKé BALL\l"
	.string "en una batalla TRAINER!\p"
	.string "{PLAYER} es fuerte, pero no tiene\n"
	.string "ni idea de las reglas básicas.\p"
	.string "Pido algo a nuestra audiencia de TV.\p"
	.string "Si ven a {PLAYER}, ¡por favor avisen\n"
	.string "al ENTRENADOR!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} es experto leyendo los\n"
	.string "movimientos del rival.\p"
	.string "¡El uso de objetos fue\n"
	.string "sorprendentemente efectivo!$"

gTVInSearchOfTrainersText07::
	.string "Sinceramente, pensé que yo\n"
	.string "podría ser bastante bueno.\p"
	.string "Aunque perdimos, tuvimos una\n"
	.string "batalla muy reñida.\p"
	.string "Pero si sufres contra mí,\n"
	.string "¡te falta camino, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Tras la batalla, pedimos a {PLAYER}\n"
	.string "un resumen conciso.\p"
	.string "El ENTRENADOR dijo: “{STR_VAR_1}”.\p"
	.string "Los POKéMON de {PLAYER}, {STR_VAR_2}\n"
	.string "y {STR_VAR_3}…\l"
	.string "Y “{STR_VAR_1}”…\p"
	.string "¡Mmm! ¡Qué profundo! ¡Hay un\n"
	.string "gran significado en esa frase!\p"
	.string "No sorprende; un buen ENTRENADOR\n"
	.string "tiene cosas buenas que decir.\p"
	.string "¡Eso es todo por hoy!\n"
	.string "¡Nos vemos en la próxima emisión!$"

ContestLadyShow_Text_Intro::
	.string "¡NOTICIAS DEL CONCURSO POKéMON!\p"
	.string "MC: ¡Perdón por interrumpir la\n"
	.string "programación y gracias por vernos!\p"
	.string "Transmitimos en vivo desde la\n"
	.string "escena de un recién terminado\l"
	.string "{STR_VAR_1}!\p"
	.string "Gente: ¡?!!!!\p"
	.string "MC: ¡Oh! ¡Parece que los participantes\n"
	.string "del CONCURSO vienen hacia acá!\p"
	.string "¡Intentaré hacer una entrevista\n"
	.string "para los que están en casa!\p"
	.string "Gente: ¡?!!!!\n"
	.string "¡?!!!!$"

ContestLadyShow_Text_Won::
	.string "MC: ¡Disculpe!\n"
	.string "¡Gracias por salir en vivo en TV!\p"
	.string "¿Puedo felicitarle por su victoria?\p"
	.string "¿Cuál fue la clave de su asombrosa\n"
	.string "victoria de hoy?\p"
	.string "BEAUTY: ¡Dimos nuestro mejor esfuerzo\n"
	.string "hoy, mi {STR_VAR_2} y yo!\p"
	.string "Pero no lo lograríamos sin toda la\n"
	.string "ayuda que recibimos antes del\l"
	.string "CONTEST!\p"
	.string "MC: ¿Hay alguien especial con quien\n"
	.string "quiera compartir su alegría?\l"
	.string "¡Escuchémoslo en vivo!\p"
	.string "BEAUTY: ¡Oye, tú!\p"
	.string "¡{STR_VAR_3}! ¿Estás viendo?\n"
	.string "¡Lo logramos!\l"
	.string "¡Gracias!$"

ContestLadyShow_Text_Lost::
	.string "MC: ¡Disculpe!\n"
	.string "¡Gracias por acompañarnos en vivo!\p"
	.string "Debe estar decepcionada. ¿Tiene\n"
	.string "algún comentario?\p"
	.string "CHICA: Es desgarrador…\n"
	.string "Mi {STR_VAR_2} y yo dimos lo mejor…\p"
	.string "Siento que defraudé a todos los que\n"
	.string "nos apoyaron en esto.\p"
	.string "MC: Odio decirlo, pero el color\n"
	.string "del POKéMON deja que desear.\p"
	.string "CHICA: {STR_VAR_3}, lo siento mucho…\n"
	.string "Lo haré mejor la próxima vez…\l"
	.string "…Snif… ¡Buaaaaah!\p"
	.string "Gente: ¿Vieron eso?\n"
	.string "¡Pobre chica!\p"
	.string "MC: Eh… Oh-oh…\p"
	.string "¡Eso es todo por hoy!\n"
	.string "¡Gracias por sintonizarnos!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: ¡Disculpa!\n"
	.string "¡Gracias por estar en vivo!\p"
	.string "¿Cómo te fue en el CONTEST?\p"
	.string "BEAUTY: Nada salió bien...\n"
	.string "Por alguna razón, mi {STR_VAR_2}\l"
	.string "no logró ganar popularidad.\p"
	.string "MC: No quiero decirlo, pero el color\n"
	.string "del POKéMON deja que desear.\p"
	.string "BEAUTY: ... ... ... ... ... ...\n"
	.string "...Snif... ¡Buaaaaah!\p"
	.string "Público: ¿Vieron eso?\n"
	.string "¡Pobre chica!\p"
	.string "MC: Eh... Oh-oh...\p"
	.string "¡Eso es todo por hoy!\n"
	.string "¡Gracias por sintonizarnos!$"
