VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Lejos, en CIUDAD VERIDIANO,\n"
	.string "está la LIGA POKéMON.\p"
	.string "Los ENTRENADORES que se reúnen allí\n"
	.string "son increíblemente hábiles.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "En la LIGA POKéMON, creo que las\n"
	.string "reglas dicen que debes luchar contra\l"
	.string "el ALTO MANDO seguido.\p"
	.string "Si pierdes con alguno, debes\n"
	.string "empezar el desafío otra vez desde el\l"
	.string "primero.$"

