SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Un volcán submarino entró en erupción\n"
	.string "y surgió desde las profundidades.\p"
	.string "Su cráter emergió del mar y\n"
	.string "se llenó con agua de lluvia.\p"
	.string "Así es como nació la CIUDAD CALOR\n"
	.string "en el mapa.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "La cueva que une CIUDAD ARRECIFE con\n"
	.string "el mundo exterior...\p"
	.string "Parece que fue hecha para evitar que\n"
	.string "algo logre salir.\p"
	.string "¿O solo me lo estoy imaginando?$"

