SaffronCity_Mart_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "Hay una gran RADIO TOWER en\n"
	.string "LAVANDA.$"

SaffronMart_Text_CooltrainerF:
	.string "Quiero ser más fuerte, pero\n"
	.string "aún no soy bueno...\p"
	.string "¿Me enseñas cómo algún día?$"
