OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Al iniciar un combate POKéMON, el que\n"
	.string "está a la izquierda sale primero.\p"
	.string "Si tienes más POKéMON en tu equipo,\n"
	.string "prueba a cambiar el orden de los\l"
	.string "POKéMON.\p"
	.string "Eso podría darte una ventaja.$"

