CeladonCity_GameCorner_MapScripts::
	.byte 0

CeladonGameCorner_EventScript_PokefanM::
	msgbox CeladonGameCorner_Text_PokefanM, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Teacher::
	msgbox CeladonGameCorner_Text_Teacher, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_FishingGuru::
	msgbox CeladonGameCorner_Text_FishingGuru, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Fisher1::
	msgbox CeladonGameCorner_Text_Fisher1, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Fisher2::
	msgbox CeladonGameCorner_Text_Fisher2, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_GymGuide::
	msgbox CeladonGameCorner_Text_GymGuide, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Gramps::
	msgbox CeladonGameCorner_Text_Gramps, MSGBOX_NPC
	end

CeladonGameCorner_Text_PokefanM:
	.string "Las máquinas tragamonedas son lo\n"
	.string "último en tecnología.$"

CeladonGameCorner_Text_Teacher:
	.string "Quiero esta máquina.\p"
	.string "Ayer me dejó sin nada, así que\n"
	.string "hoy debe dar el premio.$"

CeladonGameCorner_Text_FishingGuru:
	.string "Creo que esta máquina pagará\n"
	.string "out…\p"
	.string "Las probabilidades varían.$"

CeladonGameCorner_Text_Fisher1:
	.string "¡Gajajaja!\p"
	.string "¡No paran de salir monedas!\p"
	.string "¿Eh? ¿Qué, niño? ¿Quieres jugar?\p"
	.string "¡Compartiré mi suerte contigo!$"

CeladonGameCorner_Text_Fisher2:
	.string "¡Gajajaja!\p"
	.string "¡Me hace sentir bien hacer cosas\n"
	.string "buenas por los demás!$"

CeladonGameCorner_Text_GymGuide:
	.string "¡Hey! ¡Futuro CAMPEÓN!\p"
	.string "¿Tú también juegas a las tragas?\p"
	.string "Busco monedas para un POKéMON\n"
	.string "de premio.\p"
	.string "Pero aún no tengo suficientes...$"

CeladonGameCorner_Text_Gramps:
	.string "Hmmm... Las probabilidades son\n"
	.string "mejores en la línea de PIKACHU,\l"
	.string "pero... ¿qué hago?$"
