@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "¿Oh? ¿Quieres hacer {POKEBLOCK}S\n"
	.string "con este viejo?$"

BerryBlender_Text_Excellent:
	.string "¡Excelente!$"

BerryBlender_Text_MadeOldTimerSad:
	.string "Oh...\n"
	.string "Has puesto triste a este viejo...$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "¿Sabes hacer un {POKEBLOCK}?$"

BerryBlender_Text_LetsBerryBlender:
	.string "¡Empecemos entonces!\p"
	.string "¡A usar la BERRY BLENDER!$"

BerryBlender_Text_ExplainBerryBlending:
	.string "Te explico un poco.\p"
	.string "No te preocupes, es muy simple.\p"
	.string "Cuando la flecha de la BLENDER llegue\n"
	.string "a tu marca, presiona el Botón A.\p"
	.string "Eso es todo lo que debes hacer.\n"
	.string "Verás que es fácil al intentarlo.$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "¿Oh?\n"
	.string "¿No tienes BAYAS?\p"
	.string "Si no tienes BAYAS,\n"
	.string "no puedes hacer {POKEBLOCK}S.$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "Eso no servirá de nada, ¿verdad?\p"
	.string "Si no te importan las sobras, puedes\n"
	.string "usar una de mis BAYAS.\p"
	.string "Así haremos {POKEBLOCK}S juntos\n"
	.string "con la BERRY BLENDER.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "Si me quedaran algunas BAYAS,\n"
	.string "te daría una con gusto...\p"
	.string "Pero hoy no me sobra ninguna.\n"
	.string "Será en otra ocasión.$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "Pero tu ESTUCHE {POKEBLOCK} está lleno.\p"
	.string "Usa algunos {POKEBLOCK}S antes de\n"
	.string "venir a verme otra vez.$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "Pero no tienes un ESTUCHE de {POKEBLOCK}.\p"
	.string "Consigue un ESTUCHE de {POKEBLOCK} y\n"
	.string "luego ven a verme.$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "¡Empecemos a mezclar ya!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "¿Qué {POKEBLOCK} obtendré?\n"
	.string "¡Esto es muy emocionante!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "¡Hola! ¿Quieres mezclar algunos\n"
	.string "{POKEBLOCK}S con nosotros?$"

BerryBlender_Text_Okay:
	.string "¡Está bien!$"

BerryBlender_Text_ThatsTooBad:
	.string "Qué mal...\p"
	.string "¡Pero estaremos aquí cuando\n"
	.string "tengas ganas de mezclar!$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "Claro que sabes cómo mezclar\n"
	.string "{POKEBLOCK}S, ¿verdad?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "¡Empecemos entonces!\p"
	.string "¡A usar el BERRY BLENDER!$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "¡Bien!\n"
	.string "¡Te lo explicaré!\p"
	.string "Cuando la flecha del BLENDER\n"
	.string "llegue a tu marca, presiona\l"
	.string "el Botón A.\p"
	.string "Eso es todo.\n"
	.string "Bastante fácil, ¿no crees?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "Oh, pero espera un momento...\n"
	.string "No tienes BAYAS.\p"
	.string "No puedes hacer {POKEBLOCK}S sin\n"
	.string "BAYAS...\p"
	.string "Estaremos aquí cuando consigas\n"
	.string "BAYAS para mezclar.$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "Oh, pero espera un momento...\n"
	.string "Tu ESTUCHE {POKEBLOCK} está lleno.\p"
	.string "Usa algunos {POKEBLOCK}S y\n"
	.string "luego regresa.$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "Oh, pero espera un momento...\n"
	.string "No tienes un ESTUCHE {POKEBLOCK}.\p"
	.string "Consigue un ESTUCHE {POKEBLOCK} y\n"
	.string "luego regresa.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "¡Hola! ¿Quieres hacer algunos\n"
	.string "{POKEBLOCK}S con nuestro grupo?$"

BerryBlender_Text_OhDear:
	.string "¡Cielos!$"

BerryBlender_Text_LeftUsInShock:
	.string "Ay, cielos...\p"
	.string "¡Nos has dejado en shock!$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "Seguro que sabes cómo hacer\n"
	.string "{POKEBLOCK}S, ¿verdad?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "¡Muy bien, cielo!\n"
	.string "¡Empecemos!\p"
	.string "¡A usar el BERRY BLENDER!$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "¡Ay, cielo!\p"
	.string "Te lo explicaré detalladamente.\p"
	.string "Cuando la flecha del BLENDER gire\n"
	.string "hacia tu marca, pulsa el botón A.\p"
	.string "Eso es todo.\n"
	.string "¿No es sencillo?$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "No tienes BAYAS,\n"
	.string "¿verdad?\p"
	.string "Sin BAYAS no puedes hacer\n"
	.string "ningún {POKEBLOCK}.\p"
	.string "Aquí siempre haremos {POKEBLOCK}S,\n"
	.string "así que vuelve cuando tengas\l"
	.string "una BAYA o dos.$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "Tu ESTUCHE {POKEBLOCK} está lleno,\n"
	.string "al parecer.\p"
	.string "Usa algunos {POKEBLOCK}S y\n"
	.string "luego regresa.$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "Aún no tienes una {POKEBLOCK}\n"
	.string "CAJA, por lo que veo.\p"
	.string "Necesitas una CAJA {POKEBLOCK}\n"
	.string "antes de volver.$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "¡Bien! ¡Hoy será el día en que\n"
	.string "rompa el récord de velocidad!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "¡Cielos!\n"
	.string "Parece que eres bueno mezclando.\l"
	.string "¿Quieres unirte a nosotros?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "Haré {POKEBLOCK}S deliciosos\n"
	.string "para que mi POKéMON sea más lindo.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "Harás {POKEBLOCK}S con amigos\n"
	.string "usando BAYAS en la MEZCLADORA.\p"
	.string "¿Guardas la partida antes de\n"
	.string "conectarte con tus amigos?$"

BerryBlender_Text_SearchingForFriends:
	.string "Buscando a tus amigos…\n"
	.string "… … Botón B: Cancelar$"

BerryBlender_Text_Player1Arrived:
	.string "{STR_VAR_1} llegó.$"

BerryBlender_Text_Player1And2Arrived:
	.string "{STR_VAR_1} y {STR_VAR_2} llegaron.$"

BerryBlender_Text_AllPlayersArrived:
	.string "{STR_VAR_1}, {STR_VAR_2} y\n"
	.string "{STR_VAR_3} llegaron.$"

BerryBlender_Text_NoBerriesLink:
	.string "No tienes BAYAS.\n"
	.string "No puedes usar la MEZCLADORA.$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "Tu ESTUCHE {POKEBLOCK} está lleno.\n"
	.string "No puedes usar la MEZCLADORA.$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "No tienes un ESTUCHE {POKEBLOCK}.\n"
	.string "No puedes usar la MEZCLADORA.$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "Amo hacer {POKEBLOCK}S.\p"
	.string "Siempre llevo BAYAS conmigo.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "Si quieres, podemos hacer algunos\n"
	.string "{POKEBLOCK}S juntos con la\l"
	.string "MEZCLADORA.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string " ¿Oh?\n"
	.string "¿No tienes BAYAS?\p"
	.string "Eso no servirá de nada ahora, ¿no?\p"
	.string "Si no te importan las sobras, puedes\n"
	.string "quedarte con una de mis BAYAS.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "La usaremos para hacer {POKEBLOCK}S\n"
	.string "con la MEZCLADORA.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string " ¿Oh?\n"
	.string "¿No tienes BAYAS?\p"
	.string "Si me quedaran algunas, con gusto\n"
	.string "te daría una...\p"
	.string "Pero hoy no tengo ninguna extra.\n"
	.string "Lo siento mucho.$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_GARBAGEFLAG, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
