AquaHideout_UnusedRubyMap3_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_UnusedRubyMap3_OnTransition
	.byte 0

AquaHideout_UnusedRubyMap3_OnTransition::
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo::
	msgbox AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text, MSGBOX_NPC
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text:
	.string "¿Viste esos árboles que se mueven?\n"
	.string "¡Son POKéMON llamados SUDOWOODO!\l"
	.string "¿Lo sabías?\p"
	.string "Es un POKéMON que se disfraza\n"
	.string "de árbol pequeño.\p"
	.string "También está BONSLY, que hace\n"
	.string "lo mismo... pero no se ve tan\l"
	.string "real, o eso creo.\p"
	.string "He visto que evolucionan al\n"
	.string "imitar a otros SUDOWOODO.\p"
	.string "¿Será así como evolucionan?\p"
	.string "Si no erro, MIME JR. también\n"
	.string "evoluciona IMITANDO POKéMON.\p"
	.string "Muy distinto a mi MUNCHLAX, que\n"
	.string "evolucionó por AMISTAD, ¿no crees?$"
