PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "¡Viajar es maravilloso!\p"
	.string "¡De joven recorrí los mares\n"
	.string "y las montañas!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Suspiro...\p"
	.string "Quisiera ir de aventura\n"
	.string "con algunos POKéMON...\p"
	.string "Cruzar la hierba húmeda...\n"
	.string "Subir montañas escarpadas...\p"
	.string "Cruzar mares embravecidos...\n"
	.string "Vagar por cuevas oscuras...\p"
	.string "Y, a veces, sentir un poco\n"
	.string "de nostalgia...\p"
	.string "¡Viajar debe ser fabuloso!$"

