FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Hablando de las POKéDEX,\n"
	.string "recordé algo.\p"
	.string "Conocí a un ENTRENADOR, STEVEN,\n"
	.string "buscando piedras raras.\p"
	.string "¡Vaya!, tenía unos POKéMON\n"
	.string "increíbles con él.\p"
	.string "No solo eran raros, ¡estaban\n"
	.string "entrenados al extremo!\p"
	.string "Podría ser más fuerte que el\n"
	.string "LÍDER del GIMNASIO local…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "¿Qué es eso que tienes ahí?\p"
	.string "… … … … … …\p"
	.string "¿Ah, se llama POKéDEX?\n"
	.string "¡Es realmente genial!$"

