VermilionCity_House2_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "¿Sabes del TREN\n"
	.string "MAGNÉTICO?\p"
	.string "Es el ferrocarril que va a\n"
	.string "GOLDENROD en JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Quiero ir a SAFFRON para ver\n"
	.string "el TREN MAGNÉTICO.$"
