ViridianCity_Mart_MapScripts::
	.byte 0

ViridianCity_Mart_EventScript_Lass::
	msgbox ViridianMart_Text_Lass, MSGBOX_NPC
	end

ViridianCity_Mart_EventScript_Cooltrainer::
	msgbox ViridianMart_Text_CooltrainerM, MSGBOX_NPC
	end

ViridianMart_Text_Lass:
	.string "El LÍDER del GIMNASIO es genial.$"

ViridianMart_Text_CooltrainerM:
	.string "¿Has ido a CANNOBAR?\p"
	.string "Es una isla muy al sur de aquí.$"

