LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Los mayores misterios del planeta\n"
	.string "están en el fondo del mar.\p"
	.string "Alguien lo dijo, pero no lo sé…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Hay una fosa marina profunda\n"
	.string "entre FONDO MARINO y CALOROPOLIS.\p"
	.string "Eso fue lo que me contaron.$"

